wasmCloud/wasmCloud

crates/wascc-host/Cargo.toml, crates/wascc-host/src/actors/actor_host.rs, crates/wascc-host/src/capability/binding_cache.rs, crates/wascc-host/src/capability/extras.rs, crates/wascc-host/src/capability/native_host.rs, crates/wascc-host/src/control_plane/events.rs, crates/wascc-host/src/dispatch.rs, crates/wascc-host/src/host.rs, crates/wascc-host/src/host_controller.rs, crates/wascc-host/src/lib.rs, crates/wascc-host/src/manifest.rs, crates/wascc-host/src/messagebus/handlers.rs, crates/wascc-host/src/messagebus/hb.rs, crates/wascc-host/src/messagebus/mod.rs, crates/wascc-host/src/messagebus/utils.rs
Putting the manifest feature back into wascc host. The new manifest is not backwards compatible with the old one because new binding require the provider ID, etc.
=> Revenge of the manifest

Cargo.toml, crates/wascc-host/src/actors/actor_host.rs, crates/wascc-host/src/capability/native_host.rs, crates/wascc-host/src/control_plane/cpactor.rs, crates/wascc-host/src/control_plane/mod.rs, crates/wascc-host/src/host.rs, crates/wascc-host/src/host_controller.rs, crates/wascc-host/src/manifest.rs, crates/wascc-host/src/messagebus/hb.rs, crates/wascc-host/src/oci.rs
Firstly, there's now a pattern established for getting parameters from the host builder to the control plane actor, and there are some "unused" variables like `max_actors` and `max_providers` that are there as placeholders to make it fairly obvious how to add more tuning / configuration parameters to the control plane.
Secondly, the control plane itself isn't doing any enforcement of the `allow_latest` flag because .. .well, the CP isn't implemented yet ;) If you want to know where it _will_ be, check out the placeholder functions on the `ControlInterface` struct, which is an object handed to control plane implementations (e.g. our NATS / lattice CP).
The limited enforcement of the "allow latest" flag that _is_ in this host is from the host functions that add/load actors and providers. If …
=> Block the use of `latest` OCI images by default

crates/wascc-host/src/actors/actor_host.rs, crates/wascc-host/src/actors/mod.rs, crates/wascc-host/src/capability/native_host.rs, crates/wascc-host/src/control_plane/cpactor.rs, crates/wascc-host/src/control_plane/events.rs, crates/wascc-host/src/control_plane/mod.rs, crates/wascc-host/src/host.rs, crates/wascc-host/src/host_controller.rs, crates/wascc-host/src/messagebus/hb.rs
After talking to the people who actually know what they're doing in the Actix gitter/discord, I found that I was using a bit of an anti-pattern. It should be impossible for an actor to fail to start, and there were a couple of places, especially in the capability provider host actor, where I was pulling shenanigans like `try_new()`, which I then hid behind a builder (that also returned a result).
Instead, the recommended practice is that all actors should be 100% guaranteed to start, and if you need to set an initial state that could be rejected or invalid, then you do so through sending that message to the actor, and the actor stops itself if there's an error.
So far I've only refactored the host controller's interaction with the native capability provider host. After we agree on the …
=> Initial refactor for 'no fail' actor start

.github/workflows/release_amd64.yml, .github/workflows/release_arm64.yml, build/nfpm.amd64.yaml, build/nfpm.arm64.yaml
This PR adds `amd64` and `arm64` packaging for `wasmCloud`
Each workflow will compile and package its respective architecture, and push the resulting `deb/rpm` files to Package Cloud
**Notes:**
- The current implementation of `arm64` compiling and packaging is a placeholder until we move to a self-hosted github action runner.
=> Add arm64 and amd64 packaging

Cargo.toml, crates/control-interface/src/generated/ctliface.rs, crates/control-interface/src/lib.rs, crates/wasmcloud-host/src/actors/actor_host.rs, crates/wasmcloud-host/src/actors/mod.rs, crates/wasmcloud-host/src/capability/native_host.rs, crates/wasmcloud-host/src/control_interface/handlers.rs, crates/wasmcloud-host/src/generated/extras.rs, crates/wasmcloud-host/src/hlreg.rs, crates/wasmcloud-host/src/host.rs, crates/wasmcloud-host/src/host_controller/hc_actor.rs, crates/wasmcloud-host/src/host_controller/mod.rs, crates/wasmcloud-host/src/manifest.rs, crates/wasmcloud-host/src/messagebus/handlers.rs, crates/wasmcloud-host/src/messagebus/nats_subscriber.rs, crates/wasmcloud-host/src/messagebus/rpc_client.rs, crates/wasmcloud-host/src/messagebus/utils.rs, crates/wasmcloud-host/src/middleware/runner.rs, src/wasmcloud.rs, tests/common.rs, tests/control.rs, tests/no_lattice.rs, tests/with_lattice.rs
There's no integration test (yet) for the live update stuff because we need our own local OCI (check out the corresponding issue #31 ) that we can populate with multiple test modules. Right now the integration test for updating actors live requires us to replace an actor with that same actor's image from an OCI, and I can't mess up the public OCI with test signing keys, etc.
All the goodies should be here, however.
Also note that the host builder now has an option for enabling live updates. They will be _disabled_ by default.
=> Initial implementation of actor update functionality

crates/control-interface/src/lib.rs
Currently, consumers of the `control_interface` crate will be unable to use the `InvocationResponse` type as the struct is hidden behind a private module. If the `InvocationResponse` type is imported from `wasmcloud-host`, Rust interprets them as two different structs with the same name. This PR just adds the `pub` keyword to the `inv` module which makes those types public
=> Make inv mod public for control_interface imports

crates/control-interface/src/lib.rs
Restrict `inv` to only have Invocation and InvocationResponse structs public.
Fixes #prod-dumpster-fire
=> Make only Invocation and InvocationResponse public from inv

crates/wasmcloud-host/src/actors/actor_host.rs, crates/wasmcloud-host/src/host.rs, crates/wasmcloud-host/src/host_controller/hc_actor.rs, crates/wasmcloud-host/src/host_controller/mod.rs
Fixes #35 
By default, wasmcloud hosts (and actors) will enforce a `strict_updates_check` flag, which requires actors that live update to retain the same claims list as the original actor. 
For example:
["wascc:keyvalue", "wascc:http_server"] -> ["wascc:keyvalue", "wascc:http_server"] is valid
["wascc:keyvalue", "wascc:http_server"] -> ["wascc:keyvalue", "wascc:http_server", "wascc:blockchain"] is invalid
["wascc:keyvalue", "wascc:http_server"] -> ["wascc:keyvalue"] is invalid
["wascc:keyvalue"] -> ["wascc:http_server"] is invalid
etc...
If `strict_updates_check` is false, then an update will be allowed with a warning message.
=> Strict claims update checking for actors

crates/wasmcloud-host/src/control_interface/ctlactor.rs, crates/wasmcloud-host/src/control_interface/handlers.rs, crates/wasmcloud-host/src/host.rs, crates/wasmcloud-host/src/host_controller/hc_actor.rs, crates/wasmcloud-host/src/host_controller/mod.rs, crates/wasmcloud-host/src/manifest.rs, crates/wasmcloud-host/src/oci.rs, src/wasmcloud.rs
Fixes #63
My solution here ended up allowing for the user instantiating the host to provide a list of registries that are allowed for insecure (HTTP) connections. This option is valid regardless of authentication scheme. This way, instantiating a host with a host builder now can include the option:
```
host_builder = host_builder.oci_allow_insecure(vec!["localhost:5000"]);
```
to allow for insecure connections to a local registry, but then to use HTTPS for all other connections. The intended use of this is to let users define specific registries for testing / development purposes that they can connect via HTTP.
=> Allow specified list of HTTP connections for OCI interaction

crates/control-interface/src/generated/ctliface.rs, crates/control-interface/src/lib.rs, crates/wasmcloud-host/src/control_interface/handlers.rs, tests/lib.rs, tests/with_lattice.rs
The new behavior of the wasmCloud control interface is that the `StartActor` and `StartProvider` commands will now be acknowledged as early as possible, either if a validation failure is detected or immediately _before_ the OCI bytes are downloaded.
This has a downstream effect of requiring that any consumer of the control interface must monitor the control event stream in order to determine if an actor or provider did successfully complete the startup process.
=> Control interface start actor and provider now acknowledge prior to downloading OCI bytes

crates/wasmcloud-host/src/capability/native.rs, crates/wasmcloud-host/src/capability/native_host.rs, crates/wasmcloud-host/src/dispatch.rs
Fixes #68
`link_name` is littered across the project (162 results in 16 files) so I've attempted to do this in the most efficient way possible. I tackled two main areas of issue when creating links across wasmCloud:
1. Starting a capability provider with a link name of `""`
Tackled with `normalize_link_name` within the `capability` module. Feasibly, we could surround every occurrence of `link_name` with this function, but I see less value in that if we stop the irregular naming at the source. (If this is desired, `normalize_link_name` could be moved to a common `util` module, and I can do that refactor brute-force 😄 
2. Starting a native capability host (e.g. accessing a capability from within an actor) with a link name of `""`
This functionality was actually already present, just at a …
=> Normalizing Native Capability link names

.github/workflows/control-interface.yml, .github/workflows/control-interface_release.yml, .github/workflows/rust.yml, .github/workflows/wasmcloud-host.yml, .github/workflows/wasmcloud-host_release.yml, crates/control-interface/README.md, crates/wasmcloud-host/README.md, tests/lib.rs, tests/with_lattice.rs
This PR updates the crate READMEs along with build/release actions so we can get them released and used in `wasmCloud` and `wash`.
This test also updates the echo test, primarily increasing the delay durations to make it pass more consistently with the test suite. I've filed #83 to capture our desire to move away from fiddling with delay timers.
=> Updated crate READMEs, additional build/release actions, increased echo delay

tests/lib.rs, tests/with_lattice.rs
This moves the `distributed_echo` test to the `#[ignore]` section and tests it on its own.
=> Moved distributed echo to ignore section, still testing

crates/wasmcloud-control-interface/Cargo.toml
crates.io will not accept crates without certain metadata fields, publishing the control interface recently failed due to missing `description` and `license`. This fixes that and will enable us to publish.
=> Added metadata to control interface

crates/wasmcloud-host/Cargo.toml
For all of you out there looking at this, remember, `cargo publish` has a `--dry-run` option that you can use before you dedicate 3 PRs to publishing 2 crates
=> Pinning relative control interface dependency to version 

Cargo.toml
`cargo publish --dry-run` succeeds now, so we can release the binary
=> Pinned wasmcloud-host to version for cargo publish

Cargo.toml, samples/bench-actor/Makefile, samples/bencher/Cargo.toml, samples/bencher/README.md, samples/bencher/src/main.rs, tests/lib.rs
Make sure you run the `bencher` binary/project in release mode, otherwise you get the super-slow parsing/interpreting behavior on the wasm files.
=> Initial commit of code that invokes the benchmark actor

Cargo.toml, codegen.yaml, src/wasmcloud-lite.rs, src/wasmcloud.rs
Assuming this PR is approved and merged and everything passes, we will need to release the 0.15.3 binary to address this gap.
=> Adding support for manifest loading to the wasmcloud binary

CODEOWNERS.md
With this file commited to `main`, all of the wasmcloud team members should be requested for a review when a PR is created. Additionally, if the file only involves GitHub actions, we primarily request @billyoung and I've added myself as a secondary.
=> Implemented codeowners for automatic PR review

crates/wasmcloud-host/src/actors/actor_host.rs, crates/wasmcloud-host/src/capability/native.rs, crates/wasmcloud-host/src/capability/native_host.rs, crates/wasmcloud-host/src/host.rs, crates/wasmcloud-host/src/manifest.rs
Manifests support referencing providers as local files, but wasmcloud-host defers to the cache at `$TEMP/wasmcloudcache` for all cases, even if a local provider has changed on disk. This behavior makes sense for immutable sources, but par files on disk don't make that guarantee. This leads to very difficult-to-troubleshoot behavior when the expectation is that the referenced file is the source of truth, not a previously loaded version.
This PR changes cache behavior when loading a manifest that references local provider archives. It does not affect cache behavior for pars from a registry.
This PR also adds logging for previously silent errors and places that would have made troubleshooting this easier.
=> Fixed manifest cache behavior for local par files, added log output

crates/wasmcloud-control-interface/codegen.yaml, crates/wasmcloud-control-interface/src/broker.rs, crates/wasmcloud-control-interface/src/generated/ctliface.rs, crates/wasmcloud-control-interface/src/inv.rs, crates/wasmcloud-control-interface/src/lib.rs, crates/wasmcloud-host/README.md, crates/wasmcloud-host/src/capability/extras.rs, crates/wasmcloud-host/src/capability/native.rs, crates/wasmcloud-host/src/capability/native_host.rs, crates/wasmcloud-host/src/control_interface/ctlactor.rs, crates/wasmcloud-host/src/dispatch.rs, crates/wasmcloud-host/src/errors.rs, crates/wasmcloud-host/src/generated/core.rs, crates/wasmcloud-host/src/generated/extras.rs, crates/wasmcloud-host/src/lib.rs, crates/wasmcloud-host/src/messagebus/utils.rs, crates/wasmcloud-host/src/middleware/mod.rs, crates/wasmcloud-host/src/oci.rs, crates/wasmcloud-provider-core/src/lib.rs, samples/bench-actor/src/lib.rs, tests/common.rs, tests/control.rs, tests/lib.rs, tests/no_lattice.rs, tests/with_lattice.rs
This PR:
* Removes Wascc artifacts from previous writes
* Renames `linkdefinitions` to `link_definitions` to match naming convention with other methods
* Removes `extern crate` declaration except for log crate since 2018 edition is used
* Adds `#![cfg_attr(debug_assertions, allow(dead_code, unused_imports))]` to test modules `controls.rs` and `with_lattice.rs` modules to suppress linting warnings
* Renames  https://raw.githubusercontent.com/wascc/schemas/main/control_interface.widl to https://raw.githubusercontent.com/wasmCloud/actor-interfaces/main/schemas/control_interface.widl
=> Remove wascc related artifacts from previous life and fix few more cosmetics issues

src/wasmcloud.rs
This PR adds `--label` (`-l`) to the `wasmcloud` CLI in order to pass labels to the instantiated `wasmcloud-host`. The flag can be passed multiple times, for example:
```
wasmcloud --label x=1 --label y=2 -l z=3
```
I know that labels can be set via a manifest, but I think this is more convenient when using the CLI and it prevents overwriting all the labels at once.
=> add --label to wasmcloud

crates/wasmcloud-host/src/control_interface/handlers.rs, tests/no_lattice.rs
fixes #106 
This PR adds the provider OCI reference to the acknowledgement JSON from `wash ctl start provider` (also moved a line in the start actor function to match).
Also fixes an integration test which was just asserting true :-)
=> add provider ref to start ack

Cargo.toml, crates/wasmcloud-host/Cargo.toml, crates/wasmcloud-host/src/host.rs
Fixes an issue where the Host struct was not Send because of leftover and unnecessary use of Refcells
=> Make Host Sendable

crates/wasmcloud-host/Cargo.toml
wasmcloud-host 0.15.6
Upgrade oci-distribution dependency to 0.6, completing the tokio 1.x/actix 2 migration. 
Upgrade actix from 0.11-beta to 0.11
=> wasmcloud-host 0.15.6: upgrade oci-distribution dependency to 0.6, completing tokio 1.x/actix 2 migration

Cargo.toml, crates/wasmcloud-host/Cargo.toml, samples/bencher/Cargo.toml
Minor bump as actix-rt 2.1.0 / actix 0.11.0 / tokio 1.0 is a breaking change for developers depending on the `wasmcloud-host` crate.
=> Release 0.16.0 for wasmcloud-host and wasmcloud binary

README.md
Sorting with `semver` for the shields.io API only includes the binary version
=> Show only wasmcloud binary version release badge

crates/wasmcloud-host/src/dispatch.rs, crates/wasmcloud-host/src/messagebus/handlers.rs
no longer suppressing failed invocation results returned to the guest
=> Closing #137

crates/wasmcloud-control-interface/src/lib.rs, crates/wasmcloud-host/src/control_interface/ctlactor.rs, crates/wasmcloud-host/src/dispatch.rs, crates/wasmcloud-host/src/hlreg.rs, crates/wasmcloud-host/src/host_controller/hc_actor.rs, crates/wasmcloud-host/src/manifest.rs, crates/wasmcloud-host/src/messagebus/handlers.rs, crates/wasmcloud-host/src/messagebus/nats_subscriber.rs, crates/wasmcloud-host/src/messagebus/rpc_subscription.rs
This is mostly a logging PR to help diagnose issues and understand the flow of wasmcloud via trace logging. Some logs don't look valuable, but without them it's confusing to know if anything is happening when you poke at the host.
The large chunk of code changed in CreateSubscription is just logging. There was a lot going on there that failed silently on errors.
Piggybacking onto this PR is support for empty links, actors, and capabilities in manifest files. LMK if I should change any of the message text or back anything out.
- added logging messages
- propagated ser/des error messages  
- implemented Display for WasmCloudEntity
- allowing empty links, capabilities, and actors in manifest
=> Added logging, allowed manifests support missing fields

crates/wasmcloud-host/src/actors/wasmcloud_actor.rs, crates/wasmcloud-host/src/capability/native.rs, crates/wasmcloud-host/src/host.rs, crates/wasmcloud-host/src/lib.rs, crates/wasmcloud-host/src/manifest.rs
=> Closing #131. Documentation updates.

Cargo.toml, crates/wasmcloud-host/src/actors/actor_host.rs, src/wasmcloud.rs, tests/lib.rs
This PR allows you to run the wasmcloud binary with either the `wasm3` or `wasmtime` engine. The default is wasm3, and in order to run with wasmtime you must use the following command:
```
cargo run --features wasmtime --no-default-features
```
In order to enforce a default, as @ChrisRx noted in #56, we have to explicitly remove the default feature in order to use the other engine type. I've adjusted the default log verbosity for the `wasmtime-provider` as in `info` mode you will get a lot of output as wasmtime JITs the actor module, in `debug` mode you get an unusable amount of wasm debug output.
This PR also uncomments our integration tests.
=> Implemented feature flags for wasmcloud binary

Cargo.toml, crates/wasmcloud-control-interface/Cargo.toml, crates/wasmcloud-control-interface/src/generated/ctliface.rs, crates/wasmcloud-host/Cargo.toml, crates/wasmcloud-host/src/actors/actor_host.rs, crates/wasmcloud-host/src/capability/native_host.rs, crates/wasmcloud-host/src/control_interface/handlers.rs, crates/wasmcloud-host/src/host.rs, crates/wasmcloud-host/src/host_controller/hc_actor.rs, crates/wasmcloud-host/src/host_controller/mod.rs, crates/wasmcloud-host/src/messagebus/handlers.rs, crates/wasmcloud-host/src/messagebus/mod.rs, samples/bencher/Cargo.toml, schemas/control_interface.widl, tests/control.rs
* Host inventory (lattice) query now includes:
* revision number of actor and provider _currently running in the host_ (e.g. not retrieved from cache)
* vector of OCI references (was previously a single OCI ref, which could've been inaccurate)
* Host API has changed:
*  `providers()` function now returns a Vec of 3-tuples `(public_key, contract_id, link_name)` - was previously just public key
=> Adding more detail to host inventory and API queries

crates/wasmcloud-control-interface/src/generated/ctliface.rs, crates/wasmcloud-host/src/actors/actor_host.rs, crates/wasmcloud-host/src/host_controller/hc_actor.rs, crates/wasmcloud-host/src/host_controller/mod.rs, tests/control.rs, tests/lib.rs, tests/no_lattice.rs
Fixes #156 
A few notes:
1. My suggestion to skip serializing the field if the Vec is empty fails to deserialize (exactly as the documentation says) so I removed it
2. I added a test to ensure we don't regress in the future, which tests both `ctl` and host API
=> Ensure live update of actor puts new OCI reference

crates/wasmcloud-host/Cargo.toml
This change should enable installing using the wasmtime feature on Apple M1 hosts.
=> Bump wasmcloud-host/wasmtime-provider to 0.0.3

.github/workflows/gitpod_docker.yml, .github/workflows/publish.yml, .gitpod.Dockerfile, .gitpod.yml
Working on getting the gitpod deployment up and running a little quicker.  This PR includes a new Action that will build `.gitpod.Dockerfile` any time that it is updated and push it to azurecr.  Additionally, it changes the gitpod configuration to use that image.  This method eliminated the need to install wasmcloud and wash at start time (as it is included in the container).  
I still feel there is a good deal of optimizing that can be done (by not using that gitpod/workspace-full) as the base image, but for now, this seems a good deal faster to me.  
Note: I was NOT able to test this using Azure as I dont have ant access.  I did test is using GHCR.io and it worked well.
=> Optimizing Gitpod Deployment

.github/workflows/gitpod_docker.yml
We will need this when we release a new binary version of the `wash` or `wasmcloud` tools.  It will be manually triggerable in the UI.
=> Add manual trigger to gitpod workflow

tests/control.rs
With 5 seconds as a maximum time to wait for `echo` to be scheduled, a computer/runner with constrained resources may not be able to download the ~500k actor and have it available in the host inventory quick enough. I've increased the time to 30 seconds as a maximum to ensure we don't fail to update an actor because it didn't download fast enough.
=> Increased max time to download echo actor from 5s to 30s

Cargo.toml, crates/wasmcloud-host/Cargo.toml, samples/bencher/Cargo.toml
With the latest patch from @matthewtgilbride, I wanted to bump the wasmcloud-host version a patch version so that developers on the M1 chip can use our crate + binary with the `wasmtime` provider.
=> Bump wasmcloud-host version for wasmtime-provider

Cargo.lock
Same deal as https://github.com/wasmCloud/wash/pull/128 here, apparently the Cargo.lock was committed in a different PR so the file is dirty when `cargo publish` would run (I tested with `--dry-run` before this time :P)
=> Commit cargo lock to main repository

Cargo.lock
With just a simple `cargo build`, `Cargo.lock` updates to the point where `cargo publish` will succeed. I assume that this was due to an outstanding pull request that didn't yet pull in the changes to the `.gitignore`, so no changes have been made.
=> Update cargo lock, ensure git recognizes it

src/wasmcloud.rs
I copy-pasted this into https://github.com/wasmCloud/wash/pull/146 but it turns out it wasn't reading the files.
~If this has been broken for a long time and nobody has noticed then I would actually recommend ripping this mechanism out and just using the .creds files. I would be happy to make a PR for this instead.~ actually maybe not. Turns out if you supply the secrets as environment variables then it works fine, which is what you would be doing in kubernetes-land.
=> fix --rpc-jwt auth mechanism

Dockerfile
@StuartHarris can take most of the credit for this (I just added the debug layer).
The from-scratch image did not have certificates in the right place, so it couldn't pull actors from `eu.gcr.io/wasmcloud-k8s-demo/todo-backend:0.2`.
Alpine's libc is also not capable of loading capability provider .so files.
When setting up a kubernetes cluster, we had a few problems connecting to redis and nats, and our http capability provider would sometimes not come up correctly. I have added a `debug` target that includes the utilities needed to debug these things.
I was also thinking that it would be nice to have a `test` target, that runs some sanity integration checks (spin up a wasmcloud with a manifest and check that it works)
This has been pushed to …
=> Switch docker image to debian-slim

README.md, RESOURCES.md, crates/provider-archive/src/archive.rs
In preparation for us to release the OTP `0.50` release, as well as wash `0.6.0`, I wanted to add our resources to a README so they can be found in the future fairly easily.
=> Add pinned resources for the pre-otp host

CONTRIBUTING.md, CONTRIBUTION_LADDER.md, GOVERNANCE.md, SECURITY.md
This PR introduces a full rework of our contributing doc and introduces a new
contributor ladder document to clearly explain how someone can become a
maintainer of a wasmcloud project. If approved and merged, there will be follow
up work to make sure the proper labels are defined everywhere
This also contains a governance document. I kept this as lightweight as possible
while still adding some process. If merged, we will need to officially designate
a set of org maintainers to bootstrap the process. As part of governance, I also
added a documented security process for how we handle reported vulnerabilities.
Please let me know if there are other people we should add to the security list.
Please note: These documents draw heavily (read: were copy and modified) from the …
=> docs(*): Adds contributing and governance docs

OWNERS
@autodidaddict, @brooksmtownsend, @LiamRandall, @stevelr, @jordan-rash This PR will not be merged until you have all approved this PR to indicate your agreement to be org maintainers. I double checked with people, but an official approval is important here.
For those in the community, this initial list of org maintainers is based on people who are currently acting in this role. From here on out, all org maintainers must be added or step down as defined in the [governance doc](https://github.com/wasmCloud/wasmCloud/blob/main/GOVERNANCE.md#wasmcloud-org-maintainers)
=> chore(OWNERS): Add final list of initial org maintainers

CODEOWNERS, OWNERS
Now that this repository contains the wasmCloud host SDK, the owners list should match this.
=> chore(github): CODEOWNERS are host maintainers

OWNERS
I didn't realize that was the file that we use to indicate who are org maintainers when I merged #281
=> Adds back owners file

examples/echo/main.rs, src/actor/component.rs, src/actor/mod.rs, src/actor/module/mod.rs, src/actor/module/wasmbus.rs, src/capability/logging/discard.rs, src/capability/logging/log.rs, src/capability/mod.rs, src/capability/numbergen/rand.rs, src/main.rs, tests/actor_compat.rs, tests/actor_http_log_rng.rs
This PR adds an additional parameter to the component and module `call` functions, with another function head called `call_with_context`, and another parameter `HostInvocation` struct called `call_context`, which is an optional byte vector. Host implementers can use to add additional context onto invocations which will be propagated the entire length of the call.
The original problem this addresses is the fact that there was no way to propagate a parent span ID through a system in order to construct a full trace from the host side. I'd be happy to entertain different naming schemes for the context, different API strategies instead of a `call` and `call_with_context` function, etc. I decided to implement first to show a glimpse at what needed to be done so we can discuss.
`next`
Consumers …
=> Added `call_context` to HostInvocations and additional `call_with_context` functions

.github/stale.yaml
This PR adds a `stale.yaml` definition which marks issues as stale after 90 days, and closes them after 7 days with a `wontfix` label. I plan to take this definition and replicate it across the other wasmCloud repositories, so please leave comments here and then I can copy/paste around.
All the stale ones
N/A
=> added stale.yaml for closing old issues

.github/stale.yml
After looking at the issues, `wontfix` is a little aggressive for a stale issue, so I'm renaming it to scale. We can address issues as wontfix if we'd like
=> Less aggressive stale

.github/workflows/wasmcloud.yml, flake.nix
- Build for Windows in CI
Extracted from #293
- `nix flake check -L` on `x86_64-linux`
- `nix build -L .\#packages.aarch64-darwin.wasmcloud-x86_64-pc-windows-gnu-oci` (remote build on `aarch64-darwin` from `x86_64-linux`)
- `nix build -L .\#packages.x86_64-darwin.wasmcloud-x86_64-pc-windows-gnu-oci` (remote build on `x86_64-darwin` from `x86_64-linux`)
- `nix build -L .\#wasmcloud-x86_64-pc-windows-gnu-oci` (remote build on `x86_64-linux` from `x86_64-linux`)
- etc...
=> ci: build `wasmcloud` for `win64`

.github/workflows/wasmcloud.yml, Cargo.lock, Cargo.toml, flake.lock, flake.nix, tests/actors/rust/Cargo.lock, tests/actors/rust/Cargo.toml
`wasmcloud` interface updates are here due to `async-nats` being vulnerable as a transitive dependency of `wasmbus-rpc`. Good thing these dependencies are being removed soon.
The exact version of advisory DB used can be inspected in the `flake.lock`
https://github.com/rvolosatovs/nixify/pull/127
built the check
=> build(nix): add cargo audit

crates/host/src/bindle.rs, crates/host/src/lib.rs, crates/host/src/oci.rs, crates/host/src/par.rs, crates/host/src/wasmbus/event.rs, crates/host/src/wasmbus/mod.rs
Implement provider auction, start and stop
Similar to #371 , but incomplete
You should be able to start and stop a provider from the washboard, that's about it. The providers should show up in the inventory and on the washboard with some missing details.
```
wash start provider wasmcloud.azurecr.io/httpserver:0.16.0
wash stop provider <HOST> VAG3QITQQ2ODAOWB5TTQSDJ53XK3SHBEIFNK4AYJ5RKAX2UNSCAPHA5M default wasmcloud:httpserver
```
Note, that the start command times out due to semantic difference here from OTP. That will be addressed later, since that's not an isolated case.
=> feat(wasmbus): implement provider start/stop

crates/host/src/wasmbus/mod.rs
This PR creates the lattice metadata bucket explicitly, rather than implicitly via a stream. It also gracefully handles errors where the bucket has already been provisioned with custom settings, allowing multiple hosts to run in the same pre-provisioned lattice
Resolves https://github.com/wasmCloud/wasmCloud/issues/417
Next
This allows hosts to start in a lattice with pre-provisioned resources, e.g. the lattice metadata bucket
The existing `wasmbus` test covers creating a bucket successfully. I locally edited the code to pre-create a bucket beforehand and verified the host gracefully handles the error from the NATS client. I also tested the error case by attempting to create a bucket with an invalid name. 
See above
=> refactor: create bucket explicitly instead of stream

crates/host/src/lib.rs, crates/host/src/local/config.rs, crates/host/src/local/mod.rs, crates/host/src/wasmbus/config.rs, crates/host/src/wasmbus/mod.rs, examples/rust/http-axum/tests/local.rs, src/main.rs, tests/local.rs, tests/wasmbus.rs
There were several instances where we referred to "wasmbus" or "lattice" where I think "host" is the more appropriate term. I was getting confused so I replaced most of these with "host"
N/A
Next
N/A
No additional testing performed
=> style: rename most instances of lattice and wasmbus to host

crates/host/src/wasmbus/mod.rs, crates/runtime/src/actor/component/messaging.rs, crates/runtime/src/capability/builtin.rs, crates/runtime/tests/runtime.rs, tests/actors/rust/builtins-component-reactor/src/lib.rs, tests/wasmbus.rs
implement `wasmcloud:messaging/consumer` support,
Note that only `max-results` of `0` and `1` are supported for `request_multi`
Given, that such functionality did not exist in Smithy interface, I think we should just drop that method for now, but I'd rather do that in a separate PR and get the interface as-defined-today implemented first
#421 
blocked on #449 
=> feat: implement `wasmcloud:messaging/consumer` support

Cargo.toml, crates/host/src/wasmbus/config.rs, crates/host/src/wasmbus/mod.rs, src/main.rs, tests/wasmbus.rs
Note: this PR is based on top of https://github.com/wasmCloud/wasmCloud/pull/431
This PR adds support for setting a custom lattice prefix via args
I also moved a couple other settings into `HostConfig`. If we like this approach, I can easily add support for the rest of the host options.
Resolves https://github.com/wasmCloud/wasmCloud/issues/428
Next
Users can now start the host with a `-x foo-bar` and the `lattice_prefix` for incoming/outgoing messages will match
I updated the wasmbus test to use a custom prefix
I also tested manually with different prefixes and NATS hosts/ports
=> Custom lattice prefixes

crates/host/src/wasmbus/mod.rs, tests/wasmbus.rs
This PR adds support for RPC on non-default link names
Resolves https://github.com/wasmCloud/wasmCloud/issues/461
Next
Users can start and interact with providers on non-default link names. Note the discussion in https://github.com/wasmCloud/wasmCloud/issues/461 for why this will currently only work for wasm modules, not components
N/A
Updated the wasmbus tests
N/A
=> feat: add support for non-default link names

Cargo.toml
This removes a feature from the tracing crate, allowing higher log verbosity than info for release builds
Allowing users to specify debug/trace-level logs is important for debugging release builds. The size of the debug build is prohibitively large in some environments where viewing debug/trace logs is still helpful
=> fix(logs): allow debug and trace logs in release mode

crates/host/src/lib.rs, crates/host/src/oci.rs, crates/host/src/wasmbus/config.rs, crates/host/src/wasmbus/mod.rs, src/main.rs, tests/wasmbus.rs
This PR continues work towards OTP feature parity by using more of the CLI args provided. Specifically, this PR implements using:
1. `cluster_issuers` list by propagating the list as a part of host config. Will need to be utilized in #483 
2. `log_level` by parsing as a `tracing::Level` and passing to the `tracing_subscriber` setup
3. `provider_shutdown_delay` by adding a NATS request to gracefully shutdown the provider with this timeout
4. `allow_latest`, `allowed_insecure`, `oci_registry`, `oci_user`, and `oci_password` by adding an `OciOpts` struct that the `Host` holds as a field and will use for all OCI operations
5. `js_domain` by using the optional domain to create the Jetstream context when accessing the LATTICECACHE KV bucket.
There are still more args to implement, but I'm …
=> Implement cluster issuers, log level, provider shutdown, js_domain, and OCI CLI vars

crates/host/src/bindle.rs, crates/host/src/lib.rs, crates/host/src/oci.rs, tests/wasmbus.rs
This PR contains one chore for reordering args, and one addition to the `wasmbus` test which launches a second host instance with a _different_ cluster key in order to verify that we're passing cluster issuers into all the right places. Both of these are requests from @connorsmith256's review of #490 so I just wanted to wrap that up.
#490 
The wasmbus test suite now runs _two_ hosts. I considered adding another test for "multi-host" scenarios but I figured this would be the quickest way to proceed with the logic that we have, and by and large nothing should really be different for running multiple hosts in the same lattice.
Ran `cargo nextest run` and, by removing the host cluster issuers from each others list, the test fails with:
``` …
```
=> Add cluster issuers verification test

crates/host/src/wasmbus/mod.rs, tests/wasmbus.rs
This PR:
- stores actor and provider claims when they are started
- adds the ability to query claims and links via the host
Resolves https://github.com/wasmCloud/wasmCloud/issues/492 and https://github.com/wasmCloud/wasmCloud/issues/481
The host will now respond accurately to requests on `wasmbus.ctl.{lattice_prefix}.get.claims` and `.get.links`
I added tests to `tests/wamsbus.rs` to confirm that the hosts responds to requests for links and claims with the correct data, and also that the data returned is exactly what the control interface client returns when querying the latticedata bucket directly
I also did manual testing with `wash get claims/links` and `nats req ...`
=> feat: add claims and link query functionality

crates/host/src/wasmbus/config.rs, crates/host/src/wasmbus/mod.rs, crates/host/src/wasmbus/nats.rs, src/main.rs, tests/wasmbus.rs
This PR implements all of the connection options for RPC, CTL, and Provider RPC connections. Additionally, it adds support for the control interface topic prefix, which just defaults to `wasmbus.ctl` as before.
I made a few choices + stances in this PR:
1. RPC, CTL, and provider RPC connection arguments are _advanced_ arguments. Therefore, they are hidden by default. (I would support showing these arguments with some kind of --help --advanced flag)
2. RPC, CTL, and provider RPC connection args should fall back on the supplied NATS connection variables if not provided, instead of maintaining a separate all-around NATS connection. This way we're always internally using the correct connection, even if it's using the same parameters.
Fixes #478 
N/A …
=> Implement connection args for RPC/CTL/Prov RPC arguments

Cargo.lock, Cargo.toml, crates/host/Cargo.toml, crates/host/src/wasmbus/mod.rs, tests/wasmbus.rs
This PR populates the `uptime_human` field on heartbeats and host pings. It also populates `ctl_host`, `prov_rpc_host`, `rpc_host` on host pings.
Resolves #518 
Next
Consumers of heartbeats and host pings get more info, yay
I updated the integration test to ping hosts and verify the data that comes back
=> feat: fill in missing data in host pings and heartbeat messages

src/main.rs
The host was failing to start when passed a list of issuers along with a cluster seed, because the list was being treated as a single string. This splits the list on `,` as intended
Tests didn't catch this because we were setting the config struct ourselves, not exercising the clap parsing logic
=> fix: parse lists with a delimiter

crates/host/src/wasmbus/mod.rs
Providers should not implicitly receive environment variables from the host, since this is a security risk. Values providers need should be passed via `HostData`
Note this means we need to add `OTEL_TRACES_EXPORTER` and `OTEL_EXPORTER_OTLP_ENDPOINT` to `HostData`, which I've filed in https://github.com/wasmCloud/wasmCloud/issues/523
N/A
Next
As we rewrite providers, we should remove uses of `std::env::var`, since these values will now be empty
I started the host with an env var, launched a provider, inspected the env vars the child process had, and confirmed the host's var was not proxied to the provider
=> fix: do not proxy env vars from host to providers

crates/host/src/lib.rs, crates/host/src/wasmbus/config.rs, crates/host/src/wasmbus/mod.rs, src/main.rs, tests/wasmbus.rs
This PR:
1. Propagates and respects the `allow_file_load` parameter
2. Enables structured logging with the `json()` layer, and passes that field and `log_level` to providers as well
Marked as draft for testing with `allow_file_load`, and because I could use some advice on the structured logging and if this is sufficient. I'd also like #506 to merge first 
N/A
N/A
=> Propagate allow_file_load, implement structured logging

crates/host/src/wasmbus/mod.rs
Simply renaming one of our friendly nouns to avoid _unintended consequences_.
=> chore: rename friendly noun

crates/host/src/wasmbus/mod.rs
It appears that providers using `wasmcloud-provider-sdk` differ from the ones using `wasmbus-rpc` in that the latter return an empty response on RPCs that do not define a response, whereas the former encodes `()`. Account for both.
=> fix(host): ignore empty responses

crates/host/src/wasmbus/mod.rs, crates/provider-sdk/src/core.rs, crates/provider-sdk/src/provider_main.rs
This PR sends tracing config to providers via HostData
Resolves https://github.com/wasmCloud/wasmCloud/issues/523
Next
Downstream providers will need to be rebuilt to use the updated parsing logic
I set up an OTEL exporter and collector manually, started the HTTP server provider built with these changes, and confirmed traces were received when curling the actor's endpoint
=> feat: send OTEL config via HostData

.github/workflows/wasmcloud.yml, flake.lock, flake.nix
This makes sure that `aarch64-darwin` binaries are runnable out-of-the-box and we now build Mac binaries on Linux
https://github.com/rvolosatovs/nixify/pull/148
https://github.com/bytecodealliance/wit-deps/pull/49
```
$ unzip wasmcloud-universal-darwin.zip 
Archive:  wasmcloud-universal-darwin.zip
inflating: wasmcloud-universal-darwin  
administrator@administrators-Mac-mini ~ % chmod +x wasmcloud-universal-darwin
administrator@administrators-Mac-mini ~ % ./wasmcloud-universal-darwin 
OTEL exporter endpoint not set, defaulting to 'http://localhost:55681/v1/traces'
Error: failed to initialize host
Caused by:
0: failed to establish NATS control server connection
1: failed to connect to NATS
2: Connection refused (os error 61)
3: Connection refused …
```
=> build(nix): update dependencies

src/main.rs
The host was defaulting to `otlp`, which causes the host and providers to try to set up tracing, even when no endpoint is set
=> fix: do not set a default value for traces exporter

crates/host/src/wasmbus/event.rs, crates/host/src/wasmbus/mod.rs, tests/wasmbus.rs
This PR flattens uses of options for annotations, both for the host's internal `Annotations` type (`BTreeMap<String, String>`) as well as incoming annotations from the control interface client (`HashMap<String, String>`)
This is to avoid cases where e.g. a provider is started via a request where `"annotations" :{}`, but then the user tries to stop the provider via a request where `"annotations": null` (or where `annotations` is omitted entirely)
The host will now treat an omitted annotations field, null annotations, and an empty annotations map on requests the same way
The host will now always emit an empty annotations map in events as well. Since consumers of the events previously had to handle the omitted field, null, or an empty map, this change is backwards-compatible
Built on …
=> refactor: flatten optional annotations to always be set

crates/compat/src/http.rs, crates/runtime/tests/runtime.rs, tests/actors/rust/builtins-compat-reactor/src/lib.rs, tests/actors/rust/builtins-component-reactor/src/lib.rs, tests/actors/rust/builtins-module-reactor/src/lib.rs, tests/wasmbus.rs
Fix incorrect `path_with_query` handling - turns out `query_string` received from providers does not include `?`
General incoming HTTP testing is greatly improved here
Closes https://github.com/wasmCloud/wasmCloud/issues/575
`cargo test`
=> fix(incoming-http): properly handle `path_with_query`

crates/host/src/wasmbus/mod.rs
Without this, sending responses to things like a host stop command or publishing the host stop event can fail as we don't ensure all messages in the NATS client queue have been sent
=> fix(host): Flushes NATS clients on host stop

.github/workflows/wasmcloud.yml, flake.nix
Default to a Debian-based OCI image, since currently-released capability providers are dynamically linked to glibc
Closes #614 
Closes #618 
https://github.com/wasmCloud/capability-providers/issues/265
```
$ nats-server -js
$ docker run --rm -it --network host rvolosatovs/wasmcloud:0.78.0-rc3
$ wash start provider wasmcloud.azurecr.io/httpserver:0.19.1
```
https://github.com/rvolosatovs/wasmCloud/actions/runs/6063571716
=> build: default to a Debian-based OCI image

crates/host/src/wasmbus/mod.rs
In https://github.com/wasmCloud/wash/pull/759 we updated the wash integration tests to look for "host" and "started" to confirm the host was up, since the host currently emits `host {ID} started`. This updates the host to emit `wasmCloud host started` and sets the host ID as a field on the event
Requirement for https://github.com/wasmCloud/wash/issues/761
Next
N/A
Ran locally. Before:
```
2023-09-02T18:48:46.543474Z  INFO new: wasmcloud_host::wasmbus: host ND76IOUWEMSJ7J7564KOMDJQFDCZ2ELSEJXGEQAKEGJNWJE7IWCHYGMX started
```
After:
```
2023-09-02T18:49:16.871191Z  INFO new: wasmcloud_host::wasmbus: wasmCloud host started host_id="NDSF5YY6QIJBG263XY7744JUCQT3OVBC6ROHXC3YAMJTZO7FENWDGGAX"
```
=> chore: emit more clear start message

crates/host/src/lib.rs
The public function `fetch_*` takes `register::Settings` as a parameter, but the *register module* is not public, so it is now exposed so that `fetch_*` can be called externally.
=> fix(host): expose registry as a public module

crates/actor/src/compat/wasmcloud/bus/host.rs, crates/core/src/lib.rs, crates/host/src/wasmbus/mod.rs, crates/runtime/tests/runtime.rs, tests/actors/rust/builtins-compat-reactor/src/lib.rs, tests/actors/rust/builtins-component-reactor/src/lib.rs, tests/actors/rust/builtins-module-reactor/src/lib.rs
This PR fixes a bug where we implicitly assumed namespaces wouldn't contain slashes. However, since call aliases can be defined by users, and our own examples include slashes in call aliases, this assumption is violated.
Instead, we assume the operation string `Interface.Method` won't contain slashes, and split from the right
0.78.0-rc6
Users can now invoke actors via call aliases that include slashes
Updated tests to use a call alias with a slash
Manually tested actor-to-actor calls with aliases which include a slash ([pingpong example](https://github.com/wasmCloud/examples/blob/1670621366866736874d930a411ac8d2a2974af1/actor/actor-to-actor/wadm.yaml))
=> fix: allow namespaces with slashes

crates/host/src/wasmbus/mod.rs
=> fix(host): use named fields when publishing link definitions

.github/workflows/scorecard.yml
This PR adds the openssf scorecard, with publish results on so we can add the scorecard badge to our README. This is a recommended CLOMonitor step. https://clomonitor.io/projects/cncf/wasm-cloud
=> chore: add openssf scorecard action

GOVERNANCE.md, README.md
This PR simply adds information for https://clomonitor.io/projects/cncf/wasm-cloud to properly locate things we've been doing for a while, and some additional fun badges to keep us accountable.
=> Added badges and CLOmonitor information

crates/host/src/wasmbus/mod.rs, crates/tracing/src/context.rs, tests/wasmbus.rs
This PR treats incoming annotations on `stop_actor`, `scale_actor` (to stop), and `stop_provider` as a filter instead of a strict set (or ignored in the case of #606). Please see the description in #607 to see a few examples of this filter in use.
This PR also removes an unnecessary variable `actor_id` from the scale command, and I think we should just completely remove it from the command but that will take place in the control interface.
Fixes #607 
v0.78.0
Modified the wasmbus test to include a few test cases for scale and filtering by annotation.
=> [FEAT] Support annotation filters

crates/host/src/wasmbus/event.rs
This PR serializes actor claims on `actors_started` events in the same format as `actor_started`.
Fixes e2e tests in https://github.com/wasmCloud/wadm/pull/171
v0.78.0-rc10
=> fix(wasmbus): properly format actors_started claims

crates/host/src/policy.rs, crates/host/src/wasmbus/event.rs, crates/host/src/wasmbus/mod.rs, crates/provider-sdk/src/rpc_client.rs, crates/runtime/src/actor/component/mod.rs, crates/runtime/src/actor/mod.rs, crates/runtime/src/actor/module/mod.rs, crates/runtime/src/actor/module/wasmbus.rs, crates/runtime/src/capability/builtin.rs
This updates many instrumented functions to be at the debug or trace level. As a rule of thumb, I moved runtime internals to trace, and host functions to debug
=> chore: reduce verbosity of instrumented functions

crates/host/src/wasmbus/mod.rs, crates/tracing/src/lib.rs
This PR:
- updates the shared tracing code to allow `RUST_LOG` to override log level directives
- proxies `RUST_LOG` from the host to providers
- removes `log_level` from the host_data, since "current" (legacy) providers built from wasmbus-rpc (not the new SDK, which uses the shared tracing code) [ignores `RUST_LOG` when `log_level` in the host data is set](https://github.com/wasmCloud/weld/blob/main/rpc-rs/src/provider_main.rs#L436)
As a result, a command like `RUST_LOG=debug,hyper=info,async_nats=info ./wasmcloud --log-level debug` will:
- for the host: use debug as the default logging level
- note that the host internally already sets `async_nats` and `hyper` to info via the shared [tracing crate](https://github.com/wasmCloud/wasmCloud/blob/main/crates/tracing/src/lib.rs#L271)
- for …
=> fix(logging): proxy RUST_LOG to providers

crates/host/src/wasmbus/config.rs, crates/host/src/wasmbus/mod.rs, src/main.rs, tests/wasmbus.rs
This adds the ability to pass host labels via args to the host, e.g.:
```
./wasmcloud --label cloud=aws -l region=us-east-1
```
```
{"specversion":"1.0","id":"018af29c-45ec-fe01-4c20-f28c5e93d63c","type":"com.wasmcloud.lattice.host_started","source":"NB6UBCPWYG6RSDG2RZVXJPV5TYYJ6ONZPZVUYTVKTIU5SZA34NTIEBL2","datacontenttype":"application/json","time":"2023-10-02T22:57:22.412943Z","data":{"friendly_name":"dark-moon-7391","labels":{"cloud":"true","hostcore.arch":"aarch64","hostcore.os":"macos","hostcore.osfamily":"unix","region":"us-east-1"},"uptime_seconds":0,"version":"0.79.0"}}
```
If a label isn't provided with the right syntax, an error is returned and the host fails to start:
```
./wasmcloud --label foobar
Error: failed to parse labels
Caused by:
invalid label format `foobar`. …
```
=> feat(host): parse labels from args

crates/host/src/wasmbus/mod.rs, tests/wasmbus.rs
This PR moves the heavy-IO work of downloading the wasmCloud actor before scaling into a tokio task (and subsequently the rest of the work) in order to quick-ack the control interface request and be able to handle additional commands.
Part of this work is done in #710 but it's more essential to release and can go with 0.79.0 directly.
v0.79.0-rc2
Consumers of the control interface client will no longer receive an error unless the actual scale payload is invalid. Validation of running actors and downloading of the image reference is done within the task, so the only thing we can do there is send out `actors_start_failed` commands.
=> fix(wasmbus): download actor to scale in task

crates/tracing/src/lib.rs
This fixes an issue with https://github.com/wasmCloud/wasmCloud/pull/708, where we attempt to parse all of `RUST_LOG` at once. Apparently directives need to be split by `,` before parsing
=> fix(tracing): split directives before trying to parse

Cargo.lock, Cargo.toml, crates/provider-wit-bindgen/Cargo.toml, crates/provider-wit-bindgen/src/lib.rs, crates/provider-wit-bindgen/src/vendor/wasmtime_component_macro/bindgen.rs, crates/providers/Cargo.lock
Update vendored `wasmtime-component-macro` and related deps used by `provider-wit-bindgen`.
We're also able to remove our dependency on the older version of `syn` as newer versions of `wasmtime-component-macro` have upgraded.
Consumers are able to use latest & greatest features of `wasmtime-component-macro`, if desired.
=> chore: upgrade vendored wasmtime-component-macro bindgen

.github/CODEOWNERS
This way if Roman goes on vacation others can still review and enable auto-merge for changes against these paths :)
=> chore: add ci-maintainers to Nix-related paths

crates/host/src/wasmbus/mod.rs
This updates the expected env var prefix for host labels from `HOST_` to `WASMCLOUD_HOST_` (and deprecates the former)
Related to https://github.com/wasmCloud/wasmcloud-otp/issues/637
Next
Nothing for now, but eventually we will remove support for `HOST_` prefixes. That will solve the interaction with Nix/any other system which uses this prefix, and will break old scripts, so we'll have to wait a while before doing that.
Tested manually:
```
HOST_foo=bar ./target/debug/wasmcloud
2023-10-06T20:36:13.821866Z  WARN new: wasmcloud_host::wasmbus: labels set via HOST_ environment variables are deprecated. Please use WASMCLOUD_HOST_ as the prefix instead
2023-10-06T20:36:13.824337Z  INFO async_nats::options: event: connected
2023-10-06T20:36:13.824537Z …
```
=> fix: deprecate HOST_ label prefix in favor of WASMCLOUD_HOST_

.gitignore, Cargo.lock, Cargo.toml, crates/host/src/lib.rs, crates/host/src/local/mod.rs, crates/host/src/wasmbus/mod.rs, crates/runtime/src/actor/component/blobstore.rs, tests/wasmbus.rs, vendor/capability-providers/sqldb-postgres/src/config.rs
This PR features a few prominent changes to the handling of control interface requests, namely `scale`, `start`, and `stop` when it comes to actor components.
**External facing things**
1. Scale and Start now use `max_concurrent` instead of `count` to describe the handling of multiple instances of an individual actor. Per RFC #696, this accurately describes the way we instantiate actors, instantiating on request to handle an invocation and then exiting rather than running a certain number of things.
2. The `ActorInstance` is now the entity that stores an image reference rather than an `Actor`. This functionally doesn't change anything at this time but enables us in the future to consider running different image references of the same actor. We still report the image reference on the host …
=> [FEAT] Actor Autoscaling and scale to zero

.github/workflows/docker.yml, .github/workflows/nix.yml, .github/workflows/wasmcloud.yml
This enables our workflows on the `merge_group` event, which is used by [the merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions). Once this is validated, we can enable a merge queue to prevent issues caused by merging PRs which work independently but cause issues when integrated together
https://github.com/wasmCloud/wasmCloud/issues/424
=> ci: add merge_group event trigger to support merge queue

crates/core/src/chunking.rs, crates/provider-sdk/src/provider.rs, crates/provider-sdk/src/rpc_client.rs, crates/providers/http-server/src/lib.rs
There's a bug somewhere in the tracing/opentelemetry/collector stack where certain configurations don't play nicely with error events/logs which include `error` as a field. It seems `error` always gets set to `true`, regardless of whether the tracing information had other contents. Renaming this field to `err` is a workaround so error messages make it through to tracing tools
=> chore: replace error field name with err

.github/workflows/wasmcloud.yml
I had a sad:
```
docker run wasmcloud/wasmcloud:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
wasmcloud 0.18.2
```
=> ci: publish latest tag

Cargo.lock, crates/providers/Cargo.lock, crates/wascap/Cargo.toml, crates/wascap/src/caps.rs
This commit removes the use of `once-cell` in favor of `std::sync::OnceLock`
=> refactor(wascap): use `OnceLock` to remove `once-cell`

Cargo.lock, Cargo.toml, crates/host/Cargo.toml, crates/host/src/wasmbus/mod.rs
In https://github.com/wasmCloud/wasmCloud/pull/731, we renamed the expected prefix from `HOST_` to `WASMCLOUD_HOST_`. Unfortunately, this collides with the existing `WASMCLOUD_HOST_SEED` argument, and results in hosts which have a seed specified via env var gaining a `SEED=XXXXXXXX` label
Note: while "seed" makes this sound like it could be a security vulnerability, the host's ID keypair is not used in the signing/verifying of invocations or other security-related functionality.
v0.79.1
=> fix: change expected host label prefix to remove collision with WASMCLOUD_HOST_SEED

chart/.helmignore, chart/Chart.yaml, chart/README.md, chart/templates/NOTES.txt, chart/templates/_helpers.tpl, chart/templates/deployment.yaml, chart/templates/leafnode.yaml, chart/templates/role-binding.yaml, chart/templates/role.yaml, chart/templates/secret.yaml, chart/templates/service.yaml, chart/templates/serviceaccount.yaml, chart/values.yaml
Enables the installation of Rust-based wasmCloud host via `helm`.
#684, also supersedes #785.
=> Migrate helm chart from wasmcloud-otp

crates/providers/Cargo.lock
This syncs Cargo.lock. It not being in sync was making switching branches annoying
=> chore: update Cargo.lock

README.md
This updates the README in a few ways:
- distinguish between the stable and experimental ABIs
- mark OTP host as deprecated and un-marks the Rust host as experimental
- documents some more crates we've moved into this repo, and a couple others that aren't in this repo, for increased discoverability
- adds some greater visual separation between sections
For a preview of the changes, see https://github.com/connorsmith256/wasmCloud/tree/chore/update-readme
=> chore: update README with latest information

.github/workflows/wasmcloud-chart.yml, chart/Chart.yaml
Adds a pipeline that validates the helm chart (added in #788) and (on `chart-vX.X.X` push) publishes the helm chart to `ghcr.io/wasmcloud/wasmcloud-chart`.
#684
=> Add pipeline for validating and publishing the wasmcloud helm chart

crates/host/src/wasmbus/mod.rs
This PR splits processing historical lattice metadata entries into two parts:
- on startup, the host reads all entries out of the bucket and initializes its cache of link defs/claims. It should not publish link def put/deleted events for historical entries
- on startup, the host starts listening to new entries. For new entries, the host should publish link def put/deleted events
Next
The host should simply emit fewer events on startup
Ran the host, confirmed a bunch of `process_entry` logs were emitted, but no `linkdef_set` events were, until I ran `wash link put`
=> fix: stop sending linkdef events on startup

crates/host/src/wasmbus/mod.rs
This PR fixes a regression where we no longer published the correct number of `actor_started` and `actor_stopped` events in response to scaling an actor. This affects downstream consumers of the non-plural events when they are using the `scale` ctl operation command.
Because of the scenario where we may scale up or down, I refactored the event publishing code to be outside of the instantiate/uninstantiate function.
Regression introduced in #710 
v0.80.0
=> fix: publish correct number actor events

crates/host/src/wasmbus/mod.rs
This PR resolves a problematic ordering of locks in our concurrent control interface code. 
After doing some investigation, it looks like the ordering here is problematic. We write lock the actors RwLock and then read links, but during handling a linkdef put we write lock the links and then read lock actors. 
```rust
// handle_scale_actor_task
match (self.actors.write().await.entry(actor_id), requested_max) {
...
(hash_map::Entry::Vacant(entry), max) => {
// Starting 0 actors makes no logical sense and is interpreted as starting with unbounded concurrency
self.start_actor(entry, actor, actor_ref, max.flatten(), host_id, annotations)
.await?;
// a few lines inside start_actor
let links = self.links.read().await;
```
```rust
// process_linkdef_put
let mut links = self.links.write().await; …
```
=> fix: drop problematic write lock

crates/wash-lib/src/build.rs, crates/wash-lib/src/parser/mod.rs, crates/wash-lib/tests/parser/files/tags.toml, crates/wash-lib/tests/parser/main.rs
The signing process enabled by the wasmCloud ecosystem can confer tags on to generated artifacts. This helps in adding metadata to actors and other artifacts produced by wash.
This commit adds the ability to specify tags in `wasmcloud.toml` to `wash`, so users can more easily tag generated & signed actors
https://github.com/wasmCloud/wash/pull/951
=> feat: support specifying tags in actor config for use when signing

.github/workflows/wasmcloud.yml
I noticed the OCI build [references a file that doesn't exist](https://github.com/wasmCloud/wasmCloud/actions/runs/6698481609/job/18201730394), so I updated the workflow
=> fix(ci): use wash Dockerfile

.github/workflows/docker.yml
`dockerfile` isn't a valid parameter name. I think we want `file`: https://github.com/wasmCloud/wasmCloud/actions/runs/6698978154
=> fix(ci): fix parameter name

crates/wash-cli/src/keys.rs, crates/wash-cli/tests/wash_keys.rs
There is a problem with `wash keys` in that it always defaults to a module key, when that's not great behavior. The `keytype` arg appears to default to module even if the input is invalid, but we should error out if invalid input is inserted.
#863 
v0.79.0
improves correctness of `wash keys gen <keytype>` command
- updated [test_gen_comprehensive](https://github.com/ahmedtadde/wasmCloud/blob/69db9efcf9d8352bd3a85caea45422162d883f32/crates/wash-cli/src/keys.rs#L272)
- updated [test_invalid_keytype_input](https://github.com/ahmedtadde/wasmCloud/blob/69db9efcf9d8352bd3a85caea45422162d883f32/crates/wash-cli/src/keys.rs#L303)
- updated [integration_keys_gen_comprehensive](https://github.com/ahmedtadde/wasmCloud/blob/69db9efcf9d8352bd3a85caea45422162d88 …
=> [FEATURE] wash keys clarity, renames, and error handling

src/main.rs
@jordan-rash pointed out these options were hidden, so I un-hid them 🙂
=> chore: un-hide policy options

.github/workflows/wasmcloud.yml
I was about to release wash-lib v0.13.0, and realized this was missing
=> fix(ci): add wash-lib to list of crates possible to release

Cargo.toml
Publishing `wash-lib` failed because our workspace uses wildcard constraints:
```
the remote server responded with an error: wildcard (`*`) dependency constraints are not allowed on crates.io. Crate with this problem: `provider-archive` See 
```
https://github.com/wasmCloud/wasmCloud/actions/runs/6723759809/job/18274709187
This updates the workspace dep versions to not use `*` in cases where we want to publish crates for downstream consumption, e.g. `wash-lib`
=> fix(releases): use version numbers of internal crates to allow publishing to crates.io

.github/workflows/wasmcloud.yml
Don't do.
There was a syntax error in this script preventing host releases: https://github.com/wasmCloud/wasmCloud/actions/runs/6737821381/job/18316486221
=> fix(ci): fix syntax in release script

.github/workflows/wasmcloud.yml
I noticed publishing `v0.80.0-alpha1` overwrote the `latest` docker tag 😔
=> fix(ci): only overwrite latest tag on stable releases

.github/workflows/wasmcloud.yml
I'm not 100% confident in this, but it seems `${dir}/wasmcloud-${target}/` effectively doubles up on `wasmcloud-${target}`:
https://github.com/wasmCloud/wasmCloud/actions/runs/6738319353/job/18318008734
=> fix(ci): remove duplicated path

.github/workflows/wasmcloud.yml
`mkdir -p ${bin}` won't work, because `${bin}` is the actual binary (since we ran `chmod` on it). Instead, move all artifacts to an `artifacts` directory
=> fix(ci): create artifacts directory for final upload

.github/workflows/wasmcloud.yml
This fixes one more confusion between paths and binary names
=> fix(ci): disambiguate bin from bin_path

.github/workflows/wasmcloud.yml
Left a typo I fixed in a local script but not in-tree 🤦
=> fix(ci): fix typo

.github/workflows/wasmcloud.yml
This fixes another reason the release step was failing: the OCI image artifacts and universal binary artifact don't have a `bin/` subdirectory, they just include a single file
=> fix(ci): account for OCI images and universal binary artifacts

.github/workflows/wasmcloud.yml
`#` is for stripping prefixes, but we want to strip the `.exe` suffix, so we need `%`
=> fix(ci): fix typo stripping suffix

crates/providers/Cargo.lock, crates/wash-cli/tests/wash_claims.rs, crates/wash-lib/src/build.rs, crates/wash-lib/src/cli/claims.rs, crates/wash-lib/src/parser/mod.rs, crates/wash-lib/tests/parser/files/rust_actor_with_revision.toml, crates/wash-lib/tests/parser/main.rs
Currently, when signing an actor with wash, the version (--ver) and revision (--rev) args are not required. This will lead to claims that are missing some important information.
[859](https://github.com/wasmCloud/wasmCloud/issues/861)
v0.79.0
stricter `wash claims sign` cmd that ultimately improves the metadata output of `wash inspect`
updated integration tests [integration_claims_sign](https://github.com/ahmedtadde/wash/blob/0939a7d4b1c8c229386baedccbaef9f3621071c6/tests/integration_claims.rs#L12), [integration_claims_call_alias](https://github.com/ahmedtadde/wash/blob/21f9f2f4d751e29e88fd8990ef9014a310ed425a/tests/integration_claims.rs#L328)
=> [BUG] wash claims sign allows empty versions and revisions

.github/workflows/wash.yml, Cargo.lock, crates/wash-cli/Cargo.toml, crates/wash-cli/src/ui/mod.rs
This changes `wash ui` to download the washboard assets from a released version instead of embedding local files, which will enable publishing wash
The version defaults to v0.1.0 for now, but can be specified with `--version`:
```
./target/debug/wash ui --version v0.1.0
Washboard running on http://localhost:3030
Hit CTRL-C to stop
```
@lachieh do we need to allow overriding this behavior for local dev? Or should local dev always be done via `make run-ui`?
Resolves https://github.com/wasmCloud/wasmCloud/issues/875
v0.22.0
Built and ran locally, and confirmed I could serve the washboard UI
=> feat(wash): download washboard assets from releases instead of embedding from source

.github/workflows/wasmcloud.yml
Apparently logging into ACR breaks buildx? So I moved these steps to right before we need them: https://github.com/docker/build-push-action/issues/163#issuecomment-918590372
=> fix(ci): set up buildx after logging into ACR

.github/workflows/wasmcloud.yml
This disables the docker build-and-push step for wash, since we're currently getting 403s: https://github.com/wasmCloud/wasmCloud/actions/runs/6750332769/job/18352964847
Disabling this should allow the github release to proceed
=> ci(wash): disable docker build and push temporarily

crates/host/src/lib.rs, crates/host/src/policy.rs, crates/host/src/wasmbus/event.rs, crates/host/src/wasmbus/mod.rs, crates/runtime/src/actor/mod.rs, crates/runtime/src/actor/module/mod.rs, crates/runtime/src/actor/module/wasmbus.rs
🧹 Generally speaking, I went with:
- set instrumentation to trace if it's not useful for day-to-day observability debugging
- used `skip_all` in most places, unless there was a reason to include a field or two on spans
- downgraded many log messages to trace
- kept most logs at debug, unless they occur infrequently
- introduced several log messages at info, to give users a better idea of what the host is doing (e.g. after scaling an actor)
- removed sensitive information from logs
- updated `handle_ctl_message` to gracefully handle more error cases
Here are some before and after screenshots, when the log level is set to debug:
Scaling up an actor:
Before: 
After:
Handling an RPC call from a provider:
Before:
After:
Startup logs (deploying a KV app):
Before:
After:
=> chore(host): polish tracing and logging levels

crates/wash-cli/src/keys.rs
https://github.com/wasmCloud/wasmCloud/pull/882 added alias support for `wash keys gen` module -> actor, service -> provider, and server -> host, to accommodate nouns in the wasmCloud ecosystem. This simply clarifies the help text a little to make it more clear that these are aliases
Resolves https://github.com/wasmCloud/wasmCloud/issues/863
=> docs(wash-cli): update help text for keys gen

crates/wash-cli/README.md
Add a couple callouts for how new users can set up the language toolchains expected by wash
Resolves https://github.com/wasmCloud/wasmCloud/issues/847
=> docs(wash-cli): add instructions for setting up language toolchains

chart/README.md
While the official wasmcloud Helm chart was recently updated and published to ArtifactHub, the README was still referencing the old OTP host's Helm chart.
This commit updates the helm chart README to use recent Helm install instructions that are posted to the ArtifactHub page, and also reference that page so users can find the listing.
=> fix(docs): update helm chart install to use artifacthub

Cargo.lock, Cargo.toml, crates/wash-cli/Cargo.toml, crates/wash-cli/src/call.rs, crates/wash-cli/src/util.rs
Replace `wasmbus_rpc` by `wasmcloud_core` and `wasmcloud_provider_sdk`
This is the last occurence of usage of `wasmbus_rpc` within the root workspace. Only providers left (e.g. #745 )
#641
=> chore(wash-cli): remove `wasmbus_rpc` dependency

Cargo.lock, Cargo.toml, crates/wash-cli/Cargo.toml, crates/wash-cli/src/call.rs
Copy-paste relevant code from `wasmcloud-test-util` and `wasmcloud-interface-testing` to get rid of 492 lines of Cargo.lock removing transitive dependency on `wasmbus-rpc`, outdated `wascap` and, most importantly `ring`
Unblock #724
=> chore(wash-cli): remove `wasmcloud-test-util` dependency

crates/wash-cli/src/call.rs
=> fix(wash-cli): use valid host and public keys for wash call

chart/values.yaml
It was pointed out in #978 that the defaults we have in our chart's `values.yaml` for securityContext that gets configured for the both of the containers included in the Chart does not meet the recommendations from a security standpoint.
This PR adds a set of defaults that meets the [Restricted profile as outlined in Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/).
https://github.com/wasmCloud/wasmCloud/issues/978
I've tested this locally against a [KinD cluster running 1.27.3 (latest available KinD version)](https://github.com/kubernetes-sigs/kind/releases/tag/v0.20.0), and from review the [`1.28` changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.28.md), it did not appear anything had changed in a material …
=> Adopt Restricted profile recommendations as default securityContext for wasmcloud-chart containers

crates/wash-cli/src/up/config.rs, crates/wash-cli/src/up/mod.rs
The host added support for setting labels via `--label` and `WASMCLOUD_LABEL_XXXX` in https://github.com/wasmCloud/wasmCloud/pull/706. This adds `--label` support to `wash up`
Resolves https://github.com/wasmCloud/wasmCloud/issues/856
Next
Yay
```
./target/debug/wash up --label foobar --label baz=qux
invalid label format `foobar`. Expected `key=value`
```
```
./target/debug/wash up --label foo=bar --label baz=qux
```
```
[#12] Received on "wasmbus.evt.default"
{"specversion":"1.0","id":"018bbb2a-146b-8cab-c466-fdeccc416696","type":"com.wasmcloud.lattice.host_stopped","source":"NB3Q76LIMMFFCWP5Q62E4MWPQ7UNFDWUKGPGNDL532GCTZ5Z5VEAK2KQ","datacontenttype":"application/json","time":"2023-11-10T21:36:19.051304Z","data":{"labels":{"baz":"qux","foo":"bar","hostcore.arch":"aarch64","hostcore.os":"m …
```
=> feat(wash-cli): add --label option to wash up

Cargo.lock, crates/wash-cli/Cargo.toml, crates/wash-lib/Cargo.toml
Minor bumps for both since there have been breaking changes:
- bumps to dependencies in wash-lib (e.g. wadm)
- updates to `--context` semantics in wash-cli
=> Release/wash cli v0.23.0

.github/workflows/wasmcloud.yml
Release script expects all artifacts to be located in `wasmcloud-*`, but we were uploading `wash` LIPO into `wash-universal-darwin`. Use `wasmcloud-universal-binary` artifact for both LIPOs, just like for all other binaries.
=> ci: upload `wash-universal-darwin` binary

Cargo.lock, crates/control-interface/Cargo.toml
The current control interface uses async-nats v0.33, which creates a breaking change with downstream dependencies that may use another version of async-nats. This necessitates a minor bump
=> release(control-interface): v0.32.0

crates/wash-cli/src/common/link_cmd.rs, crates/wash-cli/src/common/start_cmd.rs, crates/wash-cli/src/common/stop_cmd.rs, crates/wash-cli/src/ctl/mod.rs, crates/wash-cli/src/ctl/output.rs, crates/wash-cli/tests/wash_start.rs, crates/wash-cli/tests/wash_stop.rs, crates/wash-cli/tests/wash_update.rs, crates/wash-lib/src/cli/get.rs, crates/wash-lib/src/cli/link.rs, crates/wash-lib/src/cli/scale.rs, crates/wash-lib/src/cli/start.rs, crates/wash-lib/src/cli/stop.rs, crates/wash-lib/src/cli/update.rs, crates/wash-lib/src/common.rs
This is something that has been bugging me for a while. It has been such a pain to look up and copy paste all the proper IDs to run various wash commands.
This PR is a breaking change for several commands (like stop provider, which reorders some things and most other commands requiring a host ID now have that as an optional flag) and makes it so you can pass a string that it will attempt to match on to find IDs
vNext
Namely the structure of many of the commands have changed, but since everything requires less, I think this is fine
I added a few more tests in places where we already had some and then manually verified the rest
```
./target/debug/wash link put echo 'http server' wasmcloud:httpserver 'ADDRESS=0.0.0.0:8080'
Published link (echo) <-> (http server) successfully
```
After …
=> feat(wash)!: Removes need for actor/provider/host IDs in almost all cases

Cargo.toml, crates/providers/Cargo.lock
It appears that this may prevent #1038 from happening in the future by enforcing that the same version of control interface is used as during publish.
Note, that this likely will block releases of `wash-cli` including control interface updates on `wadm` updates (which would be a good thing)
=> build: pin control interface version

.github/workflows/wasmcloud.yml, crates/wash-lib/src/start/wasmcloud.rs, flake.nix
Provide RISCV64 GNU binaries (musl is.. complicated for now)
Closes #724 
Closes #853 
~Blocked on https://github.com/wasmCloud/wadm/pull/218/commits/2e0e33319556d067e9664a321908ad505ba82648~
~Blocked on #935~
=> build: add `riscv64gc-unknown-linux-gnu` build

Cargo.lock, crates/wash-lib/Cargo.toml
https://github.com/wasmCloud/wasmCloud/pull/1049 bumped wash-cli, but wash-lib v0.14 still uses async-nats v0.31, so we need a minor bump here as well
=> release(wash-lib): v0.15.0

crates/providers/Cargo.lock, crates/wash-cli/.gitignore, crates/wash-cli/tests/common/mod.rs, crates/wash-cli/tests/wash_start.rs, crates/wash-cli/tests/wash_stop.rs
`TestWashInstance` is a test utility struct that encapsulates (and tracks) child processes spawned by `wash` so that they can be cleaned up upon `drop()`, and information about spawned hosts can be retrieved.
Some invocations of `wash` itself (normally from tests that ensure functionality works have been moved into `TestWashInstance` to make them easier to call -- with the *current* built version of `wash` (i.e. the cargo-provided ENV variable `CARGO_BIN_EXE_wash`).
This commit adds more invocations (`wash start provider`, `wash stop actor`, `wash stop host`) into the `TestWashInstance` struct used from tests, shortening the code required for individual tests.
All integration tests should be using the new code (and still passing)
Verified manually
=> refactor(wash-cli): move more wash invocations into TestWashInstance

Cargo.lock, Cargo.toml, crates/core/Cargo.toml
This PR bumps wasmcloud-core for 0.2.0 release in order to fix transitive conflicting NATS dependencies.
wasmcloud-core 0.2.0
=> chore(core)!: bump to 0.2.0 for async-nats release

crates/control-interface/src/broker.rs, crates/control-interface/src/lib.rs, crates/control-interface/src/types.rs, crates/host/src/wasmbus/mod.rs, tests/wasmbus.rs
This adds two new topics to the host's control interface: `wasmbus.ctl.{lattice_id}.labels.{host_id}.{put/del}`. Publishing on these topics allows users to dynamically adjust the target host's labels
Relates to https://github.com/wasmCloud/wasmCloud/issues/692
Minor bump to the control interface crate as well as the host. Functionality via wash to be added after both of the former are released
This is a potentially a step in the direction of enabling lame-duck mode on the host (we could use a special label to convey that intent)
I exercised put and delete via the wasmbus tests
```
wash get hosts -o json | jq -r '.hosts | .[] | .labels'
{
"hostcore.arch": "aarch64",
"hostcore.os": "macos",
"hostcore.osfamily": "unix"
}
nats req wasmbus.ctl.default.labels.NARZ43WTEW56DC3Q42FXIND2WJV5TFVTBYJB …
```
=> feat: enable updating host labels via the control interface

Cargo.lock, crates/control-interface/src/broker.rs, crates/control-interface/src/lib.rs, crates/host/src/wasmbus/event.rs, crates/providers/nats/README.md, tests/wasmbus.rs, washboard-ui/src/lattice/lattice-service.ts
This publishes events on `wasmbus.evt.{latticeID}.{eventName}`, in addition to the existing subject. The existing subject should be removed prior to wasmCloud 1.0
Resolves https://github.com/wasmCloud/wasmCloud/issues/1089
Next
None for now, but removing the existing subject will be a breaking change
Updated the wasmbus tests to subscribe to the new subjects
```
nats sub 'wasmbus.evt.>'
14:33:04 Subscribing on wasmbus.evt.>
[#1] Received on "wasmbus.evt.default"
{"specversion":"1.0","id":"018c0866-8bc3-d066-599f-da1fa20d346e","type":"com.wasmcloud.lattice.host_started","source":"NBG37K5KJUZ3SRRCOTFG3IOIRA77FFG3HINLDD66HXCECGEHJ4VWB7RB","datacontenttype":"application/json","time":"2023-11-25T21:33:07.395933Z","data":{"friendly_name":"mauve-dew-2146","labels":{"hostcore.arch":"aarch64","host …
```
=> feat(host): add event name as suffix on event subject

crates/host/src/wasmbus/mod.rs, crates/wash-cli/src/ctl/output.rs
This:
- updates the serialized format for claims
- actor and provider claims are now separate, removing the unused fields from each
- `sub` (`subject`), `iss`, (`issuer`), `caps` (`capabilities`), and `rev` (`revision`) are no longer abbreviated
- serde's `alias` is used to maintain backwards-compatibility with deserializing
- `capabilities` and `tags` are now `Vec<String>` instead of a comma-delimited string
- backwards-compatibility was maintained via a custom deserializer/visitor 
- both abbreviated and non-abbreviated fields are sent over the wire to maintain backwards-compatibility
- updates wash to expect the non-abbreviated fields
**Note** wadm needs to be updated to not expect the abbreviated fields as well, before the abbreviated fields can be removed
Resolves …
=> fix(host): update format for serialized claims

crates/host/src/wasmbus/mod.rs
Update the host to override previously cached call aliases when an alias is re-used. The host will emit a warning, since this can result in unintuitive behavior
Resolves https://github.com/wasmCloud/wasmCloud/issues/1011
Next
Built two copies of the ponger actor, ponger1 and ponger2:
```
wash start actor file://$(realpath pinger/build/pinger_s.wasm)
wash start provider wasmcloud.azurecr.io/httpserver:0.19.1
wash link put MB2SLLXFTWEX7HR6F6PTLPWSU35MJKHR6CQHFN4QCWEIVBVJA2CFXHLY VAG3QITQQ2ODAOWB5TTQSDJ53XK3SHBEIFNK4AYJ5RKAX2UNSCAPHA5M wasmcloud:httpserver address=0.0.0.0:1234
```
```
wash start actor file://$(realpath ponger1/build/ponger_s.wasm)
curl 127.0.0.1:1234
Ping pong1%
wash start actor file://$(realpath ponger2/build/ponger_s.wasm)
curl 127.0.0.1:1234
Ping pong2%
```
=> fix(host): override previous call alias on clash

.github/dependabot.yml
Dependabot can be pretty noisy, and since the washboard doesn't have as many maintainers or get as many contributions, daily updates feel excessive
=> ci: reduce dependabot frequency to weekly for washboard-ui

Cargo.lock, crates/control-interface/Cargo.toml, crates/control-interface/src/types.rs, crates/wash-cli/src/common/registry_cmd.rs, crates/wash-cli/tests/common/mod.rs, crates/wash-cli/tests/wash_reg.rs, crates/wash-lib/src/build.rs, crates/wash-lib/src/cli/registry.rs, crates/wash-lib/src/parser/mod.rs, crates/wash-lib/tests/parser/main.rs
As a user, I would really like it if I didn't have to manually type out my URL to push my actor every time I need to push a new version.
#860 
`wash-cli v0.23.0`
better DX
[intergration_reg_config](https://github.com/ahmedtadde/wasmCloud/blob/63d95e548e5fa063bcc7c38ae4009c6f85928f72/crates/wash-cli/tests/wash_reg.rs#L248)
=> [FEATURE] support for registry config in wasmcloud.toml 

crates/control-interface/src/broker.rs, crates/control-interface/src/lib.rs, crates/control-interface/src/types.rs, crates/host/src/wasmbus/mod.rs, crates/wash-cli/src/common/stop_cmd.rs, crates/wash-cli/src/ctl/mod.rs, crates/wash-lib/src/actor.rs, crates/wash-lib/src/cli/dev.rs, crates/wash-lib/src/cli/stop.rs, tests/common/mod.rs
In #710 we introduced a few clippy warnings about deprecated control interface functionality in order to support the start actor command in a backwards compatible way. As of the control interface 0.29.0 and applicable wadm/wash versions (TBD), this command isn't used anywhere and can be fully removed instead of just deprecated.
#740 
`wasmCloud v0.80` & `wash-cli v0.24.1`
there should be none
all unit tests and integration tests pass
=> refactor: remove deprecated code related to start actor cmd

.github/dependabot.yml
Dependabot supports a `group` setting, which tells dependabot to open PRs [as a group](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#example-3)
Resolves https://github.com/wasmCloud/wasmCloud/issues/1162
=> ci(dependabot): group wasmtime dependencies

crates/wash-cli/src/par.rs, crates/wash-lib/Cargo.toml, crates/wash-lib/src/cli/claims.rs, crates/wash-lib/src/cli/inspect.rs
This PR allows `wash` users to add `--wit` after or before their file/oci reference to print out the embedded wit world in a WASI preview 2 component. In the case that it is an empty wit world, it's assumed that it is a WASI preview 1 component and we output a message accordingly.
I also changed the heading from the claims inspect from `Module` to `Actor` and `Provider Archive` to `Capability Provider`. Keeping it as module just felt confusing when we'll be inspecting components too.
```
cargo run -- inspect wasmcloud.azurecr.io/echo:0.3.4      
Finished dev [unoptimized + debuginfo] target(s) in 0.36s
Running `/Users/brooks/github.com/wasmcloud/wasmCloud/target/debug/wash inspect 'wasmcloud.azurecr.io/echo:0.3.4'`
Echo - Actor                               
Account …
```
=> feat(wash-lib)!: add support for inspecting wit

crates/wash-lib/Cargo.toml
It looks like the `docs` feature got dropped from `wasmcloud-component-adapters`. I think we need this enabled in order to ensure the docs.rs build will pass (by avoiding downloading the adapters, which will fail inside the container)
=> fix(wash-lib): enable docs feature when building for docs.rs

crates/wash-lib/src/generate/git.rs
This PR addresses an issue where our shallow clone of a repository wouldn't `fetch` the branches. Now the `wash new` command will fetch a git repository using only the supplied branch, defaulting to `main` if not supplied.
Fixes #845
next
This doesn't change default behavior, but users that are attempting to clone templates from a repo where the primary branch is `master` will have to supply `--branch master`
Made sure this worked with #1184
=> fix(wash-lib): fix generating from git branch

crates/providers/blobstore-fs/src/bin/blobstore_fs.rs, crates/providers/blobstore-s3/src/bin/blobstore_s3.rs, crates/providers/http-client/src/bin/httpclient.rs, crates/providers/kv-redis/src/bin/kvredis.rs
This commit makes the kebab case used in provider names consistent for
in-tree providers that have been converted to use the `provider-wit-bindgen` crate.
=> chore(providers): consistent kebab case names for start_provider()

Cargo.lock, Cargo.toml, crates/host/Cargo.toml, crates/wash-cli/Cargo.toml, crates/wash-cli/src/up/config.rs, crates/wash-cli/src/up/mod.rs, crates/wash-lib/Cargo.toml, crates/wash-lib/src/start/wasmcloud.rs
- chore: bump wasmcloud to 0.81
- chore: bump wash-lib to 0.16
- chore: bump wash-cli to 0.25
This PR bumps wasmcloud, wash-lib, and wash-cli for release. We can merge this PR but it is not quite ready to release yet as there are one or two more changes required before we release:
wasmCloud 0.81
wash-lib 0.16
wash-cli 0.25
I was able to `--dry-run` publish both wash-lib and wash-cli (minus the dependency on wash-lib 0.16).
Additionally, I used the following commands to verify the proper semver release for all of these crates:
```
➜ convco version --bump
0.81.0
➜ convco version --prefix wash-lib-v -P crates/wash-lib --bump
0.16.0
➜ convco version --prefix wash-cli-v -P crates/wash-cli --bump
0.25.0
```
This PR changed the Windows artifact to `pc-windows-msvc` as per #807, so we're …
=> chore: wasmCloud 0.81 bumps

chart/templates/deployment.yaml, crates/wash-cli/src/up/config.rs
This removes references to PROC_RPC settings from wash and the helm chart, in anticipation of wasmcloud v0.81, which no longer supports these settings
=> chore: remove references to PROV_RPC settings

crates/wash-cli/src/common/start_cmd.rs, crates/wash-lib/src/cli/start.rs
A few users have been confused trying to run commands like `wash start actor /path/to/file` and seeing an error (from the host). The `file://` scheme is rough devX, so instead, if wash can detect the reference is an absolute file path (i.e. it starts with a `/`), wash can simply prefix the reference for the user
=> feat(wash-cli): prefix absolute path references with file://

crates/wash-cli/src/up/mod.rs, src/main.rs
consistent namespace prefixes for cli flags
https://github.com/wasmCloud/wasmCloud/issues/1102
=> feat: consistently prefix wash-cli arguments

crates/wash-lib/src/build.rs, crates/wash-lib/src/cli/claims.rs, crates/wash-lib/src/cli/mod.rs, crates/wash-lib/tests/parser/files/rust_actor_claims_metadata.toml, crates/wash-lib/tests/parser/files/rust_provider_claims_metadata.toml
Just like wash build infers information about a project from the `wasmcloud.toml` file, it should be a one step process to run wash claims sign to sign an existing `wasm` file without building.
#1101
`wash-cli v0.25.0`
better dx
- all existing tests work as expected; refactor has no regression
- added [rust_actor_metadata_with_project_config_overrides](https://github.com/ahmedtadde/wasmCloud/blob/39d635f907431df5ee814c5d8a13c72f228ec0d5/crates/wash-lib/src/cli/claims.rs#L1384) and [rust_provider_metadata_with_project_config_overrides](https://github.com/ahmedtadde/wasmCloud/blob/39d635f907431df5ee814c5d8a13c72f228ec0d5/crates/wash-lib/src/cli/claims.rs#L1540) to test `wasmcloud.toml` configuration on `wash claims ...` commands
all existing tests work as expected; refactor has no …
=> [FEAT] Make wash claims aware of wasmcloud.toml

crates/wash-cli/src/up/config.rs, crates/wash-lib/src/start/wasmcloud.rs
This PR just updates the wasmCloud version in wash-cli to be pinned to v0.81.0 instead of the release candidate for release.
As far as I know this was the only outstanding change, please request changes on this PR if you're aware of something else.
N/A
wash-lib 0.16.0
wash-cli 0.25.0
=> chore(wash-cli): update wasmcloud version to 0.81

Cargo.lock, crates/control-interface/Cargo.toml, crates/providers/Cargo.lock
Below is the generated changelog for the control interface.
* **host:** add event name as suffix on event topic
([6994a22](https://github.com/wasmCloud/wasmCloud/commit/6994a2202f856da93d0fe50e40c8e72dd3b7d9e6))
* enable updating host labels via the control interface
([85cb573](https://github.com/wasmCloud/wasmCloud/commit/85cb573d29c75eae4fdaca14be808131383ca3cd))
This PR bumps the control interface to `0.32.1` as per the conventional commits specifying no breaking changes. This is required to bring in a `TryFrom` impl.
control-interface v0.32.1
=> chore(control-interface): bump to 0.32.1

examples/docker/README.md, examples/docker/docker-compose-auxiliary.yml, examples/docker/docker-compose-full.yml, examples/docker/grafana-datasources.yaml, examples/docker/tempo.yaml
This migrates the docker compose examples into the main repo. The contents are mostly the same as https://github.com/wasmcloud/examples/tree/main/docker, but with updated versions and a more detailed README
=> feat(examples): add docker compose examples

crates/wash-cli/src/up/config.rs, crates/wash-cli/src/up/mod.rs, crates/wash-cli/tests/common/mod.rs, crates/wash-cli/tools/docker-compose.yml, crates/wash-lib/src/start/mod.rs, crates/wash-lib/src/start/nats.rs, crates/wash-lib/src/start/wasmcloud.rs
This bumps the NATS server versions everywhere to the latest release (2.10.7)
=> chore(wash-cli): bump NATS server version

chart/Chart.yaml, chart/README.md, chart/values.yaml
This bumps the version of the host in the chart to 0.81.0
=> chore(wasmcloud-chart): bump version of wasmcloud-charthost to 0.7.2

crates/wash-cli/src/bin/wash.rs, crates/wash-cli/tests/wash_dev.rs
This removes the `experimental` flag as a required option on `wash dev`
=> feat(wash-cli): remove experimental flag from

examples/golang/actors/http-hello-world/wit/deps.lock, examples/golang/actors/http-hello-world/wit/deps.toml, examples/golang/actors/http-hello-world/wit/deps/io/poll.wit, examples/golang/actors/http-hello-world/wit/deps/io/streams.wit, examples/golang/actors/http-hello-world/wit/deps/keyvalue/atomic.wit, examples/golang/actors/http-hello-world/wit/deps/keyvalue/batch.wit, examples/golang/actors/http-hello-world/wit/deps/keyvalue/caching.wit, examples/golang/actors/http-hello-world/wit/deps/keyvalue/error.wit, examples/golang/actors/http-hello-world/wit/deps/keyvalue/handle-watch.wit, examples/golang/actors/http-hello-world/wit/deps/keyvalue/readwrite.wit, examples/golang/actors/http-hello-world/wit/deps/keyvalue/types.wit, examples/golang/actors/http-hello-world/wit/deps/keyvalue/world.wit, examples/golang/actors/http-hello-world/wit/deps/logging/logging.wit, examples/golang/actors/http-hello-world/wit/deps/logging/world.wit, examples/rust/actors/http-hello-world/wit/deps.lock, examples/rust/actors/http-hello-world/wit/deps.toml, examples/rust/actors/http-hello-world/wit/deps/io/poll.wit, examples/rust/actors/http-hello-world/wit/deps/io/streams.wit, examples/rust/actors/http-hello-world/wit/deps/keyvalue/atomic.wit, examples/rust/actors/http-hello-world/wit/deps/keyvalue/batch.wit, examples/rust/actors/http-hello-world/wit/deps/keyvalue/caching.wit, examples/rust/actors/http-hello-world/wit/deps/keyvalue/error.wit, examples/rust/actors/http-hello-world/wit/deps/keyvalue/handle-watch.wit, examples/rust/actors/http-hello-world/wit/deps/keyvalue/readwrite.wit, examples/rust/actors/http-hello-world/wit/deps/keyvalue/types.wit, examples/rust/actors/http-hello-world/wit/deps/keyvalue/world.wit, examples/rust/actors/http-hello-world/wit/deps/logging/logging.wit, examples/rust/actors/http-hello-world/wit/deps/logging/world.wit
This PR adds `wasi:keyvalue` and `wasi:logging` to the wit dependencies for both of our hello world examples for use in the quickstart tutorials. Without this, developers would need to manually modify the `deps.toml` file and run `wit-deps` update, so now during the quickstart documentation they can simply add these imports to their `wit/hello.wit` file and then use the capabilities.
This is only a temporary fix. Ideally these examples don't come with a wit deps directory at all and the only wit modification needed will be to specify custom import/exports, and a crate like `wasmcloud-actor` would be used to wrap wit definitions. I think that it's important to start here as a baseline and then remove some of the low level WebAssembly concepts as we can, as this level of detail will be …
=> feat(example): add logging and keyvalue for tutorial use

crates/wash-lib/src/build.rs
Golang projects built by wash which have
`wasm32-wasi-preview1` set as their `wasm_target` (in `wasmcloud.toml`) fail to build due to go
bindgen (i.e. `wit-bindgen-go`) being run on them.
While the wasmcloud ecosystem is WIT-first, it is possible to build preview1/preview2 components *without* WIT (i.e. with the legacy Smithy ecosystem), and projects that are built in that way should not have bindgen run on them.
This commit improves the check to use `wit_world` to determine whether to run go-based bindgen
https://github.com/wasmCloud/wasmCloud/issues/1241
next
templates built with tinygo that are using legacy smithy interfaces will build when using `wasm_target = "wasm32-wasi-preview1"`)
There's a test that caught this failure -- `integration_build_tinygo_actor_unsigned`
Verified …
=> fix(wash): only generate tinygo when wit-dir present

crates/wash-cli/src/bin/wash.rs, crates/wash-cli/src/common/label_cmd.rs, crates/wash-cli/src/common/mod.rs, crates/wash-lib/src/cli/label.rs, crates/wash-lib/src/cli/mod.rs
This adds `wash label` as an option. It uses the `put_label` and `delete_label` control interface functions to add or remove labels
Resolves https://github.com/wasmCloud/wasmCloud/issues/692
v0.26.0 (new feature)
Jordan is happy :)
Manually tested:
```
./target/debug/wash label damp foo=bar
Host `damp-rain-7348` labeled with `foo=bar`
wash get hosts -o json | jq -r '.hosts | .[] | .labels'
{
"foo": "bar",
"hostcore.arch": "aarch64",
"hostcore.os": "macos",
"hostcore.osfamily": "unix"
}
./target/debug/wash label damp foo --delete
Host `damp-rain-7348` unlabeled with `foo`
wash get hosts -o json | jq -r '.hosts | .[] | .labels'
{
"hostcore.arch": "aarch64",
"hostcore.os": "macos",
"hostcore.osfamily": "unix"
}
```
=> feat(wash-cli): add label command to set and remove host labels

crates/wash-cli/src/ui/mod.rs, crates/wash-cli/src/up/mod.rs
This PR sets the NATS server launched with `wash up` to always listen on port 4001 for websocket connections, letting `wash ui` work out-of-the-box with a host launched with vanilla options.
N/A
v0.26.0
Users of `wash-cli` will need to be aware that this opens up a websocket port for NATS to listen on that does not have TLS enabled. `wash up` is not the recommended tool for running in production, and for those use cases it's much better to adhere to our [deployment guide](https://wasmcloud.com/docs/deployment/lattice/) to understand how to deploy NATS infrastructure.
This worked!
```
cargo run -- up -d
cargo run -- ui
```
=> feat(wash-cli)!: enable websocket port by default

crates/control-interface/src/lib.rs, crates/control-interface/src/types.rs, crates/host/src/wasmbus/event.rs, crates/host/src/wasmbus/mod.rs, crates/providers/lattice-controller/src/lib.rs, crates/providers/lattice-controller/wit/deps/lattice-control/lattice-control.wit, crates/wash-cli/Cargo.toml, crates/wash-cli/src/common/scale_cmd.rs, crates/wash-cli/src/ctl/mod.rs, crates/wash-cli/src/dev.rs, crates/wash-cli/tests/wash_scale.rs, crates/wash-lib/Cargo.toml, crates/wash-lib/src/actor.rs, crates/wash-lib/src/cli/scale.rs, crates/wash-lib/src/cli/start.rs, tests/common/mod.rs, tests/wasmbus.rs
After a month or so of working with the changes from #696, I've come to a few conclusions about the developer experience of the new scaling model. All the thoughts below are up for discussion I just wanted to propose the changes.
1. This number `--max-concurrent` is describing "the maximum number of concurrent instances allowed to execute" and and I slightly prefer `--max-instances` to describe this number. This is also a more intuitive number when describing capability provider instances, and the eventual WASI provider instances, and will be better to replace the `replicas` field in wadm manifests. This might just be `instances`, but that can be determined later.
2. The difference between scaling to `None`, `Some(0)`, and `Some(10000)` is still confusing, and "unbounded" is a scary …
=> feat(control-interface)!: rename max-concurrent to max-instances, simplify scale

crates/wash-cli/src/par.rs
This commit adds the ability to detect the arch + OS combination when building PAR files, and use that as a default valiue. It's unlikely that people will create PARs from *not* the native toolchain, and in those cases they can specify `--arch` as normal.
=> feat(wash): detect arch when building PAR files

crates/control-interface/src/types.rs, crates/host/src/wasmbus/mod.rs, tests/wasmbus.rs
- feat(host)!: change heartbeat payload to inventory
- feat(control-interface)!: add heartbeat fields to inventory
In https://github.com/wasmCloud/wadm and https://github.com/wasmCloud/lattice-observer, and any other client, after a heartbeat a host inventory query is necessary in order to get enough information to reflect the state of the host. This PR solves this issue, giving any interested client the ability to know the full state of what's running on the host with only the heartbeat or the host inventory.
Fixes #789 
wasmCloud v0.82.0
control interface v0.33.0
The only consumers of the heartbeat payload, noted above, I'll update to work with both the old payload and the new payload. Worth noting that the only deserialize breaking change here is in the heartbeat, changing the actor …
=> feat(host)!: Combine heartbeat and inventory payloads

.github/workflows/wasmcloud.yml
This PR puts the packagecloud token back into the environment so we can release via nfpm. It also removes the continue on error clause to ensure we catch issues with that workflow sooner.
=> ci(wash-cli): fix packagecloud release

crates/wash-cli/README.md, crates/wash-lib/src/build.rs, crates/wash-lib/src/parser/mod.rs
This PR allows `wash` to support other languages than Rust or TinyGo by using the `build_command` and `build_artifact` information from wasmcloud.toml. The proper usage of these fields is to supply a build command that wash can execute for you, and then the build artifact should be the path to the built Wasm component so wash can then load it to sign the component. For example, a Javascript component will be compilable by wash if you use a wasmcloud.toml like so:
```toml
name = "componentize"
language = "javascript"
version = "0.1.0"
type = "actor"
[actor]
claims = []
build_command = "node componentize.mjs"
build_artifact = "hello.component.wasm"
destination = "hello_s.component.wasm"
```
I left the language as a completely open String, so users could supply any language other than rust …
=> feat(wash-lib): support other build languages

.github/workflows/wasmcloud.yml
This PR fixes one other issue with the wash-cli release to packagecloud which was a missing environment variable for parsing the reference. The release worked great, just had the default version.
#1303
=> ci(wash-cli): parse version from github ref

.github/workflows/wasmcloud.yml
This PR, hopefully the last of its kind, resolves yet another issue that came from the apt install after publishing. Previously, the `github.ref` reference would get `cut` into:
```
wash-cli-v0.25.0
```
Which would cause this issue when attempting to install:
```
Get:1 https://packagecloud.io/wasmCloud/core/ubuntu jammy/main amd64 wash amd64 wash-cli-v0.25.0-packagecloudfix [15.1 MB]
Fetched 15.1 MB in 1s (27.3 MB/s)
dpkg: error processing archive /var/cache/apt/archives/wash_wash-cli-v0.25.0-packagecloudfix_amd64.deb (--unpack):
parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'wash':
'Version' field value 'wash-cli-v0.25.0-packagecloudfix': version number does not start with digit
Errors were encountered while processing: …
```
=> ci(wash-cli): properly format wash version

.github/workflows/wasmcloud.yml
Alrighty, so we properly got `0.25.0` released but it didn't have the executable bit set, so it would fail out of the box on deb/rpm systems.
If anyone is looking at this PR looking for a resolution, you can simply run `chmod +x /usr/local/bin/wash` and get off to the races.
#1308 
#1303
=> ci(wash-cli): make deb/rpm wash executable

crates/providers/blobstore-fs/README.md, crates/providers/messaging-kafka/README.md, examples/golang/README.md, examples/rust/README.md, examples/typescript/README.md, examples/typescript/actors/http-hello-world/README.md
While users are perusing examples, it's probably a good idea to add some language-specific information at the root for the given language.
As we current have our example structure set up to be `examples/<language>/(actors|...)`, we have a change to add a README at the `examples/<language>` level.
This commit adds READMEs for language-level folders under examples.
=> docs(examples): add README for language level

crates/host/src/wasmbus/event.rs
This PR adds another field to the `actor_scaled` event which adds some necessary information in order to replace the `actors_started` event.
Upcoming PR for wadm
v0.82.0, alongside releasing the event in the first place
No impact on consumers as this event is still unreleased
=> fix(wasmbus): publish claims with actor_scaled

.github/actions/build-nix/action.yml, .github/dependabot.yml, .github/workflows/scorecard.yml, .github/workflows/washboard.yml, .github/workflows/wasmcloud.yml
Obviates https://github.com/wasmCloud/wasmCloud/pull/1181 and https://github.com/wasmCloud/wasmCloud/pull/1182
This also groups the upload and download actions in the dependabot config, so future automated bumps should work
=> chore(ci): update artifact actions

examples/docker/docker-compose-full.yml
=> feat(DockerFileLoad): Enable actor file load for docker

examples/docker/docker-compose-auxiliary.yml, examples/docker/docker-compose-full.yml, examples/docker/grafana-datasources.yaml, examples/docker/tempo.yaml
I noticed this error:
```
docker-grafana-1    | logger=plugins.update.checker t=2024-01-17T19:00:23.605767216Z level=info msg="Update check succeeded" duration=119.701458ms
Error response from daemon: driver failed programming external connectivity on endpoint docker-wasmcloud-1 (a763906bc096c57b9addf7cead80f1eb84f61ded4344e69166a56b75f98bd801): Bind for 0.0.0.0:8000 failed: port is already allocated
```
So I simply updated the tempo port from 8000 to 7999
=> fix(examples): update port for tempo to remove conflict with host ports

Cargo.lock, crates/wash-cli/src/app/mod.rs, crates/wash-lib/Cargo.toml, crates/wash-lib/src/app.rs, crates/wash-lib/src/generate/genconfig.rs, examples/rust/actors/http-hello-world/wadm.yaml
WADM does not allow non-relative file paths to be used for values like `image:` (which is relevant for actors and providers specified in the manifest).
If a user is using a local file path, it's very likely that the host on which the declarative architecture will be deployed is the same host as the one that is running `wadm`.
To enable users to more conveniently build declarative manifests, we can resolve `file://...` paths based on the path to the WADM file itself (which is known at load time).
The basic scheme is to update the `AppManifest`s to store YAML structure rather than a simple `String`, in order to enable iterating and replacing paths as is necessary.
This commit allows for relative paths in WADM manifests that are fed to commands like `wash app deploy`.
=> feat(wadm): allow relative paths in file-based WADM manifests

crates/wash-cli/src/common/stop_cmd.rs, crates/wash-cli/src/ctl/mod.rs
While working on a different change, I noticed the `wash-cli common::stop_cmd::test::test_stop_actor_cmd_comprehensive` and `wash-cli ctl::test::test_ctl_comprehensive` tests were failing, so this fixes that.
<details>
<summary>Failing tests output</summary>
```shell
Finished test [unoptimized + debuginfo] target(s) in 0.20s
Starting 71 tests across 19 binaries
PASS [   0.012s] wash-cli build::test::test_build_comprehensive
PASS [   0.012s] wash-cli common::registry_cmd::tests::test_pull_comprehensive
PASS [   0.013s] wash-cli common::start_cmd::test::test_ctl_comprehensive
PASS [   0.014s] wash-cli call::test::test_rpc_comprehensive
FAIL [   0.014s] wash-cli common::stop_cmd::test::test_stop_actor_cmd_comprehensive
--- STDOUT:              wash-cli …
```
=> chore: Remove deprecated --count argument from wash ctl stop actor calls

Cargo.lock, Cargo.toml
[wadm v0.10.0 was released](https://github.com/wasmCloud/wadm/releases/tag/v0.10.0) yesterday, let's use it!
=> chore: Bump wadm version to 0.10

crates/host/README.md
Resolves https://github.com/wasmCloud/wasmCloud/issues/1045
I just took the first section from our top level README and added a callout that this crate is for the host runtime. Feedback welcome, but I mostly just wanted _something_ in place
=> docs(host): add README for the host crate

crates/host/src/wasmbus/mod.rs
This removes the requirement for actors to include capabilities in their claims. For components, the wit interfaces describe this information, and runtime links are now the way an operator signals intent for components to be able to communicate
Implements changes described in https://github.com/wasmCloud/wasmCloud/issues/1219
Next
N/A. We can remove/stop parsing the `claims` from `ActorConfig` in wash, once a host with this feature is released
=> feat(host): remove requirement for actors to have capabilities in claims

.github/workflows/_check-for-changes.yml, .github/workflows/wasmcloud.yml
After adding a path filter to the `wasmcloud` job, I noticed that PRs with only changes in the `washboard-ui` directory were stuck in a pending state because of [this issue](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpull_requestpull_request_targetbranchesbranches-ignore):
> If a workflow is skipped due to branch filtering, [path filtering](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore), or a [commit message](https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs), then checks associated with that workflow will remain in a "Pending" state. A pull request that requires those checks to be successful will be blocked from …
=> ci: add conditions to rust build code

crates/wash-lib/src/actor.rs, crates/wash-lib/src/wait.rs
https://github.com/wasmCloud/wasmCloud/pull/1381 updated wash-lib to listen to the scale events, but it appears these aren't in v0.81 of the host. This updates wash-lib to listen to the deprecated events and the new scale events
=> fix(wash-lib): listen to deprecated start/stop events

crates/providers/blobstore-s3/tests/storage.rs, crates/providers/http-server/src/settings.rs, crates/providers/kv-redis/src/bin/kvredis.rs, crates/providers/messaging-kafka/src/lib.rs, crates/providers/messaging-nats/src/lib.rs
After the change to bring in the deps via provider bindgen, some of the tests were not using those same deps.
=> fix(providers): Fixes broken tests in providers

crates/tracing/src/lib.rs
As it stands, the check restricts the ability to customize the OTLP tracing endpoint more than is necessary.
Discussed a couple of options with @connorsmith256 offline, and this seems like the best path forward.
=> chore: Remove check for default OpenTelemetry traces path

crates/wash-cli/src/app/mod.rs, crates/wash-cli/src/app/output.rs
This adds support for `wash app status [model]`
Given the verbosity of the status message, I'm not sure I like the table view, so I'm open to suggestions
Resolves https://github.com/wasmCloud/wasmCloud/issues/857
Next minor bump
N/A
```
~/wasmcloud/wasmcloud/target/debug/wash app status typescript-http-hello-world -o json
{
"status": {
"message": "Successfully fetched status for model typescript-http-hello-world",
"result": "ok",
"status": {
"components": [],
"status": {
"message": "Linkdef pending, waiting for file:///Users/connor/Documents/wasmCloud/wasmCloud/examples/typescript/actors/http-hello-world/build/index_s.wasm and wasmcloud.azurecr.io/httpserver:0.19.1 to start",
"type": "reconciling"
},
"version": "v0.0.1"
}
},
"success": true
}
```
``` …
```
=> feat(wash-cli): add support for wash app status

crates/tracing/src/lib.rs, examples/docker/docker-compose-auxiliary.yml, examples/docker/docker-compose-full.yml, examples/docker/docker-compose-websockets.yml, examples/docker/tempo.yaml
OTEL changed it's default port from 55680/55681 to 4317/4318 for [gRPC](https://opentelemetry.io/docs/specs/otlp/#otlpgrpc-default-port) and [HTTP](https://opentelemetry.io/docs/specs/otlp/#otlphttp-default-port) respectively [a while back in the spec](https://github.com/open-telemetry/opentelemetry-specification/pull/1839) and [in the collector](https://github.com/open-telemetry/opentelemetry-collector/pull/3743), let's switch over to using the current ports defined in the spec.
=> chore: Update the default OTLP HTTP port to match the current spec

crates/wash-cli/src/up/mod.rs, src/main.rs
This commit removes what were supposed to be ENV aliases that don't work, which were introduced by https://github.com/wasmCloud/wasmCloud/pull/1243
=> chore(wash,host): remove ineffective ENV aliases

crates/host/src/wasmbus/mod.rs
This adds the `subject` back to log messages related to processing control interface commands, which is helpful when debugging messages from incompatible clients. The `message` was on the span already, but only when trace level logs are enabled
=> fix(host): add subject to control interface logs

crates/host/src/wasmbus/mod.rs, src/main.rs, tests/wasmbus.rs
This is a simple refactor which moves the parsing logic for labels set via env vars to the main binary, rather than the host library.
Resolves https://github.com/wasmCloud/wasmCloud/issues/757
Next
v0.82.0. I also removed support for the (very old) `HOST_` prefix, so this is technically a breaking change
=> refactor(host): move label parsing out of host library

examples/typescript/actors/http-hello-world/wit/deps/io/poll.wit, examples/typescript/actors/http-hello-world/wit/deps/io/streams.wit, examples/typescript/actors/http-hello-world/wit/deps/keyvalue/atomic.wit, examples/typescript/actors/http-hello-world/wit/deps/keyvalue/batch.wit, examples/typescript/actors/http-hello-world/wit/deps/keyvalue/caching.wit, examples/typescript/actors/http-hello-world/wit/deps/keyvalue/error.wit, examples/typescript/actors/http-hello-world/wit/deps/keyvalue/handle-watch.wit, examples/typescript/actors/http-hello-world/wit/deps/keyvalue/readwrite.wit, examples/typescript/actors/http-hello-world/wit/deps/keyvalue/types.wit, examples/typescript/actors/http-hello-world/wit/deps/keyvalue/world.wit, examples/typescript/actors/http-hello-world/wit/deps/logging/logging.wit, examples/typescript/actors/http-hello-world/wit/deps/logging/world.wit
This PR includes the keyvalue and logging wit deps in the typescript example to ensure that we have that included for easy reference during our tutorial 😄
=> fix(typescript): include keyvalue and logging in wit deps

examples/docker/README.md, examples/docker/docker-compose-minimal.yml
This PR just adds the minimal docker compose example to give onlookers an idea of the required set of infrastructure they need to run. This notably excludes Wadm as there is a bit of confusion as to whether it's _required_ to run wasmCloud, so I want to be explicit on the minimal requirements.
I did make sure this compose worked.
=> feat(example): added minimal docker compose example

.github/dependabot.yml
Group minor and patch changes into a combined PR for dev dependencies and app dependencies, and leave major versions as single PRs.
Also moves dependabot check to Monday at 9am.
=> ci(dependabot): group minor/patch versions

.github/workflows/wasmcloud.yml
We've been having some unknown issues with running out of disk space during builds. This swaps to a runner with a bigger disk, and as a bonus, more cores
=> feat(ci): use larger runners

.github/workflows/update.yml
I get a daily reminder that this doesn't actually work within forks without the appropriate credentials set up, so rather than spamming everyone who forks the repo, let's only run this within the `wasmCloud` org.
=> chore: Limit nix-flake-update workflow to running only within the wasmCloud org

Cargo.lock, Cargo.toml, crates/wash-lib/Cargo.toml, crates/wash-lib/src/build.rs
Verbatim paths on Windows are not well supported,
e.g. "\\\\?\\C:\\Users..." while technically valid, causes some fs api's like `exists` to fail errantly.
The fix is to use a third party lib normpath to normalize the path to the wasm
binary.
Related issue: https://github.com/rust-lang/cargo/issues/9770
Fixes #1481
Signed-off-by: Bailey Hayes <behayes2@gmail.com>
=> fix(wash): windows path to target

crates/wash-cli/tests/wash_build.rs, crates/wash-lib/src/generate/favorites.toml
This updates the favorites file to use our componentized actor templates
**Note** that I left the interfaces and providers in there, even though those are smithy based. If we remove them, then e.g. `wash new provider` will error with:
```
Failed to generate project
Caused by:
⛔   templates missing for project type provider
```
Leaving as do-not-merge until we've released a new version of wash using v0.82 of the host
Resolves https://github.com/wasmCloud/wasmCloud/issues/1500
Next
```
~/wasmcloud/wasmcloud/target/debug/wash new actor -t hello-world-typescript hello-world-typescript
🔧   Cloning template from repo wasmCloud/wasmCloud subfolder examples/typescript/actors/http-hello-world...
🔧   Using template subfolder examples/typescript/actors/http-hello-world...
🔧   Generating template... …
```
=> feat(wash-lib): update favorites to use components

Cargo.lock, Cargo.toml, crates/providers/Cargo.lock, crates/wash-lib/Cargo.toml, tests/actors/rust/Cargo.lock
Fixes an issue where `wash-lib` published properly but failed to build with all features checked.
=> fix(wash-lib): re-lock wit-parser

examples/python/actors/http-hello-world/project-generate.toml, examples/python/actors/http-hello-world/wadm.yaml
This PR fixes an issue with the python build folder not getting copied over to the template generation, and removes a testing artifact from the wadm version 😓
=> fix(examples): python build folder and wadm ver

crates/host/src/wasmbus/mod.rs
This sets the `log_level` in the `HostData`, allowing providers built using the new SDK to inherit their logging level from the host
**This should not be merged before v0.82 of the host is released**
Resolves https://github.com/wasmCloud/wasmCloud/issues/1487
1.0, since this will break legacy wasmbus-rpc providers
See the `subscribing for` debug logs from the provider binary:
```
./target/debug/wasmcloud --log-level debug --allow-file-load
2024-02-12T22:28:16.389792Z DEBUG new: wasmcloud_host::wasmbus: adding cluster key to cluster issuers cluster_pub_key="CBW56ENZ3AWPAKOHVUELI7SD6PYNHF7WLNNWAX2VI7QHCKI2JDNFACLP"
2024-02-12T22:28:16.390373Z DEBUG new: wasmcloud_host::wasmbus: connecting to NATS control server ctl_nats_url="nats://127.0.0.1:4222"
2024-02-12T22:28:16.390496Z DEBUG new: …
```
=> fix(host): set log_level for providers

Cargo.lock, Cargo.toml
This PR updates the `command-group` dependency to v5, as v1 was pulling in an older version of the `nix` crate.
`next`
=> build(wash-lib): update command-group to v5

crates/control-interface/src/types.rs, crates/host/src/wasmbus/mod.rs, crates/runtime/src/capability/builtin.rs, crates/runtime/src/capability/mod.rs
This PR introduces mostly backwards compatible changes (new public member in control interface may be considered breaking, new functionality in RPC isn't documented but could alter behavior) to support both actor component interface linking and storing component specifications in the `LATTICEDATA` bucket.
This is designed in a way that we can make incremental progress towards a full wRPC implementation but does not alter the test functionality. Because of this, it's not recommended to merge this to `main` until we can release v0.82 after #1478.
Partially implements #1389 
v1.0.0
No tests were modified for this PR as the point is to get some of the plumbing for wRPC components implemented without modifying today's functionality.
To test this PR, I went through a few manual steps to ensure …
=> feat(wrpc): Add support for interface linking and storing component specifications

crates/wash-lib/Cargo.toml, crates/wash-lib/src/lib.rs
Fixes the build problem of `wash-lib` with `--no-default-features` flag.
Fixes issue #862 
N/A
N/A
build succeeds in `crates/wash-lib`: `cargo build --no-default-features`
N/A
N/A
N/A
=> Fix the build problem of `wash-lib` with `--no-default-features` flag.

Cargo.lock, crates/host/Cargo.toml, crates/host/src/lib.rs, crates/host/src/wasmbus/mod.rs, crates/runtime/src/actor/component/mod.rs, crates/runtime/src/capability/builtin.rs, crates/runtime/src/capability/mod.rs
This PR adds support for components serving dynamic functions based on their exports on wRPC topics. I've tested this using a small binary that invokes a component exporting a function `foo`, as shown below in the manual verification section. The vast majority of this PR is removing code that's no longer exercised for handling and sending invocations over wasmbus, instead replaced with serving dynamic functions on wRPC.
I also implemented importing functions and, using the polyfilled interfaces, invoking other components on the lattice via wRPC. This will work great for our custom interfaces, but HTTP, keyvalue, blobstore, and messaging all need to be reworked to send wRPC messages instead (see TODO under `call_operation`).
I've left a few `TODO` comments regarding policy checking and …
=> wRPC component export support

crates/provider-wit-bindgen-macro/src/wit.rs
This commit fixes a bug in determining the struct name for bundled exports. Code that was using expected a WIT interface name was receiving a WIT inteface path (which is `.`-delimited), and attempting to use it directly, rather that converting to a valid Rust identifier.
=> fix(provider-wit-bindgen): exported bundled arg invocation name

Cargo.lock, crates/provider-wit-bindgen-macro/Cargo.toml
This PR commits a new version of  `provider-wit-bindgen-macro` crates:
- `provider-wit-bindgen-macro` `v0.1.1`
While the crate is unreleased, people depending on the versions committed to `main` should benefit from the bugfixes -- in particular https://github.com/wasmCloud/wasmCloud/commit/51c4f8e271a9d4d6fea95653ed31cc57069e9665
=> chore(provider-wit-bindgen): bump version to v0.1.1

crates/control-interface/src/broker.rs, crates/control-interface/src/lib.rs, crates/control-interface/src/types.rs, crates/host/src/wasmbus/event.rs, crates/host/src/wasmbus/mod.rs, crates/providers/lattice-controller/src/bin/lattice-controller.rs, crates/providers/lattice-controller/src/lib.rs, crates/runtime/src/capability/builtin.rs, crates/test-util/src/actor.rs, crates/test-util/src/lattice/config.rs, crates/test-util/src/lattice/link.rs, crates/test-util/src/provider.rs, tests/kv-redis.rs
This PR includes quite a few changes in the control interface and host, but in sum:
1. Updates actor and provider commands on the control interface to support pulling in component IDs, which is a unique identifier for the component itself and used in routing
2. Flattens both the `ActorInstance` and `ProviderInstance` into their parent `Actor` / `Provider` struct, now that component IDs uniquely identify the component we don't need to index based on annotations
3. Drop the `link_name` and `contract_id` from providers, since we don't need them anymore. I attempted to keep the `link_name` as default in many places for some amount of backwards compat with provider things.
4. Fully support interface links through the `get` / `put` / `del` control interface topics
5. Remove the concept of …
=> Control interface component ID support, flatten actor/provider instances

Cargo.lock, Cargo.toml, crates/host/Cargo.toml, crates/host/src/wasmbus/mod.rs, crates/providers/Cargo.lock, crates/runtime/src/actor/component/http.rs, crates/runtime/src/capability/builtin.rs, crates/runtime/tests/runtime.rs, tests/actors/rust/Cargo.lock, tests/actors/rust/wrpc-pinger-component/Cargo.toml, tests/actors/rust/wrpc-pinger-component/src/lib.rs, tests/actors/rust/wrpc-pinger-component/wit/world.wit, tests/common/mod.rs, tests/wrpc.rs
Tested with an ad-hoc hand-written "provider" in the `wrpc` test
=> `wrpc:http/outgoing-handler` implementation

Cargo.lock, Cargo.toml, crates/host/src/wasmbus/mod.rs, crates/runtime/src/actor/component/http.rs, crates/runtime/src/capability/builtin.rs, crates/runtime/tests/runtime.rs
Allow components to export `wasi:http/incoming-handler` as `wrpc:http/incoming-handler`
=> feat(host): implement `wrpc:http/incoming-handler`

crates/host/src/policy.rs, crates/runtime/src/actor/component/http.rs, crates/runtime/src/actor/component/logging.rs, crates/runtime/src/actor/component/mod.rs
This PR consists of two commits that help improve the ability of the system to manage higher numbers of requests per second. The first commit updates the components to be pre-instantiated rather than doing a full instantiation each time. The second commit fixes an issue where we were write locking on the policy decision cache for every request. Now we only write lock when necessary. 
In my load testing of this locally, these led to a 25-28% increase in throughput. Please note I only did the preinstantiation for components as we're removing module support for 1.0
=> feat(runtime,host): Updates to request throughput

Cargo.lock, crates/host/src/wasmbus/mod.rs, crates/host/src/wasmbus/wasmcloud_transport.rs, crates/runtime/src/actor/component/mod.rs
This PR wraps a few traits from [wrpc-transport](https://crates.io/crates/wrpc-transport) in order to pass and send back headers when handling invocations. We already receive headers from incoming invocations, this PR just ensures that we are sending traceparent headers _back_ in response to an invocation and to send them when creating an outbound invocation.
This works and propagates headers all the way through! I tested it by invoking what we do in the wrpc integration test but invoking manually with a NATS header. For the curious:
```bash
> nats req "default.header.wrpc.0.0.1.wasmcloud:testing/pingpong.ping" "{}" -H source:myterminalteehee
[#15] Received on "default.header.wrpc.0.0.1.wasmcloud:testing/pingpong.ping" with reply "_INBOX.fnOVvdeTxGZoQazDtpSXAY.p0ShVKPK"
source: …
```
=> feat(host): wasmcloud_transport wrappers to include headers on invocations

Cargo.lock, Cargo.toml, crates/provider-wit-bindgen-macro/src/lib.rs, crates/wrpc-transport-derive-macro/Cargo.toml, crates/wrpc-transport-derive-macro/src/lib.rs, crates/wrpc-transport-derive-macro/src/rust.rs, crates/wrpc-transport-derive-macro/src/wrpc_transport/encode_sync.rs, crates/wrpc-transport-derive-macro/src/wrpc_transport/mod.rs, crates/wrpc-transport-derive-macro/src/wrpc_transport/receive.rs, crates/wrpc-transport-derive/Cargo.toml, crates/wrpc-transport-derive/src/lib.rs, crates/wrpc-transport-derive/tests/common/mod.rs, crates/wrpc-transport-derive/tests/encode_struct.rs, crates/wrpc-transport-derive/tests/roundtrip_enum.rs, crates/wrpc-transport-derive/tests/roundtrip_struct.rs
This commit adds macro crates that help users derive wrpc_transport::Encode and wrpc_transport::Receive for regular Rust structs.
=> feat(wrpc-transport-derive): derive wrpc_transport::{EncodeSync,Receive}

crates/provider-wit-bindgen-macro/src/bindgen_visitor.rs, crates/provider-wit-bindgen-macro/src/lib.rs, crates/provider-wit-bindgen-macro/src/wit.rs, crates/providers/Cargo.lock
When using a type alias in WIT (ex. `type str-list = vec<string>`), if that type is inside an interface and used from another interface, there is an extra alias made to it.
Since bindgen sees *both* the "real" alias (in Rust `type StrList = Vec<String>`) and the local binding level alias (in Rust `type StrList = super::some::iface::StrList`), we need to make sure that the "real" alias is the one that is hoisted to the top.
This commit adds some checks to ensure that the alias that is *not* a reference is sure to be hoisted to the top (all generated code uses `T`, not `super::some::iface::T`). This is a a shortcut to avoid building a type reference graph.
=> fix(provider-wit-bindgen): type aliasing for nested types

crates/host/src/metrics.rs, crates/host/src/wasmbus/mod.rs, crates/tracing/src/lib.rs, src/main.rs
Add two new metrics for actors:
* the count of the number of invocations (`wasmcloud_host.actor.invocations`)
* the count of errors (`wasmcloud_host.actor.errors`)
This also adds a bunch of new attributes to the existing actor metrics so that they make sense in an environment with multiple hosts. Specifically this adds:
* the lattice ID
* the host ID
* provider information if a provider invoked the actor: ** the contract ID
* the provider ID
* the name of the linkdef
For actor to actor calls, instead of having the provider metadata it instead has the public key of the invoking actor.
An example of what this looks like as an exported Prometheus metric:
```
wasmcloud_host_actor_invocations_total{actor_ref="wasmcloud.azurecr.io/echo:0.3.8", caller_provider_contract_id="wasmcloud:httpserver", …
```
=> feat(metrics) add invocation and error counts for actor invocations

crates/host/src/policy.rs
This PR re-tags the enum for `RequestType` since omitting it actually sets that field to `null`, breaking the policy service.
=> fix(host): re-tag request type enum policy

Cargo.lock, crates/control-interface/Cargo.toml, crates/core/Cargo.toml, crates/core/src/lib.rs, crates/core/src/wrpc.rs, crates/host/src/wasmbus/mod.rs, crates/providers/Cargo.lock
This commit moves the wasmcloud-specific wrpc transport client to the `wasmcloud-control-interface` crate. From here, it can be used by both the host (`wasmbus`) and other places like tests.
=> refactor: move wasmcloud wrpc transport client to core

crates/core/src/link.rs, crates/provider-sdk/src/lib.rs, crates/providers/blobstore-fs/src/lib.rs, crates/providers/blobstore-s3/src/client.rs, crates/providers/blobstore-s3/src/lib.rs, crates/providers/kv-redis/src/bin/kvredis.rs, crates/providers/kv-vault/src/lib.rs, crates/providers/messaging-kafka/src/lib.rs, crates/providers/messaging-nats/src/connection.rs, crates/providers/messaging-nats/src/lib.rs
This commit updates all providers that were marked with TODOs related to using named config to use `InterfaceLinkDefinition.target_config` temporarily.
The idea is to stuff configuration into the "names"s of configs that were supposed to be in use (i.e. `["NAME=VALUE", "NAME=VALUE"]` rather than `["config-1", "config-2"]`), ahead of named config being ready.
=> refactor(providers): get values from new link def constistently

chart/templates/deployment.yaml, src/main.rs
This adds a `WASMCLOUD` prefix to both the `NATS_PORT` and `NATS_URL` env vars, since there are potentially conficts with those variables in other systems. Specifically this would play badly deploying in Kubernetes with a service named `nats` running in the same namespace, since a `NATS_PORT` env var is automatically injected in that case which stops the wasmcloud binary from starting. It is also a good practice to have all of our environment variables using the same prefix.
This is a breaking change to wasmCloud CLI args for the host.
=> chore: prefix NATS_PORT and NATS_URL with WASMCLOUD

crates/wash-cli/src/build.rs, crates/wash-cli/src/dev.rs, crates/wash-cli/src/par.rs, crates/wash-lib/src/build/component.rs, crates/wash-lib/src/build/mod.rs, crates/wash-lib/src/build/provider.rs, crates/wash-lib/src/cli/claims.rs, crates/wash-lib/src/cli/dev.rs, crates/wash-lib/src/cli/par.rs, crates/wash-lib/src/parser/mod.rs
This PR implements wash building a capability provider archive just for the local arch/os target. In the future I'd love to add support for multiple other architectures as well with predefined paths, but `wash build` won't ever be responsible for cross compiling (something something sure would be nice if we had a platform agnostic binary target to compile to)
I added two TODOs re: #1624 because I found out why we're generating keys to `./keys`
next minor wash-cli
next minor wash-lib
I verified this worked for a provider that will soon be an example 😄
=> feat(wash)!: implement wash building provider for host machine

Cargo.lock, crates/core/src/wit.rs, crates/core/src/wrpc.rs, crates/host/src/wasmbus/mod.rs, crates/providers/Cargo.lock, crates/runtime/src/actor/component/bus.rs, crates/runtime/src/actor/component/mod.rs, crates/runtime/src/capability/builtin.rs, crates/runtime/src/capability/mod.rs, crates/wash-cli/Cargo.toml, crates/wash-cli/src/bin/wash.rs, crates/wash-cli/src/build.rs, crates/wash-cli/src/call.rs, crates/wash-cli/src/dev.rs, crates/wash-cli/src/par.rs, crates/wash-lib/src/build/component.rs, crates/wash-lib/src/build/mod.rs, crates/wash-lib/src/build/provider.rs, crates/wash-lib/src/cli/claims.rs, crates/wash-lib/src/cli/dev.rs, crates/wash-lib/src/cli/par.rs, crates/wash-lib/src/parser/mod.rs
Draft PR as it branches off of #1628 
This PR implements a very basic `wash call` functionality that allows developers to invoke a component that exports an interface function that takes no arguments and returns a String. It's very basic, but it will allow manual invocation of a component over wRPC and we can extend this in the future by passing in WIT files 😄 
For example, a component WIT world like:
```wit
package wasmcloud:hello;
interface easy {
call: func() -> string;
}
```
Can be invoked like:
```bash
wash call <component_id> wasmcloud:hello/easy.call
```
next wash-cli
This works great! I attempted to include basic error handling around timeouts and no responders errors.
=> feat(wash-cli): basic wasi:cli/run style wrpc invocation

crates/host/src/wasmbus/mod.rs, crates/runtime/src/actor/component/mod.rs, crates/runtime/src/capability/builtin.rs, crates/runtime/src/capability/mod.rs, crates/runtime/tests/runtime.rs
This PR updates a few of our internal structs for target entity discovery and routing and removes some outdated enum members. In addition, this PR includes some updates to error messages when a component isn't linked on a given interface.
If a component attempts to invoke something it's not linked to, here are the logs and error message:
```
2024-03-01T15:45:38.757607Z DEBUG handle_invocation{params=Custom { interface: "wasmcloud:testing/invoke", function: "call" } component_id="ponger" component_ref="file:///Users/brooks/github.com/wasmcloud/wasmcloud/tests/actors/rust/wrpc-pinger-component/build/wrpc_pinger_component_s.wasm"}:call{interface="wasmcloud:testing/invoke" function="call"}: wasmcloud_host::wasmbus: component is not linked to a lattice target for the given interface …
```
=> fix(host): improve error handling for wrpc links

.github/workflows/wash.yml, crates/host/src/metrics.rs, crates/host/src/wasmbus/mod.rs, crates/wash-lib/src/cli/claims.rs, crates/wash-lib/tests/parser/files/rust_provider_claims_metadata.toml, crates/wash-lib/tests/parser/main.rs
This PR fixes a test failure in `wash-lib` that I didn't catch PR-ing into `feat/wrpc` and pins our Go version to 1.20 which is failing a test in `main`.
=> fix(wash-lib): build provider tests

.github/CODEOWNERS
This PR adds one more team to the reviewers list, @wasmcloud/observability-maintainers. This now allows us to fully manage allowed reviewers via GitHub teams instead of a hardcoded list.
=> chore: add observability-maintainers team

crates/core/src/otel.rs, crates/host/src/wasmbus/mod.rs, crates/provider-sdk/src/provider_main.rs, crates/tracing/src/lib.rs, crates/tracing/src/metrics.rs, crates/tracing/src/traces.rs, examples/docker/docker-compose-full.yml, examples/docker/docker-compose-websockets.yml, src/main.rs
This standardizes the flags used for enabling and configuring observability, with this change observability can be:
* Enabled either for all signals at once, or selectively enabled/disable on a per-signal basis.
* Configured to emit all signals to a single endpoint or override the individual signal endpoints.
=> feat: Standardize flags for enabling and configuring observability 

crates/control-interface/src/client.rs, crates/control-interface/src/types/ctl.rs, crates/core/src/host.rs, crates/host/src/wasmbus/mod.rs, crates/provider-sdk/src/provider.rs, crates/providers/kv-redis/src/bin/kvredis.rs, crates/providers/messaging-nats/src/connection.rs, crates/providers/messaging-nats/src/lib.rs, crates/providers/messaging-nats/wasmcloud.toml, crates/test-util/src/lattice/config.rs, crates/test-util/src/provider.rs, crates/wash-lib/src/build/provider.rs, tests/kv-redis.rs, tests/kv-vault.rs
This PR implements the change to the start provider logic in the control interface and host to, instead of accepting a single config string, accept a list of named configurations in order to build the provider configuration. At runtime now we will pass a `HashMap<String, String>` to the provider which will be its configuration (built from all of the named configs).
In a followup issue, which I'll create shortly, we should support reloading this config.
https://github.com/wasmCloud/wasmCloud/issues/1648
I verified this worked by creating configuration and having NATS communicate on a different URI than supplied 😄
=> feat(control-interface)!: support static named config for providers

crates/wrpc-transport-derive-macro/src/wrpc_transport/receive.rs
This commit fixes the path in provider WIT bindgen for a use of `receive_discriminant` which caused an error when the path was exercised.
Resolves #1671 
Reproduction was successful (and easy) using the WIT  provided in the issue, thanks @jschilli!
=> fix(provider-bindgen): fix module path for receive_discriminant call

crates/providers/blobstore-fs/src/lib.rs
Fixes error with provider where deserialize cannot be derived on an Arc.
```bash
Compiling wasmcloud-provider-blobstore-fs v0.4.0 (/Users/bhayes/repos/wasmCloud/wasmCloud/crates/providers/blobstore-fs)
error[E0277]: the trait bound `Arc<PathBuf>: Deserialize<'_>` is not satisfied
--> blobstore-fs/src/lib.rs:45:11
|
45   |     root: Arc<PathBuf>,
|           ^^^^^^^^^^^^ the trait `Deserialize<'_>` is not implemented for `Arc<PathBuf>`
|
= help: the following other types implement trait `Deserialize<'de>`:
<bool as Deserialize<'de>>
<char as Deserialize<'de>>
<isize as Deserialize<'de>>
<i8 as Deserialize<'de>>
<i16 as Deserialize<'de>>
<i32 as Deserialize<'de>>
<i64 as Deserialize<'de>>
<i128 as Deserialize<'de>>
and 244 others
note: required by a bound in `next_element`
--> …
```
=> fix(providers): remove deserialize trait

crates/host/src/wasmbus/mod.rs, crates/wash-cli/src/bin/wash.rs, crates/wash-cli/src/common/registry_cmd.rs, crates/wash-cli/src/config.rs, crates/wash-cli/src/lib.rs, crates/wash-cli/src/util.rs, crates/wash-lib/src/cli/mod.rs, crates/wash-lib/src/cli/scale.rs, crates/wash-lib/src/cli/start.rs
This PR implements the `wash config` subcommand, including `get`, `put`, and `del`.
I had to make a change in the host to actually watch the config data bucket to get updates on config, so tests for this feature in wash will have to wait for the next alpha wasmcloud release.
wasmcloud v1.0.0-alpha.2
next wash
I manually made sure all of this worked! I also included a special case to ensure we aren't inserting `success:true` when people fetch JSON config, might conflict with their keys and/or cause confusion.
=> feat(wash-cli)!: wash config put/get/del implementation

Cargo.lock, Cargo.toml, crates/control-interface/Cargo.toml, crates/core/Cargo.toml, crates/provider-archive/Cargo.toml, crates/provider-sdk/Cargo.toml, crates/providers/Cargo.lock, crates/test-util/Cargo.toml, crates/tracing/Cargo.toml, crates/wascap/Cargo.toml, crates/wash-cli/Cargo.toml, crates/wash-lib/Cargo.toml
This PR bumps quite a few of the crates that changed between the release of `v0.82.0` and the release of `v1.0.0-alpha.1`. The goal of this PR is to update all crates to a version that is compatible with the latest control interface and RPC protocols and 1.0 features, and the end goal after merging this (and #1649) is to cut an alpha version of `wash`
#1649
wash-cli 0.27.0-alpha.1
wasmcloud 1.0.0-alpha.2
wasmcloud-tracing 0.2.0
wasmcloud-core 0.3.0
wasmcloud-control-interface 1.0.0-alpha.1
provider-archive 0.9
wasmcloud-provider-sdk 0.3
wascap 0.13
wasmcloud-test-util 0.1
wash-lib 0.19
Most of these crates will be incompatible with v0.82 (notably the control interface, core, provider SDK, wash-lib, wash-cli) so it is essential that when updating all the crates are updated to their latest …
=> chore: bump crates to 1.0.0 compatible versions

.github/workflows/wasmcloud.yml
The issue #1715 also exists for Ubuntu, the packages for latest Ubuntu versions aren't generated and pushed to Packagecloud. 
This PR adds Ubuntu 23.10 (id 278 in Packagecloud) and 24.04 (id 284 in Packagecloud) as targets for packagecloud.io
It's related to the issue https://github.com/wasmCloud/wasmCloud/issues/1715
Next release
No consumer impact
I can't test, as I have no access to Packagecloud site for the project.
I have recovered the information to define the targets from Packagecloud
Build the project, launch the action and see the image appear on Packagecloud site
=> Add Ubuntu 23.10 and 24.04 build

.github/workflows/wasmcloud.yml
This PR fixes the issue #1715 by adding Fedora 39 (id 279 in Packagecloud) and 40 (id 283 in Packagecloud) as targets for packagecloud.io
It fixes the issue #1715
Next release
No consumer impact
I can't test, as I have no access to Packagecloud site for the project.
I have recovered the information to define the targets from Packagecloud
Build the project, launch the action and see the image appear on Packagecloud site
=> Fix #1715 - Add Fedora 39 and 40 build

tests/actors/rust/Cargo.lock, tests/actors/rust/Cargo.toml, tests/actors/rust/builtins-component-reactor/Cargo.toml, tests/actors/rust/builtins-component-reactor/src/lib.rs, tests/actors/rust/messaging-invoker/src/lib.rs, tests/actors/rust/pinger-config-component/src/lib.rs, tests/actors/rust/ponger-config-component/src/lib.rs, tests/actors/rust/wrpc-pinger-component/src/lib.rs, tests/actors/rust/wrpc-ponger-component/src/lib.rs
=> chore: update `test-actors` dependencies

flake.nix
- Looks like Darwin support was fixed in https://github.com/NixOS/nixpkgs/pull/251527
- Remove `protobuf` dep, which is not required for build anymore
=> build(nix): include `tinygo` in devshell on aarch64-darwin

crates/provider-sdk/src/error.rs, crates/provider-sdk/src/lib.rs, crates/provider-sdk/src/provider.rs
This commit adds support for a implementer-provided provider initialization hook that `provider-sdk` can call during initialization.
=> feat(provider-sdk): add support for init()

crates/provider-blobstore-fs/src/lib.rs
Not quite sure how the original PR passed tests, but we were missing an import. This should fix the issue
=> fix(blobstore-fs): Fixes missing import

.github/workflows/wash.yml
This commit adds tests for ensuring `wash new` works for a few previous versions (and the current version) of `wash`.
This was developed as afollow up to prevent issues like https://github.com/wasmCloud/wasmCloud/issues/1721 from re-occuring.
> [!WARNING]
> Tests in this PR won't pass until https://github.com/wasmCloud/wasmCloud/pull/1758 is merged.
=> test(wash-lib): add e2e test for wash new

.github/workflows/provider.yml
Apparently pushing `latest` is prohibited:
https://github.com/wasmCloud/wasmCloud/actions/runs/8450924701/job/23149190845
```
Run ./wash push ghcr.io/wasmcloud/messaging-nats:latest "messaging-nats.par.gz"
Pushing artifacts with tag 'latest' is prohibited
```
=> ci: do not push `latest`

crates/core/src/rpc.rs, crates/provider-sdk/src/provider.rs
This commit moves the topic generation functions that were used for wasmbus RPC topics from `provider-sdk` to `core` so that they can be used/referred to more widely.
=> refactor(provider-sdk): move wasmbus RPC topic generation to core

Cargo.lock, Cargo.toml, crates/core/Cargo.toml, crates/core/src/lib.rs, crates/core/src/tls.rs, crates/host/Cargo.toml, crates/host/src/oci.rs, crates/provider-blobstore-s3/Cargo.toml, crates/provider-blobstore-s3/src/lib.rs, crates/provider-http-client/Cargo.toml, crates/provider-http-client/src/lib.rs, crates/provider-http-server/Cargo.toml, crates/provider-http-server/src/lib.rs, crates/provider-sdk/Cargo.toml, crates/wash-cli/src/ui/mod.rs, crates/wash-lib/Cargo.toml, crates/wash-lib/src/app.rs, crates/wash-lib/src/registry.rs, crates/wash-lib/src/start/github.rs, crates/wash-lib/src/start/wasmcloud.rs, tests/interfaces.rs
Include both webpki and native OS root certificates by default for TLS. This ensures that outgoing connections work *everywhere* - be it a `FROM scratch` Docker container, consumer OS behind a corporate firewall, an embedded device or anything in-between.
Eventually we should standardize TLS setup in providers and have a way to switch between the CA pools, but for now we should focus on getting things working.
~The specified `reqwest` feature set ensures both bundles are included https://github.com/seanmonstar/reqwest/blob/14e46ff8cb7550473c950f3471d049ad2e139d3f/src/async_impl/client.rs#L501-L529~ this fails when the OS bundle is missing, so simply load the native certs ourselves and log if we failed to load the native bundle
May fix - https://github.com/wasmCloud/wasmCloud/issues/1433
=> feat: use native TLS roots along webpki

crates/runtime/src/actor/component/mod.rs, crates/runtime/src/capability/provider/mem/keyvalue.rs, crates/runtime/src/io.rs, crates/runtime/src/lib.rs
Reenable `clippy::pedantic` in the runtime and address warnings introduced in the time it was missing
fixup https://github.com/wasmCloud/wasmCloud/commit/42d069eee87d1b5befff1a95b49973064f1a1d1b, where this clippy lint was removed with no explanation
=> chore(runtime): reenable `clippy::pedantic`

crates/host/src/wasmbus/event.rs, crates/host/src/wasmbus/mod.rs
This commit adds a `label_changed` event that can be listened to in order to be notified of label changes on a host.
The single event handles both updates and deletes.
Resolves #1551
=> feat(host): add label_changed event for label update/delete

Cargo.lock, Cargo.toml
We had cut a tag at alpha.3 without bumping the Cargo.toml
=> chore(*): Bumps version to alpha.4

.github/CODEOWNERS
@vados-cosmonic noticed this issue when viewing the `.github/CODEOWNERS` file which I think is caused by a capitalization in the team name. It might not, though, so 🤷‍♂️.
=> ci(github): update CODEOWNERS

crates/wash-cli/src/dev.rs, crates/wash-cli/src/down/mod.rs, crates/wash-cli/src/up/config.rs, crates/wash-cli/src/up/mod.rs, crates/wash-cli/tests/common/mod.rs, crates/wash-cli/tests/wash_stop.rs, crates/wash-cli/tests/wash_up.rs, crates/wash-lib/src/cli/stop.rs, crates/wash-lib/src/config.rs
If a wasmcloud host is runnning, `wash up` will not start an additional host unless `--scale` is passed.
When starting multiple hosts, NATS should be run independently of wasmcloud, otherwise killing the original `wash up` will also stop NATS.
Wash up should be idempotent https://github.com/wasmCloud/wasmCloud/issues/846
This will change how users start multiple wasmCloud hosts on the same machine
Integration test added.
=> Wash up should be idempotent.

examples/typescript/actors/http-hello-world/wit/deps/logging/logging.wit, examples/typescript/actors/http-hello-world/wit/deps/logging/world.wit
The TypeScript http-hello-world template is missing WIT definitions for wasi:logging and fails on build. This PR fixes the issue on the 0.82-examples branch used by v0.82 docs.
=> fix(examples): Add logging to TS deps on 0.82-examples

crates/control-interface/src/client.rs, crates/host/src/wasmbus/event.rs, crates/host/src/wasmbus/mod.rs, crates/test-util/src/actor.rs, crates/wash-lib/src/actor.rs, crates/wash-lib/src/wait.rs
This PR renames the `actor_scaled` and `actor_scale_failed` event to `component_scaled` and `component_scale_failed`. It's the last breaking change (that I know of) with the rename that we should do pre-1.0.
In this PR I also adjusted wash + wash-lib to deal with both events to ease the transition.
Consumers like wadm will need to update their event to instead handle component scaled.
=> feat(*)!: rename actor_scale* events

crates/provider-lattice-controller/src/lib.rs, crates/provider-messaging-kafka/src/lib.rs, crates/provider-messaging-nats/src/lib.rs, crates/provider-wit-bindgen-macro/src/config.rs, crates/provider-wit-bindgen-macro/src/lib.rs, crates/provider-wit-bindgen-macro/src/wit.rs
While we have yet to figure out exactly how we expose WIT related metadata about the provider to the
host (see: https://github.com/wasmCloud/wasmCloud/issues/1780), we won't be needing the wasmcloud contract specific code that was necessary before.
This commit removes `contract_id()` as a requirement for providers.
=> chore(provider-bindgen): remove contract_id

Cargo.lock, crates/wrpc-transport-derive-macro/Cargo.toml, crates/wrpc-transport-derive-macro/src/wrpc_transport/encode.rs, crates/wrpc-transport-derive-macro/src/wrpc_transport/receive.rs, crates/wrpc-transport-derive/Cargo.toml, crates/wrpc-transport-derive/src/lib.rs
This PR adds OTel integration (`#[instrument]` annotations, basically) to the implementation code generated by the derive macro.
=> feat(wrpc-transport-derive-*): add otel integration

crates/wash-cli/src/build.rs, crates/wash-lib/src/cli/claims.rs, crates/wash-lib/src/parser/mod.rs, crates/wash-lib/tests/parser/main.rs
`wash build` always generates keys in the local folder instead of `$HOME/.wash/keys
this is a draft PR with some work still in progress.
modified the default key_directory for `wash build`. tried to run wasmCloud locally to see if the changes are being resonated while creating a new actor.
=> WIP: [issue#1624-modified the default key_directory for wash build]

crates/wash-cli/src/build.rs, crates/wash-lib/src/cli/claims.rs, crates/wash-lib/src/parser/mod.rs, crates/wash-lib/tests/parser/main.rs
This reverts commit edc660d.Reverts wasmCloud/wasmCloud#1685
This was a good change, but it was failing a test. Reverting for now, @siddharthkhonde it should be pretty simple to re-open the change here just with the test fix
=> Revert "fix(wash-lib): changed the variable name for a cleaner code"

crates/wash-cli/src/completions.rs
Adjust message on first run of `wash` to include callout to check out the slack community.
`next`
No impact here since it's just developer messaging.
This is what the message looks like now:
=> feat(wash): add feedback message to 1st run message

crates/wash-cli/src/up/mod.rs
Error output was using the static version for wadm even when `--wadm-version` is set.
None
`next`
Better DX
=> fix(wash-cli): use config version in error output

crates/host/src/wasmbus/mod.rs
This commit slightly improves the wording when a provider ID and component specification URL mismatch occurs, along with specifying a possible solution.
This error is thrown by `wash` and it's a bit difficult to figure out what to resolve it otherwise.
=> chore(host): imrpove wording for spec/provider ref mismatch

crates/wash-cli/src/common/registry_cmd.rs, crates/wash-lib/src/cli/registry.rs
This commit fixes the `wash push` command to ensure it uses the `--config` switch if provided when looking up project config.
=> fix(wash): use config option when getting project config

Cargo.lock, Cargo.toml, crates/wash-cli/Cargo.toml, crates/wash-cli/src/build.rs, crates/wash-cli/src/up/config.rs, crates/wash-lib/Cargo.toml
This PR bumps a couple of crates (control-interface, wash-lib, wadm, wash-cli) in preparation for release candidate testing. Largely these components were compatible with each other already, with the exception of wadm, but this PR brings them all together in the same `wash` bundle for easy testing.
wash-lib v0.20.0-alpha.1
wash-cli v0.27.0-alpha.2
=> Prepare wash 0.27.0-alpha.2 for wasmCloud 1.0 release candidate testing

.github/workflows/wash.yml, crates/wash-cli/src/common/registry_cmd.rs, crates/wash-lib/src/parser/mod.rs, crates/wash-lib/tests/parser/main.rs
When URLs are submitted to `wash push` as the first argument, unless a `--registry` is provided, the URL is parsed as an
`oci_distribution::Reference`.
It is possible for a URL like `ghcr.io/wasmCloud/img:v0.1.0` to correctly parse *yet* fail the the `url == image.whole()` test, because the lowercasing of the *supplied* URL was not used throughout `resolve_artifact_ref()`.
This commit performs the lowercasing of the URL and registry (if supplied) consistently in `resolve_artifact_ref()`, ensuring that the comparison works, and `oci_distribution::Reference`s that correctly parse are used.
=> fix(wash): registry image URL parsing

.github/workflows/examples-components.yml
This commit modifies the release logic to use the full ref name rather than just tag name. This both is more consistent with other code, is clearer ("branch prefix" wasn't right), and avoids collisions with refs that are non-tags.
=> fix(ci): use ref prefix rather than ref name

crates/wash-cli/src/ui/mod.rs, crates/wash-cli/src/up/config.rs, crates/wash-cli/src/up/mod.rs, crates/wash-lib/src/start/nats.rs, examples/docker/docker-compose-websockets.yml, examples/docker/nats.websocket.conf, washboard-ui/CONTRIBUTING.md, washboard-ui/packages/washboard-ui/.env.development, washboard-ui/packages/washboard-ui/package.json, washboard-ui/packages/washboard-ui/src/app/components/app-lattice-client-provider.tsx
- Enable Websocket by default
- Update Default Websocket Port to `4223`
- Change washboard-ui to use new default port and bump version
`washboard-ui@0.2.1`
`wash@next`
Tested locally against current version of washboard
=> Washboard and websockets

Cargo.lock, Cargo.toml, crates/host/src/wasmbus/host_config.rs, crates/host/src/wasmbus/mod.rs, src/main.rs
While I was here, I fixed the issue where we were using the host crate version instead of the top level binary host version in our events and ctl API responses
=> chore(host): Bumps host version to rc.2

crates/host/src/wasmbus/mod.rs
This PR allows overwriting the provider reference in the component specification for a given ID if that provider is not running on this host. This primarily solves a developer experience issue where a provider is no longer running and it cannot be updated without deleting the component spec manually.
Implemented for components in https://github.com/wasmCloud/wasmCloud/pull/1829
1.0.0
=> fix(host): allow overwriting provider reference

examples/typescript/components/http-hello-world/http-hello-world.ts
This PR fixes the issue with the TypeScript example where the outgoing response stream resource wasn't dropped correctly, so requests would receive a response but then hang indefinitely.
https://github.com/bytecodealliance/ComponentizeJS/issues/99
=> fix(example): typescript hello world hang

Cargo.lock, Cargo.toml, crates/wascap/Cargo.toml
Bumping wascap to 0.14.0 so I can release the breaking change that provider-archive needs to release 0.10.0 so I can release the breaking change that wash-lib needs in order to release alongside wash-cli to crates.io. Yay.
We should definitely get to that cargo smart-releaser spike soon.
`cargo publish --dry-run` seems to indicate we are okay here.
=> chore(wascap): bump to 0.14.0

Cargo.lock, crates/wash-cli/Cargo.toml, crates/wash-cli/src/call.rs, crates/wash-cli/tests/common/mod.rs, crates/wash-cli/tests/wash_call.rs, crates/wash-cli/tests/wash_start.rs, crates/wash-cli/tests/wash_stop.rs, examples/rust/components/http-jsonify/src/lib.rs
Resolves https://github.com/wasmCloud/wasmCloud/issues/1644
This PR modifies `wash call` to be able to support sending HTTP requests to actors that implement `wasi:http/incoming-handler.handle`
=> test(wash): re-enable wash call test

examples/rust/components/blobby/src/lib.rs, examples/rust/components/echo-messaging/src/lib.rs, examples/rust/components/http-hello-world/src/lib.rs, examples/rust/components/http-jsonify/src/lib.rs, examples/rust/components/http-keyvalue-counter/src/lib.rs
Remove the redundant `world` specification for `wit-bindgen` invocations. It's not necessary when there's only one world in the package
=> chore(examples): remove redundant world spec

Cargo.lock, Cargo.toml
The 1.0 release is a grand culmination of effort from the [2024 Q1 Roadmap](https://wasmcloud.com/docs/1.0/roadmap/) which focused primarily on standardization of host control interface and RPC protocols, events, and WebAssembly component support. 
As specified in our 1.0.0 roadmap, these are the major features that wasmCloud brings as a project:
1. [Declarative WebAssembly Orchestration](https://wasmcloud.com/docs/1.0/concepts/applications)
2. [Seamless Distributed Networking](https://wasmcloud.com/docs/1.0/concepts/lattice)
3. [Vendorless Application Components](https://wasmcloud.com/docs/1.0/concepts/components#application-components)
4. [Completely OTEL Observable](https://wasmcloud.com/docs/1.0/category/observability)
5. [Defense-In-Depth Security By …
=> release: v1.0.0

README.md, examples/rust/components/http-keyvalue-counter/README.md
This PR updates our README in the repository to better match our documentation and messaging 😄
=> chore: update README based on documentation

.github/workflows/examples-components.yml, examples/rust/components/http-hello-world/.gitignore, examples/rust/components/http-jsonify/.gitignore, examples/rust/components/http-jsonify/Cargo.toml, examples/rust/components/http-jsonify/src/lib.rs, examples/rust/components/http-jsonify/wasmcloud.toml, examples/rust/components/http-keyvalue-counter/.gitignore
These commits do two things:
- fix the input streaming logic of `http-jsonify`
- bump version of http jsonify to v0.1.1 (a `component-http-jsonify-v0.1.1` tag needs to be pushed for it to be published)
=> fix(examples): http jsonify input streaming

Cargo.lock, crates/wash-cli/Cargo.toml, crates/wash-cli/src/call.rs, crates/wash-cli/tests/common/mod.rs, crates/wash-cli/tests/wash_call.rs, crates/wash-cli/tests/wash_start.rs, crates/wash-cli/tests/wash_stop.rs, crates/wash-lib/src/cli/output.rs
This commit re-adds the missing `wash call` tests to the codebase, enhancing `wash call` to be able to invoke incoming HTTP handlers along the way.
=> feat(wash-cli): re-add wash call tests

crates/wash-cli/README.md, crates/wash-cli/src/common/link_cmd.rs, crates/wash-lib/README.md, crates/wash-lib/src/cli/link.rs, crates/wash-lib/src/parser/mod.rs, crates/wash-lib/tests/parser/main.rs
This PR makes the wash `link del` interface consistent  with `link put`, renames an actor->component in build output, and adds an alias that follows our general noun verb pattern with a more common word (link query == link get).
I also updated the README while I was in there.
Fixes #1926
Fixes #1941 
wash-lib next minor
wash-cli next minor
I did verify the new `wash link del` command works
=> feat(wash-lib)!: make link del interface consistent

examples/rust/components/http-keyvalue-counter/src/lib.rs
Resolves wasmcloud/wasmcloud#1958 removing name for bucket and adding comment.
=> fix(examples): Remove foo value for bucket

crates/wash-cli/src/generate.rs, crates/wash-lib/src/generate/favorites.toml, crates/wash-lib/src/generate/mod.rs
This PR removes the no-longer-used `wash new interface` functionality as all interfaces now use wit. We may consider this in the future to help generate a WIT file, but likely this should come through WebAssembly tooling.
next minor wash-lib
next minor wash-cli
=> chore: remove "wash new interface"

crates/wash-cli/tests/wash_build.rs, crates/wash-lib/src/cli/claims.rs, crates/wash-lib/src/parser/mod.rs, crates/wash-lib/tests/parser/main.rs
Modified the default key generation directory
Upon actor creation, the keys get generated by default in the user's `$HOME` directory
Tested successfully with 2 scenarios - with and without specifying "key_directory" attribute in the wasmcloud.toml of the actor
=> fix(wash-cli): re-adding the changes to make sure tests pass sucessfully

crates/host/src/wasmbus/mod.rs
Signed-off-by: Yerzhan Zhamashev <yerzhan.contribs@novel.systems>
> When a component is scaled to a max instances value of 0, we emit two component_scaled events that assert that it was scaled to zero. 
Similarly, an extra `component_scaled` event with `max_instances: 0` is emitted for `wash scale` and `wash update`.
#1888 
`wasmCloud v1.0`
Extra `component_scaled` event with `max_instances: 0` is no longer emitted when a component is updated or scaled (and scaled to 0 i.e stopped)
All tests should work as expected
Listening to `wasmbus.evt.>` on NATS while performing `wash start`, `wash scale`, `wash update`, and `wash stop` on a component.
=> fix(host): remove extra component_scaled events

Cargo.lock, crates/provider-messaging-nats/Cargo.toml
This PR bumps the messaging NATS provider to 0.20.0 for release since it's had some breaking changes that we want to have in a non-canary release.
#1965
=> chore(messaging-nats): bump to 0.20.0

Cargo.lock, crates/provider-keyvalue-redis/Cargo.toml, crates/provider-keyvalue-redis/src/lib.rs
Without a default connection the redis KV provider would normally fail to start -- this can be quite confusing considering usually a connetion is not expected to be made yet.
This commit refactors the conenction logic to allow running a provider without a pre-made default connection, and creates one upon the first connection of an actor that relies on the default
connection (i.e. doesn't have a connection specified via link config).
=> feat(providers): allow missing default connection for redis

Cargo.lock, crates/provider-http-server/Cargo.toml, crates/provider-http-server/src/lib.rs
- **fix(http-server): handle incoming requests in task**
- **chore(http-server): bump to 0.20.1**
This PR changes the implementation of instantiating a new http-server incoming requests handler, such that the axum server is handling requests inside of a task. This was an issue as links from the HTTP server to a component would establish this server, then `await` on the server forever. Put another way, the HTTP server could only handle one server at a time because it was waiting for incoming requests.
http-server v0.20.1
=> fix: http-server background task handle

crates/host/src/wasmbus/mod.rs, crates/wash-cli/tests/wash_update.rs, crates/wash-lib/src/cli/update.rs
Skip component update if the currently running component for the component id has the same image reference.
If not skipped, `component_scaled` event is emitted asserting that the component with the new image reference is started, then another `component_scaled` event that asserts a component with the same id and image reference is scaled to 0. Thus, it is difficult to tell if it scaled to 0 or was actually updated with an image of the same reference.
#1972 
next wasmCloud v1 minor or patch release
- Updating a host's running component with the same image reference in `wash-cli` results in an error.
- If wasmCloud host receives a request to update a component and the component image reference did not change, the component update process is skipped
- Changed wash output messages for …
=> feature: prevent component update if image reference unchanged

src/bin/blobstore-s3-provider/wasmcloud.toml, src/bin/http-client-provider/wasmcloud.toml, src/bin/http-server-provider/wasmcloud.toml, src/bin/keyvalue-vault-provider/wasmcloud.toml, src/bin/messaging-kafka-provider/wasmcloud.toml, src/bin/messaging-nats-provider/wasmcloud.toml
This PR adds a `wasmcloud.toml` file for each capability provider in our `src/bin` directory so that, from the `src/bin/<provider>` directory you can build the provider with wash build.
Alternatively, from the root of the repository, you can run (for example, for HTTP server) `wash build -p src/bin/http-server-provider`. The `http-server-provider.par.gz` will be output in the directory that you ran the command.
In the future it would be great to also be able to specify a Cargo.toml manifest path inside of wasmcloud.toml so that the version can be inferred from there even if the manifest is not colocated. I will file a followup issue for this.
I did make sure this worked.
=> feat(provider): add wasmcloud.tomls for each provider

CHANGELOG.md, crates/control-interface/CHANGELOG.md, crates/core/CHANGELOG.md, crates/host/CHANGELOG.md, crates/opentelemetry-nats/CHANGELOG.md, crates/provider-archive/CHANGELOG.md, crates/provider-blobstore-fs/CHANGELOG.md, crates/provider-blobstore-s3/CHANGELOG.md, crates/provider-http-client/CHANGELOG.md, crates/provider-http-server/CHANGELOG.md, crates/provider-keyvalue-redis/CHANGELOG.md, crates/provider-keyvalue-vault/CHANGELOG.md, crates/provider-lattice-controller/CHANGELOG.md, crates/provider-messaging-kafka/CHANGELOG.md, crates/provider-messaging-nats/CHANGELOG.md, crates/provider-sdk/CHANGELOG.md, crates/runtime/CHANGELOG.md, crates/tracing/CHANGELOG.md
This PR uses [cargo-changelog](https://crates.io/crates/changelog) to generate changelogs for our crates.
=> feat(CHANGELOG): generate crate changelogs

crates/provider-messaging-nats/src/connection.rs, crates/provider-messaging-nats/src/lib.rs
This commit enables a custom inbox prefix for the NATS messaging provider.
Resolves https://github.com/wasmCloud/wasmCloud/issues/1195
=> feat(providers): custom inbox prefix for NATS messaging provider

Cargo.lock, Cargo.toml, crates/wash-cli/src/up/config.rs
This PR bumps wasmCloud and wadm inside of wash to their latest versions.
We should consider an automatic way to do this, or to pull patch releases automatically :D
https://github.com/wasmCloud/wasmCloud/issues/2032
=> chore(wash-cli): bump wasmCloud and wadm bin versions

crates/wash-cli/src/plugin.rs
Name is meant to be a friendly name for humans and not for file names
=> fix(plugins): use ID for the final saved binary on plugin install

crates/host/src/wasmbus/mod.rs, crates/runtime/src/runtime.rs, crates/runtime/tests/runtime.rs, src/main.rs
This ensures that the epoch interrupt thread is gracefully shutdown (which only occurs after there are not more engine (and therefore the host) references) without significantly slowing down the host shutdown.
In particular, this, in overwhelming majority of cases, should prevent the following error (or similar) from ever showing up:
```
Error: failed to shutdown host
Caused by:
epoch thread has not finished
```
Small change is also that I've removed the requirement for actors to be signed, as was discussed before a few times
#2023 #2002
=> feat(host): gracefully shutdown epoch interrupt thread

.github/workflows/wasmcloud.yml
This PR sets up the wash-cli release action to trigger a repository dispatch event in https://github.com/wasmCloud/homebrew-wasmcloud and https://github.com/wasmCloud/chocolatey-wash to update the formula automatically.
We'll still need to approve the PRs in those repositories after actions run, but this prevents a bunch of clicks to do a workflow_dispatch modification.
https://github.com/wasmCloud/chocolatey-wash/commit/fb9151a9663d754fbcca5906e78c5ff575122c72
https://github.com/wasmCloud/homebrew-wasmcloud/pull/61
=> ci(wash-cli): trigger homebrew/choco update

.github/workflows/wasmcloud.yml
When releasing a crate or one of our main binaries, wash-cli or wasmcloud, currently it can be very difficult to properly predict:
1. What crates need to be released
2. What order crates need to be released
3. Whether to patch bump, minor bump, or leave as-is and release
Not only that, but we should be keeping up with a changelog as well. I chose to use cargo smart-release (with workspace-deps support https://github.com/Byron/cargo-smart-release/pull/17) in order to take care of the above actions automatically.
This PR adds a workflow_dispatch trigger to our `wasmcloud` action (if desired, I can migrate to a new action since I know that the workflow_dispatch wasn't release specific before) and lets you specify a crate to release. You can either directly release the crate, or leave the …
=> ci: Enable workflow_dispatch action smart-release

crates/wash-cli/src/common/registry_cmd.rs, crates/wash-cli/tests/wash_reg.rs, crates/wash-lib/src/registry.rs
This follows a similar (but not exact) format from `docker push` and includes the digest and tag in JSON output.
Closes #2076
=> feat(push): Adds digest and tag to output of `wash push`

crates/wash-cli/src/up/config.rs, crates/wash-cli/tests/wash_reg.rs
This PR bumps the included wasmcloud version in wash 0.28 to be the latest and include patch fixes for small devices.
Fixes #1961
Wouldn't have to create this PR if #2032 was done :)
wash-cli v0.28.0
=> chore(wash-cli): bump wasmcloud v1.0.2

crates/core/Cargo.toml
This PR ensures when `oci-distribution` is used for wasmcloud-core that we use rustls-tls, which fixes a compilation issue with our default features.
Fixes #2088
next patch release of wasmcloud-core
It builds!
=> fix(core): compile with default features

Cargo.lock, crates/wash-cli/Cargo.toml, crates/wash-cli/src/common/registry_cmd.rs, crates/wash-cli/tests/common/mod.rs, crates/wash-cli/tests/wash_reg.rs, crates/wash-lib/Cargo.toml, crates/wash-lib/src/registry.rs
This addresses a couple of problems:
1. `wash push` was returning the manifest from the manifest-attached config, not the manifest itself.
2. `wash push` was passing in an empty hashmap for `annotations` even if there were none, which resulted in an empty `"annotations": {}` being stored on the registry, when it really should've just been omitted altogether
In addition, it adds logic to calculate the manifest digest locally based on an alphabetically sorted set of bytes to match the behavior of the most commonly available/widely deployed registry, [distribution](https://github.com/distribution/distribution).
=> fix: Make wash push returned digest based on the pushed manifest

.github/workflows/wasmcloud.yml
When writing this action, I forgot to ensure that we're triggering the repository dispatch in the _other_ repository, not this one. At least the PAT protections are in place and prevent triggering actions in this repo.
https://github.com/wasmCloud/wasmCloud/actions/runs/9005487474/job/24741562902
N/A, just next wash-cli release
=> ci(wash-cli): trigger repository dispatch in proper repo

.github/workflows/wasmcloud.yml
This PR will allow us to specify additional flags during release, e.g. `-d patch`, to override smart-release default behavior if necessary.
=> ci(release): allow passing additional args to smart-release

crates/wash-lib/src/registry.rs
Looking through the OCI push and pull code, I noticed that the client we set up for [pull has `extra_root_certificates` configured](https://github.com/wasmCloud/wasmCloud/blob/main/crates/wash-lib/src/registry.rs#L133-L141), but the one for push did not, so I felt like that would be worth remedying.
Presumably we'll want the same behavior in both cases.
=> fix(wash-lib): Setup extra_root_certificates for OCI push client

crates/wash-cli/src/common/registry_cmd.rs, crates/wash-lib/src/cli/registry.rs
`wash reg ping` was removed in https://github.com/wasmcloud/wasmcloud/commit/e6ee3de780ec5bc6a6cc0ec3a15457278978bca6 as part of https://github.com/wasmCloud/wasmCloud/pull/1649, but this code was left over from that.
=> Cleanup reg ping remnants

Cargo.lock, Cargo.toml, crates/host/src/oci.rs, crates/wash-lib/src/registry.rs
We're currently using 0.9.4 from 2022
=> chore: Bump oci-distribution to 0.11.0

crates/wash-cli/tests/wash_label.rs, crates/wash-lib/src/cli/label.rs, crates/wash-lib/src/cli/output.rs
This commit adds support for specifying multiple labels to `wash label`.
Users can use `wash label <host-id> key1=value1,key2=value2` to set multiple labels on the host at the same time, in a best-effort manner
=> feat(wash-lib): add support for specifying multiple labels

crates/wash-cli/src/common/registry_cmd.rs, crates/wash-cli/src/par.rs, crates/wash-cli/src/plugin.rs, crates/wash-lib/src/cli/claims.rs, crates/wash-lib/src/cli/inspect.rs, crates/wash-lib/src/cli/registry.rs, crates/wash-lib/src/registry.rs
Sometimes it can be easier to simply ignore HTTPS certificate than try to ensure that it's correctly set up correctly in the OS  trust store (such as when you have self-signed certificates), this should make those scenarios easier to use any wash commands that interact with OCI registries.
=> Add option to skip certificate validation for the OCI registry connection

Cargo.lock, Cargo.toml, crates/wash-cli/src/up/config.rs
This PR bumps to wadm v0.11.2 which is a patch to release the proper amd64 macos artifact for wadm.
Fixes https://github.com/wasmCloud/wasmCloud/issues/2134
=> chore(wash-cli): bump wadm to v0.11.2

examples/rust/composition/README.md
This adds a more simple way of composing using `wac plug` and keeps the old instructions around for advanced usage
=> ref(composition): Updates the composition README

crates/wash-lib/src/cli/link.rs
Solves #1991
Ran `cargo build` and  `cargo test` in .crates/wash-cli
ran `cargo run up` & `cargo run -- link delete source ns package` , got executed in the same way as `cargo run --link del source ns package`
=> Provides Alias for "wash link del <args>" as "wash link delete <args>"

Cargo.lock, Cargo.toml, crates/host/Cargo.toml, crates/host/src/oci.rs, crates/wash-cli/Cargo.toml, crates/wash-cli/src/common/registry_cmd.rs, crates/wash-cli/src/plugin.rs, crates/wash-lib/Cargo.toml, crates/wash-lib/src/registry.rs
This PR contains two commits: one of them updates wash to only push the new type of wasm manifest, but supports pulling both types of manifest. This is technically a small breaking change for wash, but see the commit message for more details. The second commit updates the host to support the new wasm type as well as the old manifest type. This backwards compatibility will be in place until at least wasmCloud 2.0. 
Closes #2038
=> feat(*): Updates wash and host to support new oci wasm manifests

washboard-ui/packages/lattice-client-core/package.json, washboard-ui/packages/lattice-client-core/src/connection/nats-ws-lattice-connection.ts
Found that the nats connection wasn't reconnecting if it failed to connect initially, or was disconnected for some reason. This makes the connection attempt to reconnect if a new request is made while it is disconnected/errored.
=> Handle disconnected NATS connection better

crates/wash-lib/src/start/github.rs, crates/wash-lib/src/start/wasmcloud.rs
This makes it possible to specify basic authentication credentials to be used with the configured `HTTP(S)_PROXY` (or `http(s)_proxy`) environment variables by way of specifying `WASH_PROXY_USERNAME` and `WASH_PROXY_PASSWORD` environment variables.
If we think this is a reasonable approach, I'm also happy to extend this to the [`wash ui` command](https://github.com/wasmCloud/wasmCloud/blob/main/crates/wash-cli/src/ui/mod.rs#L66-L76)
=> feat(wash-lib): Support configuring proxy credentials for HTTP(S)_PROXY when downloading artifacts

Cargo.lock, Cargo.toml, crates/wash-lib/Cargo.toml, crates/wash-lib/src/start/github.rs
This builds on https://github.com/wasmCloud/wasmCloud/pull/2175 by adding a set of tests to try out the various configurations.
I chose not to push this into #2175 in case we didn't want to go down this route for testing. The goal is mostly to prove out that #2175 works as intended.
=> chore(wash-lib): Test HTTP(S)_PROXY and WASH_PROXY_* configurations

Cargo.lock, Cargo.toml, crates/tracing/src/metrics.rs
The version of [opentelemetry](https://github.com/open-telemetry/opentelemetry-rust/) we're depending on is [a bit out of date](https://github.com/open-telemetry/opentelemetry-rust/releases/tag/v0.21.0) by now, so this brings us up to date on the release as of [2 weeks ago](https://github.com/open-telemetry/opentelemetry-rust/releases/tag/opentelemetry-0.23.0).
I tried my best to look across the various [CHANGELOG](https://github.com/open-telemetry/opentelemetry-rust/compare/v0.21.0...opentelemetry-0.23.0) entries to see if there were any breaking changes we would be impacted, it didn't seem like we should be impacted by anything other than the introduction of the new Gauge instrument kind.
=> chore: Bump opentelemetry-* crates and tracing-opentelemetry to latest version

Cargo.lock, crates/provider-http-client/Cargo.toml, crates/provider-http-client/src/lib.rs
In the interest of keeping https://github.com/wasmCloud/wasmCloud/pull/2164 focused on just the wasmcloud-internal client, this implements the suggestion of adding a default User-Agent if one isn't set in the `http-client` provider.
=> feat(http-client): Add default User-Agent header to requests

crates/core/src/tls.rs
Certain proxies will require authentication to be provided if the User-Agent header is missing when establishing a tunnel, so we should set a reasonable default here (`wasmcloud-core/<crate-version>` for now, we can adjust it later if need be) to enable usage in networks that are behind such proxies.
=> Configure reqwest with user-agent

crates/wash-cli/src/app/mod.rs, crates/wash-cli/src/up/mod.rs, crates/wash-cli/tests/common/mod.rs, crates/wash-cli/tests/fixtures/wadm/component-only.wadm.yaml, crates/wash-cli/tests/wash_up.rs, crates/wash-lib/src/app.rs, crates/wash-lib/src/cli/output.rs
This commit introduces the functionality for `wash up --wadm-manifest <path to manifest>`, which starts a host and immediately deploys an application defined in a WADM manifest, cleaning it up when the `Ctrl+C` is hit, along with normal host termination.
=> feat(wash-cli): `wash up --wadm-manifest`

Cargo.lock, crates/provider-http-client/Cargo.toml, src/bin/http-client-provider/wasmcloud.toml
This PR enables the HTTP client provider to use the platform's native certificate store at runtime, as specified in https://crates.io/crates/hyper-rustls via rustls-native-certs. As far as I know this doesn't introduce any platform specific dependencies, but it can fail in platform specific ways.
Worth noting this would also enable loading a set of certs using the `SSL_CERT_FILE` environment variable, however we don't pass environment variables to providers by default. We may need to consider adding that as a separate feature.
http-client v0.10.0
Draft pending verification this fixes an issue on machines with additional certificates
=> fix(http-client)!: use platform native system certs, enable tls 1.2

.github/workflows/license-check.yml, deny.toml, tests/components/Cargo.toml
This adds checks of licenses to avoid any faux-pen source licenses or other licenses that are in violation of our license or CNCF licensing rules
=> feat(*): Adds cargo deny checks for licenses

Cargo.lock, Cargo.toml, crates/provider-blobstore-azure/Cargo.toml, crates/provider-blobstore-s3/Cargo.toml, crates/provider-blobstore-s3/README.md, crates/provider-blobstore-s3/src/lib.rs, crates/provider-keyvalue-vault/Cargo.toml, crates/provider-keyvalue-vault/src/config.rs, deny.toml
This involved removing a dependency that we weren't commonly using or wasn't even documented in some cases (file loading a .env file in 2 providers). Things should be good to go now
=> fix(*): Clarifies additional licenses based off of CNCF license list

crates/core/src/otel.rs, crates/host/src/wasmbus/mod.rs, crates/tracing/src/lib.rs, crates/tracing/src/metrics.rs, crates/tracing/src/traces.rs, src/main.rs
We need to support OpenTelemetry's gRPC protocol in the exporter configuration as [there can be benefits](https://github.com/open-telemetry/oteps/blob/main/text/0035-opentelemetry-protocol.md#otlp-over-grpc) to using it over the (default) HTTP-based binary protocol.
This makes it possible to pass in `--observability-protocol=grpc` or `WASMCLOUD_OBSERVABILITY_PROTOCOL=grpc` to enable it.
The default is still kept with the HTTP-based binary protocol.
=> feat: Add support for configuring grpc protocol with OpenTelemetry

Cargo.lock, crates/provider-http-client/Cargo.toml, crates/provider-http-client/README.md, crates/provider-http-client/src/lib.rs, src/bin/http-client-provider/main.rs
While we're enabling additional functionality for the HTTP client, I wanted to ensure we could preserve the same behavior from rustls-native-certs's SSL_CERT_FILE environment variable as config for the http client. This PR adds three completely optional configuration values to disable loading native certificates, disable loading webpki certificates, and to load additional certificates from a file on disk.
Followup to #2193
http-client v0.10.0
=> feat(http-client): provide configuration options for http-client

Cargo.lock, Cargo.toml, crates/wash-cli/Cargo.toml, crates/wash-cli/src/app/mod.rs, crates/wash-cli/src/app/output.rs, crates/wash-cli/src/up/mod.rs, crates/wash-cli/tests/fixtures/wadm/manifests/simple.wadm.yaml, crates/wash-cli/tests/wash_app.rs, crates/wash-lib/Cargo.toml, crates/wash-lib/src/app.rs, crates/wash-lib/src/cli/output.rs
This commit adds a `wash app validate` subcommand which can be used to check and suggest fixes for WADM manifests.
As the breadth of possible errors with a manifest is wide, it's difficult to enumerate and check every possible error, but validate serves as a starting point in being able to give users proactive advice on WADM manifests.
For now, it checks:
- interface names (ex. typos, misnamed host-supported interfaces)
- dangling providers/components which aren't linked to anything
https://github.com/wasmCloud/wasmCloud/issues/2009
`next`
=> feat(wash-cli): add `wash app validate` subcommand

crates/wash-lib/src/build/component.rs, crates/wash-lib/src/build/provider.rs, crates/wash-lib/src/parser/mod.rs, crates/wash-lib/tests/parser/files/tinygo_component_module.toml, crates/wash-lib/tests/parser/main.rs
This PR adds support for `wash build` to compile and package a capability provider written in Go.
Since Go doesn't have a manifest file that easily lets us determine the binary name (please correct me if I'm wrong!) the `bin_name` is required metadata for the wasmcloud.toml. For example:
```toml
name = "KeyValue Go"
language = "go"
type = "provider"
version = "0.1.0"
[provider]
bin_name = "keyvalue-inmemory"
vendor = "wasmCloud"
```
Enables #2215 to work better!
next minor wash-lib
next minor wash-cli
Modified example toml to fit new support for overriding the go binary
Manually verified this working well with the above config and the example in the provider-sdk-go
=> feat(wash-lib)!: support building go providers

Cargo.lock, Cargo.toml, crates/wascap/Cargo.toml, crates/wascap/src/jwt.rs
Add a `Host` entity type to wascap. This allows us to generate JWTs for hosts that contains assertions about the metadata they were started with. For now this only includes host labels, but this could change in the future.
=> feat(wascap): add Host entity type

Cargo.lock, Cargo.toml, crates/wash-cli/src/common/registry_cmd.rs, crates/wash-lib/src/cli/registry.rs, crates/wash-lib/src/registry.rs
Based on feedback from users, we found out that the world isn't actually needed for pushing binary wit. This was updated in the oci-wasm library that was also updated in this PR. This removes the world flag as it is no longer needed
=> fix(wash)!: Removes need for world flag

crates/wash-cli/src/ctl/output.rs, washboard-ui/CONTRIBUTING.md, washboard-ui/packages/washboard-ui/src/app/components/components-table.tsx
To enhance the visibility of component concurrency settings by displaying the maximum instances count in both the washboard UI and the wash CLI's inventory output. This addition will help users understand the scale of their components more effectively.
resolves #2095 
Ran local development server for verifying frontend changes, along with deploying custom wadm manifests using `cargo run -- app deploy <name>` and verified wash-cli changes by `cargo run  -- get inventory` which worked as expected and showed max count as the `replicas: x` field from wadm manifests.
=> feat(wash+ui): Display max instances count in wash get inventory output and washboard output

crates/provider-blobstore-fs/src/lib.rs
This PR adjusts the ROOT path value matching behavior to convert all keys to uppercase. This makes the relevant value case-insensitive.
When configuring the value of ROOT for blobstore-fs, the only allowable spelling of the key to configure the value is "ROOT" — case sensitive.
=> fix(provider-blobstore-fs): make ROOT configuration case-insensitive

crates/wash-cli/src/up/config.rs
This PR bumps wasmCloud to v1.0.3 inside of wash in preparation for the 0.29 release. Draft while v1.0.3 is releasing.
wash 0.29.0
=> chore(wash-cli): bump wasmcloud v1.0.3

.github/workflows/examples-components.yml, crates/provider-sqldb-postgres/README.md, examples/rust/components/echo-messaging/wadm.yaml, examples/rust/components/http-blobstore/wadm.yaml, examples/rust/components/http-hello-world/wadm.yaml, examples/rust/components/http-jsonify/Cargo.toml, examples/rust/components/http-jsonify/README.md, examples/rust/components/http-jsonify/wadm.yaml, examples/rust/components/http-keyvalue-counter/wadm.yaml, examples/rust/components/sqldb-postgres-query/Cargo.toml, examples/rust/components/sqldb-postgres-query/README.md, examples/rust/components/sqldb-postgres-query/wadm.yaml, examples/rust/components/sqldb-postgres-query/wasmcloud.toml
This commit adds WADM manifests for examples that didn't have them, and also updates all manifests to have a line about how to use the local code versus the officially released components
This change *should* make it much easier to pull and run any WADM manifest in an example.
=> chore(examples): add missing manifests, use official images

.github/workflows/examples-components.yml
This commit changes the `examples-components` CI workflow to use a static (updated) version of `wash` to publish components, ahead of the release of wash 0.29.0.
=> chore(ci): use static version for publishing example components

Cargo.lock, Cargo.toml, crates/wash-cli/Cargo.toml, crates/wash-cli/src/app/mod.rs, crates/wash-cli/src/up/mod.rs, crates/wash-cli/tests/common/mod.rs, crates/wash-lib/Cargo.toml, crates/wash-lib/src/app.rs
- **feat(wash-lib)!: wrap new wadm-client**
- **feat(wash-cli)!: use new wadm-client**
This PR updates `wash-lib` and `wash-cli` to use the new wadm-client crate which provides better strongly typed methods for managing applications. It also gives us much nicer error formatting, so I was able to do a good bit of refactoring on the wash-cli side. I kept the wash-lib API as similar as possible to reduce breaking changes with dependents, but in general using the wadm-client crate directly is recommended.
While I was in there, I noticed something that has bugged me for a bit around our use of "app spec" and "model" when it could be a whole lot simpler to talk about. I updated the help text and some variable names to standardize on CRUDdy operations and the management of "applications" rather …
=> feat(wash) use wadm-client crate, update CLI

examples/rust/components/http-blobstore/Cargo.toml, examples/rust/components/http-blobstore/wadm.yaml, examples/rust/components/http-blobstore/wasmcloud.toml, examples/rust/components/http-blobstore/wit/deps.lock, examples/rust/components/http-blobstore/wit/deps.toml, examples/rust/components/http-blobstore/wit/deps/blobstore/types.wit, examples/rust/components/http-blobstore/wit/deps/blobstore/world.wit, examples/rust/components/http-blobstore/wit/world.wit
This commit updates the wadm manifest for http-blobstore, updating it to match the newer configuration values and layout of manifests.
Resolves #2256
=> fix(examples): fix wadm manifest for http-blobstore

crates/wash-cli/src/up/mod.rs
Sometimes, if a wadm process is leftover after a host exits, it can block the usage of wadm in future starts of an existing host. The symptom for this is wadm failing during wash startup with a "Couldn't download wadm: Text file busy" error.
The quickest fix for this issue is stopping the running wadm processes, but it's hard to *know* that might be the problem without intuiting what text file might be busy/what might be wrong.
This commit adds a message to the failure to download just in case this specific case occurs.
=> chore(wash-cli): Add an explicit note about leftover wadm processes

.github/workflows/dco-merge-group.yml
This PR adds a dummy check that only runs in the merge group that passes DCO. Our checks will always require DCO before a PR gets into the merge group itself, so this is simply an enabler for us to keep the check as required.
https://github.com/dcoapp/app/issues/199
=> ci(dco): pass dco in merge group

Cargo.lock, crates/core/Cargo.toml, crates/core/src/otel.rs
@brooksmtownsend pointed out that the change made in https://github.com/open-telemetry/opentelemetry-rust/pull/1706 that was brought in as part of #2197 changed the default endpoint behavior when you're passing in an explicit endpoint, which we are even if one wasn't provided.
We were relying on the prior behavior where the `/v1/<signal>` path component would be concatenated to the endpoint if it didn't already have one, but that behavior has since been changed to default to `/` instead, which does not work when you're attempting to use the OpenTelemetry collector configured at the default endpoints (which are `/v1/<signal>`).
Fixes https://github.com/wasmCloud/wasmCloud/issues/2265
=> fix: Add signal-specific path components to OtelConfig's default endpoints

Cargo.lock, crates/provider-http-client/Cargo.toml, src/bin/http-client-provider/wasmcloud.toml
This PR bumps http-client to release with the protocol fix since the provider is failing to instantiate on v1.0.2.
http-client v0.10.1
=> chore(http-client): bump to v0.10.1

crates/provider-messaging-nats/src/connection.rs, crates/provider-messaging-nats/src/lib.rs
This PR fixes some incorrect logic for propagating traces through the NATS provider by attaching trace headers to the wRPC client rather than the NATS message itself, which is effectively discarded after receipt. I also propagated the trace given the wRPC context. 
As a followup to #2278 
`next` NATS messaging provider
=> fix(messaging-nats): fix trace propagation

crates/host/src/wasmbus/handler.rs, crates/host/src/wasmbus/mod.rs, crates/provider-http-client/src/lib.rs, crates/provider-http-server/src/lib.rs, crates/provider-messaging-nats/src/connection.rs, crates/provider-messaging-nats/src/lib.rs, crates/runtime/src/actor/component/http.rs, crates/runtime/src/actor/component/mod.rs, examples/rust/components/dog-fetcher/wadm.yaml
This PR adds a `trace_ctx` parameter to a component's `Handler` which is set as invocations are received and used as invocations are sent in order to propagate the current trace context throughout a component's lifecycle.
Fixes #2263 
Traces reconnected (on trace logging so _VERY_ verbose) but not quite at the right level. Fine tuning instrumentation...
Traces reconnected at the debug level:
=> fix(host): propagate traces through components

crates/tracing/src/traces.rs
This PR fixes a small issue where an import was only used behind the `otel` feature flag, so it failed to release.
I did verify this passes a publish dry run, the provider-sdk and wash-cli both pass all lints so shouldn't be an issue on the release retry
=> chore(tracing): gate import behind feature

Cargo.lock, crates/provider-blobstore-azure/Cargo.toml, crates/provider-blobstore-fs/Cargo.toml, crates/provider-blobstore-s3/Cargo.toml, crates/provider-http-client/Cargo.toml, crates/provider-http-server/Cargo.toml, crates/provider-keyvalue-redis/Cargo.toml, crates/provider-keyvalue-vault/Cargo.toml, crates/provider-messaging-kafka/Cargo.toml, crates/provider-messaging-nats/Cargo.toml, crates/provider-sqldb-postgres/Cargo.toml, src/bin/blobstore-azure-provider/wasmcloud.toml, src/bin/blobstore-fs-provider/wasmcloud.toml, src/bin/blobstore-s3-provider/wasmcloud.toml, src/bin/http-client-provider/wasmcloud.toml, src/bin/http-server-provider/wasmcloud.toml, src/bin/keyvalue-redis-provider/wasmcloud.toml, src/bin/keyvalue-vault-provider/wasmcloud.toml, src/bin/messaging-kafka-provider/wasmcloud.toml, src/bin/messaging-nats-provider/wasmcloud.toml, src/bin/sqldb-postgres-provider/wasmcloud.toml
This PR updates each capability provider a minor version bump to bring in the latest changes in the provider-sdk for link directionality, the core crate for fixing OTEL trace exporter URLs, and trace propagation fixes in http/messaging providers.
`next` minor release of each provider
=> chore(provider-*): bump minor version for otel release

Cargo.lock, crates/wash-lib/Cargo.toml, crates/wash-lib/src/app.rs
This Pr serializes wadm manifest when putting it instead of passing a string, which is interpreted as a filepath and attempted to load as a file.
Fixes #2312 
wash-lib v0.22.1
=> fix(wash-lib): serialize manifest to deploy

.github/workflows/wasmcloud.yml
This PR enables Rust cache for Windows CI when merging into main. This should help speed up the windows builds
=> ci(wasmcloud): enable rust cache for windows

Cargo.lock, Cargo.toml, crates/provider-archive/Cargo.toml, crates/wash-cli/Cargo.toml
- **chore(provider-archive): bump to v0.11.0 for release**
- **chore(wash-cli): bump to v0.29.1 for release**
This pr bumps wash-cli to 0.29.1 for release. It also bumps provider-archive to v0.11.0 to bring in the newest nkeys library and fix the issue where wash couldn't be published to crates.io
=> chore/wash cli v0.29.1

.github/workflows/wasmcloud.yml
I noticed when releasing providers that the azure provider didn't have a pipeline associated with it. This adds a release action for blobstore-azure
=> ci(wasmcloud): add azure blobstore to release pipeline

crates/wash-cli/src/up/config.rs
This PR bumps wasmCloud to v1.0.4 inside of wash to bring in the OTEL fixes in v1.0.4.
=> chore(wash-cli): bump wasmcloud to v1.0.4

crates/wash-cli/Cargo.toml, crates/wash-cli/src/up/mod.rs
Wash up should be idempotent https://github.com/wasmCloud/wasmCloud/issues/846
Follow up to https://github.com/wasmCloud/wasmCloud/pull/1674
None
None
This will change how users start multiple wasmCloud hosts on the same machine
No integration tests changed
Unit test added for PID lookup.
None
```
❯ target/debug/wash up
🛁 wash up completed successfully, already running
🕸  NATS is running in the background at http://127.0.0.1:4222/
📜 Logs for the host are being written to /Users/colmurph/.wash/downloads/wasmcloud.log
⬇️   To stop wasmCloud, run "wash down"
❯ target/debug/wash up -d
🛁 wash up completed successfully, already running
🕸  NATS is running in the background at http://127.0.0.1:4222/
📜 Logs for the host are being written to /Users/colmurph/.wash/downloads/wasmcloud.log
⬇️   To …
```
=> Wash up should inform user that wasmcloud is already running rather than bailing

washboard-ui/packages/washboard-ui/src/app/components/lattice-settings.tsx
For events dispatched by an HTMLInputElement, regardless of the type "number" attribute used, the target.value type is string. The html5 input element though will only ever send strings that are trivially parsable as Number(event.target.value). This uses a zod coercion to preprocess the data by passing it through a Number constructor and filling the form field data on change properly.
closes [BUG] Washboard UI retryCount cannot be changed  #2354
ran the washboard ui locally and was able to update the retryCount and have form success before drawer close
=> fix(wash-ui): type mismatch number input and schema

examples/golang/providers/custom-template/main.go
This PR is a temporary workaround for a segfault that occurs when accessing the `provider` struct during the handler initialization functions.
#2374
=> fix(custom-template-go): print instead of log

crates/wash-cli/src/app/mod.rs, crates/wash-cli/src/up/mod.rs
This commit removes the cleanup that happens after `wash up --wadm-manifest`, because in the single-host situation by the time ctrl-c is received by `wash` it is *also* receieved by the child process host. When this happens, most of the time the host is *already gone* so all you get is "no responders" when trying to issue an undeploy.
There are a few ways around this but they all will likely require modifying the host/other pieces so first we should probably remove the application cleanup code and update the documentation to note that the manifest can be undeployed/deleted manually before shutting down.
=> fix(wash-cli): remove wash up with manifest cleanup

crates/provider-blobstore-s3/README.md, crates/provider-blobstore-s3/src/lib.rs
This commit adds some documentation and makes specific how we support non-AWS S3-compliant AWS object stores.
For non-AWS providers, link configuration (which is the recommended way to use this provider) should be used.
Resolves https://github.com/wasmCloud/wasmCloud/issues/2287
=> chore(providers): clarify non AWS S3 provider usage

washboard-ui/package.json, washboard-ui/turbo.json, washboard-ui/yarn.lock
Unfortunately the migration script to turbo 2.x fails, so we have to manually create it.
This PR supposed to update the washboard-ui turborepo to major version 2. [Announcement + benefits here](https://turbo.build/blog/turbo-2-0)
closes https://github.com/wasmCloud/wasmCloud/issues/2283
No customer impact as far as I know.
Since this is a build tool you should be able to successfully execute the yarn/turbo workspace scripts.
Went through the scripts:
yarn run commands, but e2e fails. 🤔, but there should be no changes around that.
=> chore(washboard-ui): bump turbo to version to and migrate the turbo.json

crates/wash-cli/src/up/mod.rs, crates/wash-lib/src/start/wadm.rs
Using regexp to detect wadm version instead of constant prefix. Also added some messages to the user, so he will know wadm version and download URL for wadm if download occurs.
Resolves #2308 
next
I think all users are affected by the bug. So please include the fix to the next release.
run `wash up` and check messages on console.
nope
run `cargo run -- up` in the folder `wasmCloud/crates/wash-cli`
=> fix(wash-lib,wash-cli): do not dowmload wadm on every invocation of wasm up

.github/workflows/wash.yml, .github/workflows/washboard.yml
This commit uses the last 3 versions of wash for washboard e2e tests, picking the latest versions available for minor versions 27, 28 and 29.
Resolves #2392
=> chore(ci): use last 3 versions of wash for washboard e2e tests

crates/provider-keyvalue-redis/src/lib.rs, crates/provider-sdk/src/lib.rs
This PR:
- Adds `Context::link_name()` utility method to easily retrieve link names
- Uses the new method from the KV redis provider
Resolves #2371
=> feat(*): add utility method for accessing link name

examples/golang/components/http-client-tinygo/wadm.yaml, examples/golang/components/http-echo-tinygo/wadm.yaml, examples/golang/components/http-hello-world/wadm.yaml, examples/golang/providers/custom-template/wadm.yaml, examples/python/components/http-hello-world/wadm.yaml, examples/rust/components/blobby/wadm.yaml, examples/rust/components/dog-fetcher/wadm.yaml, examples/rust/components/echo-messaging/wadm.yaml, examples/rust/components/http-hello-world/wadm.yaml, examples/rust/components/http-jsonify/wadm.yaml, examples/rust/components/http-keyvalue-counter/wadm.yaml, examples/rust/components/sqldb-postgres-query/wadm.yaml, examples/typescript/components/http-hello-world/wadm.yaml
Annotations in OAM must be strings, and as we had them they weren't, this commit changes all the wasmcloud.dev/categories annotations to be strings.
=> fix(examples): make annotation links comma delimited strings

.github/workflows/comment-cc.yml, .github/workflows/lint-cc.yml
This commit refactors the conventional commit lint to create comments from another secondary action, `comment-conventional-commits`.
Since `comment-conventional-commits` is triggered by a `workflow_run` (which refers to `lint-conventional-commits`), it is safe from the permission issues that forks run into.
What's better is that we don't have to rely on the forks at all to provide PR details (and thus avoid a security worry).
The approach is laid out by Github's research team here:
https://securitylab.github.com/research/github-actions-preventing-pwn-requests
=> refactor(ci): create lint comment from secondary action

crates/wash-cli/README.md, crates/wash-cli/src/bin/wash.rs, crates/wash-cli/src/common/registry_cmd.rs
#2404 
next
Just changed help output text
no changes
run `wash help` and see no info about `reg` command is present.
=> fix(wash-cli): remove help about deprecated wash reg #2404

crates/wash-cli/src/up/mod.rs, crates/wash-lib/src/start/nats.rs
Resolves #1405 
Next
ran `cargo run -- up --nats-config-file ~/Desktop/Wasm/special.conf --nats-host="127.0.0.1" --nats-port=4959` which executed as expected and also exited normally by `cargo run -- down -- all` stopping all components successfully
verified all possible failure cases , such as 
1) Providing directory path instead of file : resulted in `The provided NATS config File ["/home/aditya/Desktop/Wasm/"] is not a valid File`
2) Ommiting `--nats-host` and `--nats-port` : resulted in `the following required arguments were not provided:
--nats-host <NATS_HOST>`
=> Feat(wash): Adds flag to [wash up] to allow reading custom nats config

.github/workflows/wash.yml, crates/wash-lib/src/start/github.rs
This commit disables windows wash CLI tests due to stack overflowing, even on the windows-latest-8-cores machines.
=> chore(tests): temporarily disable windows wash CLI tests

.devcontainer/devcontainer.json, .devcontainer/setup.sh, .dockerignore
The devontainer command/tool failed due to unmaintained nix packages and some other configurations.
#2070 
```bash
devcontainer up --workspace-folder .
```
I changed the watch in the `.envrc` since it gave me errors/warnings. And little do I know about linkers so if someone has better options for the linker (not gcc) please help.
devcontainer -> `0.65.0`
docker -> `Docker version 26.1.3, build b72abbb`
docker compose -> `Docker Compose version v2.27.3`
=> fix(devcontainer): update devcontainer path and replace unmaintained lsp with maintained one

.github/workflows/wash.yml, crates/wash-cli/build.rs
`clap` has a few bugs that cause stacks to overflow on windows when doing commands like walking the full arg tree (i.e. `--help`).
Adopting a fix from one of the
issues (https://github.com/clap-rs/clap/issues/5134), we increase the size of stack during build.
=> fix(tests): increase windows stack size

.envrc
- Update vendored `nix-direnv` to a newer version
- Replace deprecated `nix_direnv_watch_file` by `watch_file`
- Also, reorder as per documentation
Thanks @markkovari for pointing this out in https://github.com/wasmCloud/wasmCloud/pull/2419#discussion_r1662571247!
https://github.com/wasmCloud/wasmCloud/pull/2419#discussion_r1662571247
=> build(nix): update `nix-direnv`

.github/workflows/provider.yml, .github/workflows/secrets-nats-kv.yml, .github/workflows/wash.yml, Cargo.toml, crates/wash-cli/tests/wash_call.rs
The "nextest" branch of taiki-e/install-action does nothing but add "nextest" to the default list of tools (see:
https://github.com/taiki-e/install-action/commit/cdf91dadbfbcd09d5ec3fe131167d4c7eb6e350b).
Rather than maintain a completely different pinned hash, we should just install nextest normally like any other tool.
=> fix(ci): install nextest via normal means

.github/workflows/comment-cc.yml, .github/workflows/lint-cc.yml, .github/workflows/provider.yml, .github/workflows/wasmcloud-chart.yml, .github/workflows/wasmcloud.yml
This PR fixes an issue where even if you specify top-level permissions for a workflow, you must specify all appropriate permissions for a workflow where you add a `permissions` block. It doesn't seem to make sense that it works this way, but the wasmCloud workflow was not running when only `packages: write` was specified.
=> ci: add explicit content read allowance

Cargo.lock, Cargo.toml, crates/provider-messaging-kafka/Cargo.toml, crates/provider-messaging-kafka/README.md, crates/provider-messaging-kafka/messaging-kafka-demo.wadm.yaml, crates/provider-messaging-kafka/src/client.rs, crates/provider-messaging-kafka/src/lib.rs, crates/provider-sdk/src/provider.rs
This commit enables consumer groups via link time configuration in the kafka provider.
The native Rust ecosystem for Kafka is somewhat immature, so to do this we must switch to a different crate
`kafka-rs` (https://crates.io/crates/kafka), which implements consumer groups but is otherwise missing some features.
With this branch, one can specify CONSUMER_GROUP in link configuration to control the consumer group that is used for Kafka consumers (whose incoming messages will trigger downstream components).
Resolves #1442
=> refactor(providers): enable consumer groups with kafka provider

.github/workflows/washboard.yml
The [previous release](https://github.com/wasmCloud/wasmCloud/actions/runs/9977762485) failed because the wash version was tacked onto the artifact name which is actually always just `washboard`. This corrects that.
=> ci(washboard): remove matrix version from release artifact

Cargo.lock, Cargo.toml, crates/core/Cargo.toml, crates/core/src/otel.rs, crates/core/src/tls.rs, crates/host/src/lib.rs, crates/host/src/oci.rs, crates/host/src/registry.rs, crates/host/src/wasmbus/mod.rs, crates/tracing/Cargo.toml, crates/tracing/src/lib.rs, crates/tracing/src/metrics.rs, crates/tracing/src/traces.rs, src/main.rs
This adds the support for providing additional CA certificates to be loaded at host initialization time, which are then configured in the OCI and OpenTelemetry clients.
It's intended for use inside of environments where there may be non-WebPKI certificates in use, such as an in-house CA.
Fixes #2460
=> feat: Add support for supplying additional CA certificates to OCI and OpenTelemetry clients

crates/core/src/host.rs, crates/core/src/logging.rs, crates/core/src/otel.rs, crates/host/src/wasmbus/mod.rs, crates/provider-sdk/src/otel.rs, crates/tracing/src/lib.rs, crates/tracing/src/traces.rs, src/main.rs
- **feat(core)!: add trace_level option**
- **feat(tracing)!: add trace_level option**
- **feat(provider-sdk)!: configure observability with trace_level option**
- **feat(host)!: configure observability with trace_level option**
- **feat(wasmcloud)!: add --trace-level option**
This PR adds a `--trace-level` option to wasmCloud which allows configuring traces and logging separately, defaulting trace level to INFO and log level to INFO. This should resolve an issue where you needed to set the log level to a fairly verbose level of debug in order to see many valuable traces.
Fixes #1932
next minor tracing
next minor provider-sdk
next minor core
wasmcloud 1.1
This is a backwards compatible breaking change, and operators of wasmCloud should be aware that as of 1.1 the default trace verbosity …
=> [FEAT] Add trace_level option to configure trace level separate from logs

Cargo.lock, crates/secrets-client/Cargo.toml, crates/secrets-client/src/lib.rs
This commit introduces `thiserror` for the errors in the `secrets-client` crate.
=> refactor(secrets-client): add usage of thiserror

.github/workflows/wasmcloud.yml
This PR ensures providers are built and published only when a tag is pushed that intentionally releases a given provider.
We should still catch breakage of provider crates during normal build, but now we can avoid building them and trying to publish them (or not) on every CI run.
This should prevent some spurrious failures we see on CI on `main` and in dependabot PRs (`download-artifact` is surprisingly unreliable)
=> refactor(ci): only run provider builds on tags

Cargo.lock, crates/host/src/wasmbus/host_config.rs, crates/host/src/wasmbus/mod.rs, crates/wash-cli/Cargo.toml, crates/wash-cli/src/up/config.rs, crates/wash-cli/src/up/mod.rs, src/main.rs
Adds a `--max-execution-time` flag to `wash up` for configuring the host's max execution time implemented in #2002 and #2015 
(1/2) of  #2016 
next
Ran `cargo run -- up --max-execution-time <humantime>` to which `wash -up` ran as usual, value propagation and time duration formatting works.
=> feat(host,cli): max_execution_time config flag support for host runtime

crates/wash-cli/tests/common/mod.rs, crates/wash-cli/tests/wash_build.rs, crates/wash-lib/src/build/provider.rs, crates/wash-lib/src/cli/claims.rs, crates/wash-lib/src/parser/mod.rs, crates/wash-lib/tests/parser/main.rs
**Support for debug build for rust providers**
This changes aims to enable building a rust provider in debug mode by enabling debug mode in the wasmcloud.toml
file like this.
```
[rust]
target_dir = "../../"
debug = true
```
=> Add support for debug build for rust providers #2298

Cargo.lock, crates/secrets-types/src/lib.rs, crates/wash-cli/Cargo.toml, crates/wash-cli/src/bin/wash.rs, crates/wash-cli/src/config.rs, crates/wash-cli/src/lib.rs, crates/wash-cli/src/secrets.rs, crates/wash-cli/tests/wash_config.rs, crates/wash-cli/tests/wash_secrets.rs
This adds a set of commands for manually managing secrets references in a wasmCloud deployment. It is effectively a wrapper around configuration that properly formats and writes the data type to the config bucket.
It also attempts to prevent you from interacting with secrets with the config subcommands by checking the name of the configuration key and redirecting you to the correct subcommand.
Closes #2494.
next
Tested locally with a wash build
=> feat(wash-cli): add secrets subcommand for managing secrets references

.github/workflows/examples-components.yml, examples/rust/components/keyvalue-messaging/wadm.yaml
The `keyvalue-messaging` example, which is accompanying the `nats-keyvalue-provider` is missing from the `examples-components.yml` workflow; this PR will remediate the omission.
The PR also updates the Wadm manifest of the example to use the published (or to be published) images of the provider and the example.
#2559 
This should improve the user experience.
=> feat: Add keyvalue-messaging example to the example components workflow

Cargo.lock, crates/host/src/secrets.rs, crates/secrets-nats-kv/tests/api.rs, crates/secrets-types/Cargo.toml, crates/secrets-types/src/lib.rs, crates/test-util/src/lattice/config.rs
Update the secrets integration in a wasmCloud host to include information about the policy that determines which backend to communicate with. This is a change that comes in from wadm where the policy block now contains the information about which backend to use.
This also passes any propertes defined on the policy to the correct backend, which are stored as a versioned string-encoded JSON object.
next
=> chore: update secrets integration to use the updated config structure

examples/README.md
These links to Rust examples were pointing to the Go or 404.
=> fix(docs): fix incorrect links to rust examples

crates/secrets-types/src/errors.rs
I'd like to have an error variant that represents an error with processing the policy that was provided in a given `SecretRequest`.
While this is not applicable to all backends, other backends that are dependent on specific configuration being present in the policy properties should have a way to communicate about that being the specific issue.
=> chore(secrets-types): Add variant to represent error processing policy

Cargo.lock, crates/provider-http-server/Cargo.toml, crates/provider-http-server/src/lib.rs, src/bin/http-server-provider/wasmcloud.toml
After digging around in the `wasmtime serve` code, I found this neat little trick around reuseaddr which works on any linux or unix-like system (sorry Windows!). In my testing, this increased HTTP throughput by 10-15%
=> fix(http-server): Improve reuse of underlying TCP socket

crates/wash-cli/src/call.rs
Noticed these were transposed when the output of the `No component responded to your request...` error
message claimed the lattice was the component and the component was the lattice.
https://github.com/wasmCloud/wasmCloud/blob/27a5005460269436d91c3e889873a93fddef704c/crates/wash-cli/src/call.rs#L175-L181 puts component_id before lattice, but lattice comes first in https://github.com/wasmCloud/wasmCloud/blob/27a5005460269436d91c3e889873a93fddef704c/crates/wash-cli/src/call.rs#L448-L454
N/A
`next`
Fortunately, this only seems to affect the contents of human readable error messages in that function.
I ran `cargo test` (oof those initial rust builds take a long time on my laptop!).
Most tests passed, including `test call::test::test_rpc_comprehensive ... ok` which I'm guessing is the main …
=> fix(wash-cli): transposed args in call.rs

.github/workflows/wasmcloud.yml
This PR fixes an issue where downloading artifacts would fail because of the docker build output. I'm not entirely sure why this was happening, but I theorize it's related to https://github.com/actions/download-artifact/issues/339 and the commenter that mentioned that invalid zips/repeated filenames cause issues.
I validated this was the issue with releasing our latest providers / 1.1.0-beta.1 because I deleted the artifact and re-ran the failed workflow and it worked.
=> ci(wasmcloud): disable docker output artifact

Cargo.lock, Cargo.toml, crates/host/src/secrets.rs, crates/secrets-client/Cargo.toml, crates/secrets-client/src/lib.rs, crates/secrets-nats-kv/src/api.rs, crates/secrets-nats-kv/src/client.rs, crates/secrets-nats-kv/src/main.rs, crates/secrets-nats-kv/src/types.rs, crates/secrets-nats-kv/tests/api.rs, crates/secrets-types/Cargo.toml, crates/secrets-types/src/lib.rs, crates/test-util/src/lattice/config.rs, crates/wash-cli/src/secrets.rs, crates/wash-cli/tests/wash_secrets.rs, tests/common/secrets.rs, tests/config.rs
This PR adds the `field` parameter to the `SecretRequest` and `SecretConfig` types, allowing secrets backends that support indexed secrets inside of an individual key to only return the desired field.
An example of this is vault, where secrets are addressable by a path (which we use the `key` parameter) and then contained in that path are multiple key=value pairs.
This PR also removes the unneeded `name` field from the Secret, since the backend doesn't actually need this value and returning the key/field arbitrarily would just increase bytes sent/encrypted.
Upcoming wadm issue to support this.
1.1.0-beta.2
=> feat: add field to secrets

crates/tracing/Cargo.toml, crates/tracing/src/lib.rs, crates/tracing/src/traces.rs
This PR fixes an issue where the wasmcloud-tracing crate didn't properly gate otel functions + enable otel features in the wasmcloud-core crate
=> fix(tracing): enable core otel features

Cargo.lock, Cargo.toml, crates/component/Cargo.toml, crates/component/README.md, crates/host/Cargo.toml, crates/host/README.md, crates/runtime/Cargo.toml, crates/runtime/README.md
This PR prepares the wasmcloud-component, wasmcloud-runtime, and wasmcloud-host crates for an eventual release. **I don't plan on releasing them quite yet**, and the top-level binary of `wasmcloud` still includes many dependencies on the provider libraries (but we should turn those off?) but this puts us in the right direction for releasing some of these crates that are listed as deprecated on crates.io.
I thought I had an issue for this but I can't find it /shrug
wasmcloud-component 0.1.0
wasmcloud-runtime 0.1.0
wasmcloud-host 0.20.0
=> chore: update component/runtime/host crate READMEs

examples/golang/providers/custom-template/main.go
```
❯ ./run.sh
./main.go:112:2: undefined: handler
```
=> Adding missing 'handler' to go provider template

crates/wash-cli/src/dev.rs, crates/wash-cli/src/down/mod.rs, crates/wash-cli/src/up/mod.rs, crates/wash-cli/tests/common/mod.rs, crates/wash-lib/src/cli/stop.rs, crates/wash-lib/src/config.rs
This addresses the root cause for https://github.com/wasmCloud/wadm/actions/runs/10208903476/job/28246069141?pr=367#step:8:159 when the host is told to stop, but it's not running on the same machine as `wash` (in the Actions example above, it's running inside of a Docker Container).
=> fix: Ensure file exists before attempting to remove

crates/host/src/wasmbus/event.rs, crates/host/src/wasmbus/mod.rs
I noticed that if a component fails to scale because of an issue with OCI downloads, claims extraction, or policy server denial, we don't publish the `component_scale_failed` event. This PR ensures:
1. Any error during component scaling is reflected as an event
1. Any scale operation, even if a no-op (e.g. requested scale that's already running) publishes an event to ensure the idempotency of the command. This helps consumers like wash always know their request completed successfully.
=> fix(host): always publish component_scale event

Cargo.lock, Cargo.toml
Bumping to 1.1.1 since I want to release https://github.com/wasmCloud/wasmCloud/pull/2674
https://github.com/wasmCloud/wasmCloud/pull/2674
wasmcloud 1.1.1
=> chore(wasmcloud): bump to 1.1.1

crates/host/src/wasmbus/host_config.rs, crates/host/src/wasmbus/mod.rs, src/main.rs
For integration testing, it would be nice to make the host heartbeat interval configurable so that it can be shortened in an integration testing that uses the heartbeats.
In the future being able to adjust the host heartbeat frequency would also open up the possibility of reducing the amount of heartbeat traffic in a large deployment, though this likely necessitates changes in other components of the system as well (i.e. adjusting the wadm side of things appropriately as well).
=> chore(host): Make wasmcloud host heartbeat interval configurable

examples/rust/components/http-blobstore/wadm.yaml
wadm manifest is incorrect
wasmcloud.dev/categories expects a string
=> Fix wadm manifest.

Cargo.lock, crates/host/src/wasmbus/host_config.rs, crates/host/src/wasmbus/mod.rs, crates/runtime/src/runtime.rs, src/main.rs
This PR surfaces additional tuning parameters that can be used to control limits on components in the wasmtime runtime, including the max number of component instances, the max size of a component instance, and the maximum amount of memory a component instance could allocate.
Could argue for a v1.1.2
=> feat(host)!: allow tuning runtime parameters

crates/core/src/rpc.rs, crates/host/src/wasmbus/config.rs, crates/host/src/wasmbus/mod.rs, crates/provider-sdk/src/lib.rs, crates/provider-sdk/src/provider.rs, src/bin/keyvalue-redis-provider/wasmcloud.toml
This PR introduces a scheme for supporting provider config updates by using the `CONFIGDATA_<lattice>` KV bucket. 
- When a provider makes a config bundle, it picks an ID (UUID v7, could add host ID)
- When the config bundle the host is maintaining updates, we push the value to the key in the KV bucket
- The host passes the key relevant to the config bundle to the provider at startup
- When the provider starts, `provider-sdk` listens independently on NATS for updates to the relevant key, and observes config updates that match it's bundle.
- The provider can implement `on_config_update()` to respond to config updates.
Resolves https://github.com/wasmCloud/wasmCloud/issues/1648
=> feat(host,provider-sdk): support provider config updates

Cargo.lock, Cargo.toml, crates/wash-cli/Cargo.toml, crates/wash-cli/src/app/output.rs, crates/wash-cli/src/ctl/output.rs, crates/wash-cli/src/util.rs
This PR introduces the `termwidth` dependency and ensures that our terminal commands don't overflow the width.
Some examples of the before and after terminal displays:
`wash app list`
`wash plugin list`
`wash get hosts`
Fixes #2660 
wash-cli 0.31.0
=> feat(wash-cli): limit terminal to width

.github/workflows/examples-components.yml, examples/golang/components/http-client-tinygo/local.wadm.yaml, examples/rust/components/dog-fetcher/local.wadm.yaml, examples/rust/components/echo-messaging/local.wadm.yaml, examples/rust/components/ferris-says/local.wadm.yaml, examples/rust/components/http-blobstore/local.wadm.yaml, examples/rust/components/http-hello-world/local.wadm.yaml, examples/rust/components/http-jsonify/local.wadm.yaml, examples/rust/components/http-keyvalue-counter/local.wadm.yaml, examples/rust/components/keyvalue-messaging/local.wadm.yaml
This commit adds a small bash script that loads an example component(s) and attempts to run it with `wash` & `wadm`, and waits until at least one component is running then exits.
=> feat(examples): add load testing for example components

crates/host/src/wasmbus/event.rs, crates/host/src/wasmbus/mod.rs
This PR introduces an event to the host `linkdef_set_failed` which can be used to let subscribers on the event bus know that a linkdef failed to be deleted. Since link creation is a synchronous command the sender of the command should be able to know that the event failed, but this will ensure that if you were subscribing to the command and event topics that you'd understand what happened.
I plan to use this in https://github.com/wasmCloud/wadm/pull/379 to make link scalers backoff & report failures to create links in their status.
next wasmCloud
=> feat(host)!: introduce linkdef_set_failed event

Cargo.lock, crates/provider-blobstore-azure/Cargo.toml, crates/provider-blobstore-azure/src/lib.rs, crates/provider-blobstore-fs/Cargo.toml, crates/provider-blobstore-fs/src/lib.rs, crates/provider-blobstore-s3/Cargo.toml, crates/provider-blobstore-s3/src/lib.rs, crates/provider-http-server/Cargo.toml, crates/provider-http-server/src/lib.rs, crates/provider-keyvalue-nats/Cargo.toml, crates/provider-keyvalue-nats/src/lib.rs, crates/provider-keyvalue-redis/Cargo.toml, crates/provider-keyvalue-redis/src/lib.rs, crates/provider-keyvalue-vault/Cargo.toml, crates/provider-keyvalue-vault/src/lib.rs, crates/provider-messaging-kafka/Cargo.toml, crates/provider-messaging-kafka/src/lib.rs, crates/provider-messaging-nats/Cargo.toml, crates/provider-messaging-nats/src/lib.rs, crates/provider-sdk/src/lib.rs, crates/provider-sdk/src/provider.rs, crates/provider-sqldb-postgres/Cargo.toml, crates/provider-sqldb-postgres/src/lib.rs, examples/rust/providers/messaging-nats/src/nats.rs
This commit introduces new methods to the `Provider` trait for deleting links -- `delete_configured_link_as_source()` and `delete_configured_link_as_target()`.
Thse new methods are meant to address an issue with deleting links in that the name of the link was unavailable -- only the source of the link was provided.
In order to phase out old uses as fast as possible, along with these new methods, the following methods are deprecated:
- delete_link()
- delete_link_as_target()
- delete_link_as_source()
=> fix(provider-sdk)!: change inputs to Provider::delete_link_*()

.github/workflows/examples-components.yml, examples/golang/components/http-echo-tinygo/wasmcloud.toml
Add two golang examples to the list of examples to push to OCI. Golang will be one of the first examples used in a new Ingress example for routing between Rust and Go.
=> ci(examples): push golang oci examples

crates/provider-blobstore-fs/README.md, crates/provider-blobstore-fs/src/lib.rs, src/bin/blobstore-fs-provider/wasmcloud.toml
We we refactored the provider last, we left some code that created the proper subdirectory, but then didn't do anything with that directory.
This gives things a reasonable default. If a `ROOT` is specified, then we use that without creating a subpath. If we are defaulting, we create a subdir with the component ID to avoid collision
=> fix(blobstore-fs): Creates a subdirectory when no root is specified

crates/wash-cli/src/drain.rs, crates/wash-lib/src/config.rs
Aborts `drain all` and `drain downloads` if wasmcloud host is active
#2788 
I started a wasmcloud instance via `cargo run -- up -d` then tried to run `cargo run -- drain all` which resulted in an error
then ran `down --all` and `drain all` which ran as expected
=> feat(wash-cli): Modify wash drain to avoid clearing downloads cache when host is running

crates/wash-cli/src/up/config.rs, crates/wash-cli/src/up/mod.rs
This PR adds `secrets-topic` and `policy-topic` flags to wash up
facilitating the wasmcloud binary in connecting the pipeline
#2631 
next
Value propogates to wasmcloud host binary, `wash up` run's as expected.
=> feat(wash-cli): Add secrets-topic and policy-topic flags to wash up

Cargo.toml, examples/rust/components/blobby/Cargo.toml, examples/rust/components/blobby/wit/deps.lock, examples/rust/components/blobby/wit/deps.toml, examples/rust/components/dog-fetcher/Cargo.toml, examples/rust/components/http-blobstore/wit/deps.lock, examples/rust/components/http-blobstore/wit/deps.toml, examples/rust/components/http-blobstore/wit/deps/blobstore/types.wit
With this I am able to serve https://github.com/wasmCloud/wasmCloud/releases/download/wash-cli-v0.30.0/wash-aarch64-apple-darwin (34.2 MB) just fine. I verified the checksum of this file streamed from FS provider.
The `=` in `wasi` crate dep specification is the fix - it is important that components use WASI 0.2.0.
`wasi` crate version `0.13.2` depends on `wasi 0.2.1`, which causes a deadlock in the component when, e.g. a function from `wasi:http/types` is called
Closes https://github.com/wasmCloud/wasmCloud/pull/2709
=> fix: blobstore examples

crates/component/src/wrappers/io.rs
I was doing some experimentation with sending off multiple HTTP requests, and I created this little helper that polls a set of pollables to completion. Is there an appetite to including this in our component library?
I'm fine with closing this, refactoring, etc, but it does seem useful for creating polling multiple futures to completion.
=> feat(component): add join helper

crates/wash-cli/src/up/config.rs
This PR updates the version of NATS to download in wash to 2.10.18. With testing with the new blobstore streaming fixes, I would get slow consumer issues when running with 2.10.7.
=> chore(wash-cli): update NATS to 2.10.18

crates/wash-cli/Cargo.toml, crates/wash-cli/src/bin/wash.rs, crates/wash-cli/src/up/config.rs
This PR updates the wadm and wasmCloud version in wash for testing in preparation for a release.
While I was here, I also added a custom version implementation.
Fixes #2642
Consumers of the starship plugin for `wash` (poke @jordan-rash ) should update their starship config to something like the following:
```toml
[custom.wash_ver]
symbol = "🛁"
when = "true"
command = "wash -V | grep wash | awk '{print $1, $2}'"
format = "[$symbol $output]($style) "
style = "bold fg:#00C389"
```
The new `-V` or `--version` looks like this:
```
cargo run -- --version
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.62s
Running `/Users/brooks/github.com/wasmcloud/wasmcloud/target/debug/wash --version`
wash          v0.30.0
├ nats-server v2.10.18
├ wadm        v0.14.0
└ wasmcloud   v1.2.0-rc.1 …
```
=> wadm 0.14.0, wasmcloud v1.2.0-rc.1, long version

Cargo.lock, Cargo.toml, crates/wash-cli/Cargo.toml, crates/wash-cli/src/app/mod.rs, crates/wash-cli/src/app/output.rs
This flag perpetually displays changes to application status until Ctrl+c is invoked
#2512
=> feat(wash-cli): Add --watch flag to wash app list for displaying live info

Cargo.lock, crates/provider-sqldb-postgres/Cargo.toml, crates/provider-sqldb-postgres/src/bindings.rs, crates/provider-sqldb-postgres/src/lib.rs, crates/provider-sqldb-postgres/wit/deps.lock, crates/provider-sqldb-postgres/wit/deps.toml, crates/provider-sqldb-postgres/wit/deps/postgres/query.wit, crates/provider-sqldb-postgres/wit/deps/postgres/types.wit, crates/provider-sqldb-postgres/wit/provider.wit, wit/postgres/wit/types.wit
This commit implements wasmcloud:postgres@0.1.1-draft for as-yet-unreleased the upcoming version of the wasmcloud postgres provider
=> feat(providers): implement wasmcloud:postgres@0.1.1-draft

crates/runtime/Cargo.toml
This PR enables the `gc` feature in our runtime crate which, as per documentation:
```
gc - Enabled by default, this enables support for a number of WebAssembly proposals such as reference-types, function-references, and gc. Note that the implementation of the gc proposal itself is not yet complete at this time.
```
Building a component with `cargo +nightly build --target wasm32-wasip2` requires the reference-types proposal, so enabling this lets us run components that were built directly to the wasm32-wasip2 target.
~As far as I can tell this is the only way to enable this functionality.~
Once we update to wasmtime 25, we can disable this feature again https://github.com/bytecodealliance/wasmtime/pull/9162
After adding this the component worked out of the box
=> feat(runtime): enable wasmtime gc feature

.github/workflows/wasmcloud-host-chart.yml, charts/ci/nats-values.yaml, charts/wasmcloud-host/.helmignore, charts/wasmcloud-host/Chart.yaml, charts/wasmcloud-host/ct.yaml, charts/wasmcloud-host/templates/_helpers.tpl, charts/wasmcloud-host/templates/configmap.yaml, charts/wasmcloud-host/templates/deployment.yaml, charts/wasmcloud-host/values.yaml
This refreshes the `wasmcloud-host` helm chart to be compatible with wasmCloud 1.0+ (defaulting to `1.2.0`).
I've left the deprecation of the old chart as a follow-up exercise once we've published this one.
=> chore(charts): Refresh wasmcloud-host chart

crates/wash-cli/src/par.rs, crates/wash-lib/src/cli/claims.rs, crates/wash-lib/src/cli/inspect.rs
Teensy PR to streamline CLI doc generation. There are six instances of angle brackets in the wash help that have to be manually wrapped in backticks in order to render the Markdown successfully in Docusaurus. So, proposing to simply wrap the offending items in backticks in the help in order to cut out the extra step (and clear the way for more complete automation down the line).
=> chore(wash-cli): help styling to streamline cli markdown

crates/wash-cli/src/app/mod.rs, crates/wash-cli/src/call.rs, crates/wash-lib/src/config.rs
- **fix(wash-cli): remove misleading creds error message**
- **feat: give a nicer error to wash app for no responders**
This PR improves one misleading error and one unhelpful error, ensuring that we aren't suggesting people we use credentials files for the former. For the latter, all `wash app` commands will now output a nicer error message in the case where no wadm server responded to the API request instead of just `no responders`.
The helper to ensure we output a nicer error for no responders could be replicated in a few places around the code IMO
=> fix: improve errors in wash-cli

charts/wasmcloud-host/Chart.yaml, charts/wasmcloud-host/templates/deployment.yaml
The secrets topic prefix naming had slipped through as not following the appropriate naming convention, and for some reason Helm did not like max linear bytes being passed in as a number instead of a string, so I'm adding some quoting to it.
=> fix(charts): Fix secrets topic prefix naming and max linear memory bytes rendering

crates/wash-cli/src/dev.rs, crates/wash-lib/src/cli/dev.rs
This commit fixes an issue wher `wash dev` assumed that component IDs had to be `ModuleId`s (i.e. nkeys).
While in the past component IDs *were* nkeys, they are no longer required to be, and can be user-friendly names.
Resolves #2887
=> fix(wash-cli): wash dev on non-xkeys component IDs

Cargo.lock, Cargo.toml, crates/wash-cli/Cargo.toml, crates/wash-cli/src/bin/wash.rs, crates/wash-cli/src/lib.rs, crates/wash-cli/src/style.rs
Adopt styling similar to cargo for wash CLI commands. This doesn't change our overridden help-text, but it does affect commands individually. We might want to consider changing/updating our overridden help/maybe not overriding it as well (or colorizing it ourselves).
=> feat(wash-cli): add CLI styling to wash

crates/wash-cli/src/common/get_cmd.rs, crates/wash-cli/src/ctl/mod.rs, crates/wash-cli/src/ctl/output.rs, crates/wash-lib/src/cli/get.rs
(2/2) done [ie -- watch flag has been implemented]
#2772 is also addressed in this PR
Programatic implementation of unix's `watch` but with multi-platform support.
#2512 
next
=> feat(wash-cli): Add --watch flag to view live changes in host inventory

crates/wash-lib/Cargo.toml
Simple fix to enable the `gc` feature in wasmtime like we do for wasmcloud, ensuring that we can run the nightly built wasm32-wasip2 components as plugins
=> chore(wash-lib): enable gc feature in wasmtime

Cargo.lock, crates/provider-blobstore-s3/Cargo.toml, crates/provider-blobstore-s3/README.md, crates/provider-blobstore-s3/src/lib.rs, crates/provider-blobstore-s3/tests/storage.rs
This change adopts localstack via testcontainers instead of Minio as the default testing backend for the `blobstore-s3` provider.
It also fixes a bug that I uncovered in how the client was being set up when no bucket region was provided.
=> refactor: Use testcontainers and localstack for blobstore-s3 provider testing

Cargo.lock, Cargo.toml, crates/control-interface/Cargo.toml, crates/test-util/Cargo.toml, crates/wash-cli/Cargo.toml, crates/wash-lib/Cargo.toml, examples/security/secrets/provider-keyvalue-redis-auth/Cargo.toml, tests/common/nats.rs, tests/config.rs, tests/example-rust-hello-world.rs, tests/example-rust-http-keyvalue-counter.rs, tests/interfaces.rs, tests/policy.rs
Upgrading to async-nats 0.36, unfortunately we have references to the `wadm` crates which depend on the `control-interface` being upgraded, so `wash-lib` and `wash-cli` will need to drop their 0.33 references after `wadm` releases a new version.
=> deps(async-nats): upgrade to 0.36

crates/host/src/wasmbus/event.rs, crates/host/src/wasmbus/mod.rs, crates/provider-http-server/src/path.rs, crates/provider-sdk/src/provider.rs, crates/test-util/src/lattice/link.rs, crates/wash-cli/src/common/link_cmd.rs, crates/wash-cli/src/ctl/output.rs, src/bin/http-server-provider/wasmcloud.toml, tests/links.rs
This PR implements rejecting links with the same source ID, wit namespace/package, and link name but with different targets. This is a scenario that components cannot support, but some providers did support this.
After this PR, if your provider supported links on the same interface to multiple targets (e.g. the HTTP server targeting many components on `wasi:http/incoming-handler`, you **must** provide a link name in order to keep these links separate. wasmCloud will reject the link if it's not supplied. In a future PR, wadm should reject this at manifest validation since it's easy to tell if there is a conflict.
Here's a diagram that illustrates the difference:
resolves issues of link deletion found in #2902 
This PR also includes fixes for capability providers not receiving the full …
=> fix(*): link uniqueness enforcement, deletes

examples/rust/components/sqldb-postgres-query/project-generate.toml
Adds a `project-generate.toml` file to the Rust sqldb-postgres-query example so that it can be used as a template in a tutorial.
=> chore(examples): add project-generate.toml to Rust postgres example

crates/wash-cli/README.md
Chore to note that the `wash-cli` crate will move to `wash` on the next release. What we can do is publish the next version of `wash-cli` with the deprecation notice, then publish to `wash` on the next release, and finally update the `wash-cli` README once and for all to point towards the new `wash` crate.
=> chore(wash-cli): note wash-cli move to wash

crates/host/src/lib.rs, crates/host/src/oci.rs, crates/host/src/par.rs
This commit removes provider caching for local file references -- when a file is loaded via a container registry, caching is enabled but if it is loaded via a local file on disk, caching is never employed.
Resolves https://github.com/wasmCloud/wasmCloud/issues/2399
=> fix(host): remove provider caching for local file references

Cargo.lock, crates/provider-blobstore-azure/Cargo.toml, crates/provider-blobstore-azure/src/lib.rs, crates/provider-blobstore-azure/tests/integration.rs, crates/provider-blobstore-azure/wit/interfaces.wit
This adds an integration test suite invoked via wRPC calls against the exposed interface.
It also fixes a couple of bugs in the implementation that I came across while developing the tests.
In case you're wondering, the tests are currently marked as `#[ignore]`, because you can't run multiple instances of a given provider in the same process as they'll attempt to stomp on each other's connections (and fail to do so). There's a bit of future work to be done to make this not an issue, which would allow all of these tests to be enabled.
=> feat(provider-blobstore-azure): Add integration tests

crates/wash-cli/src/up/config.rs
Execute `wash up --ctl-tls` will give:
```
error: invalid value '1' for '--ctl-tls'
[possible values: true, false]
```
```bash
cargo install --path ./crates/wash-cli
~/.cargo/bin/wash up --ctl-tls
```
Giving me
```
>>> ⠅⠀  Starting wadm ...                                                                                                                                                                                                                                                                                        👀 Found wadm version on the disk: wadm-cli 0.14.0
✅ Using wadm version [v0.14.0]
🏃 Running in interactive mode.
🎛️ To start the dashboard, run `wash ui`
🚪 Press `CTRL+c` at any time to exit
Error: failed to initialize host
Caused by:
0: failed to establish NATS control server …
```
=> fix: boolean flag set incorrectly

Cargo.lock, Cargo.toml, crates/provider-sqldb-postgres/Cargo.toml, crates/provider-sqldb-postgres/src/lib.rs
This removes the `rustls` flag and enables TLS support by deffault.
=> feat(provider-sqldb-postgres): Enable TLS by default, remove the need for feature flag

Cargo.lock, crates/provider-blobstore-azure/Cargo.toml, crates/provider-blobstore-azure/src/lib.rs, crates/provider-blobstore-azure/tests/integration.rs, crates/provider-blobstore-fs/Cargo.toml, crates/provider-blobstore-fs/src/lib.rs, crates/provider-blobstore-s3/Cargo.toml, crates/provider-blobstore-s3/src/lib.rs
Per @rvolosatovs's suggestion in https://github.com/wasmCloud/wasmCloud/pull/2993#discussion_r1759693691, I'm switching all of the blobstore providers we ship to use the bindings from [`wrpc-interface-blobstore`](https://crates.io/crates/wrpc-interface-blobstore) instead of generating it themselves.
=> chore: Use `wrpc-interface-blobstore` for `provider-blobstore-*`

Cargo.lock, Cargo.toml, crates/component/src/lib.rs, crates/component/wit/interfaces.wit, crates/host/src/wasmbus/handler.rs, crates/provider-keyvalue-redis/src/lib.rs, crates/runtime/src/component/keyvalue.rs, crates/runtime/src/component/mod.rs, crates/runtime/wit/host.wit, src/bin/keyvalue-redis-provider/wasmcloud.toml, tests/components/build.rs, tests/components/rust/interfaces-reactor/src/keyvalue.rs, tests/components/rust/interfaces-reactor/src/lib.rs, tests/interfaces.rs
This enables keyvalue batch support inside of the host, along with a test to make sure it works. Not all of our providers implement batch yet, so this uses the Redis provider, which did have implementions. I did have to fix the redis provider to get the right type of data back and transform it. I also had to update our wRPC versions so we could pick up on some bug fixes for the types we are encoding in the batch interface.
=> feat(host): Adds support for batch support to the host

Cargo.lock, crates/provider-sqldb-postgres/Cargo.toml, crates/provider-sqldb-postgres/src/lib.rs
This adds the `webpki-roots` crate as a dependency to the postgres provider and uses it by default to provide CA certs when TLS is enabled.
=> fix(postgres-provider): include webpki-roots in the postgres provider by default

crates/core/Cargo.toml, crates/core/README.md, crates/core/src/lib.rs, crates/core/src/registry.rs, crates/core/src/tls.rs, crates/host/Cargo.toml, crates/wash-lib/Cargo.toml
With the recent #3030 reorganization PR, it seems that building unrelated things would result in bunch of warnings related to `oci-distribution` not being available, so this changes the `oci-distribution` feature to `oci` feature and puts the functionality depending on the `oci-*` crates behind the feature flag.
It also switches the crates depending on this functionality to use the new feature.
=> chore: Switch oci-distribution to oci feature

.github/workflows/wasmcloud-host-chart.yml, charts/wasmcloud-host/Chart.yaml, charts/wasmcloud-host/templates/_helpers.tpl, charts/wasmcloud-host/templates/configmap.yaml, charts/wasmcloud-host/values.yaml
This adjusts the NATS Server defaulting behavior to better align with the deployment patterns we're seeing, which is to say that rather than using `nats://nats.default.svc.cluster.local`, we're using `nats://nats-headless.<namespace>.svc.cluster.local` to match the namespace the `wasmcloud-host` is deployed in to.
Of course the ability to override this via `config.natsAddress` remains unchanged.
=> chore: Revise the default NATS Server address logic

charts/wasmcloud-host/Chart.yaml, charts/wasmcloud-host/templates/_helpers.tpl
When included as part of another chart where you might have nats-server already being installed standalone, the configmap naming will conflict, so this disambiguates the two by changing the template to include `-leaf` in the configmap name.
=> chore(charts): Change the nats-leaf configmap name to not conflict with upstream NATS chart naming

crates/runtime/src/runtime.rs
It turns out that there are a bunch of other settings that we could have hit the limit on that we needed to set. These new settings are all set to the same as max components because you could have that number of individual components that would each have their own core module and stack.
I tested this under load to make sure it actually works
=> fix(runtime): Ensures we have the proper limits set for max components

crates/wash-cli/src/dev.rs
This commit fixes a bug in the workspace-aware project dependency gathering that caused dependencies to override each other under  the same project.
=> fix(wash-cli): multiple generated dependencies collision in project

Cargo.lock, Cargo.toml, crates/wash-cli/Cargo.toml, crates/wash-cli/src/common/registry_cmd.rs, crates/wash-lib/src/parser/mod.rs
I figured that since folks might already be using Docker CLI for managing their containers or other OCI artifacts, being able to re-use the existing keyring for wasmcloud artifacts would be handy.
=> feat: Allow wash to re-use registry credentials from Docker

Cargo.lock, crates/wash-cli/src/app/mod.rs, crates/wash-cli/tests/wash_app.rs, crates/wash-lib/Cargo.toml, crates/wash-lib/src/cli/get.rs
- Backwards compatibility with millisecond input still maintained
- Improved terminal handling while watching application lattice
- watch interval for `app list` is now configurable with a default interval of 1000ms.
- Added Short flag of -w as an alternative to --watch
next
=> feat(wash-cli): Implement Humantime duration input for --watch flags

Cargo.lock, Cargo.toml, crates/provider-blobstore-azure/Cargo.toml, crates/provider-blobstore-azure/tests/integration.rs, crates/provider-blobstore-s3/Cargo.toml, crates/provider-blobstore-s3/tests/storage.rs, crates/provider-http-server/Cargo.toml, crates/provider-http-server/src/lib.rs, crates/test-util/Cargo.toml, crates/test-util/src/lib.rs, crates/test-util/src/testcontainers/azurite.rs, crates/test-util/src/testcontainers/localstack.rs, crates/test-util/src/testcontainers/mod.rs, crates/test-util/src/testcontainers/nats_server.rs, crates/test-util/src/testcontainers/squid_proxy.rs, crates/wash-lib/Cargo.toml, crates/wash-lib/src/start/github.rs
To make it easier to test consistently against the same versions of software (and have the flexibility to change the version to different one with ease as needed), we should provide a set of predefined testcontainers that can be used across the various crates in this repository as well as pulled in by external projects as well.
This also consolidates the existing usage of testcontainers across the repository to switching them to the ones under `wasmcloud_test_util` instead.
=> feat: Provide predefined testcontainers

Cargo.lock, crates/provider-blobstore-fs/Cargo.toml, crates/provider-blobstore-fs/src/lib.rs
Fixes https://github.com/wasmCloud/wasmCloud/issues/2773
Blobstore FS provider assumes that all parent directories exist when when writing an object with directories, (i.e "/"). If those directories do not exist the call will fail.
Fixes https://github.com/wasmCloud/wasmCloud/issues/2773
next
Only affect blobstore-fs
Unit test added.
Test added.
None
Ran poprox demo with blobstore-fs and object name containing a '/'
=> Create directory before writing object.

crates/wash-cli/src/app/mod.rs, crates/wash-cli/tests/common/mod.rs, crates/wash-cli/tests/fixtures/wadm/manifests/simple.wadm.yaml, crates/wash-cli/tests/wash_app.rs, crates/wash-lib/src/cli/output.rs
This commit enables wash to:
- Undeploy all applications at the same time
- Delete all undeployed applications
The combination of `wash app undeploy --all` and `wash app delete --all-undeployed` are meant to be used to gether in order to clear all apps in a given lattice.
=> feat(wash-cli): enable undeploying and deleting multiple apps

src/main.rs
In the interest of making it easier to pass these values down to providers, let's just directly use the environment variables.
#3080
=> chore: Explicitly use OTEL_EXPORTER_ environment variables for exporter configuration

crates/core/src/otel.rs
Since we're `Default` impl for `OtelProtocol`, we should just do the same for [`Level` since it matches the value we're setting with the function](https://github.com/wasmCloud/wasmCloud/blob/71fc4b8f60a1f5f469912b712452f1c96a7744ef/crates/core/src/logging.rs#L32-L36).
=> chore(core): Use Default impl for Level

typescript/packages/lattice-client-core/package.json, typescript/packages/lattice-client-react/package.json, typescript/yarn.lock
For some reason, Yarn doesn't update sub dependencies automatically when running package updates. This is not the first time that I've had this issue, but it is making me consider reverting back to standard npm tooling, or swap to pnpm since it has better support across the board and is more aligned to the npm standards.
Anyway... this just bumps all the dependencies in the yarn.lock file and aligns some package scripts.
=> chore(deps): update yarn.lock

.github/workflows/wasmcloud.yml
This commit allows for uncommitted changes to be ignored during `cargo smart-release`, but *only* for the pre-release PR (not actual release).
This normally shows up/is useful if `Cargo.lock` is somehow behind on `main`. In that situation automation to generate the pre-release changes PR does not work since Cargo.lock will have changed (updated) and the changes will be uncommitted ("dirty").
Note that `--allow-dirty` is *not* turned on for actual releases via automation.
=> feat(ci): --allow-dirty smart release for pre-release PR

Cargo.lock, crates/control-interface/Cargo.toml, crates/control-interface/src/otel.rs, crates/control-interface/src/types/provider.rs, crates/host/src/wasmbus/mod.rs
Missing `ProviderDescription` in the list of builderized structs in `control-interface`
As far as releasing this goes, I think we can avoid a major version bump of `wasmcloud-control-interface` by yanking `v2.0.0` and releasing this as `v2.1.0`
=> chore(control-interface)!: builder-ize ProviderDescription

crates/core/src/otel.rs
Unfortunately https://github.com/wasmCloud/wasmCloud/pull/3131 breaks old Rust providers, so we need to revert this change and add the aliases for future compatibility.
We can revisit the rename in the future.
=> chore: Revert OtelProtocol rename, add future compatibility aliasing

.github/actions/configure-wkg/action.yml, .github/workflows/wash-plugins.yml, .github/workflows/wit-wasmcloud-lattice-bus.yml, .github/workflows/wit-wasmcloud-postgres.yml, .github/workflows/wit-wasmcloud-secrets.yml
Secrets are not available in context of a composite action, so this adds the ability to pass them
=> fix(ci): Pass in the OCI auth info for wkg setup

.github/actions/configure-wkg/action.yml
This bumps our default back to 0.6.0 which does have binaries attached to it
=> fix(ci): Error out when version doesn't exist

.github/workflows/nix.yml, .github/workflows/provider.yml, .github/workflows/wash.yml, .github/workflows/wasmcloud.yml
This PR downgrades our use of 16 and 8 core runners to assist with the ask of CNCF project maintainers to use the default runners where possible. I plan on watching the CI on this PR to understand what takes a long time, and I think we should optimize from there.
Other things that I'd like to do
=> ci: downgrade 16/8 core runners

.github/workflows/ts-release.yml, .github/workflows/typescript.yml
TS Pipeline is currently failing because the release workflow needs higher permissions from its parent.
In related news, we should update the required checks for merging to include this renamed pipeline.
This should be rebased and merged after #3236
=> ci: fix permissions for ts pipeline

crates/wash-lib/src/build/component.rs, crates/wash-lib/src/parser/mod.rs, crates/wash-lib/tests/parser/files/tinygo_component_scheduler_gc.toml, crates/wash-lib/tests/parser/main.rs
Changes to wasmcloud.toml as per #3216 
```
[tinygo]
scheduler = none | tasks | asyncify
garbage_collector = none | conservative | leaking
```
=> feat: Tinygo scheduler & garbage collection overrides

Cargo.toml, crates/wash-cli/src/config.rs
This PR prepares wash-cli for an 0.35 release with all the latest and greatest.
~Draft PR while v1.3.0 isn't fully released, and waiting on #3217 before we cut the full release~
=> feat(wash-cli): bump wadm 0.16.1, wasmcloud 1.3, NATS 2.10.20

crates/wash-cli/Cargo.toml, crates/wash-cli/README.md
Adds support for `cargo binstall` for the `wash-cli` crate.
None
next
No impact on existing users. Anyone using `binstall` will be able to install `wash-cli` using `cargo binstall wash-cli`. This includes the `taiki-e/install-action` GitHub Action but is only really beneficial for targets other than `x86_64-unknown-linux-gnu`.
Before:
```console
$ cargo binstall wash-cli
INFO resolve: Resolving package: 'wash-cli'
WARN The package wash-cli v0.35.0 will be installed from source (with cargo)
Do you wish to continue? yes/[no]
? y
Updating crates.io index
Installing wash-cli v0.35.0
[ ...excluding build log... ]
Finished `release` profile [optimized] target(s) in 3m 09s
Installing /Users/lheywood/.cargo/bin/wash
Installed package `wash-cli v0.35.0` (executable `wash`)
INFO Cargo finished …
```
=> chore: add cargo-binstall support for wash-cli

.github/workflows/typescript.yml
tags are matching using glob pattern, so a single `*` only matches to the next `/`. The correct pattern for this one should have been `~/**`.
=> ci: fix tag glob

charts/wasmcloud-host/templates/configmap.yaml, charts/wasmcloud-host/templates/deployment.yaml
The secret object is incorrectly defined. It should be an object as per [definition](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#secretvolumesource-v1-core) and [example](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#project-secret-keys-to-specific-file-paths)
Also modified the template for NATS configuration
next
Take the [value file](https://github.com/wasmCloud/wasmCloud/blob/main/charts/wasmcloud-host/values.yaml) with the `config.natsCredentialsSecret` set. Execute `helm template test ~/path/to/wasmCloud/charts/wasmcloud-host/  -f wasmcloud-host.yaml --debug`.
First commit to fix secret object:
Before: (line number may be different due to configurations)
```
Error: YAML parse error on …
```
=> fix: secret object for wasmcloud-host chart

crates/runtime/src/capability.rs, crates/runtime/src/component/logging.rs, crates/runtime/src/component/mod.rs, crates/runtime/wit/deps.lock, crates/runtime/wit/deps.toml, crates/runtime/wit/deps/logging-0-1-0/logging.wit, crates/runtime/wit/deps/logging-0-1-0/world.wit, crates/runtime/wit/guest.wit, crates/runtime/wit/host.wit
This brings in the new versioned wasi logging dependency and adds it to the host's default exports. This also maintains support for the unversioned logging as well.
Please note that I did not update the component crate as it should still work and its current deps can't be updated from the runtime crate. I did manually test this and will have more tests in the next commit with upgrading dependencies
=> feat(runtime): Adds support for versioned wasi logging interface

GOVERNANCE.md
I put this alongside other maintainer duties in the governance doc
Partially addresses #3305
=> docs: Adds a checklist for onboarding and offboarding maintainers

.github/workflows/wasmcloud-platform-chart.yaml
Without this, [the chart packaging step will fail](https://github.com/wasmCloud/wasmCloud/actions/runs/11308851349/job/31452128211) since we don't want to include the dependent charts as part of the repository.
=> chore(wasmcloud-platform): Fetch chart dependencies as part of packaging

MAINTAINERS.md
After a nomination and vote from current org maintainers, Colin has been added as a wasmCloud Org Maintainer and a maintainer of wash (which he has been contributing to for a while).
=> chore: Add Colin as org maintainer

.github/workflows/wasmcloud.yml
We were always running builds on PRs even if we were just changing the top level markdowns.
=> chore(ci): Makes it so we don't run wasmcloud host builds against docs

examples/rust/components/blobby/.gitignore, examples/rust/components/dog-fetcher/.gitignore, examples/rust/components/echo-messaging/.gitignore, examples/rust/components/ferris-says/.gitignore, examples/rust/components/http-blobstore/.gitignore, examples/rust/components/http-hello-world/.gitignore, examples/rust/components/http-jsonify/.gitignore, examples/rust/components/http-keyvalue-counter/.gitignore, examples/rust/components/http-task-manager/.gitignore, examples/rust/components/keyvalue-messaging/.gitignore, examples/rust/components/sqldb-postgres-query/.gitignore, examples/rust/components/wash-plugin-rust/.gitignore, examples/rust/providers/custom-template/.gitignore, examples/rust/providers/custom-template/component/.gitignore, examples/rust/providers/messaging-nats/.gitignore
After `wash new`-ing a rust example, the initial `git commit` of worktree files includes the `target` directory, which normally should not be checked in.
This PR also re-enables the `Cargo.lock` file (which normally *is* checked in) -- ensuring those files aren't checked in to `wasmcloud/wasmcloud` should be done at a higher level `.gitignore`.
=> chore(examples): git exclude target directories for examples

crates/host/src/wasmbus/config.rs
Small fix to be less aggressive with an error that usually appears during the shutdown of a host
=> fix(host): warn if config sender is dropped

.github/workflows/secrets-nats-kv.yml
This commit adds automation to CI to build and release binaries for `nats-kv-secrets` when tags are pushed to wasmcloud/wasmcloud.
=> feat(ci): build release binaries for nats-kv-secrets

typescript/apps/washboard-ui/src/app/components/providers-table.tsx, typescript/apps/washboard-ui/src/components/status-indicator/index.tsx, typescript/packages/lattice-client-core/src/controllers/providers.ts, typescript/packages/lattice-client-core/src/helpers.ts, typescript/packages/lattice-client-core/src/index.ts, typescript/packages/lattice-client-core/src/types.ts, typescript/packages/lattice-client-react/src/use-lattice-data.ts
As the related issue states, the healthiness of the providers never turn to `Running` although the bucket says otherwise. 
Tested it manually with multiple providers and hosts.
Everything looks good for now, but we might consider test it on multiple levels based on the estimated effort.
Should fix #2627 .
Should fix the falsy health indicator for providers.
1. Start hosts 
- you can do it with ```wash up --multi-local --label zone=us-east-1 -d``` ways
2. Open wash UI
- ```wash ui``` 
3. Deploy some applications
- ```wash new component hello --template-name hello-world-rust```
- ```cd hello```
- ```wash build && wash deploy wadm.yaml```
4. Monitor the provider entries health indicator
- wait it to to be Running and green
5. Validate with 
```nats kv get wadm_state provider_default --raw | …
```
=> fix(washboard-ui): provider status is in incorrect state

crates/core/src/registry.rs
This commit fixes a bug that ignored the `allow_insecure` setting when building registry configuration.
Resolves #3366
=> fix(core): allow missing registry authentication

.github/workflows/examples-components.yml, Cargo.lock, crates/wash-cli/src/appearance/spinner.rs, crates/wash-cli/src/build.rs, crates/wash-cli/src/cmd/dev/deps.rs, crates/wash-cli/src/cmd/dev/devloop.rs, crates/wash-cli/src/cmd/dev/mod.rs, crates/wash-cli/src/cmd/dev/wit.rs, crates/wash-cli/src/common/registry_cmd.rs, crates/wash-cli/src/wit.rs, crates/wash-cli/tests/wash_build.rs, crates/wash-lib/Cargo.toml, crates/wash-lib/src/app.rs, crates/wash-lib/src/build/component.rs, crates/wash-lib/src/build/mod.rs, crates/wash-lib/src/build/provider.rs, crates/wash-lib/src/cli/claims.rs, crates/wash-lib/src/cli/registry.rs, crates/wash-lib/src/config.rs, crates/wash-lib/src/lib.rs, crates/wash-lib/src/parser/mod.rs, crates/wash-lib/src/start/wasmcloud.rs, crates/wash-lib/tests/parser/files/separate_project_paths.toml, crates/wash-lib/tests/parser/main.rs
Decent wash-lib refactor which should simplify understanding the code and give us a nice `WasmcloudDotToml` struct to point at in documentation.
This PR:
Fixes #2757 
next minor wash-cli
next minor wash-lib
None of these changes for overriding the build/wit directories (which is the main point of this pr) will break existing manifests as the default behavior is the same.
Existing manifests that had the `claims`, `push_insecure`, or `call_alias` fields will parse fine as well, as we'll just ignore them.
Added a unit test to ensure this works as expected
Added an integration test to ensure this works as expected. This test will need to change with #3132 because it sed-style replaces the WIT directory in the code.
=> feat(wash): allow overriding project, wit, build folders

crates/wash-cli/src/cmd/dev/deps.rs, crates/wash-lib/src/parser/mod.rs, crates/wash-lib/src/start/mod.rs
This fixes the doctest that depends on #3379 and updates the remaining doctests that were failing.
In the case of the doctests where I had to add `ignore`, that's because those are marked as `pub(crate)` and can't be accessed by doctests, so there's no way to actually build them (hence `ignore` instead of `no_run`).
=> fix: Make remaining doctests not fail

flake.nix, nix/images/default.nix, nix/update-images.sh
- add `nix/update-images.sh` script
- by some reason `skopeo` run from CLI and within Nix sandbox behave differently running the same commands - on CLI it omits the repository metadata in the downloaded tarball, but in the sandbox it includes it. That causes a hash mismatch, so for now the generated output is manually patched. This will be fixed tomorrow
- we never actually specified the correct arch when fetching the image, handling of this generally depends on the OCI registry/image, i.e. for multi-arch images that's a problem, but not for single arch images. It's likely that `wolfi` image was not multi-arch originally, which is why we did not run into issues
=> build(oci): update images, manually patch hashes

crates/wash-lib/src/build/component.rs, crates/wash-lib/src/parser/mod.rs, examples/rust/README.md, rust-toolchain.toml
Now that `wasm32-wasip2` is a [tier 2 target in rust](https://doc.rust-lang.org/nightly/releases.html#compiler), we can support it natively in `wash build`! So, now, when a Rust component has a wasm_target of wasm32-wasip2, we'll use the native target instead of adapting the core module/p1 module.
I considered making `wasm32-wasip2` the default here instead of the unknown module, but that would be a significant breaking change for the wasmcloud.tomls that don't specify a target. I'll file a followup issue instead to make this a default after the next release of wash.
wash 0.36
=> feat(wash): add support for Rust wasm32-wasip2 target

.github/workflows/wash.yml
This commit ensures that the `wasm-tools` binary is installed, as it is required for running some integration tests, particularly the golang tests.
=> fix(ci): add missing wasm-tools binary for running golang tests

crates/wash-cli/src/ui/mod.rs, typescript/apps/washboard-ui/package.json
Bumps washboard version to 0.5.0
This will be merged after the release for wash 0.36.0
=> chore: bump washboard version

.github/workflows/wash.yml, crates/wash-cli/src/cmd/dev/deps.rs
As of 0.36.0, there may be multiple versions of a deployed manifest. We want to ensure we delete all versions when the dev session ends.
wash-cli 0.36.1
=> fix(wash): delete manifest when dev stops

crates/wash-cli/tests/wash_build.rs, crates/wash-lib/src/build/mod.rs
When using wash 0.36 with wrpc, we get an error:
```
❯ wash build
failed to build provider
Caused by:
0: failed to load lock file
1: unable to parse lock file from path
2: TOML parse error at line 1, column 1
|
1 |
| ^
missing field `version`
```
This PR changes the wkg logic to skip dependencies fetching if `wit/deps.toml` file is present.
=> fix: Only run wkg if 'deps.toml' is not present

.github/CODEOWNERS, nix/update-images.sh
- `skopeo` invocation would not copy the source image name and tag over to the pulled artifact, which caused the hash mismatch, that's now fixed
- enforce TLS verification for OCI fetches
https://github.com/containers/skopeo/issues/1609
=> build(nix): fix OCI update script

.github/actions/wasm-lang-toolchain-setup/action.yml
Based on my testing it appears that something changed from `0.14.0` to `0.15.0` such that a component that could've been built everything leading up to `0.14.0` worked, but now in `0.15.0` does not.
For this reason and others, we need to pin `componentize-py` to a known good version.
Separately I'll see if I can track down the regression and open up an issue in upstream or PR it even.
=> chore(ci): Pin componentize-py to known good version

Cargo.lock, Cargo.toml, crates/core/Cargo.toml, crates/core/src/oci.rs
So it turns out that our digest check and invalidation was working perfectly, but changes to a provider weren't working properly. This was due to the _separate_ caching step for the actual extracted binary. To fix this, I made the oci loader return an enum indicating whether it was a cache hit or miss and then converted that over to do the right thing when loading the par
Also, I bumped the version to 0.14 of wasmcloud-core because that is the version that is released on crates.io. I don't know why it ended up that way, but I wanted to make sure things reflected reality
=> fix(core)!: Fixes issue with provider cache invalidation

crates/test-util/src/testcontainers/nats_server.rs
Given that JetStream is a common dependency, it makes sense to enable it by default in our NatsServer test image
Resolves #3490
=> chore(test-util): Enable jetstream by default

GOVERNANCE.md
This PR adds a new section to the wasmCloud project governance on how project and org maintainers can take a leave of absence. As this is a governance change, we should have a super-majority of org maintainers approving this change before merging.
Other votes and comments are welcome, but are non-binding
=> chore: Update governance with leave policy

crates/wash-cli/tests/wash_build.rs, crates/wash-lib/src/build/mod.rs, crates/wash-lib/src/parser/mod.rs
This PR fixes issues related to `wit`, `build` dirs and WIT deps override paths when using the `wash build -p <path/to/project>` argument by canonicalizing relative paths.
There's also some additional error context that I've added to the monkey patch function in case there were errors there to aid in tracking down the issue.
In the latest commit, I've pushed a fix to enable building components when a `wit` dir is not available, which is completely fine when a crate like `wasmcloud_component` already generated all of the bindings.
wash-lib 0.30.1
=> fix(wash-lib): canonicalize wit, build, override paths

Cargo.lock, Cargo.toml, crates/provider-http-client/src/lib.rs, crates/provider-http-server/src/address.rs, crates/provider-http-server/src/lib.rs, crates/provider-sdk/src/provider.rs
- Optimize HTTP server provider
- disable TCP keepalive - we are quite chatty on the wire and generally these connections are short-lived, so no need for the extra overhead.
- disable HTTP keepalive - http-server provider is a proxy, which establishes its own TCP connections to NATS server, so keepalive here actually slows down the performance by effectively blocking requests, instead strive for higher degree of concurrency by disabling keepalive and so achieving greater throughput
- set TCP nodelay
- Update wRPC (with improved NATS transport)
- Optimize export serving by handling each invocation in a separate tokio task. In my testing, this performed much better
Tested on a Linux box with `Intel(R) Xeon(R) Platinum 8481C CPU @ 2.70GHz`
`nats-server 2.10.14`
Old host, old HTTP server:
``` …
```
=> feat: optimize communication

Cargo.lock, crates/provider-keyvalue-redis/Cargo.toml, crates/provider-keyvalue-redis/src/lib.rs, examples/rust/components/dog-fetcher/src/lib.rs, examples/rust/components/dog-fetcher/wasmcloud.lock, examples/rust/components/dog-fetcher/wit/deps/wasi-cli-0.2.2/package.wit, examples/rust/components/dog-fetcher/wit/deps/wasi-clocks-0.2.2/package.wit, examples/rust/components/dog-fetcher/wit/deps/wasi-http-0.2.2/package.wit, examples/rust/components/dog-fetcher/wit/deps/wasi-io-0.2.2/package.wit, examples/rust/components/dog-fetcher/wit/deps/wasi-random-0.2.2/package.wit, examples/rust/components/dog-fetcher/wit/world.wit, src/bin/keyvalue-redis-provider/wasmcloud.toml
This PR fixes a panic in the dog-fetcher component and a deadlock in the kv-redis provider
next dog-fetcher
keyvalue-redis-provider 0.28.2
=> Fix dog-fetcher panic and Redis provider deadlock

Cargo.lock, Cargo.toml, crates/wash-cli/Cargo.toml, crates/wash-lib/Cargo.toml
This is a simple dependency bump to pick up the fix from wkg on locking files on windows
=> fix(wash): Fixes wasmcloud.lock on windows

crates/host/src/wasmbus/handler.rs, crates/runtime/src/capability.rs
While I was diagnosing an issue, I noticed that the log levels that get logged from `wasi:logging` calls didn't look quite right:
```console
INFO log: wasmcloud_host::wasmbus::handler: ... level=Level::Info ...
```
what I was expecting instead was something like this:
```console
INFO log: wasmcloud_host::wasmbus::handler: ... level="info" ...
```
This implements `Display` and calls it via `to_string` in the logging handler.
=> chore: convert `wasi:logging` levels into more conventional format

.github/workflows/examples-components.yml, .github/workflows/examples-providers.yml, .github/workflows/nix.yml, .github/workflows/secrets-nats-kv.yml, .github/workflows/typescript.yml, .github/workflows/wash.yml, .github/workflows/wasmcloud.yml
Since we're already using `concurrency:` to cancel in-flight requests keyed by SHA, I thought it might be useful in PRs to cancel them by pull request number so as to only test the latest changes.
This was inspired by https://turso.tech/blog/simple-trick-to-save-environment-and-money-when-using-github-actions
=> chore(ci): cancel in flight duplicate pull_request workflows

Cargo.lock, Cargo.toml, crates/provider-http-server/Cargo.toml, src/bin/http-server-provider/wasmcloud.toml
This PR bumps wasmCloud to 1.4.1 and the HTTP server to 0.24.0 to release performance improvements in previous PRs.
#3510 #3511
wasmCloud 1.4.1
http-server 0.24.0
=> chore: bump wasmCloud 1.4.1, httpserver 0.24

crates/provider-keyvalue-redis/README.md, crates/provider-messaging-kafka/README.md, crates/provider-sqldb-postgres/README.md
Replicas have been deprecated in favor of instances.
See wasmCloud/wadm#314 as an example.
=> docs(provider): update README.md to use instances

Cargo.lock, Cargo.toml, crates/host/Cargo.toml, crates/host/src/wasmbus/mod.rs
We had the correct code for extracting tracing headers from wRPC calls, but our use of `in_current_span` was creating unintentionally orphaned spans. This adds an explicit span for each incoming invocation. See the comment added in the code for additional information
=> fix(host): Fixes orphaned traces

Cargo.lock, Cargo.toml, crates/wash-cli/Cargo.toml, crates/wash-lib/Cargo.toml
Brings in `wadm-types` and `wadm-client` up to `0.7.1` in order to update `wascap` to `0.15.2`
=> chore: Bump wash-lib to 0.31.1

.github/workflows/wasmcloud.yml
https://packagecloud.io/wasmCloud/core is currently missing `fedora/41` packages.
From https://packagecloud.io/api/v1/distributions.json, the fedora 41 id is `302`
=> chore: Adding wash package for 'Fedora 41'

charts/wasmcloud-host/Chart.yaml, charts/wasmcloud-host/templates/deployment.yaml
Small fix for the observability related flags in the wasmcloud-host chart, since they're actually `Option<bool>` in the host so they need explicit values.
Also fix a typo so that the relevant options are in the `args` block in the template.
=> fix(charts/wasmcloud-host): set observability flags correctly

Cargo.lock, Cargo.toml, crates/wash-cli/Cargo.toml, crates/wash-lib/Cargo.toml, crates/wash-lib/src/generate/mod.rs, crates/wash-lib/src/generate/project_variables.rs, crates/wash-lib/src/generate/template.rs
This replaces the `weld-codegen` [Renderer](https://github.com/joonas/weld/blob/main/codegen/src/render.rs) functionality with direct dependency on Handlebars which is what's doing the heavy lifting anyway.
Since it doesn't look like we're actually making use of the additional helpers methods introduced in `weld-codegen`, this should be just a drop-in replacement.
=> chore: Replace `weld-codegen` with `handlebars`

README.md, chart/Chart.yaml
Deprecation of old helm chart and removal of badge from the main README
#2868 
next
Deprecates the old helm chart
helm linted the charts
=> wip: chore(charts): deprecate old helm chart

typescript/apps/washboard-ui/package.json, typescript/package.json, typescript/packages/eslint-config/package.json, typescript/packages/lattice-client-core/package.json, typescript/packages/lattice-client-react/package.json, typescript/yarn.lock
Addresses vulnerability in `cross-spawn` versions prior to 7.0.5 while waiting for our dependencies to update to it.
https://github.com/advisories/GHSA-3xgq-45jj-v275/
=> chore: pin cross-spawn to 7.0.5 for `GHSA-3xgq-45jj-v275`

Cargo.lock, Cargo.toml, crates/wash-lib/Cargo.toml
https://github.com/wasmCloud/wasmCloud/pull/2769 removed the code that made use of these dependencies, so let's clean up the unused dependencies.
This also addresses [`RUSTSEC-2021-0127`](https://rustsec.org/advisories/RUSTSEC-2021-0127)
=> chore: Remove serde_cbor and serde-transcode

README.md
While reviewing how the OpenSSF Scorecard works, I noticed that the repository URIs are in fact case-sensitive, for comparison:
* [`github.com/wasmcloud/wasmcloud`](https://securityscorecards.dev/viewer/?uri=github.com/wasmcloud/wasmcloud) has scorecard of `5.2`, which is incorrect
* [`github.com/wasmCloud/wasmCloud`](https://securityscorecards.dev/viewer/?uri=github.com/wasmCloud/wasmCloud) has scorecard of `5.9`, which is correct.
=> chore: Update OpenSSF Scorecard badge url

typescript/apps/washboard-ui/src/app/components/app-lattice-client-provider.tsx, typescript/apps/washboard-ui/src/app/components/connection-status.tsx, typescript/apps/washboard-ui/src/app/components/lattice-settings.tsx, typescript/packages/lattice-client-react/src/context/lattice-config-context.tsx, typescript/packages/lattice-client-react/src/context/lattice-config-provider.tsx, typescript/packages/lattice-client-react/src/index.ts, typescript/packages/lattice-client-react/src/use-lattice-config.ts
Fix washboard wnot change when webssocket url change
- Add LatticeConfigProvider component to manage lattice configuration
- Update AppLatticeClientProvider to use LatticeConfigProvider
- Modify ConnectionStatus and LatticeSettings to use new config context
- Update useLatticeConfig hook to use LatticeConfigContext
closes #3551
https://github.com/user-attachments/assets/ba75ad38-bc06-4e05-9139-c8cab5438520
=> fix(lattice-client-react): refresh washboard content when URL change

crates/wash-cli/src/bin/wash.rs, src/main.rs
WasmCloud Host should utilize the same `clap-markdown` capability implemented in wash-cli  in order to auto-generate docs. Additionally docs should exist on how to update the documentation for copy into wasm docs. 
https://github.com/wasmCloud/wasmcloud.com/issues/597
next
- wasm host binary invocations and arg parsing
- wasm documentation output
=> Adding clap-markdown feature into arg parsing logic of wasmCloud host

.github/workflows/ts-release-app-washboard.yml, .github/workflows/ts-release-package-lattice-client-core.yml, .github/workflows/ts-release-package-lattice-client-react.yml
The `release-kit/semver` uses GITHUB_REF_NAME with is the short name of the ref (i.e. `typescript/apps/washboard-ui/v0.6.0` instead of `refs/tags/typescript/apps/washboard-ui/v0.6.0`). This new pattern matches both with and without anyway.
=> ci: correct regex pattern when ref prefix doesn't exist

src/main.rs
This PR fixes a panic when running `./wasmcloud --help` by removing the conflicting short help flag for help markdown.
=> fix(wasmcloud): remove short help-markdown flag

crates/wash-cli/src/cmd/dev/deps.rs, crates/wash-cli/src/cmd/dev/devloop.rs, crates/wash-cli/src/cmd/dev/wit.rs, crates/wash-cli/tests/wash_dev.rs, crates/wash-lib/src/parser/mod.rs
This PR supports specifying wildcard interfaces in the wasmcloud.toml to prevent multiple overrides for the same interface.
For example, to override KV nats with Redis:
```toml
[[dev.overrides.imports]]
interface_spec = "wasi:keyvalue@0.2.0-draft"
image_ref = "ghcr.io/wasmcloud/keyvalue-redis:0.28.2"
config = { values = { url="redis://127.0.0.1:6379" } }
```
This PR also started using config & secrets where they weren't being used before, so an integration test started failing. I added support for a secrets policy in the event that one is specified in the last commit.
This PR initially broke an integration test related to overrides because it brought in secrets that were configured on the ovveride
I manually tested with the above
=> feat(wash-cli): support interface wildcard overrides

Cargo.lock, Cargo.toml, deny.toml, tests/components/rust/Cargo.lock
- General `cargo` dependency update
- Update to Wasmtime 26
- Update to wRPC 0.14
- Allow `Zlib` license, which is OSI and FSF approved. We already use `zlib` anyway (e.g. by virtue of using `git` for source-control)
- Allow `Unicode-3.0` license, which should be fine as well, following an offline discussion
=> build(rust): update dependencies

charts/wasmcloud-platform/Chart.yaml
Fix a problem installing/trying out Helm to major cloud providers for wasmcloud-platform chart:
```
Error: chart requires kubeVersion: >=1.24.0 which is incompatible with Kubernetes v1.29.9-gke.1177000
Error: chart requires kubeVersion: >=1.24.0 which is incompatible with Kubernetes v1.29.9-eks-ce1d5eb
```
The root cause is just Helm semVer function doesn't play nice with the actual version being used by public cloud providers. As highlighted in here: <https://github.com/helm/helm/issues/10375>
N/A
`next`
No changes or impact to general users
```
$ helm pull oci://ghcr.io/wasmcloud/charts/wasmcloud-platform
$ vi charts/wasmcloud-platform/Chart.yml # and apply the changes
$ helm upgrade --install \
wasmcloud-platform \
--values https://raw.githubusercontent.com/wasmCloud/wasmcloud/main/char …
```
=> fix: kubeVersion block helm to install into major clouds

crates/core/src/otel.rs, crates/host/src/wasmbus/mod.rs, crates/provider-sdk/src/otel.rs, crates/tracing/src/traces.rs, src/main.rs
This adds the ability for provider to configure some of the tunables for tracing via config. The underlying SDK defaults (and hence, the host) use the standard environment variables
Please note that some of our traces are using a span that lives for the lifetime of the application, so the sampling percentage may not work until we fix that as well
=> feat(otel): Adds the ability to configure sampling and buffer size

crates/wash-cli/src/ui/mod.rs, crates/wash-lib/src/start/github/mod.rs
Change in the tags for washboard means that washboard is no longer at the same URL. This adds the new URL pattern, and falls back to the old one if it cannot be found.
It might be worth noting that this will need an additional URL when the washboard code moves to its own repo.
Didn't add tests because I wouldn't have a clue where to even start with writing tests in rust but I'm happy to learn if someone wants to give me some direction.
Closes #3428
=> fix(wash-cli): add new url to check for washboard releases

crates/host/src/wasmbus/mod.rs, examples/rust/components/http-hello-world/wasmcloud.lock
This PR removes our use of a `JoinSet` and then awaiting the completion exported invocation task in the `select!{}` loop. This caused a set of delays when handling component invocations as it would wait for a previous invocation to finish before accepting _any_ new invocations depending on which branch the `select!{}` loop selected.
=> fix(host): remove export joinset

Cargo.lock, crates/provider-messaging-nats/Cargo.toml, crates/provider-messaging-nats/src/lib.rs, src/bin/messaging-nats-provider/wasmcloud.toml
This PR ensures the nats messaging provider initializes observability and re-uses wRPC clients for invocations. This should result in a general efficiency improvement for handling messages since we don't recreate the wRPC client on each message.
Lastly, I'm pushing a commit to remove the semaphore from the NATS message subscription. It seems odd to arbitrarily limit the incoming messages at 75, which must've been an artifact of previous performance testings.
Combined with #3670 here's the debug level trace of the echo-messaging component
=> fix: nats messaging init observe

crates/wash-cli/src/bin/wash.rs
The _wash dev_ command will panic with a _broken pipe_ when piped to another program and CTRL^C is pressed by the user:
```console
wash dev -o json | jq
```
Please refer to issue #3639 as it contains the analysis for this issue.
**REMARK** Please note that it is (nearly) impossible to capture the JSON output from **wash dev** and pipe it to **jq** when pressing CTRL^C since the latter will terminate sooner than the former. See the '_Manual Verification_' section on how this can be achieved.
Partially fixes issue #3639.
To verify the solution do something like (and press CTRL^C):
```console
mmooij@gandalf:~/dev/hello-wc1$ wash dev --work-dir . -o json | jq
ℹ️  Resolved wash session ID [AsJHq7]
ℹ️  No running hosts found, will start one...
🚧 Starting a new host...
👀 Found nats-server …
```
=> fix(wash-cli) wash dev with JSON output will panic when piped into jq

.github/workflows/examples-components.yml, .github/workflows/examples-providers.yml
After introducing this: https://github.com/wasmCloud/wasmCloud/issues/2032
some of the github ci steps are flaky doe to the external dependency (GitHub api)
example https://github.com/wasmCloud/wasmCloud/actions/runs/12060066556/job/33630065389
where the sleep is not giving enough time for the `wash up` to get the new version of the wasmcloud and/or wadm before `wash app deploy ...`.
I did some measurement before the commit and now with the following command:
```
hyperfine --runs 100 "../../target/release/wash up -d" --prepare="../../target/release/wash down --all && ../../target/release/wash drain all" --cleanup="../../target/release/wash down --all && ../../target/release/wash drain all" --time-unit=microsecond --export-json={{old|new|new_with_version}}.json
```
and the difference in …
=> ci(wash-up-tests): example providers and component github actions are early

flake.nix
Talking to @rvolosatovs, we probably should split up individual builds eventually, but I did want to make it easier to install wash from the flake (since I'm working on adding one for wadm, and having wash in the devShell there would be good)
=> feat(flake): Adds wash output package to the flake

crates/wash-cli/src/bin/wash.rs
Using colours for the main help. 🎉 
although I have a question: compared to the "not overwritten" version of the help this command is not in the list of commands when using the custom 🤔 
I know it i behind experimental flag, but was it intentionally hidden from the cli?
> capture      Capture and debug cluster invocations and state
and I updated the comments above the (Sub)Commands to reflect the plain text version. 
Some of them have been out of sync (beside the `NOTE`).
Did a minimal research too if there is a dynamic stuff or not, but not really 😞 manual maintenance it is.
closes: #2873 
```console
cd crates/wash-cli
```
```console
cargo run --
```
=> style(wash-cli): main help is colorized

.github/renovate-config.json, .github/renovate.json, .github/workflows/update-example-providers.yml
Unfortunately dependabot is not flexible enough other than the existing [ecosystems](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem). Although renovate-bot can do that with regular expressions.
Heads-up, you might need to [onboard renovate app](https://docs.renovatebot.com/getting-started/installing-onboarding/) for the repository.
The PRs which will be open should look like this https://github.com/markkovari/wasmCloud/pull/36
- update -> even should create only one PR from now on.
Feel free to edit the name/description/schedule, not sure what is the most convenient.  
closes: #2339
=> chore(renovate): add scheduled renovate to bump providers for examples

crates/wash-cli/src/app/mod.rs
This option was evidently confusing, and would cause `wash app deploy` to hang for a bit while waiting for STDIN. It is likely better to force users to pass `-` directly to read from STDIN.
Resolves https://github.com/wasmCloud/wasmCloud/issues/3604
=> fix(wash-cli)!: disable loading from stdin

typescript/apps/washboard-ui/.eslintrc.cjs, typescript/apps/washboard-ui/src/app/components/components-table.tsx, typescript/apps/washboard-ui/src/app/components/configs-table.tsx, typescript/apps/washboard-ui/src/app/components/connection-status.tsx, typescript/apps/washboard-ui/src/app/components/hosts-summary.tsx, typescript/apps/washboard-ui/src/app/components/lattice-settings.tsx, typescript/apps/washboard-ui/src/app/components/links-table.tsx, typescript/apps/washboard-ui/src/app/components/providers-table.tsx, typescript/apps/washboard-ui/src/app/components/settings.tsx, typescript/apps/washboard-ui/src/components/data-table/index.tsx, typescript/apps/washboard-ui/src/components/sheet/index.tsx, typescript/apps/washboard-ui/tests/common/test.ts, typescript/apps/washboard-ui/tests/common/wasmcloud-instance.ts, typescript/apps/washboard-ui/tests/e2e/fixtures/home-page.fixture.ts, typescript/apps/washboard-ui/tests/e2e/home.spec.ts
Added some new E2E tests for the washboard ui. There's a number of changes in the `typescript/apps/washboard-ui/src` folder which are related to fixing bugs and accessing ui elements through some common `data-testid` attributes. Because of this, it might be easier to review the changes in the `typescript/apps/washboard-ui/tests` folder first.
- **test(washboard): make wasmcloud fixture automatic and configurable**
- **test(washboard): add UI e2e tests**
- **chore(washboard): update eslint config for better e2e devx**
=> Add more e2e tests

crates/wash-cli/src/common/get_cmd.rs
Fixed the spinner rendering inconsistencies by separating out the logic to the match statement
Reviewed-by: Zahir S
Refs: #3584
Signed-off-by: Zahir Sabotic <zahirsabotic@bennington.edu>
Spinner rendering error in wash-cli crate.
This refers to issue #3584.
Target release: next.
No impact on consumers, just removes the visual artifact that was leftover from improper handling of the spinner.
No changes or additions to the acceptance or integration test suite 
As seen above, visual artifact does not show up anymore.
=>     fix(wash-cli): spinner rendering error

.github/workflows/update-example-providers.yml
This uses the same [GitHub App](https://github.com/apps/wasmcloud-automation-app) we've set up for the [Nix flake update](https://github.com/wasmCloud/wasmCloud/pull/3827) and [Nix OCI image update](https://github.com/wasmCloud/wasmCloud/pull/3828) actions so that it doesn't show up under my personal account.
=> chore(ci): Use `create-github-app-token` action for Renovate workflow

Cargo.lock, Cargo.toml, crates/control-interface/Cargo.toml, crates/control-interface/src/broker.rs, crates/control-interface/src/lib.rs, crates/control-interface/src/types/component.rs, crates/control-interface/src/types/ctl.rs, crates/control-interface/src/types/link.rs, crates/control-interface/src/types/provider.rs, crates/control-interface/src/types/rpc.rs, crates/wash-lib/src/spier.rs
Inspired by some of the pain @joonas went through to release the last version of wash-cli
This PR:
- ~Removes the host-sys crate, which was an initial experiment but hasn't been touched since its creation (@rvolosatovs please feel free to push back if this is serving a function somewhere~
- Removes unused dependencies from the `control-interface` and `core` crates.
- Removes the reliance on the `core` crate in `wasmcloud-control-interface` by using Strings instead of type aliases.
This is related to a broader issue in this monorepo where crates are too hard to release and there's too much inter-reliance for a tiny subset of functionality. In this case, the reliance on the `core` crate for string type aliases created a dependency where any core crate release would also require a control …
=> Host-sys, control-interface and core dep cleanup

crates/wash-lib/src/generate/favorites.toml
closes #3829 
We moved Go http-hello-world example to `go` repository and turned it into an actual wash template.
This means users no longer need to change the package name inside `go.mod` before `wash build`.
This is a sample run using this new favorites toml.
```
/tmp ❯ wash new component --favorites ./favorites.toml bla
✔ Select a project template: · hello-world-tinygo: a hello-world component (in TinyGo) that responds over an HTTP connection
🔧 Cloning template from repo wasmCloud/go subfolder templates/component/http-hello-world...
🔧 Using template subfolder templates/component/http-hello-world...
🔧 Generating template...
[ 1/39]   Done: .gitignore
[ 2/39]   Done: README.md
[ 3/39]   Done: bindings.wadge.go
[ 4/39]   Done: go.mod
✨ Done! New project created /private/tmp/bla
Project …
```
=> chore: Go HTTP Component Template update

crates/host/src/wasmbus/experimental.rs, crates/host/src/wasmbus/handler.rs, crates/host/src/wasmbus/mod.rs, crates/runtime/src/component/messaging/mod.rs, crates/runtime/src/component/messaging/v0_2.rs, crates/runtime/src/component/messaging/v0_3.rs, crates/runtime/src/component/mod.rs, crates/runtime/src/experimental.rs, crates/runtime/src/lib.rs, crates/runtime/src/runtime.rs, crates/test-util/src/host.rs
- **refactor(host): consistently name features**
- **feat(host): gate messaging@v3 behind feature flag**
This PR:
1. More consistently names the builtin features
1. Gates the wasmcloud:messaging@v3 interface behind a feature flag to note its experimental status.
The integration tests fail if this feature flag is not enabled, as designed:
```bash
TRACE handle:call_http_incoming_handle:wit-bindgen import: wasmcloud_runtime::capability::wasmtime_bindings::wasmcloud::messaging0_3_0::types: call name="" module="types" function="[static]client.connect"
TRACE handle:call_http_incoming_handle:wit-bindgen import: wasmcloud_runtime::capability::wasmtime_bindings::wasmcloud::messaging0_3_0::types: return result=Err(wasmcloud-messaging-v3 feature flag is disabled, rejecting invocation) module="types" …
```
=> fix: gate messaging behind feature flag

.github/workflows/wash.yml
~Draft for a moment while I make sure all my PRs get the right results.~
It's currently impossible for us to require `wash` CI to pass (unit tests and integration tests) before merging because we filter wash actions to only run when `wash` is modified. This leaves us with three options (probably more but pause for dramatic effect):
1. Don't require `wash` actions, possibly allow merging failing wash checks to `main` (current)
2. Require `wash` actions, always run `wash` actions on every PR (slow)
3. Something magical (this PR)
This PR changes the path based filtering to use ~https://github.com/dorny/paths-filter~ https://github.com/tj-actions/changed-files instead of GitHub workflow's path filtering, and then adds a final job to the `wash.yml` action called `wash_successful_checks`. This …
=> ci(wash): add wash_successful_check requirement

.github/workflows/wasmcloud.yml
This PR uses https://github.com/tj-actions/changed-files to ensure that we only run wasmCloud CI if there is a change to a file that would affect the wasmCloud builds or tests. More importantly, it adds a summary job called `wasmcloud_successful_checks` that we can make required in order to pass CI since it will always run
#3875 
When I first submitted this PR, I left out the clause to run the wasmCloud CI if the action is changed. The result of that is https://github.com/wasmCloud/wasmCloud/actions/runs/12517799771, which skipped all wasmCloud CI and finished in 30s.
=> ci(wasmcloud): add wasmcloud_successful_checks 

.github/actions/install-cached-wash-cli/action.yml, .github/actions/wasm-lang-toolchain-setup/action.yml, .github/workflows/examples-components.yml, .github/workflows/examples-providers.yml
This moves wash install into an action that can be reused. If no version is specified, it will do a super basic check on which files have changed to see if it is better to use the commit from main, or the commit from the PR to build `wash` from. This means if the PR is just a change to examples, the latest commit on main has most probably already been built and cached.
This could also be used in E2E tests as per the improvements in #3889
=> ci: add action for cached-install of wash

.github/workflows/wasmcloud.yml, crates/provider-http-client/src/lib.rs
- **ci(wasmcloud): require cargo when providers change**
- **chore(http-client): address clippy warning**
Slight oversight in the wasmcloud_successful_check is that clippy checks the status of the entire workspace, so we need to run the cargo action if a provider changes too.
=> fix: clippy ci requirement

crates/host/src/wasmbus/handler.rs
This PR fixes a failure in the Windows build on main.
Here's a previous version of this PR that ran the windows build successfully , which normally just runs on `main` https://github.com/wasmCloud/wasmCloud/actions/runs/12562395410/job/35022758233?pr=3901
=> fix: windows ambiguous as_ref

.gitignore, crates/wash-cli/src/cmd/wit/build.rs, crates/wash-cli/src/cmd/wit/deps.rs, crates/wash-cli/src/cmd/wit/publish.rs, crates/wash-lib/src/build/mod.rs, crates/wash-lib/src/cli/mod.rs, crates/wash-lib/src/deps.rs, crates/wash-lib/src/lib.rs
This PR does some refactoring of our wit fetching and override logic to ensure the same logic is used everywhere for extended project overrides.
Fixes #3871
=> fix(wash)!: use extended interface overrides everywhere

.github/workflows/wasmcloud.yml
This PR ensures the build-doc action runs on tag actions as it's required for releases. You can see in https://github.com/wasmCloud/wasmCloud/actions/runs/12589041687 where the release action didn't complete since it wasn't run.
=> ci(wasmcloud): build-doc on releases

.github/workflows/secrets-nats-kv.yml, .github/workflows/wash-plugins.yml, .github/workflows/wasmcloud.yml, .github/workflows/wit-wasmcloud-lattice-bus.yml, .github/workflows/wit-wasmcloud-postgres.yml, .github/workflows/wit-wasmcloud-secrets.yml
This PR downgrades the actions-gh-release action to 2.1.0 just like https://github.com/dj95/kdl-fmt/commit/f7c3fd9d587738332a6579a3bba688072270c7da#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R99.
Upstream issue https://github.com/softprops/action-gh-release/issues/555
Can be reverted after https://github.com/softprops/action-gh-release/pull/562 releases
This prevented wasmCloud 1.5.0 from having the release artifacts, so going to delete and re-create the tag afterwards https://github.com/wasmCloud/wasmCloud/actions/runs/12602813631/job/35130401952#step:5:18
=> ci: downgrade action-gh-release 2.1.0

flake.nix
Set a timestamp for Docker images built in Nix
Note that this, of course, makes these builds non-reproducible
=> build(nix): use current time for OCI timestamps

Cargo.toml, crates/wash-cli/tests/wash_app.rs, crates/wash-cli/tests/wash_dev.rs
Add an integration test to verify that `wash dev` uses buffered writes to stdout as defined in feature #3706
This PR adds a regression test for issue #3680
Using **crates/wash-cli** as working directory it can be tested as follows:
```console
cargo build
cargo test --test wash_dev -- integration_dev_hello_component_piped_stdout
```
To test a failure; i.e. broken pipe error, replace the **write!()**- to **println!()** calls in **src/bin/wash.rs**.
Following tests have been added:
- wash_dev::integration_dev_hello_component_piped_stdout
=> feature(wash-cli) test buffered stdout of wash dev

.github/workflows/wasmcloud.yml
Use `wolfi` as the default image base as requested by @joonas 
This is a breaking change for users of `latest`, `canary` and version tags depending on Debian being the base image.
E.g.:
- Providers dynamically linked to glibc *will fail to startup*
- Downstream users using images via e.g. `FROM` and using `apt` etc. to add packages will break
=> ci!: use wolfi as a default image base

Cargo.lock, Cargo.toml, crates/host/Cargo.toml, crates/host/src/metrics.rs, crates/host/src/wasmbus/mod.rs, crates/tracing/Cargo.toml, crates/tracing/src/lib.rs, crates/tracing/src/metrics.rs, crates/tracing/src/traces.rs
Quite a bit has changed since `0.23`, most notably the breaking changes introduced in [`0.27`](https://github.com/open-telemetry/opentelemetry-rust/blob/a1dda220deed9f69bd8502e8ffc0a45d72ac836e/opentelemetry-otlp/CHANGELOG.md#0270).
I tried to keep the changes here as minimal and focused on the upgrade without changing much else
=> chore: upgrade opentelemetry libraries to 0.27

.github/workflows/check-conventional-commits.yml
This adjusts the conditions for the conventional commit checks so that the comment steps will run when appropriate
=> ci: always run comment steps

examples/rust/components/ferris-says/README.md
fix(examples): ferris-says README wash call instructions
Wrong function call in README
Will lead to a not successful usage of the README
=> Update README.md Ferris Says example

Cargo.lock, Cargo.toml, crates/wash-cli/src/call.rs, crates/wash-cli/src/config.rs
I suppose dependabot would get this eventually but this also updates wadm inside of wash to 0.19. Also includes a pretty strange code fix for a type internal to wash that wasn't getting deserialized properly
next wash
```
Running `target/debug/wash --version`
wash          v0.37.0
├ nats-server v2.10.20
├ wadm        v0.19.0
└ wasmcloud   v1.4.2
```
=> feat(wash): update wadm to 0.19

crates/control-interface/src/client.rs, crates/control-interface/src/types/host.rs, crates/host/src/wasmbus/mod.rs
Allow deletion of labels without providing `value`
Closes #3913
`next`
Nothing.
Running a deletion without providing the value should now work.
1. Launch locally built wasmCloud using `wash up --host-path target/debug/wasmcloud`
2. Get the host ID, use for next two commands
3. Run `nats req "wasmbus.ctl.v1.default.label.put.NCZBHUNUKL6J47Z6U7YODISBKW6FHLMIXKHBF6BCCPT4DYGVBMQZENHX" '{"key":"foo","value":"bar"}'`
4. Run `nats req "wasmbus.ctl.v1.default.label.del.NCZBHUNUKL6J47Z6U7YODISBKW6FHLMIXKHBF6BCCPT4DYGVBMQZENHX" '{"key":"foo"}'`
5. See it working
=> fix: allow deletion of labels without providing value

crates/host/src/wasmbus/mod.rs
```
$ curl http://localhost:9090/     
unknown endpoint `/`
$ curl http://localhost:9090/hello
unknown endpoint `/hello`
$ curl http://localhost:9090/readyz
{"status":"ok"}
$ curl http://localhost:9090/livez 
{"status":"ok"}
$ curl --head http://localhost:9090/livez
HTTP/1.1 200 OK
date: Tue, 14 Jan 2025 10:03:31 GMT
$ curl --head http://localhost:9090/readyz
HTTP/1.1 200 OK
date: Tue, 14 Jan 2025 10:03:34 GMT
```
See commit messages for details
Refs https://github.com/wasmCloud/wasmCloud/pull/3874
=> refactor: HTTP admin endpoints

crates/wash-cli/src/cmd/config/path.rs, crates/wash-cli/src/cmd/dev/mod.rs, crates/wash-cli/src/cmd/wit/build.rs, crates/wash-cli/src/cmd/wit/deps.rs, crates/wash-lib/src/cli/mod.rs, crates/wash-lib/src/parser/mod.rs
Signed-off-by: Abhinav Prakash <abhinav.prakash319@gmail.com>
- **fix::> Proper exposure of path.rs**
- **fix::> Proper logic of Paths resolution**
- **fix::> replaced all std::env::current_dir() references in wash-cli**
- **fix::> Changed the impl acc to discussion**
- **fix::> publically exposed the config-path**
- **fix::> Cleanupgit add crates/wash-cli/src/cmd/dev/mod.rs crates/wash-cli/src/cmd/mod.rs crates/wash-cli/src/cmd/wit/build.rs crates/wash-cli/src/cmd/wit/deps.rs crates/wash-lib/src/parser/mod.rs**
- **fix::> Cleanupgit add crates/wash-cli/src/cmd/config/mod.rs**
- **chore(wash-cli): remove unused import comment**
It appears I am not a git wizard, and there's something up that closes PR #3855. These are all of the original commits from there by @PsychoPunkSage, who did a …
=> PR #3855 reopened

.github/workflows/wasmcloud.yml
actions/runner-images#10443
This fixes an issue with the way we use `unshare` and Ubuntu 24.04.
=> ci(wasmcloud): use ubuntu 22.04 for oci

crates/host/src/wasmbus/mod.rs, crates/host/src/wasmbus/providers/http_server/address.rs, crates/host/src/wasmbus/providers/http_server/mod.rs, crates/host/src/wasmbus/providers/http_server/path.rs, crates/provider-sdk/src/provider.rs, crates/test-util/src/provider.rs, tests/builtins.rs
This PR refactors the builtin HTTP server for code reuse and adds an implementation for path-based routing. This uses the same link configuration and handling code as the native binary HTTP server and should be a drop-in replacement for path-based application yamls.
Fixes #3741
wasmCloud 1.6.0
Included a unit test to validate the link handling. https://github.com/wasmCloud/wasmCloud/actions/runs/12601826784/job/35123739425?pr=3924#step:4:2173
Marked as draft while I write an integration test for actually testing path routing.
=> feat(host): builtin http-server path routing

Cargo.toml
As per https://github.com/wasmCloud/wasmCloud/actions/runs/12813978751/job/35729348587 this is not an allowed category.
=> chore: remove platform category from Cargo.toml

crates/host/src/wasmbus/event.rs, crates/host/src/wasmbus/mod.rs
This PR adds the missing `host_id` field on the provider_start_failed event.
Generally we don't actually need this, because the `source` of the event is the host ID. Since we put this field on many other event payloads though, let's just get to parity and then make a longer term decision to keep or remove it from events.
=> fix(host): output host_id on provider_start_failed

charts/.gitignore, charts/benchmark/.helmignore, charts/benchmark/Chart.lock, charts/benchmark/Chart.yaml, charts/benchmark/README.md, charts/benchmark/dashboards/grafana-dashboard-global.json, charts/benchmark/dashboards/grafana-dashboard-namespaces.json, charts/benchmark/dashboards/grafana-dashboard-nodes.json, charts/benchmark/dashboards/grafana-dashboard-pods.json, charts/benchmark/dashboards/grafana-dashboard-testbed.json, charts/benchmark/example-values.yaml, charts/benchmark/k6/test.js.tpl, charts/benchmark/templates/NOTES.txt, charts/benchmark/templates/_helpers.tpl, charts/benchmark/templates/collector-config.yaml, charts/benchmark/templates/dashboard-provider-config.yaml, charts/benchmark/templates/dashboards-config.yaml, charts/benchmark/templates/k6-test.yaml, charts/benchmark/templates/loki.yaml, charts/benchmark/templates/test-config.yaml, charts/benchmark/values.yaml, flake.nix
Adds a new chart for running simple benchmarking tests against wasmCloud hosts. I'll follow this up with a publish pipeline for the chart
=> feat(chart): Adds one click benchmarking chart

wit/bus/README.md
Updates example WIT in readme for wasmcloud:bus to include version numbers.
=> chore(wit): add versions to packages in example WIT for wasmcloud:bus

examples/rust/components/sqldb-postgres-query/wasmcloud.toml
This commit adds a note explaining how to use wash dev for the Postgres query example, which is not yet covered by automatic dependency creation (i.e. we don't yet perform automatic creation/bring up of Postgres clusters).
=> fix(examples): add note for PG example

.github/workflows/k6runner.yml, ci/Dockerfile.k6runner
In order to collect the test results from k6 into a configmap (which can then be collected and published wherever we want), we need to build k6 with custom extensions. Even if we choose to publish these in other ways in the future, we'll still need a custom runner like this. This is just a simple pipeline and dockerfile for building said custom runner
=> feat(ci): Adds pipeline for custom k6 test runner

.github/workflows/wasmcloud.yml, crates/provider-archive/src/archive.rs, crates/provider-http-client/src/lib.rs, crates/runtime/src/runtime.rs, crates/wash-lib/src/start/github/mod.rs, flake.lock, flake.nix
- Run `oci` job on the larger runner again
- Remove `buildah` usage - use `skopeo` instead and manually generate a multi-arch manifest
- Update `wit-deps`
- Update `nixify` and fix clippy errors, which we now encounter due to more recent Rust version
For manifest spec see https://github.com/opencontainers/image-spec/blob/main/image-index.md
Refs https://github.com/rvolosatovs/nixify/pull/337
Refs https://github.com/bytecodealliance/wrpc/pull/625
Refs https://github.com/actions/runner-images/issues/10443
Refs #4005
=> ci: run `oci` job on larger runner, use `skopeo`

crates/wash-cli/src/cmd/dev/mod.rs
This PR fixes an issue in `wash-cli` where if an extra wkg configuration file wasn't supplied we couldn't use the `--work-dir` flag with `wash dev`
wash 0.38.0
=> fix(wash-cli): use work dir without extra package args

.github/workflows/provider.yml, .github/workflows/wasmcloud.yml, crates/provider-sqldb-postgres/Cargo.toml, flake.nix
Build each binary in the project individually, as opposed to always building all binaries in the workspace.
- `clippy` still runs on the whole workspace
- wasmCloud `nextest` still builds all provider binaries (this is the lowest-hanging fruit for future optimization and requires no changes to Nix flake/github actions)
- each provider-target pair gets its own CI job
- each wash-target pair gets its own CI job
=> ci: split binary builds into separate flake outputs

charts/benchmark/Chart.yaml, charts/benchmark/README.md, charts/benchmark/k6/test.js.tpl, charts/benchmark/templates/NOTES.txt, charts/benchmark/templates/_helpers.tpl, charts/benchmark/templates/k6-test.yaml, charts/benchmark/templates/sa.yaml, charts/benchmark/values.yaml, ci/aggregate_data.py
This PR focuses on updating the test to publish all results to configmaps so they can be pulled out and aggregated as desired post test. This is a first step for setting up regular benchmarking tests for wasmCloud. It also includes the script we can run as part of our CI tests when we add them
=> feat(charts): Adds result aggregation to the benchmark chart

crates/wash-cli/tests/wash_build.rs
This PR re-enables the test that I disabled temporarily while we upgraded `wascap`
https://github.com/wasmCloud/wasmCloud/pull/4020
N/A
=> test(wash-cli): re-enable build provider test

.github/workflows/wasmcloud.yml
Refs https://github.com/rvolosatovs/nixify/pull/342, which was pulled in via #4030.
All Mac binaries, including universal ones, for all architectures, are now signed. Some Nix derivation closure size optimizations are also made for these, before signing.
Signing is done via https://github.com/indygreg/apple-platform-rs/tree/main/apple-codesign
In this PR we simply add verification steps to CI to ensure that our Mac binaries are indeed signed.
=> ci(mac): verify binary signatures

crates/wash-lib/src/cli/link.rs
The `link-name` flag in `wash link del` should not be required as there is a default value
=> fix(wash): Removes required for link name

.github/actions/install-nix/action.yml
Due to the deprecation of the GH cache API it relies on, we have to remove this step from installing nix. I also removed the env var in the action because we aren't using the caching step there anymore and `env` can't be set at the top level of an action unlike in a workflow
=> chore(ci): Removes magic nix cache action

crates/host/src/wasmbus/ctl.rs, crates/host/src/wasmbus/mod.rs
This PR is a pure refactor for the functions that implement the control interface functionality into a separate `ctl` module. This module contains a trait, `ControlInterfaceServer`, which describes all of the operations that the host implements for the control interface itself. The methods in the host module now are slim wrappers around this trait that deal with de/serialization.
I have not made any functional changes to the code so that we can make future improvements easier. While going through the code, though, a couple of items I'd like to discuss improving are:
For now, I'll leave these solely as items to ponder on.
Starts to highlight some inconsistencies for #3914
`next`, no need to release
N/A
=> refactor(host): implement ControlInterfaceServer trait

crates/provider-http-server/src/address.rs
This PR ensures that when the last link is deleted for an address the HTTP server is using that the socket is removed. This was causing an issue where deleting the last link for an address wouldn't allow for a new link to reserve a socket.
=> fix(http-server): remove socket for last delete

.github/workflows/wasmcloud.yml
This PR ensures we build the wash binary for provider releases.
See https://github.com/wasmCloud/wasmCloud/actions/runs/13160153715 which did not build wash and therefore did not release the provider
=> ci(wasmcloud): build wash for provider releases

crates/host/src/wasmbus/ctl.rs, crates/host/src/wasmbus/mod.rs, crates/host/src/wasmbus/providers/http_server/mod.rs, crates/host/src/wasmbus/providers/messaging_nats.rs, crates/host/src/wasmbus/providers/mod.rs
This PR introduces a feature that is likely what users expect from the host, which is that when it is supervising a capability provider it will ensure that the provider gets restarted in the case of a `kill -9` or a binary exit. Before this PR, if a provider is killed forcefully or panics, it will exit and the host will still report it as running until manually restarted. After this PR, a provider that exits before it's stopped by wasmCloud will restart with the same parameters. 
This PR also makes a few refactors to push the binary provider execution logic into the `wasmbus::providers` module
Marked as draft as there's one more aspect of restarting to take into account, which is that we need to fetch new links, config, secrets, etc which came up after the provider initially started
#3990 …
=> feat(host): supervise providers, restart on exit

.github/workflows/wasmcloud.yml
I've been doing a slightly naughty thing and publishing these crates manually. This change ensures that when we publish a tag for them the crate gets published too.
=> ci(wasmcloud): allow publishing httpserver/nats provider crates

.github/actions/build-nix/action.yml, .github/workflows/nix.yml, .github/workflows/wasmcloud.yml
Sometimes, connection to Nix network substituters (like Cachix) can fail (like in https://github.com/wasmCloud/wasmCloud/actions/runs/13174200900/job/36770534710)
In such cases, fall back to building from source rather than failing CI run.
See https://nix.dev/manual/nix/2.25/command-ref/nix-build.html#opt-fallback for more info
=> ci: run Nix with `--fallback`

crates/wash-cli/src/cmd/dev/devloop.rs, crates/wash-cli/src/cmd/dev/mod.rs
This PR ensures that on each dev loop we attempt to reload the project configuration. We need this so that you can make changes to interface overrides, configuration, etc and have the dev loop update to pick up the latest changes.
Enables https://github.com/wasmCloud/wasmcloud.com/pull/679 without the caveat!
wash 0.39
=> feat(wash-cli): support reloading wasmcloud.toml on dev loop

.github/workflows/provider.yml, .github/workflows/wasmcloud.yml, crates/wash-cli/src/par.rs
This PR adds an option to embed provider WIT information into the provider archive. The HTTP capability providers actually do not have a wit directory and they implement the wrpc interface directly via the crate, so we avoid embedding the WIT there.
```bash
➜ WIT_DIR=./crates/provider-blobstore-azure/wit cargo run -p wash-cli -- par create --vendor me --name az --binary ./target/debug/blobstore-azure-provider --compress
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.57s
Running `target/debug/wash par create --vendor me --name az --binary ./target/debug/blobstore-azure-provider --compress`
Successfully created archive blobstore-azure-provider.par.gz
➜ cargo run -p wash-cli -- inspect --wit ./blobstore-azure-provider.par.gz
Finished `dev` profile [unoptimized + debuginfo] …
```
=> ci(wasmcloud): support WIT embed for released providers

.github/actions/build-nix/action.yml, .github/workflows/provider.yml, .github/workflows/wasmcloud.yml
Cache most Nix outputs using https://github.com/actions/cache
This allows PRs from forks to benefit from caching, e.g. `oci` job should not need to build `wasmcloud` and `wash` binaries again anymore, since those builds should be pulled in from the cache.
Unfortunately, using caching for checks like `nextest` and `clippy` does not make sense, caching these takes enormous amount of time - that's due to the fact that we build all workspaces as part of running these checks. (https://github.com/wasmCloud/wasmCloud/issues/4050 is going to be the first step in fixing that)
=> ci: cache Nix builds

.github/workflows/wasmcloud.yml
A few optimizations/improvements to #4072 
> Rust dependencies take quite a bit of space and caching them takes a lot of time
Based on status checks from https://github.com/wasmCloud/wasmCloud/actions/runs/13186347877
=> ci: optimize caching

.github/release.yml, .github/workflows/wasmcloud.yml
This PR separates the release jobs for wasmcloud and wash, which notably drop the requirement for wash to be built to release wasmcloud and vice versa.
I also included something nice in this PR to remove all of the dependabot commits from our generated release notes, which should be useful while we research conventional commit tools to do this 😄 
When I tried to release wasmcloud v1.6.0 it didn't complete because the job required wash to be built https://github.com/wasmCloud/wasmCloud/actions/runs/13186620296
=> ci: wasmcloud wash separate releases

.github/workflows/oci.yml, .github/workflows/wasmcloud.yml
~This PR enables building the wash binary on wasmCloud releases so the `oci` action can run. I could copy/paste that action into two separate blocks, but it truly is better as a matrix / reusable workflow.~
~I'll consider making that a reusable workflow as well. For now I was just opting for the simplest solution.~
This PR pulls the `oci` action out into a reusable workflow and calls it from `oci-wash` and `oci-wasmcloud` instead of in a matrix. This is helpful to ensure that we can use the same logic for both pieces of code, but not require wash to build and run through OCI for wasmCloud releases and vice versa.
#4076
=> ci: separate oci action into reusable workflow

.github/workflows/check-conventional-commits.yml
This PR introduces a ONE HUNDRED PERCENT HOME-GROWN HAND-WRITTEN job step after validating that commits are conventional that attaches relevant labels to PRs based on the commit message. It includes the following labels that it can add based on commits:
TYPE:
1. fix: -> bug
2. feat: -> enhancement
3. ci: -> ci
SCOPE
1. wash-cli|wash-lib|wash -> wash-cli
2. wasmcloud|host|runtime|core -> wasmcloud
3. control-interface|ctl -> wasmcloud-control-interface
BREAKING -> breaking
Gives us the basis for https://github.com/orgs/wasmCloud/projects/7/views/13?pane=issue&itemId=93877347 along with #4076's release.yml to generate changelogs based on conventional commits using PR labels 🚀
You can see an example fix to wash in https://github.com/brooksmtownsend/wasmCloud/pull/15
You can see an example …
=> ci(cc): add automatic PR commit labeler

Cargo.lock, Cargo.toml, crates/runtime/Cargo.toml, crates/runtime/src/component/mod.rs
This PR fixes an issue where parsing an unversioned WIT interface would end up bringing in the fully qualified WIT name instead of just the interface.
runtime 0.8.1
wasmcloud 1.6.1
=> fix(runtime): extract suffix from version not name

.github/workflows/oci.yml, .github/workflows/wasmcloud.yml
- update ubuntu-22.04 to ubuntu-24.04
- switch OCI job to run on GitHub hosted runners (this should ensure we can reuse caches from previous runs, hopefully....)
- run `nextest` on a beefier machine
=> ci: run on ubuntu 24.04

.github/actions/build-nix/action.yml, .github/workflows/oci.yml, .github/workflows/wasmcloud.yml
Nix caches stored on GitHub are trusted, so no need to check signatures
=> ci(nix): avoid checking signatures on import

crates/provider-http-client/Cargo.toml, crates/provider-http-client/src/lib.rs
Since the test is flaky and it's not clear why, log at a higher verbosity level, so once it happens, we have a trace to debug
=> add more logs to the flaky single conn HTTP client provider test

flake.nix, nix/patches/rust-spiffe.patch
See https://github.com/wasmCloud/wasmCloud/pull/4118#issuecomment-2666030967
This pulls in https://github.com/maxlambrecht/rust-spiffe/pull/138 as a patch applied within Nix sandbox to enable building wasmCloud binary depending on this crate while still depending on the published releases, thus not preventing `wasmcloud` from being published to crates.io
Refs https://github.com/rvolosatovs/nixify/pull/355
Tested via (on a Mac):
```
$ curl -sL https://github.com/wasmCloud/wasmCloud/pull/4118.patch | git am -3
$ nix build -L
```
=> build: patch `rust-spiffe`

src/main.rs
This adds `WASMCLOUD_TLS_CA_PATH` (or should it be called `WASMCLOUD_TLS_CA_PATHS`?) environment variable as alternative to `--tls-ca-path` for configuring additional CA paths to load into the OCI and OpenTelemetry clients.
This intended to make implementing https://github.com/wasmCloud/wasmCloud/issues/4109 slightly easier.
https://github.com/wasmCloud/wasmCloud/issues/4109
=> chore: Add WASMCLOUD_TLS_CA_PATH to mirror tls-ca-path flag

Cargo.lock, Cargo.toml, crates/host/Cargo.toml, crates/host/src/lib.rs, crates/host/src/wasmbus/mod.rs
This PR fixes an issue where we used additional CA certificates during component pulls but not provider pulls.
=> fix(wasmcloud): use tls certs for provider pull

.github/actions/build-nix/action.yml
Upload nix-store artifact even on cache hit
=> ci: always upload `nix-store` artifact

.github/workflows/benchmark.yml
I realized that we weren't passing credentials needed for cleanup of volumes after a test run
=> fix(ci): Ensure credentials are passed to cleanup step

.github/workflows/secrets-nats-kv.yml, flake.nix
This uses the existing steps for building with nix so we're releasing with the same base images (and wolfi) as our other images
=> feat(ci): Adds docker build the NATS KV secrets implementation

examples/rust/components/blobby/Cargo.toml, examples/rust/components/blobby/src/lib.rs
This PR converts the previous Blobby functionality to use the `wasmcloud_component` crate, along with its various helpers for handling HTTP requests using the Rust `http` library. Since this crate includes functionality to deal with streaming, much of this component is made simpler since it simply can return a `wasi::io::streams::InputStream` and we take care of actually streaming that to the requester.
blobby v0.5.0
I did test this with a ~700MB file which worked without any issue with the filesystem provider. I plan to test this with the S3 provider as well to ensure the streaming is properly working there.
=> feat(blobby): modernize blobby with wasmcloud_component

examples/rust/components/echo-messaging/wadm.yaml
A user on slack using a docker-compose setup where `nats` was running at `nats:4222` (rather than the default `localhost`) ran into an issue with the `echo-messaging` example since it:
- assumes the `localhost:4222` NATS normally available in a non-docker environment
- didn't properly configure the provider -> component *and* component -> provider connections
This PR improves the non-local `wadm.yaml`, making it a bit clearer how and what to change, and fixing the config.
=> chore(examples): improve clarity of echo-messaging wadm example

Cargo.lock, Cargo.toml, crates/control-interface/Cargo.toml, crates/provider-sdk/src/lib.rs
PR for upgrading async-nats to 0.39, pointing at a few branches / upstream repositories where needed. 
~This PR currently doesn't build because of trait mismatches which I think can be resolved with a better patch / upgrade to use all new released wrpc crate versions~
Depends on https://github.com/wasmCloud/wadm/pull/620 which depends on this. I think what we will do is merge the wadm PR, point this PR at `wadm` in main, then release crates until we get to the control interface, release new version of wadm-client, and finally depend on the new version of wadm-client for wash.
=> chore(async-nats)!: upgrade to 0.39

Cargo.lock, crates/provider-sqldb-postgres/Cargo.toml, crates/provider-sqldb-postgres/README.md, crates/provider-sqldb-postgres/src/config.rs, src/bin/sqldb-postgres-provider/wasmcloud.toml
This PR adds an extra (optional) configuration field to the postgres provider that allows configuring the max connection pool size for an individual component. I also made the `tls_required` field optional, because I thought that by default we would just not require TLS.
sqldb-postgres 0.9.0
=> feat(sqldb-postgres)!: allow configuration of max connections

crates/provider-http-server/README.md, crates/provider-http-server/src/host.rs, crates/provider-http-server/src/lib.rs
Got the http path router and adapted to header/host routing.
This introduces two new settings:
- `routing_mode = host` new routing mode
- `header` = which header to read the host from
=> feature: host based http routing

flake.lock, flake.nix
Use `k8s`, `go` and `nats-server` from `nixpkgs-unstable` (i.e. bleeding edge, latest versions)
Unfortunately, it appears that `tinygo` is currently broken on `nixpkgs-unstable` (at least on Mac), so keep using the *stable* version of it, at least for now. (https://github.com/NixOS/nixpkgs/pull/389791)
~Blocked on #4215~
=> build(nix): use latest tools

.github/actions/install-cached-wash-cli/action.yml, .github/workflows/wash.yml, .github/workflows/wasmcloud.yml
While we're unaffected by the SHA (`0e58ed8671d6b60d0890c21b07f8835ace038e67`) identified by Step Security, we need to stop using the action in question.
For more context, see:
* https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised
* https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/
=> chore(ci): Replace tj-actions/changed-files action

crates/host/src/wasmbus/mod.rs
Following up on [the comment @brooksmtownsend](https://github.com/wasmCloud/wasmCloud/pull/4118#discussion_r1996234888) left in the PR to initially introduce workload identity before I merged things in.
@brooksmtownsend PTAL and let me know if this is the change you had in mind or if I maybe misinterpreted?
=> chore(host): Match non-workload identity first

ci/manifests/wasmcloud/kustomization.yaml, crates/wash/src/cli/cmd/up.rs, crates/wash/src/lib/common.rs, crates/wash/src/lib/start/mod.rs, crates/wash/src/lib/start/nats.rs
Happen to notice in CI output that we're still shipping [`2.10.7`, which is from December 2023](https://github.com/nats-io/nats-server/releases/tag/v2.10.7) and that has some known vulnerabilities in it's dependencies, so let's bump to the latest version (`2.10.26`).
=> chore(wash): Bump nats-server version to 2.10.26

crates/wash/tests/common/mod.rs, crates/wash/tests/wash_up.rs
When updating the tests, I forgot to gate the process killing feature behind a target family of Unix. This should fix the failing wash tests on windows
=> fix(wash): Fixes wash tests on windows

Cargo.lock, Cargo.toml
Now that the new wadm version is out, we can use it from crates again
=> chore: Moves back to wadm from crates

flake.nix
Looks like this was missed in 3ccffe1d9
refs https://github.com/wasmCloud/wasmCloud/issues/4266
=> fix(nix): remove reference to nonexistent function

Cargo.lock, Cargo.toml, crates/core/Cargo.toml, crates/core/src/http.rs, crates/core/src/lib.rs, crates/core/src/messaging.rs, crates/host/Cargo.toml, crates/host/src/wasmbus/providers/http_server/address.rs, crates/host/src/wasmbus/providers/http_server/mod.rs, crates/host/src/wasmbus/providers/messaging_nats.rs, crates/provider-http-server/Cargo.toml, crates/provider-http-server/src/address.rs, crates/provider-http-server/src/lib.rs, crates/provider-messaging-nats/Cargo.toml, crates/provider-messaging-nats/src/connection.rs, crates/provider-messaging-nats/src/lib.rs, crates/provider-sdk/Cargo.toml, crates/runtime/Cargo.toml, crates/tracing/Cargo.toml
Our current host had a circular dependency loop with itself because it depended on the http and messaging providers. In order to break this, I moved the common http and messaging types we use for builtins into `wasmcloud-core` behind feature flags that aren't on by default. As such, this is a breaking change as I moved stuff around, but mostly didn't change any code.
Please note that I only bumped version numbers on things we had released already (and anything else we already released that depends on core). Some of these crates had not yet been released and do not need another bump
=> refactor!: Removes dependencies from host on provider libraries

.github/workflows/wit-wasmcloud-identity.yml
Release https://github.com/wasmCloud/wasmCloud/releases/tag/v1.7.0 went out but the wit interface didn't.
This is a copy/pasta from postgres.
=> chore: Publish wasmcloud:identity WIT

crates/host/src/wasmbus/providers/mod.rs, crates/tracing/src/metrics.rs, crates/tracing/src/traces.rs
We weren't properly discovering resource attributes from the environment. This should fix the issue in both the host and provider. This also changes our start provider process to proxy through all OTEL env vars to the process
=> feat(tracing): Adds support for resource attributes

crates/provider-keyvalue-nats/README.md
Having sample deployment YAML reduces friction when learning to use a provider. This PR adds sample YAML for keyvalue-nats following the model of keyvalue-redis.
=> chore(providers): Add sample deployment YAML for keyvalue-nats

crates/host/src/wasmbus/ctl.rs, crates/host/src/wasmbus/mod.rs, crates/test-util/src/provider.rs, tests/builtins.rs
This commit enables hosts to ignore auctions for builtin providers if they are enabled. While in the past a response to start_provider was assumed for every message, we loosen that to return an optional response.
Resolves #4232
=> fix(host): ignore auctions for builtin providers when disabled

.github/actions/build-nix/action.yml, .github/workflows/oci.yml, .github/workflows/wasmcloud.yml
We're trying to install packages from `nixpkgs` input in our flake, but we don't have such an input, so `nixpkgs#` references were falling back to upstream https://github.com/NixOS/nixpkgs, which, incidentally, recently introduced a regression for wine64, which caused Windows builds to fail (we use `wine64` to test execution of binaries)
Fix this by importing from `nixpkgs-unstable`, which is an input we *do* have in our flake
Refs https://github.com/NixOS/nixpkgs/issues/397271
Example failing CI: https://github.com/wasmCloud/wasmCloud/actions/runs/14346060267/job/40215978618
=> ci(nix): use pinned nixpkgs

crates/wash/Cargo.toml, crates/wash/src/bin/wash.rs
This commit fixes a bug with wash where a no-argument plugin command (e.g. `wash hello`) was being interpreted as a wash command (but with no actual internal wash command matching), and printing help.
Resolves https://github.com/wasmCloud/wasmCloud/issues/4287
I tested this locally after building a no-argument plugin (and a regular one)
=> fix(wash): use of no-arg plugins

.github/workflows/check-conventional-commits.yml
The error was caused by the script attempting to interact with the GitHub repository without first confirming whether the current directory was initialized as a valid Git repository. To resolve this, I added an initial check that verifies if the directory contains a valid Git repository before proceeding with the rest of the operations.
Closes #4296
=> [CI] Implemented a repo check on conventional-commit action to handle failed command

crates/wash/src/cli/cmd/up.rs, crates/wash/src/lib/config.rs
Angle brackets in the help documentation causes the generated Markdown to error (if not offset with a backtick) when deployed to the docs site. A few angle brackets have crept in around URLs, and this PR removes them.
=> chore(wash): adjust URL formatting in help

.github/workflows/secrets-nats-kv.yml, .github/workflows/wash-plugins.yml, .github/workflows/wasmcloud.yml, .github/workflows/wit-wasmcloud-identity.yml, .github/workflows/wit-wasmcloud-lattice-bus.yml, .github/workflows/wit-wasmcloud-postgres.yml, .github/workflows/wit-wasmcloud-secrets.yml
This PR updates the action-gh-release that previously got downgraded that NOW got upgraded again to a broken version for uploading artifacts
Uploading artifacts for wasmCloud v1.8.0 failed because of this https://github.com/wasmCloud/wasmCloud/actions/runs/14579950627/job/40894792365
v1.8.0
=> ci: update action-gh-release to v2.2.2

crates/host/src/metrics.rs, crates/host/src/wasmbus/mod.rs, crates/tracing/src/lib.rs
This PR adds a new metric, `wasmcloud_host.component.active_instances`, which tracks the number of currently executing instances of a component. This is extremely useful to be able to measure the actual number of components executing at any given time. This lets you understand if your scale is correct, if you need to scale up, down, etc.
Additionally, this lets you setup alerts if you're approaching your max instances.
A followup commit also adds `wasmcloud_host.component.max_instances` so that you can create views and alerts based on saturation, e.g. `component_active_instances / component_max_instances > 0.8`
This PR also adds a timeout for the component future which will ensure that semaphores are dropped after a component stops executing, even if it's killed by the epoch counter. …
=> feat(host): track active component instances

crates/host/src/wasmbus/mod.rs, crates/provider-lattice-controller/src/client_cache.rs, crates/secrets-nats-kv/src/main.rs, crates/wash/src/cli/call.rs, crates/wash/src/lib/config.rs
Work in progress. 
Related to issue #3519
In order to check this PR, I build the wash-cli on my local machine with `cargo build --release`. Then I used the locally built wash cli from the rust-hello-world example project with `wash dev`. Finally, I checked the nats connections with the nats cli: `nats server report connections` to verify that nats connections have names.
=> feat(nats): Add names to nats connections

crates/host/src/nats/provider.rs, crates/host/src/wasmbus/ctl.rs, crates/host/src/wasmbus/providers/mod.rs
Turns out we were not using the [`wasmcloud_core::rpc` helper methods](https://github.com/wasmCloud/wasmCloud/blob/main/crates/core/src/rpc.rs#L25-L68) for provider subjects consistently.
=> chore(host): Reference wasmcloud_core::rpc helper methods consistently

crates/provider-http-server/src/address.rs
This commit improves the error message produced by the HTTP server provider when it cannot create a link, printing the error message out via tracing as well as bubbling up to the host.
Note that while the host will still only see the minimal message (which does not show *why*), looking at the host output stream should reveal the cause.
=> feat(providers): improve http server error message

examples/docker/docker-compose-full.yml
docker-compose-full.yaml is actually not full. It only contains half the OTEL stack and configuration-wise not much is working there. When it comes to OTEL, this fix applies exactly what docker-compose-otel.yaml does already (without touching anything else)
I can imagine to take this even further and:
a) question the usefulness of docker-compose-auxiliary.yml / docker-compose-websockets.yml
b) subseqently remove those configs not located in "/config"-folder
c) even question docker-compose-otel.yml (DRY + if you only want to use OTEL, you can opt to not start nats, registry, wasmcloud and wadm)
/
/
Blast radius is restricted to the docker-compose-examples so no one should be harmed in production. Newbies tho get OTEL running faster and with less hassle.
/
/
/
`docker-compose -f …
=> fix(examples): full OTEL-stack in docker-compose-full.yml

crates/wash/src/lib/start/wasmcloud.rs
This commit fixes the windows build suffix that has been used for wash, as we moved from publishing a -pc-windows-msvc version to pc-windows-gnu
Resolves #4485
=> fix(wash): windows build suffix

.github/workflows/wash.yml
CI is doing too much work
- Probably.
- Next release
- Faster CI
- All previous CI
- No longer producing debug info for tests
- Waiting on CI
=> ci(wash): Don't build throwaway files

crates/provider-keyvalue-redis/src/lib.rs, src/bin/keyvalue-redis-provider/wasmcloud.toml
This PR fixes an issue where the default values for the connection manager for Redis didn't work properly for retried connections. Now, by default, the provider will be robust and reconnect to the server whether it could establish a connection at first and it was lost, or if the connection didn't establish from the start. Components will be able to gracefully handle an error for a dropped connection, which will resolve after it retries the connection.
keyvalue-redis 0.30.0 (last release was mistakenly 0.3.0)
=> fix(keyvalue-redis): use default config for connection manager

Cargo.lock, Cargo.toml
I released a new oci-wasm library in conjunction with the oci-client crate release a few weeks ago. Wanted to get those updated here as well so we were picking up off the latest changes
=> chore(deps): Updates to latest OCI dependencies

crates/wash/src/cli/cmd/up.rs, crates/wash/src/cli/down/mod.rs, crates/wash/src/lib/start/wadm.rs, crates/wash/tests/start_wadm.rs
The `wadm.pid` constant was defined twice in the code. This PR removes one of the declarations and centralizes such declarations in the 'config' module.
- Might create conflicts with #4558 as code changes are to similar locations.
None
=> refactor(wash): remove duplicate constant for wadm.pid filename

flake.nix
Using vault-bin instead of vault allows to skip compiling the entirety of Vault when evaluating the flake. This reduces the flake devShell initial evaluation by around 5 minutes with barely any downside (from locally compiling the binary).
None.
I test built stuff like `nix build .#keyvalue-vault-provider-oci`, but I am guessing the Vault binary is mostly used for integration testing. I don't think I can "test" this locally very well.
=> ci(nix): switch from vault to vault-bin package to speed-up flake

crates/wash/tools/deps_check.py, flake.nix
Various elements require wasm-tools to be installed in the devShell. For instance, the wash test `lib::build::component::tests::golang_generate_bindgen_component_multi_world` requires it. However, the flake devShell does not contain it as a dependency, nor does `make deps-check` ensure that it is present.
None. I didn't bother creating an issue but if needed I can create one.
No consumer impact.
Tests such as the one mentioned above no longer fail when running `make test-unit` in the `wash` crate (when using `direnv` and the [provided `.envrc`](https://github.com/wasmCloud/wasmCloud/blob/main/.envrc)).
Ran `make deps-check` without `wasm-tools` to ensure that it triggers and install. Ran the unit tests for `wash` with and without `wasm-tools`, passing and failing respectively.
=> fix: add wasm-tools to dev dependencies for `wash`

crates/wash/src/cli/cmd/dev/mod.rs, crates/wash/src/cli/cmd/dev/session.rs
Wash reads the host ID from the hosts it starts with `dev` from the log file. This is not very nice. Instead, we are passing a key seed to infer the ID the host will use. This avoids having to go through logs.
- #3823
None
- Removed the tests that checked the parsing of the logs.
None
- Ran `wash dev` a couple of times. Validated that the ID in the logs matches the one inferred by the code (by additionally logging it to stdout).
=> fix(wash): pass host key seed to infer host id rather than read from log

.github/actions/install-cached-wash-cli/action.yml, .github/workflows/wash.yml, .github/workflows/wasmcloud.yml
Turns out, if you write exclusion rules, you HAVE to include `matches: all` or else the `!` rule will actually match on all the things.
I tested this out in my fork to confirm https://github.com/brooksmtownsend/wasmCloud/actions/runs/15909932422/job/44874450038?pr=21
This PR will trigger both wash and wasmCloud since the actions change but in later PRs it will be improved.
Resolves https://github.com/wasmCloud/wasmCloud/issues/4600
=> ci: ignore unspecified paths-filter paths

crates/wash/src/bin/wash.rs, crates/wash/src/cli/cmd/dev/mod.rs, crates/wash/src/cli/cmd/dev/session.rs, crates/wash/src/cli/cmd/up.rs, crates/wash/src/cli/completions.rs, crates/wash/src/cli/down/mod.rs, crates/wash/src/cli/keys.rs, crates/wash/src/cli/ui.rs, crates/wash/src/cli/util.rs, crates/wash/src/lib/cli/mod.rs, crates/wash/src/lib/config.rs, crates/wash/src/lib/context/fs.rs, crates/wash/src/lib/drain.rs, crates/wash/src/lib/plugin/mod.rs, crates/wash/tests/wash_up.rs
The current implementation does not really respect best practices on where data should be stored (whether config data, cache data, runtime data, etc). This is an attempt to support best practices using XDG directories on Linux and Mac, and using the standard Windows scheme on Windows. This also slightly refactors the way these directories are accessed from other packages to simplify their usage.
Goal of this PR would be:
- Implement best practices.
- Keep possibility for configuring everything in a fine grained manner as described in the related story.
- Simplify handling on config directories, ensuring they are created upon use.
- Unify the handling of files in the configuration directories a little.
- #4372
I guess next? This is on the Q2 Roadmap in status "Ready for Work".
This might …
=> replace use of `~/.wash` with XDG Base Directory Specification

.github/workflows/release-and-build.yml, .github/workflows/wasmcloud.yml, Dockerfile
This starts by adding a Dockerfile that can be used to build the image with the given binary. I started by copying what we had in wadm and adjusted from there. We can slowly migrate things over, but this removes the image build step from the nix build for now.
Please note that this gets rid of our debian only builds in favor of the wolfi images only. They have been our default for a while now. If desired, we can still publish a `-wolfi` suffixed tag if we want to. This pipeline constantly overwrites a canary tag rather than continuously adding sha tagged versions as well
=> feat(ci): Starts process of moving release pipelines away from Nix

examples/rust/components/http-blobstore/README.md
This is a follow-up to #4632 that corrects the doc links so they do not break the wasmcloud.com build.
=> Correct links in `http-blobstore` example component `README.md`

examples/rust/components/dog-fetcher/Cargo.toml, examples/rust/components/echo-messaging-0-3-0/Cargo.toml, examples/rust/components/echo-messaging/Cargo.toml, examples/rust/components/ferris-says/Cargo.toml, examples/rust/components/http-blobstore/Cargo.toml, examples/rust/components/http-jsonify/Cargo.toml, examples/rust/components/keyvalue-messaging/Cargo.toml, examples/rust/components/sqldb-postgres-query/Cargo.toml, examples/rust/components/wadm-status-receiver/Cargo.toml, examples/rust/components/wash-plugin-rust/Cargo.toml
This PR updates the wit-bindgen version in examples which was causing some pointer misalignment issues.
Fixes #3894
=> chore: update wit-bindgen in rust examples

crates/wash/CHANGELOG.md, crates/wash/src/cli/cmd/dev/mod.rs, crates/wash/tests/wash_dev.rs
This PR adds a --dashboard flag to the wash dev command to enable running washboard (the web UI) alongside the application during local development. This addresses feedback that wash dev should provide a complete "inner development loop" experience including the visual dashboard interface.
Fixes #4129 - wash dev should have an option for standing up washboard (wash ui)
_
This change is additive and backward compatible. Existing users of wash dev will experience no changes to their workflow unless they opt-in to the new `--dashboard` flag or set the `WASH_DEV_DASHBOARD` environment variable. The impact is minimal as it only adds optional functionality without modifying existing behavior.
Added integration test to verify that the UI spins up correctly when the --dashboard flag is used.
- …
=> feat(wash): add dashboard option for dev

Cargo.lock, crates/provider-sqldb-postgres/Cargo.toml, crates/provider-sqldb-postgres/README.md, crates/provider-sqldb-postgres/src/lib.rs
This PR allows folks who aren't already using a server-side load balancing framework like PgBouncer to do some connection pool sharing at the provider layer.
next minor provider-sqldb-postgres
=> feat(sqldb-postgres): support connection pool sharing

crates/host/src/lib.rs, crates/wash/src/lib/wait.rs
Incorrect `provider_ref` was sent to `provider_started` event if it was a file.
Closes #4645 
None
`parse_references` was modified in `crates/host/src/lib.rs:212`
Now it works successfully
```
wash start provider ./bin_ollama_provider.par.gz my-id --host-id NC645VOKJPRD23O7LZH5RFTWP3TRWAXVHY5TUJZW3MXKX5OEJEMKRCL4
Provider [my-id] (ref: [file:///home/pagafonov/projects/kuber-boring/components/ollama_provider/build/bin_ollama_provider.par.gz]) started on host [NC645VOKJPRD23O7LZH5RFTWP3TRWAXVHY5TUJZW3MXKX5OEJEMKRCL4]
```
=> fix(host): start provider from file by CLI

crates/core/src/registry.rs, crates/host/src/lib.rs, crates/host/src/wasmbus/mod.rs
An unfortunate error that led to frustrating failures when enabling `ALLOW_LATEST`, actually not taking effect.
~I've made this fix, but it doesn't fully address the issue and I know where it's coming from. So I'll mark this as draft for now and follow up tomorrow.~
There was an additional step in the host that was necessary to fix which is that if there is not a registry explicitly configured, we should fall back on the provided defaults as given to wasmCloud at startup. Instead of defaulting to the defaults of the `RegistryConfig` struct (e.g. allow_latest: false) we will now fall back to the provided additional CA certs, allow insecure, allow latest, and anonymous auth.
Fixes #4298
=> fix: use allow-latest for allow_latest, default registry config improvement

crates/host/src/wasmbus/mod.rs
This PR fixes an area in the host inventory related to component limits where we were calling `expect` when an option map would do.
v1.9
=> fix(wasmbus): expect when we should've mapped

examples/rust/components/blobby/src/lib.rs
exercising `finish` so the OutgoingValue knows we are done with the stream.
=> blobby: Finish upload stream

Cargo.lock, Cargo.toml, crates/component/Cargo.toml, tests/components/rust/Cargo.lock, tests/components/rust/Cargo.toml
Bump wit-bindgen and wasmcloud-component to 0.3.0 to avoid pointer misalignment issues.
=> chore: bump wasmcloud-component 0.3.0
