wasmCloud/wasmCloud

hack/docker-compose.yml
This adds a local docker-compose configuration for local development.
=> Add docker-compose file for local dev

tests/control.rs
All tests work locally.
Aka... **_works on my machine_**
=> Fixing control interface tests.

.github/workflows/release_amd64.yml, .github/workflows/release_arm64.yml, .github/workflows/rust.yml, build/nfpm.amd64.yaml, build/nfpm.arm64.yaml
This change removes the matrix build in favor of a simple `for` loop. Also updates the branding in our `nfpm` configuration.
=> Fix packaging

crates/wasmcloud-host/src/capability/native_host.rs
On linux the library must be loaded with `RTLD_NOW | RTLD_NODELETE` to fix a SIGSEGV that happens when a thread terminates AFTER a library is unloaded. This has the effect of keeping the library loaded in-memory until the process ends.
Fixes #98
=> Load linux shared libraries with RTLD_NODELETE

Cargo.toml, crates/wasmcloud-host/Cargo.toml, crates/wasmcloud-host/src/actors/actor_host.rs, crates/wasmcloud-host/src/capability/native_host.rs, crates/wasmcloud-host/src/dispatch.rs, crates/wasmcloud-host/src/messagebus/handlers.rs, crates/wasmcloud-host/src/messagebus/rpc_subscription.rs, tests/control.rs, tests/lib.rs
.. and the RPC proxies after a message bus unsubscribe.
=> Closing #103 explicitly terminates actor and provider hosts

Cargo.toml
Version bump for a few merged PRs
Thank you @StuartHarris , @jsoverson , and @snnsnn for contributing to this version 😄
=> 0.15.4 release

build/nfpm.arm64.yaml
:pray: this will _hopefully_ fix the NFPM ARM path issue
=> Fix path for NFPM ARM config

Cargo.toml, crates/wasmcloud-host/Cargo.toml, crates/wasmcloud-host/src/host.rs, crates/wasmcloud-host/src/messagebus/handlers.rs, crates/wasmcloud-host/src/messagebus/mod.rs, samples/bencher/Cargo.toml, tests/common.rs, tests/lib.rs, tests/no_lattice.rs
=> Adds additional queries to host API for lattice cache data

.gitpod.yml
=> Fix docker container URL

.github/workflows/gitpod_docker.yml, .gitpod.Dockerfile
=> Fix docker tags

Cargo.toml, crates/auth-nats-account/Cargo.toml, crates/auth-nats-account/src/lib.rs
=> Adding a NATS account server authorizer implementation

.github/workflows/wasmcloud_docker.yml, .github/workflows/wasmcloud_docker_tag.yml, Dockerfile
The action is set to build and push to both dockerhub and azure.  I figured there was no reason not to keep the history in both places.  Also, I think I think i should add an additional action for when the repo is tagged so we have a tag of the tag as well.
=> Dockerfile + Automation

src/wasmcloud.rs
Fixes #189 
There is a quirk in this PR, I realized that a host can be launched without an rpc connection but with a control interface connection, this allows control interface commands to work but doesn't use NATS for RPCs. I allow this with a `warn` log, if this isn't desired behavior this can be changed.
=> Allow host to launch without nats when manifest is present

Cargo.lock, crates/wasmcloud-host/Cargo.toml, crates/wasmcloud-host/src/dispatch.rs
=> Fixing a runtime panic when guest calls fail

Cargo.lock, Cargo.toml, samples/bencher/Cargo.toml
True story....whoever does the version bump gets credit for all the work that was done.  
I did a really great job here
=> Bump to 0.18.2

Cargo.lock, Cargo.toml, crates/wasmcloud-control-interface/Cargo.toml, crates/wasmcloud-control-interface/src/generated/ctliface.rs, crates/wasmcloud-control-interface/src/lib.rs, crates/wasmcloud-host/Cargo.toml, tests/control.rs
Signed-off-by: Kevin Hoffman <autodidaddict@users.noreply.github.com>
=> Adding actor count to stop actor message

README.md
=> Added powered by webassembly badge

README.md, awesome-wasmcloud/README.md
I wanted to start a list given some of the awesome projects we've seen over the past few weeks.
=> Initial commit of some awesome projects

awesome-wasmcloud/README.md
Thanks to some awesome work by @emmatiza, we've got a great gitpod template!
=> Added emmatiza's gitpod template

LICENSE, README.md, ROADMAP.md
I also fixed a license issue where we didn't have the date set
=> docs(roadmap): Adds a proposed roadmap document for wasmCloud projects

Cargo.toml, examples/echo/main.rs, src/actor/component.rs, src/actor/mod.rs, src/actor/module/mod.rs, src/actor/module/wasmbus.rs, src/capability/logging/discard.rs, src/capability/logging/log.rs, src/capability/logging/mod.rs, src/capability/mod.rs, src/capability/numbergen/mod.rs, src/capability/numbergen/rand.rs, src/lib.rs, src/main.rs, src/runtime.rs, tests/actor_http_log_rng.rs
Rework handler API:
- Remove the generic bounds from `Runtime`, `{Module,Component}Instance` and everything in between
- Remove impls for `()`
- Introduce `Invocation` enums
- Handlers now return a singular level error, rather than "two-dimensional" ones
- `anyhow::Error` is used as a standard error type across the repository (could be changed in the future, but for now standardized Rust errors are still in flux)
=> refactor: rework handler API

src/actor/component.rs, src/actor/mod.rs, src/actor/module/mod.rs, src/actor/module/wasmbus.rs, tests/actor_http_log_rng.rs
Avoid capability checking by default, since host does not have enough context
Unit tests
=> feat: avoid capability checking by default

Cargo.lock, Cargo.toml, tests/actor_compat.rs, tests/actor_http_log_rng.rs, tests/actors/compat-component/foobar-guest/Cargo.toml, tests/actors/compat-component/foobar-guest/src/lib.rs, tests/actors/compat-component/foobar-host/Cargo.toml, tests/actors/compat-component/foobar-host/src/lib.rs, tests/actors/compat-component/foobar/Cargo.toml, tests/actors/compat-component/foobar/src/lib.rs, tests/actors/compat-component/wit/foobar.wit, tests/actors/compat-component/wit/guest.wit, tests/actors/compat-component/wit/host.wit, tests/actors/compat-component/wit/wasmcloud.wit, tests/common/mod.rs
Add a composed component, which wraps the internal `foobar` component with guest-side and host-side compatibility layers
All components are using WASI
`<wasmcloud host> <-> <foobar-host> <-> <foobar> <-> <foobar-guest> <-> <wasmcloud guest>`
This is the chain, which is fully tested in the unit test. Everything uses WASI and I even added a println! to the inner component
Yes, see the `actor-compat-component`
Unit tests
=> test: add a wrapped composed component

src/actor/module/mod.rs
Fixes `tinygo` module actors, this is already used and tested in https://github.com/wasmCloud/wasmcloud-otp, opening PR now, since #300 now depends on https://github.com/rvolosatovs/depit and free from subtree merges, which means rebasing is not a problem anymore
Will be added after #300 is merged (already WIP)
Tested in 0.62 release of OTP
=> fix: call `_start` for tinygo actor modules

.github/workflows/wasmcloud.yml
`--version` flag is not relevant here
This is a CI fix
=> ci: remove redundant `--version` flag in test

README.md
=> Fixed broken README links

Cargo.lock, Cargo.toml
This enables Dependabot to run, note that dependency update is mandatory for this, otherwise dependabot fails updating serde (no idea why)
=> build: explicitly include test-actors in workspace

ADOPTERS.md
Reverts wasmCloud/wasmCloud#327
=> Revert "Update ADOPTERS.md"

OWNERS
After an org maintainer vote, @ricochet was accepted as a new org maintainer. This PR adds her to the list
=> Adds Bailey as an org maintainer

ADOPTERS.md
add Orange to the list of adopters
Signed-off-by: Yann Cardon <yann.cardon@orange.com>
=> add Orange to adopters

.github/actions/install-nix/action.yml, flake.nix
This action should be faster, more reliable and easier to use. We don't need the local cache, since we already have `cachix` and from experience, the local cache only slows things down
Closes https://github.com/wasmCloud/wasmCloud/pull/311
This is a CI change
=> ci: use `nix-installer`

Cargo.lock, Cargo.toml, crates/actor/Cargo.toml, crates/actor/derive/Cargo.toml, crates/actor/derive/src/lib.rs, crates/actor/src/lib.rs, crates/actor/src/module/host.rs, crates/actor/src/module/http.rs, crates/actor/src/module/logging.rs, crates/actor/src/module/mod.rs, crates/actor/src/module/random.rs, crates/host/src/actor/module/wasmbus.rs, flake.nix, tests/actor_http_log_rng.rs, tests/actors/rust/Cargo.lock, tests/actors/rust/Cargo.toml, tests/actors/rust/echo-module/Cargo.toml, tests/actors/rust/echo-module/src/lib.rs, tests/actors/rust/http-log-rng-component/Cargo.toml, tests/actors/rust/http-log-rng-component/src/lib.rs, tests/actors/rust/http-log-rng-module/Cargo.toml, tests/actors/rust/http-log-rng-module/src/lib.rs
This is the first step in addition of a "transitional" module support to `wasmcloud_actor` crate. When `module` feature is enabled, `wasmcloud_actor` relies on legacy wasmbus API. The module-based API mimics functionality exposed by component model-based support, meaning, that switch to components will be a breeze for users.
#317 
- All traits are now good-old `sync`, that may change in the future depeding on how the component model API will shape up, TBD. It seems that `sync` is actually, explicitly, desired
- No direct `wasmbus-rpc` usage in actors
- Fail in builtin execution will result in runtime panic on the actor side, since component model API for these functions does not provide a way to handle errors. That's fine, since users should transition to component model anyway and that's …
=> feat(actor): introduce module support

.devcontainer/devcontainer.json
Adds support for dev containers - allowing for easily pulling in a pre-configured environment to work on wasmcloud
ran the repo & tests within the dev container defined here
=> feat: add devcontainer support

Cargo.lock, flake.lock, tests/actors/rust/Cargo.lock, tests/wasi-adapter/Cargo.lock
Regular dependency update
`cargo test`
=> build: update dependencies

README.md
Quick update to the README to better reflect structure, it's brief on purpose, since we're still breaking things
Closes https://github.com/wasmCloud/wasmCloud/issues/322 (first step)
=> doc: update according to current repo state

.cargo/audit.toml, Cargo.lock, Cargo.toml, crates/host/Cargo.toml, crates/host/src/lib.rs, crates/host/src/wasmbus/config.rs, crates/host/src/wasmbus/mod.rs, garnix.yaml, src/main.rs
#361 
This does not actually handle any lattice commands, just the core functionality and some command parsing
Tested alongside OTP as part of bigger changeset
=> feat: introduce `wasmbus` lattice

crates/host/src/wasmbus/mod.rs, src/main.rs
implement host ping and stop
`wash down --all`
=> feat(wasmbus): implement host ping and stop

crates/host/src/wasmbus/mod.rs
Implement inventory command
~Blocked on #368~
`wash get inventory <host>`
=> feat(wasmbus): implement inventory

OWNERS
@stevelr is moving to emeritus status. Thank you for all your work over the years!
=> Update org maintainer list

crates/host/Cargo.toml, crates/host/src/bindle.rs, crates/host/src/lib.rs, crates/host/src/oci.rs, crates/host/src/wasmbus/event.rs, crates/host/src/wasmbus/mod.rs
Implementation of most of the actor operations
```sh
$ wash start actor wasmcloud.azurecr.io/echo:0.3.4
$ wash call MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5 HttpServer.HandleRequest '{"body":"test","header":{}}'
$ wash inventory get <HOST>
```
Note, that the first actor launch always times out in `wash` - that is due to the fact that in current implementation, the host only returns success once the whole chain of actions has been completed, which involves time-consuming compiling Wasm.
That will be optimized later.
=> feat(wasmbus): implement actor operations

Cargo.lock, Cargo.toml, crates/host/Cargo.toml, crates/host/src/wasmbus/event.rs, crates/host/src/wasmbus/mod.rs
Use structs from `wasmcloud-control-interface` rather than ad-hoc `json!` macro
Closes https://github.com/wasmCloud/wasmCloud/issues/373
Refs https://github.com/wasmCloud/wasmCloud/pull/372#discussion_r1264078707
`wash start actor`, `wash get inventory`, `wash stop actor`
=> refactor(wasmbus): use `wasmcloud-control-interface`

.github/actions/install-nix/action.yml
Use https://github.com/DeterminateSystems/magic-nix-cache and update the nix installer while we're at it
CI
=> ci(nix): use `magic-nix-cache`

.github/ISSUE_TEMPLATE/rfc-template.md, adr/0012-rfc-management.md
This PR adds an ADR to complete #381, committing our RFC management decision as a part of our decision record.
This ADR is deliberatively a little heavy handed to illustrate the desired process to complete RFCs and commit them.
=> [ADR-0012] RFCs are Managed in GitHub and Completed As ADRs

flake.nix
This improves caching efficiency
=> build(nix): ignore irrelevant paths

adr/README.md
This PR updates the main README in the ADR folder to include the latest ADR as I forgot it in the previous PR.
=> docs(adr): add ADR-0012 to ADR README

.github/dependabot.yml
enable dependabot on `tcp-component-command`
=> ci: enable dependabot on `tcp-component-command`

tests/actors/rust/Cargo.toml, tests/actors/rust/builtins-compat-reactor/Cargo.toml, tests/actors/rust/builtins-component-reactor/Cargo.toml, tests/actors/rust/builtins-module-reactor/Cargo.toml, tests/actors/rust/http-compat-command/Cargo.toml, tests/actors/rust/logging-module-command/Cargo.toml, tests/actors/rust/tcp-component-command/Cargo.toml
Small refactoring done in hopes of fixing dependabot updates for this crate
=> build(test-actors): utilize workspace metadata

Cargo.lock, crates/providers/Cargo.lock, tests/actors/rust/Cargo.lock, tests/actors/rust/tcp-component-command/Cargo.lock
Update Rust dependencies throughout the repository
=> build(rust): update dependencies

Cargo.lock
Something in the pipeline failed to update `Cargo.lock` (https://github.com/wasmCloud/wasmCloud/pull/410 ?), which now results in failing CI, since the package in missing from the lock
=> fix(build): add missing `wasmparser` dependency

wit/blobstore/blobstore.wit, wit/messaging/messaging.wit
This makes sure the wasmCloud interface WIT compiles, also remove unused messaging world
=> fix(wit): use correct syntax

Cargo.lock, Cargo.toml, crates/provider-sdk/Cargo.toml, crates/provider-sdk/src/provider_main.rs
This solves a Dependabot warning and removes a dependency we don't need
=> refactor(provider-sdk): remove `atty` dependency

Cargo.lock, Cargo.toml, crates/host/src/local/mod.rs, crates/host/src/wasmbus/mod.rs, crates/runtime/src/actor/component.rs, crates/runtime/src/actor/mod.rs, crates/runtime/src/actor/module/mod.rs, crates/runtime/src/actor/module/wasmbus.rs, crates/runtime/src/capability/builtin.rs, crates/runtime/src/capability/mod.rs, crates/runtime/src/runtime.rs, crates/runtime/tests/runtime.rs, tests/actors/rust/builtins-component-reactor/src/lib.rs, tests/wasmbus.rs
Actor -> Provider linking via `wasmcloud:messaging` interface (interface itself only partially implemented)
Closes https://github.com/wasmCloud/wasmCloud/issues/375
`cargo test`
=> feat(wasmbus): implement actor -> provider linking

crates/runtime/src/actor/component/blobstore.rs, crates/runtime/src/actor/component/bus.rs, crates/runtime/src/actor/component/http.rs, crates/runtime/src/actor/component/keyvalue.rs, crates/runtime/src/actor/component/logging.rs, crates/runtime/src/actor/component/messaging.rs, crates/runtime/src/actor/component/mod.rs, crates/runtime/src/capability/builtin.rs, crates/runtime/src/capability/mod.rs, crates/runtime/src/runtime.rs
- split interface implementations into modules
- add missing `Blobstore` trait placeholder
=> refactor(runtime): split interface implementations into modules

crates/host/src/wasmbus/event.rs, crates/host/src/wasmbus/mod.rs, tests/wasmbus.rs
handle launch commands concurrently
#367 - it could potentially close it, but we still need to do more research about what should/could be parallelized 
This is a blocker for #449 , since without this change starting three providers is just too slow
`cargo test`
=> feat(wasmbus): handle launch commands concurrently

src/main.rs
Avoid panic on invalid arguments
=> fix(bin): do not panic on errors

src/main.rs
`Args` fields should not be `pub`
=> fix(bin): remove unused `pub`

crates/host/src/wasmbus/mod.rs
Generate a friendly name for the host based on a random number.
Names we pulled from a list of friendly or neutral adjectives and nouns suitable for use in public and on hosts/domain names
bring the adjectives and nouns over from https://github.com/wasmCloud/wasmcloud-otp/blob/main/host_core/lib/host_core/namegen.ex
fix: https://github.com/wasmCloud/wasmCloud/issues/491
=> feat: generate host name based on a random number

crates/host/src/wasmbus/mod.rs
fix: https://github.com/wasmCloud/wasmCloud/issues/495
=> avoid fetching actor bytes twice when scaling actor

crates/provider-sdk/Cargo.toml, crates/providers/Cargo.lock, tests/actors/build.rs, tests/providers/build.rs
Without this, providers panic on startup in development profile
fixup #476 
=> fix(provider-sdk): enable `ansi` feature

crates/host/src/wasmbus/mod.rs
Claims need to be deleted in the following cases:
1. stop an actor and instances is empty
2. scale an actor to 0
3. stop provider
related pr: https://github.com/wasmCloud/wasmCloud/pull/510
=> feat: delete claims when actors or providers are stopped

crates/host/src/wasmbus/mod.rs
This reverts commit 31b76fd2754e1962df36340275ad5179576c8d07.
In the context of only a single wasmCloud host, it makes sense to delete claims after a resource stops. However, when more than one wasmCloud host will ever run in a single lattice (which we make no assumptions about) deleting claims could lead to the strange behavior of being unable to verify invocations and claims.
Therefore, claims should remain a cache that is grow-only. I could see value in exposing functionality in `wash` to purge old claims, but for now there isn't much of a reason to worry about the storage of claims.
#532 
=> Revert "feat: delete claims when actors or providers are stopped"

crates/runtime/src/actor/component/mod.rs
When methods of instantiation fail, show all related errors from attempts rather that only the last one.
=> refactor: error message for instantiation failure

crates/host/src/wasmbus/mod.rs
Claims also need to be stored when scale triggers the start of an actor.
https://github.com/wasmCloud/wasmCloud/blob/4e0c5b02b50759c01c2e6689d02342f86d6c5bc7/crates/host/src/wasmbus/mod.rs#L1675-L1683
Storing claims in the `start_actor` function ensures that claims are stored for the newly started actor.
=> store claims when the scale triggers the startup actor

crates/host/src/wasmbus/mod.rs, tests/actors/build.rs
This PR implements invocation verification in terms of validating that the invocation is from a valid issuer, that it hasn't been tampered with or expired, and that the actor is allowed to make / receive that invocation.
Fixes #483 
Added a test for validate_antiforgery to cover each invalid option, as well as showing the happy path.
=> feat(wasmbus)!: validate invocations

adr/0014-detach-ui-from-host.md, adr/README.md
=> Add ADR for detached UI

crates/actor/wit/deps.lock, crates/actor/wit/deps.toml, crates/runtime/wit/deps.lock, crates/runtime/wit/deps.toml
Switch to upstream `wasi:blobstore`
https://github.com/WebAssembly/wasi-blob-store/pull/11 got merged, so switch to upstream
=> build(wit): switch to upstream `wasi:blobstore`

crates/host/Cargo.toml, crates/tracing/src/lib.rs
I'm having dependency issues with wamcloud-host crate in a new project.
```bash
$ cargo build                                                                               101 ↵
Compiling wasmcloud-tracing v0.1.0 (/Users/icebergu/workspace/wasm/wasmcloud/wasmCloud/crates/tracing)
error[E0433]: failed to resolve: use of undeclared crate or module `opentelemetry`
--> /Users/icebergu/workspace/wasm/wasmcloud/wasmCloud/crates/tracing/src/context.rs:7:5
|
7 | use opentelemetry::{
|     ^^^^^^^^^^^^^ use of undeclared crate or module `opentelemetry`
error[E0432]: unresolved import `tracing_opentelemetry`
--> /Users/icebergu/workspace/wasm/wasmcloud/wasmCloud/crates/tracing/src/context.rs:12:5
|
12 | use tracing_opentelemetry::OpenTelemetrySpanExt;
|     ^^^^^^^^^^^^^^^^^^^^^ use of undeclared …
```
=> fix(tracing): pub the context mod only with the otel feature enabled

.github/workflows/wasmcloud.yml, flake.lock, flake.nix
Push multi-arch Docker images tagged by the commit rev on each push to this repo and each workflow dispatch. Tag pushes will be handled later as part of the release process.
just like https://github.com/bytecodealliance/wit-deps/pull/54 https://github.com/bytecodealliance/wit-deps/pull/55
https://github.com/rvolosatovs/wasmCloud/actions/runs/6037286627
https://github.com/rvolosatovs/wasmCloud/pkgs/container/wasmcloud/123726133?tag=0.78.0-rc1
=> ci: setup release process

.github/workflows/wasmcloud.yml
Ensure OCI ref is lowercase https://github.com/wasmCloud/wasmCloud/actions/runs/6039451354/job/16388852264
Fixup #598 
Tried in a fork https://github.com/rvolosatovs/wasmCloud/actions/runs/6039917691
=> ci: ensure that OCI ref is lowercase

.github/workflows/wasmcloud.yml
Current https://wasmcloud.github.io/wasmCloud docs are not very helpful, since they point to documentation of the binary crate, default to much-more-useful `wasmcloud_host`
=> doc: default to `wasmcloud_host` package doc

.github/workflows/wasmcloud.yml
=> ci: login to Azure first

crates/host/src/wasmbus/mod.rs, crates/runtime/src/actor/component/logging.rs, crates/runtime/src/actor/module/mod.rs, crates/runtime/src/capability/builtin.rs
Enable wasi:logging for actors
=> implement wasi:logging for actors

Cargo.lock, Cargo.toml, crates/host/Cargo.toml, crates/host/src/wasmbus/mod.rs, crates/opentelemetry-nats/Cargo.toml, crates/opentelemetry-nats/src/lib.rs, crates/provider-sdk/src/lib.rs, crates/provider-sdk/src/provider.rs, crates/provider-sdk/src/rpc_client.rs, crates/providers/Cargo.lock, crates/providers/Cargo.toml, crates/providers/nats/Cargo.toml, crates/providers/nats/src/bin/nats_messaging.rs, crates/providers/nats/src/lib.rs, crates/tracing/src/context.rs, crates/tracing/src/lib.rs
Parse headers from CTL interface and RPC messages, and publish tracing headers on CTL and RPC responses
Leaving in draft for now, since there's probably a way to avoid making as many allocations as I did. But it does work:
=> fix: attach traces on inbound and outbound messages

crates/host/src/bindle.rs, crates/host/src/lib.rs, crates/host/src/oci.rs, crates/host/src/registry.rs, crates/host/src/wasmbus/config.rs, crates/host/src/wasmbus/mod.rs
Various clean-ups for consistency and clarity
Mostly fixup #547 
`cargo test`
=> refactor(host): clean-up

crates/host/src/lib.rs, crates/host/src/wasmbus/mod.rs
Store claims on fetch, since there is a race condition between writing to bucket and processing the claim put event otherwise
Fixup https://github.com/wasmCloud/wasmCloud/pull/586 mostly
=> fix(wasmbus): store claims on fetch

crates/provider-wit-bindgen/src/lib.rs
Fix determining namespace & package names when dealing with a `world` that only has exports for a provider.
=> fix(provider-wit-bindgen): single export support

.github/workflows/wasmcloud.yml, flake.lock
Provide a build for aarch64 android
https://github.com/wasmCloud/wasmCloud/issues/633
https://github.com/rvolosatovs/nixify/pull/162
Run it on an Android phone
=> build: provide an Android binary

crates/host/src/wasmbus/mod.rs
=> fix(host): proxy SYSTEMROOT to providers on Windows

crates/host/src/wasmbus/mod.rs
In cases where wadm was fairly busy, we started getting errors that the host wasn't acking our scale actor commands (even though it was actually scaling). So I added in some flushing when we send responses so we can be sure that the response actually got sent
=> fix(wasmbus): Flushes clients when responding to ctl requests

Cargo.lock, Cargo.toml, crates/host-sys/Cargo.toml, crates/host-sys/build.rs, crates/host-sys/src/lib.rs
just a first step in adding proper C FFI
#633 
```
cargo build -p wasmcloud-host-sys
cc test.c -o test -lwasmcloud_host_sys -Ltarget/debug/
LD_LIBRARY_PATH=target/debug ./test
```
This showed up as a valid host
test.c:
```c
extern void run_host();
int main(void) {
run_host();
return 0;
}
```
=> feat: add host C FFI bindings

flake.nix
- avoid replacing `/bin` in the container (https://github.com/NixOS/nixpkgs/issues/240919)
- add CA certificates (from nixpkgs directly, please test that this works fine for the use case - they should)
Closes https://github.com/wasmCloud/wasmCloud/issues/655
With the image built by this patchset `rvolosatovs/wasmcloud:0.78.0-rc8`:
-  `apt update && apt install curl` worked just fine
- simple `docker run` worked
@protochron please confirm that this now works as you have expected
=> fix(oci): avoid replacing `/bin`, add CA certs

crates/host/src/wasmbus/mod.rs
This PR carries over a piece of logic from the OTP host that enforces that image references are unique for actors. It's not something that we want to keep forever, but this maintains backwards compatibility with expectations _and_ prevents us from getting into an undesirable state with regards to running multiple actor versions with the same ID.
At this time, I view this solely as a limitation with the way we structure data, so this change will help maintain compatibility _but_ I would like to clarify this in the future by changing the representation of actors running in a host. RFC to follow.
v0.78.0-rc10
=> fix(wasmbus): enforce unique image references for actors

crates/providers/README.md
`git subtree pull --prefix=vendor/capability-providers providers main`
Closes #673 
=> chore: pull in latest `capability-providers`

crates/host/src/wasmbus/mod.rs, src/main.rs
- Always include a timeout for graceful shutdown (e.g. if NATS connection dies, it will never finish)
- Stop if one of the core wasmbus tasks dies
- Flush NATS queues concurrently on shutdown
- Handle `stopped` method errors
build and run, then:
- try starting the host, killing NATS and `^C` - it will shutdown after 10 seconds of trying to gracefully shutdown
- the usual `wash stop host`
=> fix: rework host shutdown

CONTRIBUTING.md
I noticed our CONTRIBUTING.md buries the lede a bit :)
=> docs: move how to contribute sections to the top

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
This PR adds feature and bug issue templates, largely copied from `wash`, to this repository. I wanted to make it easier to file these issues instead of seeing only the RFC template and then bailing.
=> chore: add bug and feature request template

crates/providers/Cargo.toml, tests/actors/rust/Cargo.toml
See https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
Virtual manifests use resolver version 1 by default, but Rust edition 2021 we use defaults to version 2.
Unfortunately, `cargo` is unable to pick the right resolver today, so explicitly set it
https://github.com/wasmCloud/wasmCloud/pull/662#discussion_r1337367938
closes https://github.com/wasmCloud/wasmCloud/issues/713
https://github.com/rust-lang/cargo/pull/12573
https://github.com/rust-lang/cargo/issues/12557
=> build: set resolver to `2`

.github/CODEOWNERS
=> ci: ensure `host-maintainers` maintain everything related to cargo

crates/host/src/wasmbus/mod.rs
This updates the host to gracefully respond to malformed invocations. Currently, if the host fails to decode an invocation, it logs an error and moves on. This leaves RPC clients waiting until the NATS request times out, and doesn't provide any troubleshooting information. Now the host will reply with an error message containing the deserialization error
Resolves https://github.com/wasmCloud/wasmCloud/issues/674
Next
@jordan-rash should be a little more happy :)
Since virtually all clients should be using code-gen to communicate over the lattice, this shouldn't really impact anyone else. But for the brave pioneers who hand-roll invocations, things should be a little easier to debug now
Tested manually:
Before (no response from the host):
```
nats …
```
=> fix(host): return an InvocationResponse when failing to decode an invocation

crates/host/src/wasmbus/mod.rs
This just adds/updates some logs related to processing common control interface commands
=> chore: add some control interface logs

crates/host/src/wasmbus/mod.rs
This just adds some logs related to setting registry credentials
=> chore: add logs related to registry config

crates/host/src/lib.rs, crates/host/src/wasmbus/mod.rs
Resolves https://github.com/wasmCloud/wasmCloud/issues/776
https://github.com/wasmCloud/wasmCloud/issues/776
Next
Users can use a broader set of references to start resources on a host
Added a unit test
=> chore: improve reference parsing

.github/workflows/wasmcloud.yml
See example run https://github.com/wasmCloud/wasmCloud/actions/runs/6614576526/job/17964950149
=> ci: fix `if` conditional for crate release

Cargo.lock, Cargo.toml, crates/host/Cargo.toml, crates/runtime/Cargo.toml
bump version of crates due to Wasmtime update
#784 
0.80.0
=> build: bump crate versions

.github/workflows/wasmcloud-chart.yml, chart/.helmignore, chart/ct.yaml
This cleans up the `wasmcloud-chart` workflow a little bit since the configuration options are shared between the `lint` and `install` validation steps.
=> Make use of chart-testing's --config option in lint and install steps

.github/workflows/wash.yml
Come on GitHub, why isn't this the default?
https://github.com/wasmCloud/wasmCloud/pull/807
=> ci(wash): run wash CI when wash CI changes

.github/CODEOWNERS
=> chore: use wash-maintainers group

flake.nix
This may be used by `cargo doc`
#807 
=> build(nix): do not remove wash README from sandbox

tests/actors/rust/Cargo.toml, tests/actors/rust/builtins-component-reactor/Cargo.toml, tests/actors/rust/builtins-module-reactor/Cargo.toml, tests/actors/rust/foobar-component-command/Cargo.toml, tests/actors/rust/logging-module-command/Cargo.toml, tests/actors/rust/tcp-component-command/Cargo.toml
=> chore: do not use workspace edition/version in tests

crates/wash-lib/README.md
=> fix(wash-lib): correct typo and link in README

crates/wash-cli/src/up/config.rs, examples/golang/actors/http-echo-tinygo/README.md
Now that v0.80.0 is out, bump the version
=> release(wash-cli): wash-cli-v0.22.0

README.md
This PR just changes a couple of high level bullet points to match our website, and add a 3 command quickstart to the README.
=> chore: update README with docs messaging

.github/workflows/wasmcloud-chart.yml
GitHub Container Registry namespaces are required to be in all lowercase, so we can't use the `github.repository_owner` directly.
=> Convert the organization name to lowercase for publishing to ghcr.io

Cargo.lock, Cargo.toml, crates/providers/Cargo.lock, crates/wascap/Cargo.toml, crates/wascap/src/caps.rs, crates/wascap/src/errors.rs, crates/wascap/src/jwt.rs, crates/wascap/src/lib.rs, crates/wascap/src/wasm.rs, crates/wash-lib/src/cli/claims.rs
Enable `clippy::pedantic` in `wascap` and address (or silence with a TODO) all the generated warnings
Since the external API of the crate has a minor change - bump the version and update `wash-lib` usage
=> chore(wascap): address clippy issues

Cargo.lock, Cargo.toml
=> chore: update `wadm` to 0.8

crates/wash-lib/src/context/fs.rs
`wash ctx default <anything>` should not empty out host configuration
#866 
`wash v0.22.0`
this is mainly a q.o.l change.
[round_trip_happy_path](https://github.com/ahmedtadde/wasmCloud/blob/6d5fbb90c896b654af4da9cc46fc7b62c300531e/crates/wash-lib/src/context/fs.rs#L171-L172)
=> fix(washt-ctx): ensure expected behavior when creating/switching context

.github/workflows/wasmcloud.yml
Simplify the binary release script and make sure to publish all binaries
Revert https://github.com/wasmCloud/wasmCloud/pull/907
Revert https://github.com/wasmCloud/wasmCloud/pull/913
it works: https://github.com/rvolosatovs/wasmCloud/actions/runs/6773644063
=> ci(artifacts): use correct, generic paths

flake.nix
Update Debian to https://hub.docker.com/layers/library/debian/12.2-slim/images/sha256-ea5ad531efe1ac11ff69395d032909baf423b8b88e9aade07e11b40b2e5a1338?context=explore
=> build(nix): update Debian image

.github/workflows/wasmcloud.yml
- Add (almost) all crates in the workspace to publish pipeline
- Dry-run publish on all non-tag builds (on tags, we just publish the crate we need)
- Only publish non-RC tags
Closes https://github.com/wasmCloud/wasmCloud/issues/641
=> ci: setup crate publish pipeline

.github/workflows/wasmcloud.yml, flake.nix
- Integrate `wash` into existing OCI release pipeline
- Publish `canary` tags for wasmCloud (for consistency with `wash`)
- Add labels to wasmCloud image (for consistency with `wash`)
- Unlike before, OCI image version label value for `wash` is now taken directly from `Cargo.toml` independent from the git tag
- Remove `wash` binary from wasmCloud OCI image
- Test Debian-based OCI images after build
- Always build Debian-based OCI images
- Always run `docker run` with `--rm`
- Do not override `$PATH` in images
- Fix prerelease check for crate publish
- Fix `wash` release tag match
https://github.com/rvolosatovs/wasmCloud/actions/runs/6789376691
https://github.com/rvolosatovs/wasmCloud/actions/runs/6789374979
https://github.com/rvolosatovs/wasmCloud/actions/runs/6789373032 …
=> ci: publish `wash` OCI images

crates/core/Cargo.toml, crates/provider-sdk/Cargo.toml, crates/tracing/Cargo.toml
Crates missing description cannot be published to crates.io: https://github.com/wasmCloud/wasmCloud/actions/runs/6801435131/job/18492386414
=> chore: add descriptions to crates

crates/opentelemetry-nats/Cargo.toml
https://github.com/wasmCloud/wasmCloud/pull/964
=> chore: document opentelemetry-nats

.github/workflows/artifacthub.yml, .github/workflows/wasmcloud-chart.yml, chart/.helmignore, chart/artifacthub-repo.yml
In order to fulfill the [Best Practices section of CLOMonitor.io](https://clomonitor.io/projects/cncf/wasm-cloud#wasmcloud_best_practices), we need to publish the `wasmcloud-chart` on ArtifactHub (and link the ArtifactHub.io badge in our README once that's done).
This implements a pipeline that allows us to publish the [ArtifactHub.io Metadata file](https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml) and work towards [Verified Publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher) while also helping us with [Official status](https://artifacthub.io/docs/topics/repositories/#official-status).
=> Add configuration and pipeline to publish ArtifactHub Metadata file for wasmcloud helm chart

README.md
Adds [![Artifact Hub](https://img.shields.io/endpoint?url=https://artifacthub.io/badge/repository/wasmcloud-chart)](https://artifacthub.io/packages/search?repo=wasmcloud-chart) for [`wasmcloud-chart`](https://ghcr.io/wasmcloud/wasmcloud-chart) in the README for [CLOMonitor](https://clomonitor.io/projects/cncf/wasm-cloud#wasmcloud_best_practices)
=> Add ArtifactHub.io badge to README

crates/core/src/chunking.rs, crates/core/src/lib.rs, crates/core/src/logging.rs
Address clippy issues and enable stricter linting
#973 #929
=> refactor(core): address clippy issues

crates/tracing/src/context.rs, crates/tracing/src/lib.rs
Enable stricter linting, fix issues
=> chore(tracing): address clippy warnings

crates/provider-wit-bindgen/Cargo.toml
We need to be able to publish this crate
=> chore(provider-wit-bindgen): allow publishing crate

crates/provider-wit-bindgen/src/lib.rs
WIT can only represent maps as `list<tuple<K,V>>`, which we refer to as "WIT-ified maps" in the codebase.
Up until now, WIT-ified maps were not explicitly supported by provider-wit-bindgen. This means that these structures were passed through *as-is*, expecting that the code on the other end also expects to deal with WIT-ified maps (accepting a list, instead of a proper map).
Legacy (smithy) interfaces use *real* maps (simplest of which being a HashMap), and as such the legacy interfaces (like http-client) can't use code that returns list parading as a map.
This commit adds support for WIT-ified maps, converting them during the bindgen process to `std::collections::HashMap`s
=> feat(bindgen): support witified maps

flake.lock, flake.nix
This fixes the Darwin host builds.
Also update deps, while we're at it
=> build(nix): fix Darwin host builds

chart/Chart.yaml
To release a new version of the `wasmcloud-chart` with a SecurityContext that meets the Pod Security Standards `Restricted` profile added in https://github.com/wasmCloud/wasmCloud/pull/984
#978
=> Bump wasmcloud-chart version to 0.7.1

Cargo.lock, Cargo.toml, crates/provider-sdk/src/provider.rs, crates/provider-sdk/src/rpc_client.rs, crates/providers/Cargo.lock, crates/providers/Cargo.toml, crates/providers/nats/src/bin/nats_messaging.rs, crates/wash-lib/src/capture.rs, tests/wasmbus.rs
Update `async-nats` to latest release
This unblocks #724  (or at least it should)
=> build: update `async-nats` to 0.33

.cargo/audit.toml
Extracted from #979 
Follow-up on #1003
=> chore: remove `cargo audit` exclusions

crates/wash-cli/tests/common/mod.rs, crates/wash-cli/tests/wash_call.rs, crates/wash-cli/tests/wash_up.rs
This commit adds a test to ensure specifying labels via wash up works
=> test(wash-cli): add a test for wash up labels

Cargo.lock, crates/control-interface/Cargo.toml
https://github.com/wasmCloud/wasmCloud/actions/runs/6880738981/job/18716369864?pr=1019
=> build: update `wasmcloud-control-interface`

.github/actions/install-nix/action.yml
=> ci: update Nix install action

.github/workflows/update.yml
Update the nix flake update action. Most importantly the update action now uses the official https://github.com/actions/create-github-app-token
Unfortunately, the action still fails to run in this repo, due to invalid GitHub App configuration. It appears that the GitHub App is not installed for this repository:
https://github.com/wasmCloud/wasmCloud/actions/runs/6932414237/job/18856290231 (#1046)
```
owner and repositories not set, creating token for the current repository ("wasmCloud")
Failed to create token for "wasmCloud" (attempt 1): Not Found
Failed to create token for "wasmCloud" (attempt 2): Not Found
Failed to create token for "wasmCloud" (attempt 3): Not Found
Failed to create token for "wasmCloud" (attempt 4): Not Found
RequestError [HttpError]: Not Found
at …
```
=> ci: update Nix update action

Cargo.lock, Cargo.toml, crates/providers/Cargo.lock
Since [wadm](https://github.com/wasmCloud/wadm) is located outside the workspace, pin to a git rev to fix the recursive dependency until https://github.com/wasmCloud/wadm/issues/219 is addressed
Until then users will be able to install `wash-cli` via
```
cargo install wash-cli --git https://github.com/wasmcloud/wasmcloud
```
Do note that this will block further publishes of `wash-cli` to crates.io until https://github.com/wasmCloud/wadm/issues/219 is done and dep updated here, which is a good thing - we don't want to publish broken crates
Closes https://github.com/wasmCloud/wasmCloud/issues/1038
Ref https://github.com/wasmCloud/wadm/pull/218
Ref https://github.com/wasmCloud/wadm/issues/219
```
cargo install wash-cli --git https://github.com/rvolosatovs/wasmcloud --branch fix/update-wadm …
```
=> build: update `wadm` to 0.9

Cargo.lock, crates/wash-cli/Cargo.toml
Bump wash version for release. Please verify that that's indeed a patch bump.
#1038
=> build: bump wash to 0.24.0

Cargo.toml
=> chore: pin workspace crates to minor

Cargo.lock, Cargo.toml, crates/provider-sdk/Cargo.toml
We need this one to release `wash-cli`
```
error[E0308]: mismatched types
--> src/call.rs:356:13
|
355 |         RpcClient::new(
|         -------------- arguments to this function are incorrect
356 |             nc,
|             ^^ expected `async_nats::client::Client`, found `async_nats::Client`
|
= note: `async_nats::Client` and `async_nats::client::Client` have similar names, but are actually distinct types
note: `async_nats::Client` is defined in crate `async_nats`
--> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-nats-0.33.0/src/client.rs:52:1
|
52  | pub struct Client {
| ^^^^^^^^^^^^^^^^^
note: `async_nats::client::Client` is defined in crate `async_nats`
--> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-nats-0.31.0/src/client.rs …
```
=> chore: bump `provider-sdk` to 0.2.0

crates/wash-cli/README.md
This PR just adjusts the brew install command to include the tap
=> chore(wash): update brew install command

Cargo.lock, crates/wash-cli/Cargo.toml, flake.lock
Fix
```
$ codesign -v ./wash-aarch64-apple-darwin 
./wash-aarch64-apple-darwin: invalid signature (code or signature have been modified)
In architecture: arm64
```
Bump wash for a new release
Undo https://github.com/rvolosatovs/nixify/pull/178 (https://github.com/rvolosatovs/nixify/pull/190)
I've removed this mistakenly thinking that https://github.com/ipetkov/crane/pull/418 (fixing https://github.com/ipetkov/crane/issues/417) has landed in the crane release we're using, but apparently it has not, which resurfaced this issue, which we have fixed a while ago already before.
=> fix: aarch64 darwin codesign

adr/0015-actor-autoscaling.md, adr/README.md
Fixes #696 
This ADR closes out the autoscaling RFC. I should've submitted this a bit ago, but here we are!
=> chore(ADR-0015): add actor autoscaling RFC

crates/wash-cli/src/call.rs, crates/wash-lib/src/cli/mod.rs, crates/wash-lib/src/config.rs
=> chore: replace broken URLs

tests/wasmbus.rs
This updates the wasmbus tests to use separate CTL and RPC NATS connections
I also removed a TODO around waiting for an event after starting an actor
Resolves https://github.com/wasmCloud/wasmCloud/issues/520 
N/A
N/A
Yes.
=> chore: use separate CTL and RPC NATS connections in test

crates/wash-lib/src/app.rs
In the absence of a client library provided by wadm itself, I've started using `wash-lib` for this purpose, but I noticed that [`model.status` operation](https://github.com/wasmCloud/wadm/blob/dbe3c284dd3021b79653d776ddf63ee09b484928/src/server/mod.rs#L188-L198) isn't currently supported, so I thought I'd add it.
=> feat(wash-lib)!: Add support for model.status wadm operation in wash-lib

Cargo.lock, Cargo.toml, crates/wash-lib/Cargo.toml, flake.lock, flake.nix
This revs to the latest adapters on the pre-release of wasmtime 16.
=> Use latest wasmtime 16 adapters

Cargo.lock, Cargo.toml, crates/providers/Cargo.lock, flake.lock, flake.nix, tests/actors/rust/Cargo.lock
Ref https://github.com/wasmCloud/wasmcloud-component-adapters/pull/18
=> build(rust): update dependencies (incl wasmtime 16)

Cargo.lock, crates/providers/Cargo.lock, tests/actors/rust/Cargo.lock
Run `cargo update` in all workspaces
=> chore: update Rust dependencies

Cargo.lock
Updating cargo.lock for our wash-cli binary
Missed this in https://github.com/wasmCloud/wasmCloud/pull/1251
wash-cli 0.25.0
=> chore: update main Cargo.lock

Cargo.lock, Cargo.toml, crates/providers/Cargo.lock, crates/providers/blobstore-s3/Cargo.toml, crates/wash-cli/Cargo.toml, crates/wash-cli/src/bin/wash.rs, crates/wash-cli/src/call.rs, crates/wash-cli/src/common/registry_cmd.rs, crates/wash-cli/src/ctx/mod.rs, crates/wash-cli/src/down/mod.rs, crates/wash-cli/src/par.rs, crates/wash-cli/src/up/mod.rs, crates/wash-lib/Cargo.toml, crates/wash-lib/src/build.rs, crates/wash-lib/src/cli/claims.rs, crates/wash-lib/src/cli/mod.rs, crates/wash-lib/src/start/mod.rs, crates/wash-lib/src/start/nats.rs, crates/wash-lib/src/start/wadm.rs, crates/wash-lib/src/start/wasmcloud.rs
Resolves https://github.com/wasmCloud/wasmCloud/issues/994
=> chore: replace env_logger with tracing_subscriber

crates/wash-lib/src/build.rs
This commit fixes a tiny typo that was left out of a preivous PR (#1246)
=> fix(wash): fix spelling mistake from previous PR

.github/CODEOWNERS
Add @connorsmith256 to the provider-wit-bindgen crate owners
=> chore: add connor to provider-wit-bindgen crate owners

Cargo.lock, tests/actors/rust/Cargo.lock
Bumps deps together
Obviates https://github.com/wasmCloud/wasmCloud/pull/1281, https://github.com/wasmCloud/wasmCloud/pull/1279, https://github.com/wasmCloud/wasmCloud/pull/1297, https://github.com/wasmCloud/wasmCloud/pull/1285
=> chore: update deps

src/main.rs
Adopt kebab-case for service name in tracing to make it easier for downstream consumers.
=> chore: Normalize wasmCloud Host as wasmcloud-host for tracing

Cargo.lock, crates/providers/Cargo.lock, crates/tracing/Cargo.toml, crates/tracing/src/lib.rs
Standardizing on using kebab-case makes it easier for downstream consumers to operate on the names of services
=> chore: Normalize service.names to use kebab-case

adr/0016-rename-lattice-prefix.md, adr/README.md
Adds the ADR for renaming lattice prefix to lattice. Small change, but worth recording and closing out that RFC
Closes #1221 
N/A
=> adr(0016): rename lattice prefix

crates/control-interface/src/lib.rs
https://github.com/wasmCloud/wasmCloud/pull/1381 was able to be merged with a compilation issue. This fixes it
=> fix(control-interface): fix compilation

examples/docker/README.md, examples/docker/docker-compose-websockets.yml, examples/docker/nats.websocket.conf
Adds a docker example with a websocket enabled
Semi-related to #1377
=> feat(docker): add websocket example

washboard-ui/packages/lattice-client-core/src/lattice-client.ts
Update lattice topic to subscribe for all new event topics
Related to #1091
=> feat(washboard): fix lattice topic

crates/wash-lib/src/build.rs
The child process we spawn to handle the custom build command was inheriting the parent's stdout/stderr pipes, causing output from the child to appear unexpectedly in the output from wash. This updates the child's output to go to pipes, so we can control the output
Resolves https://github.com/wasmCloud/wasmCloud/issues/1400
Next
Users can safely pipe JSON output from wash again
Tested using the branch from https://github.com/wasmCloud/wasmCloud/pull/1399
Success:
```
~/wasmcloud/wasmcloud/target/debug/wash build
Actor built and signed and can be found at "/Users/connor/Documents/wasmCloud/wasmCloud/examples/python/actors/http-hello-world/build/http_hello_world_s.wasm"
```
```
~/wasmcloud/wasmcloud/target/debug/wash build -o json
{
"signed": true,
"success": true,
"built": true, …
```
=> fix(wash-lib): pipe child output of custom build command to parent

crates/providers/http-server/src/settings.rs, crates/providers/kv-redis/src/bin/kvredis.rs, crates/providers/lattice-controller/src/lib.rs, crates/providers/messaging-nats/src/lib.rs
Something must have gone wrong with a rebase because I definitely fixed this before
=> fix(providers): Fixes duplicate test imports

crates/provider-sdk/src/rpc_client.rs
This mirrors https://github.com/wasmCloud/wasmCloud/pull/1439. Just pushing to my fork to see if I get the same error in CI
=> fix(provider-sdk): use send_request to handle request timeout

crates/wash-cli/src/common/scale_cmd.rs, crates/wash-lib/src/cli/scale.rs
A simple change that makes the message for unlimited a little bit nicer
=> feat(wash): Better scale message

examples/docker/config/grafana-datasources.yaml, examples/docker/config/loki.yaml, examples/docker/config/otel-collector.yaml, examples/docker/config/prometheus.yaml, examples/docker/config/tempo.yaml, examples/docker/docker-compose-otel.yml
In #1431, @brooksmtownsend mentioned that it would be nice to have a [standalone observability setup for docker compose](https://github.com/wasmCloud/wasmCloud/pull/1431#pullrequestreview-1871005201), which I thought was a great idea, so this implements that.
This does duplicate some of the changes made in #1431, and while working through this I started wondering if we should consider using the [Docker Compose `include`](https://docs.docker.com/compose/multiple-compose-files/include/) directive to de-duplicate some of this configuration from the other compose files where we'd like to have a full observability setup.
The downside of doing so would be that we'd essentially pin the required Docker for Desktop version to [4.22.0 and newer, which was released August …
=> feat(examples): Add standalone docker compose setup for OTEL

crates/wash-cli/src/up/config.rs
Bumps the wasmCloud and wadm version in `wash` for release
wash-cli v0.26.0
=> feat(wash-cli)!: update wasmcloud 0.82, wadm 0.10

adr/0016-rename-lattice-prefix.md, adr/0017-define-interfaces-using-WIT.md, adr/README.md
This commit adds ADR 0017, which records the decision to define interfaces using WIT instead of Smithy going forward in the wasmCloud host, providers and actors.
Resolves #336
=> docs(adr): record ADR 0017

crates/host/src/lib.rs, crates/host/src/metrics.rs, crates/host/src/wasmbus/mod.rs, crates/tracing/Cargo.toml, crates/tracing/src/lib.rs, crates/tracing/src/metrics.rs, examples/docker/README.md, examples/docker/docker-compose-auxiliary.yml, examples/docker/docker-compose-full.yml, examples/docker/grafana-datasources.yaml, examples/docker/otel-collector.yaml, examples/docker/prometheus.yml, src/main.rs
In support of #664, this lays the initial foundation to be able to add support for various metrics outlined in the RFC for the wasmcloud-host.
It's worth mentioning that the goal of this PR is not to add comprehensive coverage of all the possible metrics outlined in #664, but instead lay the foundation to allow anyone to come in and add them as it makes sense.
=> feat: Add initial support for metrics

adr/0018-otel-metrics.md, adr/README.md, adr/template.md
This commit adds ADR 0018, which records the decision to implement OTEL-compliant metrics for the wasmCloud host.
Resolves #664
=> docs(adr): record ADR 0018

Cargo.lock, Cargo.toml, crates/providers/Cargo.lock, crates/runtime/Cargo.toml, crates/runtime/src/actor/component/http.rs, crates/runtime/src/actor/component/logging.rs, crates/runtime/src/actor/component/mod.rs, crates/runtime/src/actor/module/mod.rs, crates/runtime/src/capability/builtin.rs, crates/runtime/tests/runtime.rs
yay, lists and records
Doing this in `main` is actually too much work due to the `guest` bindings
=> Wasmtime 18 and composite type reflection in polyfills

crates/control-interface/src/broker.rs, crates/control-interface/src/lib.rs, crates/control-interface/src/types.rs, crates/host/src/wasmbus/event.rs, crates/host/src/wasmbus/mod.rs, tests/common/mod.rs, tests/wasmbus.rs
This is the first in a set of changes to move over to named config. It is not technically complete as you essentially have to name your config the same as the actor ID. I did this purposefully so as to not have a PR of doom with all the changes. The next PR will be adding named config to the scale command, then support for named config and providers in another PR after that
=> feat(ctl)!: Changes config topic to be for named config

crates/runtime/src/actor/component/mod.rs
=> feat(runtime): record polyfilled component imports 

Cargo.lock, Cargo.toml, crates/control-interface/src/lib.rs, crates/test-util/Cargo.toml, crates/test-util/src/actor.rs, crates/test-util/src/host.rs, crates/test-util/src/lattice/config.rs, crates/test-util/src/lattice/link.rs, crates/test-util/src/lattice/mod.rs, crates/test-util/src/lib.rs, crates/test-util/src/provider.rs, tests/common/minio.rs, tests/common/mod.rs, tests/common/nats.rs, tests/common/redis.rs, tests/common/vault.rs, tests/kv-redis.rs
This commit adds a `wasmcloud-test-util` crate, which contains utilities for testing wasmCloud hosts, providers, and actors locally
=> feat(tests): add wasmcloud-test-util crate

crates/control-interface/src/lib.rs, crates/control-interface/src/types.rs, crates/host/src/wasmbus/mod.rs, crates/test-util/src/actor.rs, crates/test-util/src/provider.rs
This PR tackles a large refactor to better wrap errors and responses for the control interface. After #1108 our topics are much more predictable, but it still remained difficult to differentiate between protocol errors, deserialization errors, and control interface handling errors. This PR makes this _much_ easier to do by more strongly typing handlers in the host and the control interface, so as a user you can tell the difference between these issues.
Note that a good bit of the handlers use helpers like `CtlResponse::success()` or return `CtlResponse<()>`, which is because of the generic type. Even if we return `None` as a response, we still need to "type" it just in case it was a Some. This works pretty well though.
This is based off of #1575 and moved into its own PR because it's …
=> feat(control-interface)!: wrap all operations in CtlResponse

crates/host/src/wasmbus/mod.rs
fix wRPC usage:
- don't spoof function call responses (this potentially may cause logical errors in the application, which is very dangerous)
- ensure parameters are transmitted fully before returning
=> fix(wasmbus): correctly invoke custom functions

Cargo.lock, Cargo.toml, crates/host/Cargo.toml, crates/host/src/wasmbus/mod.rs, crates/runtime/src/actor/component/blobstore.rs, crates/runtime/src/actor/component/keyvalue.rs, crates/runtime/src/capability/builtin.rs, crates/runtime/src/capability/mod.rs, crates/runtime/src/capability/provider/mem/blobstore.rs, crates/runtime/src/capability/provider/mem/keyvalue.rs, crates/runtime/src/io.rs, tests/actors/rust/builtins-component-reactor/src/lib.rs
No tests yet, let's get providers working first and then use the existing test bench for this
=> feat(host): switch to `wrpc:{keyvalue,blobstore}`

crates/host/src/wasmbus/mod.rs
First step in getting incoming HTTP (and others) working - opening this PR to avoid merge conflicts later, since it includes pretty big set of changes
=> feat: begin incoming wRPC invocation implementation

Cargo.lock, Cargo.toml, crates/providers/Cargo.lock, crates/runtime/src/actor/component/blobstore.rs, crates/runtime/src/actor/component/keyvalue.rs, crates/runtime/src/capability/provider/mem/blobstore.rs, crates/runtime/src/capability/provider/mem/keyvalue.rs, crates/runtime/src/io.rs, tests/actors/rust/wrpc-pinger-component/src/lib.rs, tests/wrpc.rs
See https://github.com/rvolosatovs/wrpc/commit/7fd68ab80bf1f962f8cae9637ed70a527dff0ed2
=> feat: improve byte stream efficiency

crates/runtime/src/runtime.rs
This leads to significant performance increases on Linux and brings it up to the same performance levels as other operating systems. Please note that I explicitly did not expose any of these knobs directly in the host yet as it is really finnicky to tweak properly without requesting too much memory. I'd really like to sit down with some of the wasmtime folks before exposing this to users and see if we can dynamically figure out what these numbers should be. For now, these seem to be fairly sensible defaults
=> feat(runtime): Switches runtime config to use a pooling allocator

crates/host/src/metrics.rs, crates/host/src/wasmbus/mod.rs
This PR refactors a bit of the invocation handling code to better slot metrics tracking within the invocation of a component.
Initial PR #1602
=> chore(host): refactor component invocation tracking

performance.md
Adds a new markdown doc describing some of the testing we've done around wasmcloud performance
=> docs(*): Adds performance document

crates/core/src/lattice.rs
Doesn't look like `LatticeTargetId` was in use
=> fix: remove LatticeTargetId

crates/host/src/wasmbus/mod.rs
This PR refactors the component specification `links` parameter from a nested hashmap designed for component import lookups to a `Vec<InterfaceLinkDefinition>` which allows for storing the entirety of the link and (somewhat) easier lookups. It's less efficient than a map/set structure at lookups, but the only way to use a hashset like before would be to provide a very strange `Hash,Eq` impl that asserts links are equal when they are truly not.Instead, I opt to translate the list of links in a component specification into the efficient lookup structure that a component needs when the component starts or the spec updates. 
This PR also ensures we're storing component specifications for providers, supporting putting links before a …
=> feat(host)!: refactor component spec, deliver links to providers

.github/CODEOWNERS
=> chore: update CODEOWNERS for provider bindgen macro

crates/tracing/src/lib.rs, crates/tracing/src/metrics.rs
This PR fixes a few issues with the tracing crate compiling for release with the `otel` flag.
=> fix(tracing): fix compilation issue in tracing

crates/tracing/src/metrics.rs
this fixes just two more lints
=> fix(tracing): unused metrics functions

crates/wash-cli/src/up/config.rs
This PR bumps the version of wasmCloud in wash-cli to v1.0.0-alpha.2 to bring in the latest bug fixes and improvements, setting up wash for a release.
wash-cli v1.0.0-alpha.2
=> chore(wash-cli): update wasmcloud to v1.0.0-alpha.2

crates/host/src/wasmbus/mod.rs
This fixes an issue where if you add a new custom interface to an actor when updating it, it would fail to have the imports in place
=> fix(host): Recreates polyfill imports on update

.github/actions/install-nix/action.yml, .github/dependabot.yml
Update Nix actions. Added `.github/actions` to dependabot explicitly, hopefully this will make it update the in-tree actions as well
=> ci: update Nix actions

.gitignore, Cargo.lock, Cargo.toml, crates/runtime/Cargo.toml, crates/wascap/Cargo.toml, crates/wash-cli/Cargo.toml
Remove unused dependencies from the workspace
=> chore: remove unused dependencies

.github/dependabot.yml
Set in-tree action paths correctly, such that dependabot could manage them
=> ci: fix in-tree action dependabot paths

Cargo.lock, Cargo.toml, crates/actor/src/lib.rs, crates/runtime/Cargo.toml, crates/runtime/src/actor/component/blobstore.rs, crates/runtime/src/actor/component/http.rs, crates/runtime/src/actor/component/keyvalue.rs, crates/runtime/src/actor/component/mod.rs, crates/runtime/src/capability/mod.rs, tests/actors/rust/Cargo.lock, tests/actors/rust/builtins-component-reactor/src/lib.rs, tests/actors/rust/interfaces-reactor/src/http.rs
Update to wasmtime 19
https://github.com/wasmCloud/wasmcloud-component-adapters/pull/21
https://github.com/bytecodealliance/wasmtime/pull/7905
blocked on:
#1736 
#1723
=> build: update to wasmtime 19

crates/provider-blobstore-fs/src/lib.rs
Simplify the file stream implementation
=> refactor: simplify `blobstore-fs` reading

.github/workflows/wasmcloud.yml
setup `provider-wit-bindgen` crate family release pipeline
=> ci: setup `provider-wit-bindgen` crate family release pipeline

Cargo.lock, Cargo.toml, crates/core/src/wrpc.rs, crates/provider-blobstore-fs/Cargo.toml, crates/provider-blobstore-fs/src/lib.rs, crates/provider-blobstore-s3/Cargo.toml, crates/provider-blobstore-s3/src/lib.rs, crates/provider-http-client/Cargo.toml, crates/provider-http-client/src/lib.rs, crates/provider-keyvalue-redis/Cargo.toml, crates/provider-keyvalue-redis/src/lib.rs, crates/provider-keyvalue-vault/Cargo.toml, crates/provider-keyvalue-vault/src/lib.rs, crates/provider-sdk/Cargo.toml, crates/provider-sdk/src/interfaces/blobstore.rs, crates/provider-sdk/src/interfaces/http.rs, crates/provider-sdk/src/interfaces/keyvalue.rs, crates/provider-sdk/src/interfaces/mod.rs, crates/provider-sdk/src/lib.rs, src/bin/blobstore-fs/main.rs, src/bin/blobstore-s3/main.rs, src/bin/http-client/main.rs, src/bin/http-server/main.rs, src/bin/keyvalue-redis/main.rs, src/bin/keyvalue-vault/main.rs
Replace boilerplate by nicer-to-use traits
Closes https://github.com/wasmCloud/wasmCloud/issues/1756
=> feat: provider interface SDK

.github/workflows/wasmcloud.yml, Cargo.lock, Cargo.toml, crates/control-interface/src/broker.rs, crates/control-interface/src/client.rs, crates/core/Cargo.toml, crates/core/src/lib.rs, crates/host/src/wasmbus/mod.rs, crates/wash-cli/Cargo.toml, crates/wash-lib/Cargo.toml
This should be the final breaking change of the API and it will require a two phased rollout. I'll need to cut new core and host versions first and then update wash to use the new host for tests.
=> feat(*)!: Adds version to control API

src/main.rs
Tiny PR to document the environment variable you can use for labels.
next wasmCloud
=> chore: document environment var for labels

crates/host/src/wasmbus/mod.rs
This PR fixes an issue where previously we were only considering links where the provider ID was the source. This does mean we need to iterate through every link to find the ones that are related to the provider, which we may be able to do more efficiently in the future with different data structures. Totally open to ideas there.
This also cleans up the logic a bit with a stream that uses `filter_map`.
next alpha/rc of wasmcloud
If anyone experiences this now, the fix is just to re-put any target links that your provider needs after it starts.
=> fix(host): deliver target links to started provider

crates/test-util/src/host.rs, tests/config.rs, tests/interfaces.rs, tests/policy.rs
This commit adds a basic test for an always-deny policy that ensures starting providers and actors fails.
=> test(policy): add a test for always deny policy

Cargo.lock, Cargo.toml
This PR bumps to 1.0.0-alpha.5 for release after #1796.
=> chore(host): bump to v1.0.0-alpha.5

crates/provider-sdk/src/provider.rs, crates/provider-wit-bindgen-macro/src/lib.rs
This commit adds tracing information (if provided) to the wRPC client when creating it manually from inside a provider (and when using an `InvocationHandler`).
=> feat(providers): add trace context to wrpc client

crates/wash-cli/src/common/registry_cmd.rs
This commit fixes test failures with wash pull & push within `wash-cli`
=> fix(wash-cli): wash pull/push test failures

Cargo.lock, crates/control-interface/Cargo.toml
This PR bumps the control interface library to 1.0.0-alpha.3 to release the changes to scale component.
=> chore(control-interface): bump v1.0.0-alpha.3

crates/host/src/wasmbus/mod.rs
This is a fix that ensures each component has its own set of link name targets. Before this, it was sharing the whole set of link names between all running component instances (of each individual component).
=> fix(host): Don't clone targets with handlers

Cargo.lock, crates/host/src/wasmbus/event.rs, crates/wash-cli/Cargo.toml, crates/wash-cli/src/ctl/output.rs, crates/wash-cli/src/up/config.rs, crates/wash-cli/tests/common/mod.rs, crates/wash-cli/tests/wash_get.rs, crates/wash-cli/tests/wash_scale.rs, crates/wash-cli/tests/wash_start.rs, crates/wash-cli/tests/wash_update.rs, crates/wash-lib/Cargo.toml, crates/wash-lib/src/actor.rs, crates/wash-lib/src/cli/start.rs, crates/wash-lib/src/cli/stop.rs, crates/wash-lib/src/cli/update.rs, crates/wash-lib/src/parser/mod.rs, crates/wash-lib/src/wait.rs, examples/security/README.md
This PR renames ctl actor to component for wash. This is a protocol change with the control interface hence the reason for the new host version and finally going back to pinning the control interface to the workspace.
=> chore(wash)!: rename ctl actor to component

crates/host/src/wasmbus/mod.rs
This PR fixes a hole in one of our common operations, scale component. There are two things that this PR addresses:
1. When scaling a component that you've previously stopped on all hosts to a new image reference, the component will update to the new image reference
1. When scaling a component that's currently running to a new level of scale, the host will scale the currently running component to the specified scale WITHOUT updating the image reference.
This primarily fixes a particularly annoying issue where you're trying to just update a component that you ran previously. As a secondary aspect we now properly enforce the scale operation being something that's meant to declaratively change the scale of a component, not something that supports upgrades.
wasmCloud 1.0.0-rc.1
=> fix(host): warn scaling with different imageref

examples/rust/components/http-jsonify/src/lib.rs
This commit fixes the use of `IncomingBody` and slightly simplifies the buffer shinking.
=> fix(examples): http-jsonify stream usage

.github/workflows/examples-components.yml
This commit fixes a bug in CI where `wash push` required configuration to be specified.
=> fix(ci): specify wasmcloud.toml when doing wash push

.github/workflows/wasmcloud.yml
Fix typo
Originally discovered in #1629
=> ci: use correct blobstore provider keys

.github/workflows/examples-components.yml
=> fix(ci): use wash push in a single line

crates/test-util/src/component.rs, crates/test-util/src/lib.rs, tests/config.rs, tests/interfaces.rs, tests/policy.rs
=> refactor(test-util)!: replace actor with component

.github/workflows/examples-components.yml
=> fix(ci): branch prefix on example component publish

.github/workflows/examples-components.yml
=> fix(ci): registry push creds for examples

crates/provider-http-server/src/lib.rs
This commit implements OTEL tracing for the HTTP server provider in order to enable telemetry for provider -> component calls.
=> feat(providers): implement OTEL tracing for HTTP server provider

.github/workflows/examples-components.yml
=> fix(ci): secret name for AzureCR examples publish

examples/golang/components/http-echo-tinygo/wadm.yaml, examples/rust/components/blobby/wadm.yaml
This PR updates the remaining wadm manifests in this repository to match the format expected for 1.0.
=> chore: update example wadms for 1.0 format

Cargo.lock, Cargo.toml, crates/provider-archive/Cargo.toml
This PR bumps `provider-archive` to include the breaking changes to remove capability claims.
provider-archive v0.10.0
=> bump(provider-archive): v0.10.0

Cargo.lock, Cargo.toml, crates/wash-cli/Cargo.toml, crates/wash-cli/src/up/config.rs
This PR bumps wadm and prepares a wash alpha 3 release.
wash-cli v0.27.0-alpha.3
=> chore/wash cli 0.27.0 alpha.3

Cargo.lock, Cargo.toml, crates/wash-cli/src/up/config.rs
Bumps wadm version before alpha.3 release of wash to include config support.
=> chore(wash-cli): bump wadm v0.11.0-alpha.4

examples/rust/components/http-keyvalue-counter/wadm.yaml
=> fix(examples): keyvalue-redis provider -> 0.24.0

Cargo.lock, Cargo.toml, crates/wash-lib/Cargo.toml
Bumps to v0.20.0 for wash-lib.
=> chore(wash-lib): bump to v0.20.0

Cargo.lock, Cargo.toml, crates/control-interface/Cargo.toml, crates/wash-lib/Cargo.toml
Bumps the control interface to 1.0.0
=> chore(control-interface): bump to v1.0.0

crates/provider-messaging-nats/src/lib.rs
=> fix(providers): ensure trace context is attached for messaging-nats

Cargo.lock, crates/wash-cli/Cargo.toml, crates/wash-cli/src/up/config.rs
Just a bump to the crate and then the internal bump of wadm and wasmcloud within the up configuration.
=> FEAT: Update wash for wasmCloud v1.0.0

.gitignore, tests/actors/build.rs, tests/actors/src/lib.rs, tests/example-rust-http-keyvalue-counter.rs
Add a unit test for `http-keyvalue-counter`
Would be nice to use Wadm as a library here instead of manually setting up entities
=> Test `http-keyvalue-counter` example

crates/host/wit/deps.lock, crates/host/wit/deps.toml
Update URLs to point to https://github.com/wrpc
=> chore: update URLs to `wrpc` org

README.md
Just a small change to the README to note the need to `wash build` the component.
=> fix(README): instruct to wash build

crates/provider-blobstore-fs/src/lib.rs, crates/provider-blobstore-s3/src/lib.rs, crates/provider-http-client/src/lib.rs, crates/provider-keyvalue-redis/src/lib.rs, crates/provider-keyvalue-vault/src/lib.rs, crates/provider-sdk/src/lib.rs, crates/provider-sdk/src/otel.rs
This PR adds OTEL propagation to various providers
This was verified manually w/ the OTEL tools running in the background.
=> feat(providers): add otel propagation

README.md, examples/README.md, examples/docker/README.md, examples/golang/README.md, examples/python/README.md, examples/rust/README.md, examples/security/README.md, examples/typescript/README.md
Improve documentation around examples -- how to run them and context on what they're meant to do/display.
=> doc(examples): improve example documentation

Cargo.lock, crates/test-util/Cargo.toml, crates/test-util/src/host.rs, crates/test-util/src/lattice/link.rs, crates/test-util/src/lib.rs, crates/test-util/src/provider.rs, crates/test-util/tests/common/mod.rs, crates/test-util/tests/common/nats.rs, crates/test-util/tests/quickstart.rs, tests/config.rs, tests/example-rust-http-keyvalue-counter.rs, tests/interfaces.rs, tests/policy.rs
This commit adds documentation and tests for the test util crate, in preparation for it being published an replacing the `wasmcloud-test-util` that is currently published to crates.io.
=> docs(test-util): fill out more documentation, tests

.github/workflows/examples-components.yml, examples/rust/components/blobby/.gitignore, examples/rust/components/http-hello-world/wasmcloud.toml, examples/rust/components/http-keyvalue-counter/wasmcloud.toml
This commit publishes more of our examples to the GitHub Container Registry (and Azure Container Registry).
NOTE: after this merges, tags need to be pushed for the 4 added Rust components
=> chore: publish more Rust examples to registry

examples/rust/components/blobby/wadm.yaml
This PR fixes an issue where the link in the blobby manifest was getting parsed incorrectly.
Fixes #1996 
I did verify this works
=> fix(blobby): rename link scaler

Cargo.lock, Cargo.toml, crates/host/src/wasmbus/handler.rs, crates/host/src/wasmbus/mod.rs, crates/runtime/src/actor/component/http.rs, crates/runtime/src/actor/component/messaging.rs, crates/runtime/src/actor/component/mod.rs, crates/runtime/src/capability/mod.rs
=> feat: update to Wasmtime 20

examples/README.md
Update the README with the now-published component artifact URLs
I used all of these URLs with `wash start component` manually
=> chore: update example component OCI urls

crates/host/src/lib.rs, crates/host/src/oci.rs, crates/host/src/wasmbus/mod.rs, crates/runtime/src/lib.rs, crates/runtime/src/runtime.rs, crates/wash-lib/src/build/component.rs
This PR replaces "actor" with "component" across crates in the codebase.
=> chore(host, runtime, wash-lib): replace 'actor' with 'component'

crates/provider-keyvalue-redis/src/lib.rs
=> fix(providers): ignore URL config key vase for kv redis provider

crates/host/src/wasmbus/mod.rs, crates/runtime/src/actor/component/mod.rs
Follow-up on https://github.com/wasmCloud/wasmCloud/pull/2002
=> feat(host): propagate `max_execution_time` to the runtime

crates/host/src/wasmbus/mod.rs, crates/runtime/src/runtime.rs, crates/runtime/tests/runtime.rs
=> feat(runtime): count epoch in a separate OS thread

crates/provider-archive/src/archive.rs, crates/provider-blobstore-fs/src/lib.rs, crates/wash-cli/src/par.rs, crates/wash-lib/src/capture.rs, crates/wash-lib/src/cli/inspect.rs, crates/wash-lib/src/context/fs.rs, crates/wash-lib/src/registry.rs
This PR makes file open errors more informative across the codebases
=> refactor(*): more informative file open errors

.github/workflows/examples-components.yml
This commit changes the naming scheme of component artifacts to be `ghcr.io/wasmcloud/components/<name>-<lang>:<version>`.
Resolves #2008
=> refactor(examples): rename component artifacts

crates/provider-sdk/src/provider.rs
- **feat(provider-sdk)!: support storing directional links**
- **refactor(provider-sdk)!: remove link_name**
This PR adds support to the provider SDK to store links in 2 different hashmaps, one for links where the provider is the source and one for where the provider is the target. This directionality is necessary in order to properly store different configuration, WASI interfaces, and different links where the provider is the source.
I don't believe this is a breaking change technically but I did modify the logic for link storage so providers might unknowingly depend on that, so a minor bump is appropriate.
provider-sdk v0.5.0
=> feat(provider-sdk)!: support directional link storage

Cargo.lock, Cargo.toml
Bump to 1.0.1 to release patches
=> chore(wasmcloud): bump to 1.0.1

.github/workflows/artifacthub.yml, .github/workflows/examples-components.yml, .github/workflows/provider.yml, .github/workflows/scorecard.yml, .github/workflows/wash-plugins.yml, .github/workflows/wasmcloud.yml
This commit makes the naming for workflows a bit more consistent, opting for an all-lower case kebab style.
=> refactor(ci): consistent naming for workflows

crates/wash-cli/build.rs, crates/wash-cli/tests/wash_scale.rs, crates/wash-cli/tests/wash_start.rs, crates/wash-cli/tests/wash_stop.rs, crates/wash-cli/tests/wash_up.rs, crates/wash-cli/tests/wash_update.rs
=> test(wash-cli): update cfg attr checks for ghcr.io

crates/wash-lib/src/cli/start.rs
Enable starting providers with relative paths. The following now work:
```
wash start provider ../../messaging-nats-provider.par.gz test-1
wash start provider file://../../messaging-nats-provider.par.gz test-2
```
`next`
Users should be able to more easily start providers.
The commands above were tested locally on the branch
=> feat(wash-lib): allow relative paths when starting providers

.github/workflows/examples-components.yml
=> fix(ci): remove duplicated http-jsonify example

crates/control-interface/CHANGELOG.md, crates/core/CHANGELOG.md, crates/host/CHANGELOG.md, crates/opentelemetry-nats/CHANGELOG.md, crates/provider-archive/CHANGELOG.md, crates/provider-blobstore-fs/CHANGELOG.md, crates/provider-blobstore-s3/CHANGELOG.md, crates/provider-http-client/CHANGELOG.md, crates/provider-http-server/CHANGELOG.md, crates/provider-keyvalue-redis/CHANGELOG.md, crates/provider-keyvalue-vault/CHANGELOG.md, crates/provider-lattice-controller/CHANGELOG.md, crates/provider-messaging-kafka/CHANGELOG.md, crates/provider-messaging-nats/CHANGELOG.md, crates/provider-sdk/CHANGELOG.md, crates/runtime/CHANGELOG.md, crates/tracing/CHANGELOG.md
This PR is a result of running `cargo changelog --no-preview --execute` at the root of this repository, which triggers generation of changelogs for each crate based on latest changes.
Consider this PR more of a test run for what cargo smart-release will generate for us. I'll keep generating these "manually" for a little while until I can get actions prepared to do so.
=> chore(CHANGELOG): update for 1.0.1 release

.github/workflows/washboard.yml, washboard-ui/package.json, washboard-ui/packages/lattice-client-core/package.json, washboard-ui/packages/lattice-client-react/package.json, washboard-ui/packages/washboard-ui/.eslintrc.cjs, washboard-ui/packages/washboard-ui/package.json, washboard-ui/packages/washboard-ui/tsconfig.json, washboard-ui/packages/washboard-ui/tsconfig.node.json, washboard-ui/turbo.json
- update eslint rules for node files
- move script implementation details to packages
=> Update eslint config for node files

crates/wash-cli/src/down/mod.rs
This commit adds missing code for reporting filenames when operations fail -- in particular for `wash down`.
=> fix(wash-cli): report filenames when operations fail

washboard-ui/packages/washboard-ui/src/app/components/lattice-settings.tsx
This commit updates the `LatticeSettings` component to reflect the new options that are now configurable.
Resolves #1318
=> feat(washboard): reflect new options in LatticeSettings component

crates/runtime/src/runtime.rs
We found that on hosts with less then 2GB of memory (give or take a little) the host would fail to start when the pooling allocator started allocating virtual memory. You could get around this by setting `vm_overcommit` to 1 or 2, but this is not the best experience for those running in production. This fixes the issue by falling back to the dynamic memory allocator if setup fails.
We already have a plan to add some more of these tunables as options for the host, but those will be added in future PRs as a feature add
=> fix(runtime): Fixes issue with running runtime on smaller hosts

crates/wash-lib/src/build/component.rs, examples/golang/components/http-echo-tinygo/wasmcloud.toml, examples/golang/components/http-hello-world/wasmcloud.toml, examples/python/components/http-hello-world/wasmcloud.toml, examples/rust/components/blobby/wasmcloud.toml, examples/rust/components/echo-messaging/wasmcloud.toml, examples/rust/components/http-blobstore/wasmcloud.toml, examples/rust/components/http-hello-world/wasmcloud.toml, examples/rust/components/http-jsonify/wasmcloud.toml, examples/rust/components/http-keyvalue-counter/wasmcloud.toml, examples/rust/components/wash-plugin-rust/wasmcloud.toml, examples/typescript/components/http-hello-world/wasmcloud.toml
This PR updates the `[actor]` block in the wasmcloud.tomls to `[component]` since that is supported as of wash 0.27.
=> chore(examples): update [actor] to [component]

Cargo.lock, Cargo.toml
This PR bumps to v1.0.2 to bring in #2052 and any other fixes.
#2052
wasmCloud v1.0.2
=> chore(wasmcloud): bump to v1.0.2

.github/workflows/wasmcloud.yml
=> ci(wasmcloud): include cargo publish token

Cargo.lock
Simple deps update to rustls-tls to 0.22.4.
=> build(deps): update rustls-tls 0.22.4

examples/rust/components/wash-plugin-rust/Cargo.toml, examples/rust/components/wash-plugin-rust/src/lib.rs, examples/rust/components/wash-plugin-rust/wit/deps.lock, examples/rust/components/wash-plugin-rust/wit/deps/subcommand/subcommand.wit
Also adds some more functionality and examples showing how to parse args and load files
=> feat(examples): Updates plugin to match new wit

.github/workflows/wasmcloud.yml, flake.nix
This adds [wolfi](https://github.com/wolfi-dev/) as an alternative base image for the wasmCloud host and wash OCI images.
=> Add wolfi image

Cargo.lock, crates/wash-cli/Cargo.toml, crates/wash-lib/Cargo.toml
Patch bumps to release wash-cli and wash-lib
=> chore(wash): bump patch for release

Cargo.lock, Cargo.toml, crates/provider-blobstore-s3/src/lib.rs
=> chore(providers): update aws config verison for blobstore-s3

washboard-ui/packages/washboard-ui/package.json, washboard-ui/packages/washboard-ui/tests/common/wasmcloud-instance.ts, washboard-ui/yarn.lock
=> chore(washboard): update execa dep

Cargo.lock
Updating quarantined dependencies.
=> feat(quarantine): Removing quarantined dependencies

examples/rust/components/http-keyvalue-counter/wadm.yaml
=> fix(kvcounter): keyvalue interface

crates/provider-http-client/README.md
The README is out of date with regards to the underlying implementation, so let's fix that.
=> fix(providers): Correct http-client provider README, reference hyper instead of reqwest

crates/wash-cli/src/app/mod.rs
This commit enables `wash app delete` to delete applications by manifest file, rather than strictly by model name inside the manifest.
We do this simply by checking whether the filename is a valid file path, and attempting to read that file, with the assumption that it is very unlikely someone would call their model `wadm.yaml` (or any variation of a normally named YAML WADM manifest.
=> feat(wash-cli): enable deleting manifests by file name

crates/wash-cli/src/app/mod.rs
This commit adds an option `--replace` to `wash app deploy` which helps run repeated deploys of the *same* manifest by undeploying the specified model right before deploying.
While this isn't quite as robust as we want an option like `wash app dev` to be, it does enable easy scripting.
I tested this locally -- you can use the following from `crates/wash-cli`:
```
cargo run -- app deploy --replace <path to wadm.yaml>
```
=> feat(wash-cli): add --replace option to `wash app deploy`

.github/workflows/wit-wasmcloud-postgres.yml, wit/postgres/query.wit, wit/postgres/types.wit
This commit adds the wasmcloud:postgres WIT to the top level `wit` folder in the repository and also creates an artifact that we can use for referencing releases of the WIT contract.
=> feat: add wasmcloud postgres WIT and artifact

Cargo.lock, Cargo.toml, crates/wash-cli/src/common/registry_cmd.rs, crates/wash-cli/tests/wash_claims.rs, crates/wash-cli/tests/wash_inspect.rs, crates/wash-cli/tests/wash_reg.rs, crates/wash-lib/src/cli/registry.rs, crates/wash-lib/src/registry.rs, crates/wash-lib/src/start/github.rs
This rounds out a feature I didn't think we'd need for a while. This should allow us to push any type of component
=> feat(*): Allows for pushing binary wit packages with wash

crates/wash-cli/docs/DEVELOPMENT.md
This PR addresses a gap in the documentation for new contributors regarding the process of testing local changes to wash-cli. The absence of detailed instructions in the DEVELOPMENT.md file might leave new contributors unsure of how to build and run their local modifications, potentially hindering their ability to effectively contribute to the project.
next
=> doc(wash-cli): Updated DEVELOPMENT.md to include steps for testing wash locally

crates/provider-sqldb-postgres/src/lib.rs
This commit add missing trace context propagation for the Postgres provider
=> feat(providers): add trace context propagation for pg provider

Cargo.lock, Cargo.toml, crates/wash-cli/src/keys.rs, crates/wash-lib/src/cli/mod.rs
Update to nkeys 0.4 in preparation for using xkeys in the host.
=> chore: update nkeys to 0.4

Cargo.lock, Cargo.toml, crates/wascap/Cargo.toml, crates/wascap/src/jwt.rs
This reverts commit add7bb1e11bf76eb235f7aa7b7c6ef7db93bae5e.
Because of an issue with the DCO check it was disabled and this went in without a signoff. I will re-submit the PR with the right signoff.
=> Revert "feat(wascap): add Host entity type"

washboard-ui/packages/lattice-client-core/package.json, washboard-ui/packages/lattice-client-core/src/controllers/links.ts
Minor change to types of delete method on links controller
=> [lattice client]: correct types

crates/wash-cli/src/up/config.rs
This PR updates wadm to v0.12.0.
=> chore(wash): update wadm to v0.12.0

examples/rust/components/sqldb-postgres-query/README.md
Without the mapping , i get a connection error in the provider. I added a port mapping to make it work.
=> feat(port): Specify port mapping for postgres example

examples/rust/components/dog-fetcher/wadm.yaml
This commit fixes the OCI reference for the dog-fetcher example component.
=> fix(examples): OCI reference for dog-fetcher

examples/rust/components/wash-plugin-rust/.cargo/config.toml, examples/rust/components/wash-plugin-rust/README.md, examples/rust/components/wash-plugin-rust/project-generate.toml
This commit adds a few missing documentation like things to the wash plugin example:
- README
- .cargo/config.toml just in case people want to build with cargo
- project-generate.toml for template usage
Resolves #2258
=> chore(examples): add project generate for wash plugin

crates/wash-cli/src/down/mod.rs
This PR allows for purging NATS jetstream persistent streams and kv buckets that are needed by wadm, wasmcloud, or both. For example, to completely reset local wasmCLoud, run:
```
wash down --purge all
```
While I was in there I downgraded some of the errors in `wash down` to just be warning logs, like trying to shutdown the local NATS/wadm if the wasmCloud pidfile was missing. I want `down` to feel like something you can run over and over, and a command that supports removing incompletely cleaned up resources.
Fixes #1740
wash 0.29 or 0.30 depending on time
=> feat(#1740): support purging NATS during down

examples/rust/components/dog-fetcher/src/lib.rs
This commit fixes a bug with OutgoingBody/stream usage in the dog-fetcher example -- in this case we weren't properly releasing the child resource (the outgoing-stream produced by write()) before finishing the OutgoingBody.
=> fix(examples): response stream usage in dog-fetcher

Cargo.lock, Cargo.toml, crates/provider-blobstore-s3/README.md, crates/provider-blobstore-s3/src/lib.rs, crates/provider-blobstore-s3/tests/storage.rs, examples/rust/components/blobby/src/lib.rs
=> feat(providers): support location constraint w/ blobstore-s3

crates/wash-cli/src/app/mod.rs
This commit adds the ability to `wash undeploy` a model via file rather than only model name.
Resolves #1444
=> feat(wash-cli): enable undeploying models by file name

Cargo.lock, Cargo.toml, crates/provider-sdk/src/provider.rs, crates/tracing/Cargo.toml, crates/tracing/src/lib.rs, crates/tracing/src/traces.rs, src/main.rs
Avoid locking whole process on each logging statement
=> feat(tracing): use `tracing-appender`

crates/core/README.md, crates/core/src/host.rs, crates/core/src/link.rs, crates/core/src/logging.rs, crates/core/src/nats.rs, crates/core/src/otel.rs, crates/core/src/rpc.rs, crates/core/src/tls.rs, crates/core/src/wit.rs, crates/core/src/wrpc.rs
=> docs(core): add README and update docs

crates/wash-lib/src/cli/update.rs
This commit updates wash-lib to throw an error when attempting to update a component that multiple hosts run.
Resolves https://github.com/wasmCloud/wasmCloud/issues/1980
=> feat(wash-cli): error when updating a component multiple hosts run

crates/provider-keyvalue-redis/src/lib.rs
This commit adds a warning when non-empty bucket names are used with the KV redis provider as it does not yet support using the bucket name properly.
Resolves #1939
=> feat(providers): warn for non-empty bucket name w/ kvredis

crates/host/src/wasmbus/handler.rs
This commit adds the "link-name" header to invocations performed by the host using wRPC.
Resolves https://github.com/wasmCloud/wasmCloud/issues/2332
=> feat(host): add link name to wRPC invocations

Cargo.lock, Cargo.toml, crates/provider-sdk/src/provider.rs, crates/tracing/Cargo.toml, crates/tracing/src/lib.rs, crates/tracing/src/traces.rs, src/main.rs
Generate flame graphs using https://docs.rs/tracing-flame/latest/tracing_flame/index.html if configured to do so, also refactor the observability function to do that in a sane way
=> feat(tracing): add support for flame graph generation

crates/provider-http-client/README.md, crates/provider-messaging-kafka/README.md, crates/provider-sqldb-postgres/README.md, crates/wash-cli/tests/common/mod.rs, examples/golang/components/http-client-tinygo/wadm.yaml, examples/golang/components/http-echo-tinygo/wadm.yaml, examples/golang/components/http-hello-world/wadm.yaml, examples/python/components/http-hello-world/wadm.yaml, examples/rust/components/blobby/wadm.yaml, examples/rust/components/dog-fetcher/wadm.yaml, examples/rust/components/echo-messaging/wadm.yaml, examples/rust/components/http-blobstore/wadm.yaml, examples/rust/components/http-hello-world/wadm.yaml, examples/rust/components/http-jsonify/wadm.yaml, examples/rust/components/http-keyvalue-counter/wadm.yaml, examples/rust/components/sqldb-postgres-query/wadm.yaml, examples/rust/composition/http-hello/wadm.yaml, examples/rust/composition/http-hello2/wadm.yaml, examples/rust/composition/wadm.yaml, examples/typescript/components/http-hello-world/wadm.yaml
This PR just mass updates our capability providers in wadm to match the latest published provider versions.
This feels like a good thing we could automate :eyes:
=> chore(examples-*): update to latest provider references

crates/wash-cli/src/up/config.rs
This Pr brings in a fix for the wadm delete handler.
https://github.com/wasmCloud/wadm/pull/305
wash-cli v0.29.2
=> chore(wash-cli): update wadm to v0.12.1

crates/wash-cli/src/call.rs, crates/wash-cli/src/common/start_cmd.rs, crates/wash-cli/src/common/stop_cmd.rs, crates/wash-cli/src/ctl/mod.rs, crates/wash-cli/src/dev.rs, crates/wash-cli/src/up/mod.rs, crates/wash-cli/tests/common/mod.rs, crates/wash-cli/tests/wash_reg.rs, crates/wash-cli/tools/README.md, crates/wash-cli/tools/kvcounter-example.sh
Replace actor reference by component in wash-cli crate.
#1827
=> chore(wash-cli): Replace actor by component

.github/workflows/lint-conventional-commits.yml, CONTRIBUTING.md
=> chore(ci): add lint for conventional commits

crates/wash-cli/README.md
Add documentation on using wash behind a proxy.
=> docs(proxy): Include proxy auth information in wash

.github/workflows/wash.yml
This commit updates macos-11 with macos-12 runners, as macos-11 is deprecated.
=> chore(ci): replace macos-11 runners with macos-12

ADOPTERS.md
Add MachineMetrics to list of adopters.
N/A
N/A
N/A
N/A
N/A
N/A
Reading it ;-)
=> Add MachineMetrics to list of adopters

crates/wash-cli/tests/wash_dev.rs, crates/wash-lib/src/cli/mod.rs, crates/wash-lib/src/start/nats.rs
Resolves https://github.com/wasmCloud/wasmCloud/issues/2066
=> chore(test): remove warnings on windows

crates/host/src/wasmbus/mod.rs
Resolves https://github.com/wasmCloud/wasmCloud/issues/2113
=> feat(host): allow empty payloads to trigger stop_host

examples/golang/providers/custom-template/main.go
This PR ensures the link maps are initialized in the custom template.
=> fix(custom-template-golang): initialize maps

examples/golang/providers/custom-template/component/.gitignore, examples/golang/providers/custom-template/component/go.mod
Fixing the go version in custom template for wash build to work
=> fix(build): Fix the go version for wash build

crates/control-interface/src/client.rs, crates/control-interface/src/types/host.rs, crates/wash-cli/tests/wash_get.rs
Resolves https://github.com/wasmCloud/wasmCloud/issues/2183
=> chore(*): order labels in wash get inventory

crates/host/src/wasmbus/handler.rs, crates/runtime/src/capability/builtin.rs
This commit improves error messaging when we fail to call a target for an interface that has no link specified.
Resolves https://github.com/wasmCloud/wasmCloud/issues/1927
=> chore(*): improve error messages for missing links

examples/golang/components/http-client-tinygo/wadm.yaml, examples/golang/components/http-echo-tinygo/wadm.yaml, examples/golang/components/http-hello-world/wadm.yaml, examples/golang/providers/custom-template/wadm.yaml, examples/python/components/http-hello-world/wadm.yaml, examples/rust/components/blobby/wadm.yaml, examples/rust/components/dog-fetcher/wadm.yaml, examples/rust/components/echo-messaging/wadm.yaml, examples/rust/components/http-blobstore/wadm.yaml, examples/rust/components/http-hello-world/wadm.yaml, examples/rust/components/http-jsonify/wadm.yaml, examples/rust/components/http-keyvalue-counter/wadm.yaml, examples/rust/components/sqldb-postgres-query/wadm.yaml, examples/typescript/components/http-hello-world/wadm.yaml
This commit adds comments explaining linking and custom annotations to WADM manifests in examples.
=> docs(examples): add comments and annotations to WADM

crates/control-interface/src/client.rs, crates/control-interface/src/types/ctl.rs, crates/host/src/wasmbus/mod.rs
Resolves https://github.com/wasmCloud/wasmCloud/issues/1818
=> feat(*): add update to scale component command

Cargo.lock, crates/provider-keyvalue-redis/Cargo.toml
This commit releases `provider-keyvalue-redis` v0.26.0, with emphasis on the following fixes:
- Support for per-link-name connection maintenance
- Warning for non-empty bucket names
=> release(providers): provider-keyvalue-redis v0.26.0

crates/provider-keyvalue-redis/README.md
=> chore: update references to new version of kvredis provider

crates/wash-lib/src/cli/link.rs
This PR adds a simple alias for a common typo when creating a link.
wash-lib next patch
=> chore(wash-lib): add alias for --interfaces

examples/rust/components/dog-fetcher/Cargo.toml, examples/rust/components/dog-fetcher/wadm.yaml
This is to release the resource drop issue related to the stream close.
=> chore(examples): bump dog-fetcher to v0.1.1

examples/rust/components/dog-fetcher/project-generate.toml
=> fix: add project-generate.toml to dog-fetcher template

.github/workflows/artifacthub.yml, .github/workflows/comment-cc.yml, .github/workflows/examples-components.yml, .github/workflows/license-check.yml, .github/workflows/lint-cc.yml, .github/workflows/nix.yml, .github/workflows/provider.yml, .github/workflows/secrets-nats-kv.yml, .github/workflows/update.yml, .github/workflows/wash-plugins.yml, .github/workflows/washboard.yml, .github/workflows/wasmcloud-chart.yml, .github/workflows/wasmcloud.yml, .github/workflows/wit-wasmcloud-postgres.yml
This PR addresses some workflow security issues that came up during security scanning.
=> fix(ci): workflow security

.github/actions/build-nix/action.yml, .github/actions/install-nix/action.yml, .github/workflows/artifacthub.yml, .github/workflows/examples-components.yml, .github/workflows/license-check.yml, .github/workflows/lint-cc.yml, .github/workflows/nix.yml, .github/workflows/provider.yml, .github/workflows/scorecard.yml, .github/workflows/secrets-nats-kv.yml, .github/workflows/update.yml, .github/workflows/wash-plugins.yml, .github/workflows/wash.yml, .github/workflows/washboard.yml, .github/workflows/wasmcloud-chart.yml, .github/workflows/wasmcloud.yml, .github/workflows/wit-wasmcloud-postgres.yml
Pin some CI deps to improve security of the repo:
- pin softprops/aciton-gh-release to v2.0.6
- pin actions/download-artifact@ to v4.1.8
- pin docker/setup-buildx-action to v3.4.0
- pin docker/login-action to v3.2.0
- pin swatinem/rust-cache to v2.7.3
- pin actions/setup-go to v5.0.2
- pin actions/checkout to v4.1.7
- pin actions/checkout to v4.3.4
- pin taiki-e/install-action to nextest branch
- pin oras-project/setup-oras to v1.2.0
- pin EmbarkStudios/cargo-den-action to v1.6.3
- pin sudo-bot/action-docker-compose to latest tag
- pin DeterminateSystems/nix-installer-action to v12
- pin DeterminateSystems/magic-nix-cache-action to v7
- pin cachix/cachix-action to v15
- pin actions/setup-python to v5.1.1
- pin actions/setup-node to v4.0.3
- pin acifani/setup-tingo to v2
- pin …
=> chore(ci): pin various versions of CI deps

Cargo.lock, Cargo.toml, crates/runtime/src/component/mod.rs
small follow-up on #2459 , I did not want to touch that PR after being reviewed
- instrument the component export handlers
- do not fail if component exports something we do not support (like, another component or a resource), just log a warning
- check if a component exports resources, and if so, warn that those will be ignored
- propagate the invocation timeout into the polyfill
=> chore: update wRPC

crates/provider-sdk/Cargo.toml
Resolves https://github.com/wasmCloud/wasmCloud/issues/2403
=> chore(provider-sdk): enable otel feature for docsrs

crates/wash-cli/tests/common/mod.rs, crates/wash-cli/tests/wash_call.rs, crates/wash-cli/tools/docker-compose.yml, crates/wash-lib/src/start/wadm.rs
These commits fix some issues with wash integration tests that have been failing lately. The issue stemmed from output being routed to STDOUT (and thus printed along with JSON) when it should have been printed to STDERR.
=> fix(wash-*): integration tests

examples/rust/components/blobby/Cargo.toml, examples/rust/components/blobby/wadm.yaml, examples/rust/components/blobby/wasmcloud.toml
Some community members ran into issues with blobby and while their issue *seems* unrelated: 
- The version of blobby we're using in the repo looks to be old
- Some features are also unreleased
- The ROOT dir setting in the WADM file could be removed could be improved
=> chore(examples): update blobby image and release new version

.github/workflows/examples-components.yml
This commit adds the `packages: write` permission to the examples-components workflow
=> fix(ci): re-add missing package write permission

washboard-ui/packages/washboard-ui/src/app/components/lattice-settings.tsx, washboard-ui/packages/washboard-ui/src/app/components/settings.tsx
Minor organization and styling updates to settings panel for easier future expansion
=> fix(washboard-ui): update settings panel components

crates/wash-cli/src/ui/mod.rs, washboard-ui/packages/washboard-ui/package.json, washboard-ui/packages/washboard-ui/src/app/components/lattice-settings.tsx, washboard-ui/packages/washboard-ui/src/app/components/settings.tsx
Update washboard version in package and in `wash-cli` crate.
Should merge after #2506
=> chore: update washboard version

crates/core/src/tls.rs, crates/host/src/oci.rs
Light refactor from CA certs PR comments
=> refactor(host, core): ca certs followup

crates/wash-cli/src/ctl/output.rs
This PR improves the output of `wash get inventory` command.
[Issue #2398](https://github.com/wasmCloud/wasmCloud/issues/2398)
The new output format has been tested locally.
=> feat: Improved the output of wash get inventory command, as outlined in issue #2398

Cargo.toml, crates/test-util/Cargo.toml
This commit prepares `wasmcloud-test-util` for a release of the next "major" version (following semver pre 1.x semantics), version 0.12.0.
=> chore(test-util): prep for release v0.12.0

crates/wash-cli/src/app/mod.rs
This PR removes an Option<String> that was being logged in favor of suggesting the user should check that the provided application name is a valid file for `wash app put`.
=> fix(wash-cli): better format of optional in error

crates/provider-keyvalue-nats/src/lib.rs, crates/provider-messaging-kafka/messaging-kafka-demo.wadm.yaml, crates/wash-cli/tests/fixtures/wadm/component-only.wadm.yaml, crates/wash-cli/tests/fixtures/wadm/manifests/simple.wadm.yaml, examples/golang/components/http-client-tinygo/wadm.yaml, examples/golang/components/http-echo-tinygo/tests/fixtures/wadm.template.yaml, examples/golang/components/http-echo-tinygo/wadm.yaml, examples/golang/components/http-hello-world/wadm.yaml, examples/golang/providers/custom-template/wadm.yaml, examples/python/components/http-hello-world/wadm.yaml, examples/rust/components/blobby/wadm.yaml, examples/rust/components/dog-fetcher/wadm.yaml, examples/rust/components/echo-messaging/wadm.yaml, examples/rust/components/http-blobstore/wadm.yaml, examples/rust/components/http-hello-world/wadm.yaml, examples/rust/components/http-jsonify/wadm.yaml, examples/rust/components/http-keyvalue-counter/wadm.yaml, examples/rust/components/keyvalue-messaging/wadm.yaml, examples/rust/components/sqldb-postgres-query/wadm.yaml, examples/rust/composition/http-hello/wadm.yaml, examples/rust/composition/http-hello2/wadm.yaml, examples/rust/composition/wadm.yaml, examples/rust/providers/custom-template/wadm.yaml, examples/typescript/components/http-hello-world/wadm.yaml
Replicas will soon be deprecated.
Use the non-deprecated field for all examples and doc, `instances`.
https://github.com/wasmCloud/wadm/pull/314
`next`
None, these are all doc comment and example changes.
=> doc(wadm): use instances for examples

examples/rust/components/http-jsonify/Cargo.toml, examples/rust/components/http-jsonify/src/lib.rs, examples/rust/components/http-jsonify/wasmcloud.toml
=> fix(examples): http jsonify request input reading

.github/workflows/wash.yml
=> chore(ci): run wash tests during merge queue

crates/wash-lib/src/start/wasmcloud.rs
=> fix(wash-lib): invalid target_arch riscv64gc

.github/workflows/secrets-nats-kv.yml
Pulls https://github.com/wasmCloud/wasmCloud/pull/2575/commits/e5276a6e86125ebe7fc021dca0de3620a8d6708b into it's own PR since #2575 is otherwise already covered in #2564.
=> chore(ci): Add secrets-client to secrets-nats-kv workflow

crates/provider-sdk/Cargo.toml, crates/provider-sdk/README.md
This PR adds a README to the provider-sdk crate.
=> chore(provider-sdk): update README

crates/core/src/secrets.rs, crates/provider-blobstore-azure/src/config.rs, crates/provider-blobstore-azure/src/lib.rs, crates/provider-sdk/src/provider.rs
=> chore(*): migrate azure blob to use secrets

.github/workflows/wasmcloud.yml, Cargo.lock, crates/host/src/secrets.rs, crates/host/src/wasmbus/mod.rs, crates/secrets-client/src/lib.rs, crates/secrets-nats-kv/src/client.rs, crates/secrets-nats-kv/src/main.rs, crates/secrets-nats-kv/tests/api.rs, crates/secrets-types/Cargo.toml, crates/secrets-types/src/lib.rs, crates/test-util/Cargo.toml, crates/test-util/src/lattice/config.rs, crates/wash-cli/src/secrets.rs, crates/wash-cli/tests/wash_secrets.rs, tests/common/secrets.rs, tests/config.rs
This PR will contain a couple of fixes & cleanup for the secrets implementation found after testing. For now, the only fix relates to building the map to give to components & providers using the name of the secret, rather than the backend-specific key.
More fixes to follow, specifically around the policy properties format.
=> fix(secrets): cleanup & fix secrets impl

crates/wash-cli/tests/wash_secrets.rs
This PR fixes an issue in an integration test for wash.
=> fix(wash-cli): correct integration test

crates/secrets-client/Cargo.toml
Even if we don't publish this, it should've been included originally, but it wasn't.
=> chore: Add description for wasmcloud-secrets-client crate

crates/secrets-types/Cargo.toml
=> chore(secrets-types): add README

crates/wash-cli/build.rs
=> chore(wash-cli): suppress warning for new rust cfg check

Cargo.toml
Fixes https://github.com/wasmCloud/wasmCloud/actions/runs/10148276884/job/28060744309#step:5:297
=> chore: Update wasmcloud-secrets-* version

Cargo.lock, Cargo.toml
This PR bumps wasmCloud to 1.1.0, in preparation for a beta and then full release afterwards.
=> chore(wasmcloud): bump to 1.1.0

crates/runtime/src/runtime.rs
This commit increases the max memory that can be addressed by a single component to 10mb.
=> chore(runtime): increase max memory size to 10mb

.github/workflows/wasmcloud.yml
This PR should fix an issue where the smart-release action was not able to create a PR.
=> ci(wasmcloud): give smart-release PR privileges

README.md
This PR updates our README with updated language & links.
=> chore(README): update with messaging

crates/provider-keyvalue-redis/README.md, crates/provider-sqldb-postgres/README.md, crates/wash-cli/tests/common/mod.rs, examples/golang/components/http-client-tinygo/wadm.yaml, examples/golang/components/http-echo-tinygo/wadm.yaml, examples/golang/components/http-hello-world/wadm.yaml, examples/python/components/http-hello-world/wadm.yaml, examples/rust/components/blobby/wadm.yaml, examples/rust/components/dog-fetcher/wadm.yaml, examples/rust/components/http-blobstore/wadm.yaml, examples/rust/components/http-hello-world/wadm.yaml, examples/rust/components/http-jsonify/wadm.yaml, examples/rust/components/http-keyvalue-counter/wadm.yaml, examples/rust/composition/http-hello/wadm.yaml, examples/rust/composition/http-hello2/wadm.yaml, examples/rust/composition/wadm.yaml, examples/security/secrets/run.sh, examples/typescript/components/http-hello-world/wadm.yaml
Update various parts of the codebase to HTTP server 0.22.0 to surface an already released wRPC fix
Resolves #2624
=> chore(*): update example http server

.github/workflows/wasmcloud.yml
This PR ensures that the committer of the pull request is the automation account. The author will be whoever triggered the workflow
=> ci(wasmcloud): smart-release commit by automation

adr/0019-secrets.md
This PR explains motivations, context, and design details around the decision to add secrets support to wasmCloud.
Fixes #2190
=> chore: add ADR-0019 secrets

.github/workflows/wasmcloud.yml
This PR adds the `contents: write` bit to the smart-release action, which is required as per https://github.com/peter-evans/create-pull-request/tree/main?tab=readme-ov-file#action-inputs to create a PR
=> ci(wasmcloud): smart-release write bit

crates/provider-blobstore-s3/src/lib.rs, crates/provider-keyvalue-nats/README.md, crates/provider-keyvalue-nats/src/config.rs, crates/provider-keyvalue-nats/src/lib.rs, crates/provider-keyvalue-redis/README.md, crates/provider-keyvalue-redis/src/lib.rs, crates/provider-keyvalue-vault/src/config.rs, crates/provider-keyvalue-vault/src/lib.rs, crates/provider-messaging-kafka/README.md, crates/provider-messaging-kafka/src/lib.rs, crates/provider-messaging-nats/src/connection.rs, crates/provider-messaging-nats/src/lib.rs, crates/provider-sqldb-postgres/README.md, crates/provider-sqldb-postgres/src/config.rs, crates/provider-sqldb-postgres/src/lib.rs
=> chore(providers): update providers to use secrets

crates/wash-cli/tests/common/mod.rs, crates/wash-cli/tests/wash_call.rs
=> feat(wash-cli): include simple invocation in wash call tests

Cargo.lock, Cargo.toml, crates/wash-cli/src/up/config.rs
This PR is a draft that folks can use to test wash with the latest changes & libraries for wadm and wasmcloud.
```bash
cargo install wash-cli --git https://github.com/wasmCloud/wasmCloud --branch feat/wash-cli-1.1-beta --force
```
If you're looking for documentation on secrets, you can use our preview https://deploy-preview-526--dreamy-golick-5f201e.netlify.app/docs/concepts/secrets.
This currently pins to wasmCloud 1.1.0-beta.2, 1.1.0 is releasing now
=> feat(wash): wadm 0.13.0, wasmcloud 1.1.0

Cargo.lock, Cargo.toml, crates/wash-lib/src/cli/inspect.rs, examples/rust/components/http-hello-world/Cargo.toml, examples/rust/components/http-keyvalue-counter/Cargo.toml, tests/components/rust/Cargo.lock
=> chore(deps): update upstream wasm deps to *.214.0

examples/rust/components/http-jsonify/wadm.yaml
We really should make these completely separate files... but until we do at least this path should be right.
=> fix(examples): http-jsonify local file path

crates/wash-lib/src/cli/scale.rs
This PR fixes an issue where the `scale` command waited for the event twice, essentially always timing out.
Here's a before and after of how long a scale operation takes to work:
```
➜ time wash scale component NDIL5CSMAKAFA3H6AKFYKUWNHYI3UFDT622LMAQTPALZAGES3HSC67FH ghcr.io/brooksmtownsend/http-hello-world-rust:0.1.0 foobar -c 27      
Failed to scale component [foobar] (ref: [ghcr.io/brooksmtownsend/http-hello-world-rust:0.1.0]) on host [NDIL5CSMAKAFA3H6AKFYKUWNHYI3UFDT622LMAQTPALZAGES3HSC67FH]
Caused by:
Timed out waiting for applicable event, operation may have failed
wash scale component NDIL5CSMAKAFA3H6AKFYKUWNHYI3UFDT622LMAQTPALZAGES3HSC67FH  0.09s user 0.02s system 1% cpu 5.224 total
➜ time ../../target/debug/wash scale component …
```
=> fix(wash-cli): remove double event wait for scale

crates/wash-cli/src/build.rs, crates/wash-lib/src/build/provider.rs
=> chore(wash-*): improve error messages

Dockerfile, crates/secrets-nats-kv/Dockerfile, crates/wash-cli/Dockerfile
=> chore(ci): consistent casing for FROM/AS in Dockerfiles

examples/rust/components/ferris-says/wadm.yaml, examples/rust/components/http-hello-world/wadm.yaml
We're not actually using these yet... but `rusg/` is not what we want
=> fix(examples): typo in paths to components

Cargo.lock, Cargo.toml, crates/component/Cargo.toml, crates/component/src/lib.rs, crates/component/src/wrappers/io.rs, crates/component/src/wrappers/random.rs, tests/components/rust/Cargo.lock
Wrap upstream [`wasi`](https://docs.rs/wasi/latest/wasi/index.html) crate instead of e.g. implementing our own `Read` and `Write` traits.
This will be used in https://github.com/wasmCloud/wasmCloud/pull/2709
=> feat(component): wrap upstream `wasi` crate

Cargo.lock, Cargo.toml, crates/runtime/Cargo.toml, crates/runtime/src/component/http.rs, crates/runtime/src/component/messaging.rs, crates/runtime/src/component/mod.rs, crates/wash-lib/Cargo.toml, crates/wash-lib/src/build/component.rs, crates/wash-lib/src/build/mod.rs, crates/wash-lib/src/cli/inspect.rs, crates/wash-lib/src/plugin/subcommand.rs, examples/rust/components/http-hello-world/Cargo.toml, examples/rust/components/http-keyvalue-counter/Cargo.toml, examples/rust/components/http-keyvalue-counter/src/lib.rs, flake.lock, flake.nix, tests/components/Cargo.toml, tests/components/build.rs, tests/components/rust/Cargo.lock
Update Wasmtime and a few wRPC crates
=> feat: update to Wasmtime 23

Cargo.lock, Cargo.toml
This bumps wasmCloud to 1.2.0 so we can start cutting release candidates!
Note that we released 1.1.0 about 2 weeks ago, and ideally 1.2.0 comes out about a month after 1.1, but it can go anytime!
=> release(wasmcloud): v1.2.0-rc.1

crates/wash-lib/src/spier.rs
This PR fixes some logic that we had that assumed that `wash spy` payloads were going to be cbor/msgpack encoded, and instead we just decode the bytes raw. This will work well enough to show the raw decoded payloads, in the future (once we add more support to something like wash call) we may be able to interpret the operation & decode the payload in an intelligent way
Before:
```
➜ wash spy --experimental echo
Spying on component echo
[2024-08-14 09:42:57.443268 -04:00]
From: rust_echo_messaging-nats  To: echo
Operation: wasmcloud:messaging/handler@0.2
Message: 14
[2024-08-14 09:42:57.443954 -04:00]
From: echo                      To: rust_echo_messaging-nats
Operation: wasmcloud:messaging/consumer@0.2
Message: 38
[2024-08-14 09:42:57.443964 -04:00]
From: echo                      To: …
```
=> fix(wash-lib): decode body payload as string

Cargo.lock, Cargo.toml, src/main.rs
=> feat(host): Implement NATS subject validation for secret-topic and policy-topic

Cargo.lock, Cargo.toml, crates/wash-lib/src/start/github.rs
=> chore(deps): update testcontainers to stable version

crates/wash-lib/src/cli/start.rs
This commit improves the component reference parsing/resolution to be as advanced for components as it is for providers.
=> feat(wash-lib): ref parsing for components to match providers

Cargo.lock
=> chore(deps): update wit-bindgen-wrpc to 0.6.3

Cargo.lock, Cargo.toml, crates/provider-http-server/Cargo.toml, crates/provider-http-server/src/lib.rs
Handle HTTP and wRPC I/O errors while streaming HTTP response body in the server provider
HTTP server should not fail fast on errors
tested with blobby
=> feat(http-server): handle I/O and body errors

examples/rust/components/blobby/src/lib.rs
Following our discussion during a community call, switch to using `wasi:io` directly for forwarding data from one stream to another for (slightly) better performance.
In my totally scientific profiling of this using `blobstore-fs` and a bunch of random bytes written to disk:
before:
```
$ curl http://127.0.0.1:8000/test > /dev/null
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 3497M    0 3497M    0     0   133M      0 --:--:--  0:00:26 --:--:--  135M
```
after:
```
$ curl http://127.0.0.1:8000/test > /dev/null
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 5943M    0 5943M    0     0   138M      0 --:--:--  0:00:43 --:--:--  138M …
```
=> refactor(blobby): use `wasi:io` directly

src/bin/keyvalue-vault-provider/wasmcloud.toml, src/bin/sqldb-postgres-provider/wasmcloud.toml
=> fix(providers): target_paths in wasmcloud.toml

.github/workflows/examples-components.yml, examples/rust/components/sqldb-postgres-query/local.wadm.yaml
=> fix(examples): fix metadata for sqldb-pg-query, add local.wadm.yaml

Cargo.lock, Cargo.toml, crates/wash-cli/src/app/mod.rs, crates/wash-cli/src/app/output.rs, crates/wash-lib/src/app.rs
This PR uses the new feature from https://github.com/wasmCloud/wadm/pull/362 to display a very robust app status.
The `wash app status <app-name>` view changes from:
```
➜ wash app status rust-hello-world
Name               Deployed Version   Deploy Status   Status Message
rust-hello-world   v0.0.1            Reconciling      "Event modified scaler state, reconciling"
```
to this:
```
➜ cargo run -- app status rust-hello-world
rust-hello-world@v0.0.1 - Failed
Name                                          Kind           Status
http_component                                SpreadScaler   Deployed
http_component_sad                            SpreadScaler   Failed (*)
totally_unrelated_component                   SpreadScaler   Failed (*)
httpserver -(wasi:http)-> http_component …
```
=> feat(wash-cli): display detailed app status

crates/wash-cli/src/up/config.rs
Simply bumping to use v1.2.0 here
=> chore(wash-cli): wasmcloud v1.2.0

src/bin/blobstore-azure-provider/wasmcloud.toml, src/bin/blobstore-s3-provider/wasmcloud.toml
This PR bumps the azure and s3 providers for release with the latest blobstore fixes
blobstore-azure v0.4.0
blobstore-s3 v0.10.0
=> chore(azure,s3): bump minor for release

Cargo.lock, Cargo.toml
=> feat: update to Wasmtime 24

Cargo.lock, Cargo.toml, crates/provider-sqldb-postgres/Cargo.toml, crates/provider-sqldb-postgres/README.md
=> release(providers): sqldb provider 0.5.1

crates/component/Cargo.toml, tests/components/rust/Cargo.lock
Just addressing a small TODO I saw in the Cargo.toml of the component crate
We should release this crate!
=> feat(component): make serde optional

Cargo.lock, Cargo.toml, tests/components/rust/Cargo.lock
1. Update `wit-bindgen-wrpc` dep spec
2. `cargo test`
3. `for d in examples/rust/components/*; do pushd $d && cargo update -p prettyplease -p syn; popd; done`
4. `cd tests/components/rust`
5. `cargo update -p prettyplease -p syn`
closes https://github.com/wasmCloud/wasmCloud/pull/2871
=> chore: update `wit-bindgen-wrpc`

Cargo.lock, crates/component/Cargo.toml
Remove unused `serde` feature from `wasmcloud-component`
Follow-up on https://github.com/wasmCloud/wasmCloud/pull/2875
=> fix(component): remove unused `serde` feature

src/main.rs
It's a bit clumsy to have to provide the seed and jwt separately when they could be just read from the credentials file, so let's add support for that.
=> feat(host): Add support for supplying a NATS credentials file

Cargo.lock, crates/provider-sqldb-postgres/Cargo.toml
=> release(providers): sqldb provider v0.5.2

crates/wash-cli/Cargo.toml
=> chore(wash-cli): fix missing feature, create release commit

.github/workflows/examples-components.yml
=> chore(ci): enable automated release for the http task manager

crates/runtime/src/runtime.rs, src/main.rs
This PR relaxes the memory limits on a component a bit, from 10 MiB to 256 MiB. I picked the number because it's a power of two.
In all seriousness, we have a couple of options when it comes to memory limits on components. Many orchestrators and schedulers do not impose a default limit _at all_, which is certainly an option for us. In the interest of using the controls wasmtime gives us, I believe we should set this value sufficiently high to allow for reasonable workloads to load objects into memory for processing by default. 256 MiB felt like a sufficiently high value to use _by default_ for wasmCloud. As an orchestrator that is built for workloads anywhere from machines with hundreds of gigs of RAM to a raspberry pi where less than a gigabyte may be available, this value lets a …
=> feat(runtime)!: increase component memory limit to 256 MiB

Cargo.lock, crates/wash-cli/Cargo.toml, crates/wash-cli/src/dev.rs, crates/wash-lib/src/parser/mod.rs
This is one of the first PRs on the way to #2508
=> feat(wash-lib,wash-cli): wash dev interface usage detection

.github/workflows/wasmcloud.yml
=> chore(ci): enable separate releases of some crates

crates/wash-cli/src/call.rs
This commit changes `wash call` to return the bytes from a request as a string, rather than a `bytes::Bytes`, which was causing output like `"body": [123, 123, 123, 123]` rather than the actual stringified bytes.
Since requests that can be satisfied by `wash call` of wasi:http are expected to be quite simple, they can be expected to be strings -- when JSON is expected `--extract-json` can be specified.
=> fix(wash-cli): return a string as the body from wash call

Cargo.lock, Cargo.toml
Bumping a patch to release the fix for component max memory
=> release(wasmcloud): v1.2.1

Cargo.lock, crates/wash-cli/Cargo.toml, crates/wash-cli/src/up/config.rs
releases wash-cli with wasmcloud 1.2.1
~draft since 1.2.1 isn't out yet~
=> release(wash-cli): v0.32.1

.github/workflows/wasmcloud.yml
=> feat(ci): allow release of wasmcloud-component

Cargo.lock, Cargo.toml, crates/wash-lib/Cargo.toml
Setting up `wash-lib` for a patch release for wash 0.32.1
=> release(wash-lib): v0.25.1

examples/rust/providers/custom-template/Cargo.toml, examples/rust/providers/custom-template/src/provider.rs, examples/rust/providers/messaging-nats/Cargo.toml, examples/rust/providers/messaging-nats/src/nats.rs
=> fix(examples): update wasmcloud-provider-sdk version

.github/workflows/wasmcloud.yml
=> chore(ci): allow automated release of secrets types

Cargo.lock, crates/wash-cli/src/app/mod.rs, crates/wash-cli/tests/wash_app.rs, crates/wash-lib/Cargo.toml, crates/wash-lib/src/app.rs
=> feat(wash-cli): Add ability to check and validate OCI image references in WADM manifests

ADOPTERS.md
=> chore: update ADOPTERS to include BMW AG

crates/provider-sdk/src/provider.rs
This will make it easier to figure out which connection might be associated with what provider.
For illustrative example, compare the before and after outputs:
Before:
```
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                Top 3 Connections out of 3 by subs                                                                               │
├─────┬──────────────────────────────┬──────────────────────────────────────────────────────────┬─────────┬─────────────────┬─────────┬────────┬─────────┬──────────┬──────────┬───────────┬──────┤
│ CID │ Name                         │ …
```
=> feat(provider-sdk): name the provider's NATS connection

crates/host/src/wasmbus/handler.rs
This PR increases a debug log in the `invoke` code to a warning, and adds another warning log for a different error in that same path.
#2978
=> chore(host): set missing link log to warn

crates/provider-messaging-nats/README.md
The document of `provider-messaging-nats` is not correct
The configurations should be `subscriptions` and `cluster_uris`, but they are written as `subscription` and `uri`.
Reference: https://github.com/wasmCloud/wasmCloud/blob/d21d2a9e7dffd16315eeb565e2cd0e1f1aeeac6c/crates/provider-messaging-nats/src/connection.rs#L10
next
N/A
N/A
N/A
N/A
I ran with the previous configuration but it didn't work. Then I changed to the current configuration and confirm that it works.
=> doc: fix provider-messaging-nats

Cargo.lock, Cargo.toml, crates/tracing/src/lib.rs, crates/wash-cli/Cargo.toml, crates/wash-cli/src/dev.rs
This PR builds on #2962 and adds local sessions along with multi-host usability to `wash dev`. While some functionality (like standard locations for files) could be moved up to `wash-lib` I've put that off here until we stabilize the new stuff (pre-release).
=> feat(wash-cli): allow multi host usage, add local sessions to `wash dev`

.github/CODEOWNERS
Simple PR to allow go maintainers to maintain Go examples :)
=> chore(CODEOWNERS): give golang maintainers examples

crates/wash-cli/src/dev.rs
=> feat(wash-cli): write out generated wadm

crates/wash-cli/src/dev.rs
This PR is stacked on top of another one, so note that the important commit is https://github.com/wasmCloud/wasmCloud/pull/2991/commits/8479b5da170d87f36dbcfa98f9189e7448413951
=> feat(wash-cli): add hints for deps

Cargo.lock, tests/components/rust/Cargo.lock, tests/links.rs
Update dependencies, which fixes a vulnerability in one of our deps among other things (https://github.com/wasmCloud/wasmCloud/actions/runs/10875438557/job/30173908657?pr=3010)
`cargo test`
=> chore: update dependencies

crates/host/src/wasmbus/mod.rs
If you were running a high number of concurrent component invocations, it would result in a warning (and possible hang/dropped message) due to a full channel. This change attempts to set the channel size to the `max_instances` value with a minimum and a maximum possible value (i.e we don't want something with 20k instances to have a channel that large).
=> fix(host): Sets a higher value for the incoming events channel

crates/wash-cli/src/common/stop_cmd.rs, crates/wash-cli/src/dev.rs, crates/wash-lib/src/cli/stop.rs
This PR contains a breaking change for `wash-lib` (basically a breaking refactor) and code that enables `wash dev` to work with providers.
=> feat(wash-cli): enable wash dev for providers

crates/host/src/wasmbus/mod.rs, crates/runtime/src/component/mod.rs
it helps to know when handling a function failed
=> fix(host): log handling errors

Cargo.toml
=> chore(deps): allow default features for url (prep for no-std)

.github/workflows/wash.yml, crates/wash-lib/src/parser/mod.rs, crates/wash-lib/tests/parser/files/rust_actor_custom_build.toml, rust-toolchain.toml
Let's get rid of all the warnings that show up on examples :)
We can probably delay releasing this in the next version a little bit, since people may be running with older versions of Rust which don't have the warning
=> chore(wash-cli): update wasi rust target

crates/provider-sdk/src/otel.rs
This commit updates the `wasmcloud-provider-sdk` to override OTEL related configuration via provided config.
At present, OTEL config is specified to the host but *not* passed along (via ENV) to providers because of isolation between the environments in which binaries wrong (we wouldn't want sensitive ENV variables to make it through). 
While the answer would normally be to pass along the related ENV so that it can affect the libraries used by providers (if that is enabled), some client libraries in the OTEL ecosystem ignore manually set variables with ENV, which means it would be difficult to configure the host and provider independently if ENV was passed through (the variables would always be jointly set for host and spawned providers). 
Here, we choose to override the `otel_config` …
=> fix(provider-sdk): override OTEL vars from config

.github/workflows/wasmcloud.yml
=> chore(ci): enable releasing provider-sdk via automated workflow

crates/wash-cli/src/dev.rs
=> chore(wash-cli): update wash dev kv provider to keyvalue-nats 0.3.0

README.md
wasmCloud is made so much better by our contributors, let's highlight them!
=> chore(README): contributors front and center

Cargo.lock, Cargo.toml
=> chore(deps): update wadm-types & wadm-client to v0.4.0

Cargo.lock, Cargo.toml, crates/core/Cargo.toml
remove redundant `tower` dep
closes #3097
=> chore: remove redundant `tower` dep

.github/workflows/examples-components.yml, .github/workflows/secrets-nats-kv.yml, .github/workflows/wash.yml, .github/workflows/wasmcloud.yml
=> ci: ensure cargo is up to date before use

examples/golang/components/http-client-tinygo/local.wadm.yaml, examples/golang/components/http-client-tinygo/wadm.yaml, examples/golang/components/sqldb-postgres-query/local.wadm.yaml, examples/rust/components/dog-fetcher/local.wadm.yaml, examples/rust/components/dog-fetcher/wadm.yaml, examples/rust/components/echo-messaging/local.wadm.yaml, examples/rust/components/echo-messaging/wadm.yaml, examples/rust/components/http-blobstore/local.wadm.yaml, examples/rust/components/http-blobstore/wadm.yaml, examples/rust/components/http-hello-world/local.wadm.yaml, examples/rust/components/http-hello-world/wadm.yaml, examples/rust/components/http-jsonify/local.wadm.yaml, examples/rust/components/http-jsonify/wadm.yaml, examples/rust/components/http-keyvalue-counter/local.wadm.yaml, examples/rust/components/http-keyvalue-counter/wadm.yaml, examples/rust/components/http-task-manager/local.wadm.yaml, examples/rust/components/http-task-manager/wadm.yaml, examples/rust/components/keyvalue-messaging/local.wadm.yaml, examples/rust/components/keyvalue-messaging/wadm.yaml, examples/rust/components/messaging-image-processor-worker/local.wadm.yaml, examples/rust/components/messaging-image-processor-worker/wadm.yaml, examples/rust/components/sqldb-postgres-query/local.wadm.yaml, examples/rust/components/sqldb-postgres-query/wadm.yaml, examples/rust/providers/custom-template/wadm.yaml
=> chore(examples): add examples of OTEL settings

.github/workflows/wit-wasmcloud-lattice-bus.yml, wit/bus/README.md
Fixes copy-paste error in readme for wit bundle.
=> docs(wit): wit bundle link in bus README.md

Cargo.lock, Cargo.toml, crates/control-interface/Cargo.toml, crates/control-interface/src/client.rs, crates/control-interface/src/lib.rs, crates/control-interface/src/types/component.rs, crates/control-interface/src/types/ctl.rs, crates/control-interface/src/types/host.rs, crates/control-interface/src/types/link.rs, crates/control-interface/src/types/registry.rs, crates/control-interface/src/types/rpc.rs, crates/host/src/registry.rs, crates/host/src/wasmbus/event.rs, crates/host/src/wasmbus/mod.rs, crates/test-util/src/component.rs, crates/test-util/src/lattice/config.rs, crates/test-util/src/lattice/link.rs, crates/test-util/src/provider.rs, tests/links.rs
This commit prepares control-interface for v2.0.0 release, in particular:
- Trimming publically available API surface
- Ensuring provided are appropriately marked with `#[non_exhaustive]`
The goal of this prep is to prevent future breaking changes in `wasmcloud-control-interface` releases.
This code *does* represent a breaking change for `control-interface`.
=> refactor(control-interface)!: prep for v2 release

.github/workflows/wasmcloud.yml
=> chore(ci): enable automated release of control-interface

Cargo.toml, crates/control-interface/CHANGELOG.md
=> release: control-interface v2.0.0

crates/core/src/otel.rs
Provider SDKs need to handle this appropriately as there's no point serializing empty options.
https://github.com/wasmCloud/wasmCloud/issues/3080
=> chore(core)!: Skip serializing Option fields if set to None

crates/core/src/otel.rs
Since we include this in the host data to providers, we should standardize on lowercase for consistency.
=> chore(core)!: Rename OtelProtocol variants to lowercase

.github/workflows/wasmcloud.yml
=> chore(ci): allow publishing pre-releases

.github/workflows/wasmcloud.yml
=> chore(ci): enable releasing wasmcloud-test-util

.github/workflows/wasmcloud.yml
=> refactor(ci): use the crate name in branch

Cargo.lock, Cargo.toml
Bumping wasmCloud to v1.3.0 so we can cut a release candidate, test, and possibly promote to the 1.3.0 release.
=> release(wasmcloud): v1.3.0-rc.1

crates/wash-cli/src/dev.rs
This PR fixes two issues in `wash dev`
1. Previously, when generating a dependency for something like `wasi:keyvalue/store` and `wasi:keyvalue/atomics`, we would generate two capability components in the manifest. Now, I use a hashmap to remove the duplicate component during manifest creation.
1. Additionally, these links are now combined into one link
1. We're watching paths recursively, so generated `target` / `node_modules` type directories triggers many many rebuilds. I added an `--ignore-dir` flag so that users can submit their own, but I made sure to ignore target + build to start.
=> fix: wash dev no duplicate components, ignore generated files

crates/wash-cli/src/dev.rs, crates/wash-lib/src/config.rs, crates/wash-lib/src/drain.rs, crates/wash-lib/src/generate/emoji.rs
- **fix(wash-cli)!: remove duplicate components, ignore generated paths**
- **fix(wash-dev): combine links**
- **fix(wash-cli): continue dev loop when build fails**
- **fix(wash-cli): differentiate config, support fast-reload**
This PR includes a couple more fixes for the stability + capabilities of wash dev, separated by commits
=> fix(wash-cli): developer loop improvements

crates/wash-cli/src/dev.rs
This commit allows failure of WADM manifest component generation in wash dev, ignoring it if it occurs.
Generation of WADM manifest components is likely to fail for *new* interfaces that may be imported or exported -- likely unknown interfaces that we can't possibly generate a known component for.
In this case we probably do *not* want to error right away, but rather produce a warning
=> fix(wash-cli): ignore failed generation of components in `wash dev`

.github/actions/configure-wkg/action.yml, .github/workflows/wash-plugins.yml, .github/workflows/wit-wasmcloud-lattice-bus.yml, .github/workflows/wit-wasmcloud-postgres.yml, .github/workflows/wit-wasmcloud-secrets.yml
I think I got this right, but I'll be able to push some test tags (probably with the wash plugin wit) to test it once we merge
=> feat(ci): Uses wkg to build and push wit package binaries to OCI

Cargo.lock, Cargo.toml, tests/components/rust/Cargo.lock
update to latest `wrpc`
Also ran `cargo update` since I was bumping deps anyway
A few bindgen fixes and a fix in nested future handling.
wasmCloud does not use nested futures, so no breaking changes on protocol level
=> build: update `wrpc`

.github/workflows/wasmcloud.yml
=> chore(ci): avoid building containers on pull requests

.github/workflows/wash.yml, Cargo.lock, crates/control-interface/CHANGELOG.md, crates/control-interface/Cargo.toml, crates/control-interface/src/client.rs, crates/control-interface/src/types/component.rs, crates/control-interface/src/types/ctl.rs, crates/control-interface/src/types/host.rs, crates/control-interface/src/types/link.rs, crates/control-interface/src/types/provider.rs, crates/control-interface/src/types/rpc.rs, crates/host/src/wasmbus/event.rs, crates/host/src/wasmbus/mod.rs, crates/test-util/src/lattice/link.rs, tests/links.rs
=> fix(control-interface)!: wrong data returned from provider auction

Cargo.lock, Cargo.toml, crates/wash-cli/Cargo.toml, crates/wash-cli/src/app/mod.rs, crates/wash-cli/src/cmd/config/delete.rs, crates/wash-cli/src/cmd/config/get.rs, crates/wash-cli/src/cmd/config/put.rs, crates/wash-cli/src/cmd/up.rs, crates/wash-cli/src/common/link_cmd.rs, crates/wash-cli/src/common/registry_cmd.rs, crates/wash-cli/src/ctl/output.rs, crates/wash-cli/src/dev.rs, crates/wash-cli/src/down/mod.rs, crates/wash-cli/tests/wash_get.rs, crates/wash-cli/tests/wash_scale.rs, crates/wash-cli/tests/wash_up.rs, crates/wash-cli/tests/wash_update.rs, crates/wash-lib/Cargo.toml, crates/wash-lib/src/capture.rs, crates/wash-lib/src/cli/capture.rs, crates/wash-lib/src/cli/claims.rs, crates/wash-lib/src/cli/get.rs, crates/wash-lib/src/cli/label.rs, crates/wash-lib/src/cli/link.rs, crates/wash-lib/src/cli/start.rs, crates/wash-lib/src/cli/stop.rs, crates/wash-lib/src/cli/update.rs, crates/wash-lib/src/common.rs, crates/wash-lib/src/component.rs, crates/wash-lib/src/spier.rs
=> chore(wash-cli, wash-lib) remove async nats 033

flake.lock, flake.nix
Update `wit-deps` to latest release and Rust target spec from `wasm32-wasi` to `wasm32-wasip1`
=> build(nix): update `wit-deps` and Rust target spec

.github/workflows/wash-plugins.yml, .github/workflows/wit-wasmcloud-lattice-bus.yml, .github/workflows/wit-wasmcloud-postgres.yml, .github/workflows/wit-wasmcloud-secrets.yml
Also fixes issue with other wit not checking out the actions dir during sparse checkout
=> fix(ci): Enable correct permissions for wash plugin wit CI

.github/workflows/examples-components.yml, .github/workflows/examples-providers.yml
Resolves https://github.com/wasmCloud/wasmCloud/issues/2701
=> feat(examples): add CI for testing example providers

.github/workflows/examples-providers.yml, crates/wash-cli/src/cmd/up.rs, crates/wash-lib/src/start/nats.rs, examples/rust/providers/messaging-nats/local.wadm.yaml
Resolves https://github.com/wasmCloud/wasmCloud/issues/3109
=> fix(wash-cli): up fails silently creating wadm

typescript/apps/washboard-ui/src/app/contexts/settings-context.tsx, typescript/apps/washboard-ui/src/components/toast/use-toast.ts
TS Build is failing because of formatting changes 💅🏻
=> chore: update formatting after eslint-plugin-unicorn update

README.md
This PR brings a delightful touch of elegance by streamlining the code, reducing the number of lines from five to three. By refining the logic and removing unnecessary complexity, this change not only enhances readability but also makes the code more efficient. The result? A cleaner, more concise implementation that's easier to maintain and a joy to work with! Less is more, and this PR proves it.
=> chore(README): quicker quickstart

Cargo.lock, Cargo.toml, crates/wash-cli/src/config.rs
Update wadm to 0.17.0 to properly bring in the latest control interface.
=> deps(wadm): upgrade to 0.17.0

tests/links.rs
This commit adds some waiting for the HTTP server to actually become reachable in order to reduce flakiness when running the `link_name_support` test
=> fix(tests): link name support test flake

crates/wash-cli/Cargo.toml, crates/wash-cli/src/wit.rs
This is almost exactly the same as `wkg publish` but exposed for convenience within wash
=> feat(wash): Adds a wit publish command

Cargo.lock, crates/wash-lib/Cargo.toml, crates/wash-lib/build.rs, crates/wash-lib/src/app.rs, crates/wash-lib/src/start/github.rs, crates/wash-lib/src/start/nats.rs, crates/wash-lib/src/start/wasmcloud.rs
This commit fixes some tests that were failing (i.e. `make test-all`) when trying to test wash.
=> fix(wash-lib): constantly failing tests

charts/wasmcloud-host/Chart.yaml
Publishes the changes from #3277
=> chore: Bump wasmcloud-host chart version

Cargo.lock, Cargo.toml
=> release(wasmcloud): v1.3.1

charts/wasmcloud-platform/Chart.yaml
Incorporates changes from #3288 into the `wasmcloud-platform` chart
=> chore(wasmcloud-platform): Update wasmcloud-host dependency to 0.8.4

RELEASE.md, RELEASE_RUNBOOK.md
This includes a higher level release process doc and an actual runbook for releasing
Closes #3295
=> docs: Adds documentation for our release process

MAINTAINERS.md
This PR adds organizations to our current maintainers listed in MAINTAINERS.md
=> chore(MAINTAINERS): add organizations

MAINTAINERS.md
This makes sure there is a newline for each item in a maintainers entry
=> fix(docs): Fixes some formatting issues with MAINTAINERS

examples/security/secrets/provider-keyvalue-redis-auth/Cargo.toml
The example code was failing to build:
```shell
Compiling wasmcloud-example-auth-kvredis v0.1.0 (.../examples/security/secrets/provider-keyvalue-redis-auth)
error[E0277]: the trait bound `WrpcClient: Serve` is not satisfied
--> src/provider.rs:70:13
|
70 |             bindings::serve,
|             ^^^^^^^^^^^^^^^ the trait `Serve` is not implemented for `WrpcClient`
|
note: required by a bound in `bindings::serve`
--> src/provider.rs:19:5
|
19 | /     wit_bindgen_wrpc::generate!({
20 | |         with: {
21 | |             "wrpc:keyvalue/atomics@0.2.0-draft": generate,
22 | |             "wrpc:keyvalue/store@0.2.0-draft": generate,
23 | |         }
24 | |     });
| |______^ required by this bound in `serve`
= note: this error originates in the macro `wit_bindgen_wrpc::generate` (in …
```
=> chore(examples): bump wit-bindgen-wrpc version for provider-keyvalue-redis-auth

MAINTAINERS.md
=> chore(MAINTAINERS): kevin to emeritus

crates/host/src/wasmbus/config.rs
This PR ensures the config sender isn't considered "dropped" when it's moved into the tokio tasks for config updates by holding it as a field.
Fixes https://github.com/wasmCloud/wasmCloud/issues/3329, Fixes https://github.com/wasmCloud/wasmCloud/issues/2807
v1.3.2 or v1.4.0
=> fix(host): ensure config sender is not dropped

crates/provider-keyvalue-nats/README.md
Fixes the keyvalue-nats provider noting that configuration values are uppercase, when in fact the code expects lowercase and does not make them case insensitive.
=> fix(keyvalue-nats): README link keys lowercase

crates/wash-cli/src/cmd/up.rs
Noticed this while @liamwh was demoing
=> chore(wash-cli): NATS doesn't listen on http

.github/workflows/secrets-nats-kv.yml
=> chore(ci): trigger nats-secrets-kv binary releases with tags

Cargo.lock, Cargo.toml
This PR prepares wasmCloud for a v1.4.0 release, primarily to enable additional interface support. Included in this is:
1. wasi:logging and wasi:logging@0.1.0-draft
1. wasi:config/runtime and wasi:config/store
1. wasi:*@0.2.2 in addition to @0.2.1 and @0.2.0
This can first be released as v1.4.0-rc.1 to test & ensure new support is functioning as intended, but then can be released as 1.4.0
=> release(wasmcloud): v1.4.0

crates/wash-lib/src/start/wadm.rs
Currently `wash up` isn't able to bring wadm down once you send a ctrl-c or issue `wash down` since it's looking for the `wadm.pid` in a different directory (`~/.wash/downloads/wadm.pid` vs `~/.wash/wadm.pid`), this fixes that and adds a test to verify the expected behavior to avoid future regressions.
=> fix(wash-lib): Store wadm.pid in the correct location

crates/core/src/wit.rs
This fixes previously broken test cases, adds an actual test to run them.
=> chore(core): Improve parse_wit_package_name handling

flake.nix
=> chore(nix): Update wolfi-base image digest and sha256

.github/workflows/wasmcloud.yml, crates/provider-sqldb-postgres/Cargo.toml, crates/provider-sqldb-postgres/src/lib.rs, crates/wash-lib/src/build/mod.rs, crates/wash-lib/src/cli/link.rs, crates/wash-lib/src/config.rs
- fix doc tests in the workspace
- run doc tests in CI
- ~add Rust `ignore` attribute to SQL doc fences in postgres WIT. Switch to WIT from local path for the provider to pull it in~
- do not run doctests in postgres provider (because of the generated markdown SQL code fences in comments originating from the WIT definition)
- add missing `Default` impl for wash connection options
https://github.com/ipetkov/crane/pull/720
https://github.com/rvolosatovs/nixify/pull/283
https://github.com/rvolosatovs/nixify/pull/284
=> ci: enable doctests

.github/workflows/wasmcloud.yml, flake.nix
Roughly:
```
nix-prefetch-docker --arch amd64 cgr.dev/chainguard/wolfi-base
nix hash to-sri --type sha256 $sha256 | pbcopy
```
```
nix-prefetch-docker --arch arm64 cgr.dev/chainguard/wolfi-base
nix hash to-sri --type sha256 $sha256 | pbcopy
```
Revert https://github.com/wasmCloud/wasmCloud/pull/3210 - we do want to know if a PR breaks container builds
Revert https://github.com/wasmCloud/wasmCloud/pull/3315 - this PR breaks merges of PRs that only modify markdown. Such PRs should not cause rebuilds and if they do - let's fix the caching instead. Generally, we should just skip the irrelevant builds depending on the changes and create a "marker" job, which would signify success and would be the required job for merges
=> ci: update `wolfi` images

crates/wash-cli/src/config.rs
Updating wasmCloud to 1.4.0 within `wash up`
=> chore(wash): update wasmcloud to 1.4

Cargo.lock, Cargo.toml, crates/wash-cli/src/cmd/dev/deps.rs, crates/wash-cli/src/cmd/dev/devloop.rs, crates/wash-cli/src/cmd/dev/manifest.rs, crates/wash-cli/src/config.rs, crates/wash-cli/tests/wash_dev.rs, crates/wash-lib/src/app.rs, crates/wash-lib/src/parser/mod.rs
This PR updates wadm to 0.18.0 for release.
=> feat(wash): update wadm to 0.18

.github/workflows/wash.yml
Follows up on https://github.com/wasmCloud/wasmCloud/pull/3423 to update the second location it was used, and making it  easier to change in the future.
=> chore(ci): Use environment variable for (Tiny)Go versions to centralize updating it

.github/workflows/wasmcloud.yml
=> fix(ci): use larger equinix runner for container image builds

crates/wash-cli/README.md, examples/rust/composition/README.md
=> chore(docs): update all cargo wash-cli install commands to --locked

.github/actions/wasm-lang-toolchain-setup/action.yml, .github/workflows/examples-components.yml, .github/workflows/wash.yml
=> fix(ci): language version usage when setting up toolchains

.github/workflows/examples-components.yml, examples/golang/components/http-hello-world/wasmcloud.toml
=> fix(ci): tinygo example builds

Cargo.lock, crates/component/Cargo.toml, crates/component/src/lib.rs, crates/component/src/wrappers/http.rs, crates/component/src/wrappers/mod.rs, tests/components/rust/Cargo.lock, tests/components/rust/pinger-config-component/Cargo.toml, tests/components/rust/pinger-config-component/src/lib.rs
- Ported over most of https://github.com/bytecodealliance/wasi-rs/pull/90
- Adapted a few things from https://github.com/wrpc/http/blob/dbc6a6ba307ef9f53e175da9982c5a757d1a7eaa/src/lib.rs
- On top of the above, implemented `OutgoingBody` abstraction and `IncomingBody` wrapper
- Added From family of traits analogues to `wasmcloud_component`, these should go away once WASI support is added to upstream libraries (I'll make sure to extract stuff from this PR to e.g. `http` crate)
This PR is meant to be a basis on top of which #3399 could be implemented further. I have not done much testing of this PR, just something we quickly sketched together with @brooksmtownsend and I later wrapped it up.
Going forward, I think we should add `ServerAsync`, which would create a Tokio runtime and implement …
=> feat(component): add `http` crate integration

examples/golang/components/http-client-tinygo/wasmcloud.toml
The custom `build_command` is making the tests very unhappy, so let's get rid of that.
=> chore(examples): Remove custom build_command from http-client-tinygo

crates/wash-cli/tests/wash_build.rs, examples/golang/components/http-client-tinygo/project-generate.toml
Addresses the underlying reasons for why the following tests fail:
```
wash-cli::wash_build integration_build_tinygo_component_separate_paths
wash-cli::wash_build integration_build_tinygo_component_signed
```
=> fix: wash-build tinygo tests

CONTRIBUTING.md
This PR corrects links & process for RFCs/ADR
=> chore(CONTRIBUTING): correct ADR process

crates/host/src/wasmbus/mod.rs, crates/runtime/src/runtime.rs
This PR fixes the issue where we still had remaining references to the wasmtime Engine when the host was stopping, so the epoch interruption thread didn't complete.
This may or may not be the "correct" way to solve this problem. I approached this from the perspective that
1. This error is misleading when the host is shutting down
1. We want to make sure we finish executing the thread that's running the epoch interrupter, whether or not we've properly removed all references to the underlying engine.
Fixes https://github.com/wasmCloud/wasmCloud/issues/3316
=> fix(host): end epoch interruption, don't await

.github/workflows/wasmcloud.yml
=> fix(ci): oci step

.github/workflows/provider.yml
=> feat(ci): add tests for provider builds

.github/workflows/examples-components.yml, examples/typescript/components/http-password-checker/wasmcloud.toml
=> feat(ci): enable publishing of HTTP password checker TS example

crates/component/README.md, crates/component/src/wrappers/http.rs
This PR improves the README and some doc comments for the wasmcloud-component crate.
#3444
wasmcloud-component 0.2.0
=> chore(component): improve README.md for guidance

crates/wash-lib/src/build/component.rs, crates/wash-lib/src/build/provider.rs
=> feat(wash-lib): suppress stderr output of tinygo generate

crates/provider-http-server/Cargo.toml, crates/provider-http-server/src/address.rs, src/bin/http-server-provider/wasmcloud.toml
=> fix: more descriptive message, release http server v0.32.2

.github/workflows/provider.yml, Cargo.lock
=> fix(ci): provider test build

crates/wash-cli/src/cmd/dev/devloop.rs, crates/wash-cli/src/cmd/dev/mod.rs
After additional testing with `wash dev` in release mode, sometimes the developer loop can actually finish just a few milliseconds before the final build artifact writes out, triggering yet another reload. To combat this, I'm adding a a short wait (250ms) after the build and then taking any remaining value out of the channel.
This is a pretty unnoticeable time sleep in the dev loop, but it's immediately obvious that we're not getting duplicate reloads with this. 
wash 0.37.0
=> fix(wash-cli): avoid an immediate reload

.github/workflows/examples-components.yml
This:
1. Removes duplicate entry for `sqldb-postgres-query`
2. Converts duplicate `http-echo-tinygo` entry to `http-client-tinygo`
3. Updates Go language versions to 1.23 across the board
4. Corrects wasm binary names
=> chore(ci): clean up example-components workflow

.github/workflows/wash.yml
=> chore(ci): add missing language-version argument

wit/secrets/README.md
We're planning on replacing this all with `wkg` usage, but before we do (and in the case where we *can't* use `wkg` if there are new contracts it does not know about, or with providers), the link shouldn't be wrong.
=> fix(wit): link to wasmcloud secrets release

crates/wash-cli/src/cmd/dev/mod.rs, crates/wash-cli/src/config.rs
Bumping to the latest version of wasmCloud and the hTTP server for wash dev with perf improvements.
wash 0.37.0
=> chore(wash-cli): bump wasmCloud to v1.4.1

crates/wash-cli/src/config.rs
Bumping wasmcloud in wash-cli to 1.4.2
wash CLI 0.37.0
=> deps(wash-cli): download wasmcloud 1.4.2

README.md
Our README incorrectly stated we are a sandbox project, which is not accurate as of yesterday 🚀
=> chore(README): correct project status

crates/wash-cli/src/bin/wash.rs, crates/wash-cli/src/cmd/dev/devloop.rs, crates/wash-cli/src/cmd/dev/mod.rs, crates/wash-cli/src/cmd/dev/session.rs, crates/wash-cli/src/cmd/up.rs, crates/wash-cli/tests/common/mod.rs, crates/wash-cli/tests/wash_dev.rs, crates/wash-lib/src/start/wadm.rs
This PR, in order of commit:
- Rewords a couple help texts and reorders `eprintln` statements in wash dev to ensure more consistent and less duplicated output.
- Attempts to reorder some code logic to ensure the main devloop is where all output is printed from instead of being from nested functions, if possible.
- Ensures that wash dev is being run when only one host exists, allowing the existence of more than one host _only_ when a host ID is specified and that host is running. This also includes recommendations for users to run `wash down --all` to wipe to a clean slate in the case of bad state.
- Adds a spinner to the build process, during text output mode, to show that wash-cli is doing work and not just sitting there hoping for it to finish
- Fixes an issue where wadm wouldn't stop …
=> [FEAT] wash dev output improvements and fixes

README.md
While reviewing the [wasmCloud bestpractices.dev](https://www.bestpractices.dev/en/projects/6363) page I noticed that the badge link has been updated since we added it to the README, so I figured it was worth updating it to match the current recommendation.
=> chore: Update OpenSSF Best Practices badge

.github/workflows/dco-merge-group.yml, .github/workflows/ts-build.yml, .github/workflows/ts-release-app-washboard.yml, .github/workflows/ts-release-package-lattice-client-core.yml, .github/workflows/ts-release-package-lattice-client-react.yml, .github/workflows/ts-release.yml, .github/workflows/ts-test.yml, .github/workflows/typescript.yml, .github/workflows/wash-plugins.yml, .github/workflows/wash.yml, .github/workflows/wit-wasmcloud-lattice-bus.yml, .github/workflows/wit-wasmcloud-postgres.yml, .github/workflows/wit-wasmcloud-secrets.yml
Doing another round of reviewing the various workflows and their permissions to tighten things down.
=> chore(ci): tighten github actions workflow permissions

examples/c/components/http-hello-world/Makefile, examples/c/components/http-hello-world/README.md
While trying the examples I stumbled upon some issues in example/c/components/http-hello-world.
- Fixed: Only set WASI_SDK_DIR variable to **/opt/wasi-sdk** in _Makefile_ when it has not been defined yet.
- Documentation: corrected path to wasm binary in wasmtime example.
Follow steps as described in README for this example.
=> Fixed example C component HTTP hello world

Cargo.lock, Cargo.toml
This addresses a whole host of outstanding RUSTSEC advisories.
=> chore(deps): Bump wasm-pkg-client and wasm-pkg-core

crates/test-util/src/testcontainers/squid_proxy.rs
=> fix(infra): squid proxy image

.github/workflows/update.yml
Refs #3413 
Example update PR generated: https://github.com/wasmCloud/wasmCloud/pull/3665
=> ci: update OCI bases nightly

.github/workflows/wasmcloud-platform-chart.yaml, charts/wasmcloud-platform/Chart.yaml, charts/wasmcloud-platform/ct.yaml
=> fix(charts): chart-testing configuration for wasmcloud-platform

.github/workflows/examples-providers.yml, crates/wash-cli/.gitignore, crates/wash-cli/src/cmd/dev/session.rs, crates/wash-cli/src/cmd/up.rs, crates/wash-cli/tests/common/mod.rs, crates/wash-cli/tests/wash_up.rs, crates/wash-lib/Cargo.toml, crates/wash-lib/src/start/github/api.rs, crates/wash-lib/src/start/github/mod.rs, crates/wash-lib/src/start/mod.rs
Wouldn't it been nice if new crispy wadm and wasmcloud would be handy with new patch versions? Well that PR supposed to implement this.
Fixes: #2032
Users using `wash up` should download new version of the mentioned binaries.
=> feat(wash-cli): check for wadm and wasmcloud patch version updates

crates/wash-lib/tests/parser/main.rs
=> fix(wash-cli): exclude test which uses hard-coded '/tmp' on windows

.github/workflows/examples-providers.yml, .github/workflows/ts-test.yml
=> chore(ci): update versions of wash used in tests

Cargo.lock
Addresses [`RUSTSEC-2024-0399`](https://rustsec.org/advisories/RUSTSEC-2024-0399.html) / [`GHSA-qg5g-gv98-5ffh`](https://github.com/advisories/GHSA-qg5g-gv98-5ffh)
=> fix: RUSTSEC-2024-0399

.github/workflows/update.yml
=> chore(ci): Pin nix-flake-update actions to hashes

.devcontainer/Dockerfile, crates/secrets-nats-kv/Dockerfile
Pins the image versions used in our Dockerfiles.
=> chore: Pin dockerfile dependencies

examples/typescript/components/http-hello-world/package-lock.json, examples/typescript/components/http-hello-world/package.json, examples/typescript/components/http-password-checker/package-lock.json, examples/typescript/components/http-password-checker/package.json
This commit updates the versions of jco to bring in fixes for top level resources.
=> chore(examples): update jco versions

.github/dependabot.yml
Follow-up on https://github.com/wasmCloud/wasmCloud/pull/3719#pullrequestreview-2470539904
=> chore(deps): Add dependabot for Dockerfiles

crates/runtime/src/runtime.rs
=> feat: Enable memory_init_cow in wasmtime

.github/workflows/examples-providers.yml
=> fix(examples): build dependent component for custom providers

.github/workflows/provider.yml, .github/workflows/wasmcloud.yml
Since we opted to remove `lattice-controller` from the features in https://github.com/wasmCloud/wasmCloud/pull/3739, we need to remove it also from the tests that try to interact with it.
=> chore(ci): Remove `lattice-controller`

.github/workflows/examples-providers.yml
=> fix(ci): working dir for component build

.github/workflows/examples-components.yml, .github/workflows/examples-providers.yml
=> chore(ci): rename jobs for easier targeting

crates/wash-cli/src/cmd/dev/mod.rs
This PR fixes a bug where we attempt to create a NATS and control interface client before wash dev actually starts NATS, essentially requiring NATS to be running when the process starts.
Instead, now we only require NATS to be running if attempting to connect to an existing host.
=> fix(wash-cli): dont require NATS to start

crates/host/src/wasmbus/providers/messaging_nats.rs, crates/provider-messaging-nats/src/connection.rs, crates/provider-messaging-nats/src/lib.rs
This adds support for JetStream consumers in builtin NATS messaging provider. The new `consumers` config key takes in in-line JSON, here's an example:
```diff
diff --git a/examples/rust/components/echo-messaging/local.wadm.yaml b/examples/rust/components/echo-messaging/local.wadm.yaml
index 078eb5f5..59973c68 100644
--- a/examples/rust/components/echo-messaging/local.wadm.yaml
+++ b/examples/rust/components/echo-messaging/local.wadm.yaml
@@ -32,7 +32,7 @@ spec:
- name: nats
type: capability
properties:
-        image: ghcr.io/wasmcloud/messaging-nats:0.23.1
+        image: wasmcloud+builtin://messaging-nats
@@ -57,4 +57,4 @@ spec:
source_config:
- name: simple-subscription
properties:
-                  subscriptions: wasmcloud.echo
+                  consumers: …
```
=> feat(nats): add JetStream consumer support

typescript/packages/lattice-client-core/package.json, typescript/packages/lattice-client-core/src/controllers/applications.ts, typescript/packages/lattice-client-core/src/types.ts
- **fix(lattice-client-core): update types with recent wadm types**
- **chore(release): bump package version for release**
=> Update lattice client types

.github/workflows/nix.yml
`nix fmt` now requires directories/files to be specified
=> ci: use correct `nix fmt` syntax

.github/workflows/ts-test.yml, typescript/apps/washboard-ui/package.json, typescript/turbo.json
- **test(ts-e2e): fix e2e runner in CI**
=> Improve E2E test run and coverage

crates/wash-lib/src/build/component.rs
Resolves https://github.com/wasmCloud/wasmCloud/issues/3666
=> fix(wash-cli): print output for custom build commands

.github/renovate.json
This changes [commits](https://github.com/wasmCloud/wasmCloud/pull/3818/commits/af39f8ffeb90300f985ad293f4951df81871d723) that the [Renovate workflow](https://github.com/wasmCloud/wasmCloud/blob/main/.github/workflows/update-example-providers.yml) makes in two crucial ways:
1. It adds [signoff](https://docs.renovatebot.com/presets-default/#gitsignoff) to satisfy DCO.
2. It changes the author from [renovate-bot](https://github.com/renovate-bot) to [GitHub Actions bot](https://github.com/actions/checkout?tab=readme-ov-file#push-a-commit-using-the-built-in-token) to match the [automated commits from our Nix updater workflow](https://github.com/wasmCloud/wasmCloud/pull/3798/commits/a5ab5122a7b74e8777cd07b7c3dfef9194839184).
=> chore: Add signoff and author for Renovate commits

crates/wash-cli/src/cmd/dev/session.rs
In testing the wash dev changes added in #3820, I found that the process would panic if it encounter *any* log line that didn't have a match.
#3820
wash@next
I went ahead and extracted the logic into its own function so that I could add some tests. If there's a better way to do this, I'm all ears.
=> fix: correct regex and add tests

.github/workflows/examples-components.yml, crates/provider-sqldb-postgres/README.md, examples/rust/components/messaging-image-processor-worker/wasmcloud.toml
=> fix(examples): docker image deps

.github/workflows/examples-components.yml
This commit fixes the release tag for the image processor worker written in Rust.
=> fix(ci): image processor worker release tag

examples/rust/components/messaging-image-processor-worker/wadm.yaml
=> fix(examples): messaging worker image ref

crates/wash-cli/tests/wash.rs
This PR introduces simple tests for wash help options
=> test(wash-cli): add tests for wash help short and help markdown

crates/host/src/wasmbus/host_config.rs, crates/host/src/wasmbus/mod.rs, src/main.rs
Implement (opt-in) health checks in the host for better integration with cloud-native tooling
Note, there's no trailing newline in the response, which generally should not matter, but I'm not sure about the assumptions that k8s tooling might make
```
cargo run -- --http-admin '[::1]:9090'
```
```
$ curl http://localhost:9090/hello      
curl: (52) Empty reply from server
$ curl -X GET http://localhost:9090/livez 
{"status":"ok"}
$ curl -X POST http://localhost:9090/livez 
curl: (52) Empty reply from server
$ curl -X GET http://localhost:9090/readyz    
{"status":"ok"}
```
=> feat(host): implement health check API

.github/CODEOWNERS
This PR updates the CODEOWNERS file as an initial step to greatly simplify the required reviewers for this repository. As a monorepo, the required reviewers list can often get complicated very quickly. This PR is the first step in a direction to require `org-maintainers` less, and leave reviews to their respective teams wherever possible. For context, every PR that merges in this repository requires a review from the CODEOWNER of the modified files.
The biggest change in this PR is to remove the requirement that a file that doesn't match the CODEOWNERS rules be an `org-maintainer`. We don't have enough content in this repository to require an org-maintainer when we don't have a rule covering a specific file.
In the long term, I'm proposing https://github.com/wasmCloud/org-admin will be …
=> chore(CODEOWNERS): simplify org maintainer requirements

.github/actions/install-cached-wash-cli/action.yml, .github/workflows/wash.yml
Signed-off-by: Lachlan Heywood <lachieh@users.noreply.github.com>
=> fix(ci): handle non pr actions

crates/wash-cli/tests/fixtures/integrated-wkg-extended/.cargo/config.toml, crates/wash-cli/tests/fixtures/integrated-wkg/.cargo/config.toml, crates/wash-cli/tests/fixtures/old-examples/http-hello-world-go/wasmcloud.toml, crates/wash-cli/tests/fixtures/separate-wkg/.cargo/config.toml, crates/wash-lib/src/build/component.rs, crates/wash-lib/src/common.rs, examples/golang/providers/custom-template/component/wasmcloud.toml, examples/rust/components/http-blobstore/.cargo/config.toml, examples/rust/components/http-jsonify/.cargo/config.toml, examples/rust/components/http-task-manager/README.md, examples/rust/components/messaging-image-processor-worker/README.md, examples/rust/components/messaging-image-processor-worker/wasmcloud.toml, examples/rust/components/sqldb-postgres-query/.cargo/config.toml, examples/rust/components/wash-plugin-rust/.cargo/config.toml, rust-toolchain.toml, tests/components/build.rs, tests/components/rust/pinger-config-component/.cargo/config.toml, tests/components/rust/ponger-config-component/.cargo/config.toml
=> fix(wash-cli): wit fetch use of shallow clones

flake.nix
```
$ nix build -L .#wasmcloud-aarch64-unknown-linux-musl-oci-wolfi
$ docker inspect wasmcloud:arm64 | jq '.[].Config.User'
"65532:65532"
$ docker run --rm -it wasmcloud:arm64 /bin/sh -c whoami
nonroot
```
=> build(nix): use `nonroot` in wolfi images

crates/host/src/wasmbus/host_config.rs, crates/host/src/wasmbus/mod.rs, src/main.rs
For some deployments it is beneficial not to manage binary providers
=> feat: allow disabling auction participation

crates/wash-cli/src/bin/wash.rs, crates/wash-cli/tests/wash.rs
Ensures that the correct output format is used for the wash-cli version flag.
#3884
`next` minor version.
Improves version output and makes it slightly easier to parse with common tools such as jq.
Included two additional tests to ensure version output is as expected.
Built and run with the following options:
```sh
wash --version
wash          v0.37.0
├ nats-server v2.10.20
├ wadm        v0.19.0
└ wasmcloud   v1.4.2
```
```sh
wash -V
wash          v0.37.0
├ nats-server v2.10.20
├ wadm        v0.19.0
└ wasmcloud   v1.4.2
```
```sh
wash --version -o json
{
"nats-server": "v2.10.20",
"wadm": "v0.19.0",
"wash": "v0.37.0",
"wasmcloud": "v1.4.2"
}
```
```sh
wash -V -o json
{
"nats-server": "v2.10.20",
"wadm": "v0.19.0",
"wash": "v0.37.0",
"wasmcloud": "v1.4.2"
}
```
=> fix(wash-cli): ensure correct output format used for version

crates/host/src/wasmbus/event.rs
@lxfontes pointed out a couple rogue TODOs in the cloudevents payloads, this actually implements them.
=> fix(host): nbf/exp in cloudevents

.github/workflows/benchmark-chart.yml, charts/benchmark/Chart.lock, charts/benchmark/ct.yaml
Adds a basic pipeline for ensuring the chart can deploy properly as well as pushing to OCI on tagging
=> feat(charts): Adds pipeline and basic test for benchmark 

GOVERNANCE.md
This was one of the remaining items from the TOC feedback for incubating.
Closes #3305
=> chore: Updates governance with email addresses and communication

.github/workflows/k6runner.yml
My initial pipeline forgot to check for lowercasing the org name
=> fix(ci): Lowercase org name for publishing

.github/workflows/wasmcloud.yml
Noticed this step was failing on main
=> fix(ci): Correct paths for wash copy

Cargo.lock, Cargo.toml, crates/control-interface/Cargo.toml
Bump for releasing latest things that smart-release didn't catch
=> chore: bump control-interface v2.3.0

Cargo.lock, crates/runtime/Cargo.toml, crates/runtime/src/component/mod.rs
Use semver to check whether we should polyfill instances, rather than hard-coding exact names. This ensures host is forwards-compatible with WASI versions it does not know about.
https://github.com/wasmCloud/wasmCloud/issues/4057
Closes #4063
Tested with component from https://github.com/wasmCloud/wasmCloud/issues/4057 (https://github.com/bytecodealliance/sample-wasi-http-rust), but via `cargo component`
=> feat(rt): fully support WASI >0.2.2

Cargo.lock, Cargo.toml
=> chore(deps): update wasi deps from 0.221.x -> 0.224.0

Cargo.lock, Cargo.toml
This PR prepares wasmCloud for its 1.6.0 release
=> chore(wasmcloud): bump for 1.6.0 release

charts/benchmark/Chart.yaml, charts/benchmark/k6/test.js.tpl
Found these while testing this with the upcoming benchmark pipeline
=> fix(chart): Fix issues with running chart in other namespaces

.github/workflows/check-conventional-commits.yml
This is a fix for my bash logic which does space delimited labels, removes spaces from the labels
=> ci(conventional-commits): remove spaces

.github/workflows/check-conventional-commits.yml
=> ci(labeler): fix permissions

ci/cluster-template-managed.yaml, ci/common-env, ci/delete-cluster.sh, ci/manifests/wadm.yaml, ci/manifests/wasmcloud/kustomization.yaml, ci/manifests/wasmcloud/namespace.yaml, ci/manifests/wasmcloud/nats/kustomization.yaml, ci/manifests/wasmcloud/nats/nats-leaf.conf, ci/manifests/wasmcloud/nats/nats.conf, ci/manifests/wasmcloud/nats/nats.yaml, ci/manifests/wasmcloud/service.yaml, ci/manifests/wasmcloud/wadm/kustomization.yaml, ci/manifests/wasmcloud/wadm/wadm.yaml, ci/manifests/wasmcloud/wasmcloud-host/host.yaml, ci/manifests/wasmcloud/wasmcloud-host/kustomization.yaml, ci/nats-proxy.sh, ci/run-benchmarks.sh, ci/setup-cluster-api.sh, ci/values.yaml
This adds a set of scripts and assets for running a benchmark test using Oracle Cloud provided by the CNCF. Follow up PR will add a pipeline for running the test
=> feat(ci): Adds benchmarking script

charts/wasmcloud-platform/Chart.yaml, charts/wasmcloud-platform/templates/host-config.yaml
This adds support for the functionality introduced in https://github.com/wasmCloud/wasmcloud-operator/pull/72 to allow the operator to configure additional TLS Certificate Authorities (per https://github.com/wasmCloud/wasmCloud/pull/2468) in the OCI and OpenTelemetry clients.
With this change in place, you'll be able to pass in the following looking configuration as part of [`hostConfig`](https://github.com/wasmCloud/wasmCloud/blob/main/charts/wasmcloud-platform/values.yaml#L70-L83) to have the operator configure the hosts with additional TLS CAs:
```yaml
hostConfig:
enabled: true
certificates:
authorities:
- name: kube-root-ca
configMap:
name: kube-root-ca.crt
- name: private-root-ca
secret:
secretName: private-root-ca
````
The specific name of each `authorities` entry and the configMap …
=> chore(wasmcloud-platform): Add support for WasmCloudHostConfig certificates field

charts/wasmcloud-platform/templates/host-config.yaml
This change didn't get pushed up into #4125 for some reason, but it needs to go in before we tag the new version of the chart.
#4125
=> fix(wasmcloud-platform): Correct certificate authorities configMap casing

Cargo.lock, Cargo.toml, crates/wash-cli/Cargo.toml, crates/wash-cli/src/config.rs, crates/wash-lib/Cargo.toml
This PR prepares the release of wash 0.39 by bumping crates + tool versions.
wash-cli 0.39
wash-lib 0.33
=> chore: prepare wash release

.github/workflows/wasmcloud.yml
=> ci: remove `host-sys` crate support

flake.nix
Now that we're patching dependencies (#4132), parsing multiple `Cargo.lock`s and just stuffing all the contents in a single generated one does not work that well anymore (and it never really did anyway). Use https://crane.dev/API.html?highlight=vendorMultiple#cranelibvendormultiplecargodeps instead, which should also remove the requirement for all dependencies to be same version (e.g. see #4041) - we still should ensure that they are, but we probably should not fail CI because of it.
This approach should potentially also improve caching performance
=> build(nix): switch to `vendorMultipleCargoDeps`

crates/provider-http-client/src/lib.rs
Refs #4133 , can never have too many logs
=> test: log more in flaky `single_conn` test

crates/provider-sqldb-postgres/README.md
README.md missing `POSTGRES_DATABASE` config field
=> docs(sqldb-postgres): missing POSTGRES_DATABASE

.github/workflows/secrets-nats-kv.yml
This PR adds releasing the secrets-nats-kv library to crates.io to the release pipeline for the binary
=> ci(secrets-nats-kv): support crates.io release

crates/wash-cli/src/cmd/dev/session.rs, crates/wash-cli/src/cmd/up.rs, crates/wash-lib/src/start/wasmcloud.rs, crates/wash-lib/tests/start_wasmcloud.rs
=> fix(wash): host version pulling for wash dev

.github/actions/wasm-lang-toolchain-setup/action.yml, .github/workflows/examples-components.yml, .github/workflows/examples-providers.yml, .github/workflows/wasmcloud.yml, crates/wash/README.md
This PR removes the deprecation warning and updates the badge information for `wash`
=> ci(wash): update READMEs and pipelines to finalize wash-cli rename

examples/rust/components/blobby/wadm.yaml
Super small PR to bump blobby to the latest version.
Pending release 🤞🏻 https://github.com/wasmCloud/wasmCloud/actions/runs/13775360760
=> chore(blobby): bump version to v0.5.0

.github/actions/install-cached-wash-cli/action.yml, .github/actions/wasm-lang-toolchain-setup/action.yml, .github/workflows/benchmark.yml, .github/workflows/check-conventional-commits.yml, .github/workflows/examples-providers.yml, .github/workflows/secrets-nats-kv.yml, .github/workflows/wash.yml
Hey it's me, Dependabot, updating the install-action to the latest version which has `wash` as a package.
https://github.com/taiki-e/install-action/pull/895
=> deps: update taiki-e/install-action for wash

.github/workflows/check-conventional-commits.yml
Don't need to be so aggressive with the same comments if nothing changes.
=> ci(checks): less eager commenting

crates/host/src/wasmbus/experimental.rs, crates/host/src/wasmbus/mod.rs
While working on #4245 I realized it would be better to make distinct features for each component of workload identity, so this takes the existing `worload-identity` feature and renames it to `workload-identity-auth`.
=> chore: Rename workload-identity feature to workload-identity-auth to better reflect its intended purpose

crates/provider-sqldb-postgres/src/lib.rs
This commit fixes an issue with the postgres provider in which it did not ensure that a single client from the pool had a statement prepared for it.
Statements are `prepare`d for single clients, but `deadpool_postgres` does not support preparing for a pool, so we must use the statement cache on a given client pulled out of the pool to ensure the statement we're about to use has been `prepare`d.
Resolves #3998
=> fix(providers): ensure prepared statements for pool clients

crates/provider-sqldb-postgres/README.md, examples/rust/components/http-blobstore/README.md, examples/rust/components/messaging-image-processor-worker/README.md, examples/rust/components/sqldb-postgres-query/README.md, examples/rust/components/wadm-status-receiver/README.md
This commit updates links that are going to be auto-copied to docs, so they can be used from the wide internet as well as in-repo.
=> fix(docs): update links in prep for auto-copy

crates/host/src/wasmbus/ctl.rs, crates/wash/src/cli/cmd/up.rs, crates/wash/src/cli/config.rs, crates/wash/src/lib/cli/label.rs, crates/wash/tests/wash_label.rs
=> Fix(wash)=disallow overriding hostcore labels

crates/host/src/wasmbus/providers/http_server/host.rs, crates/host/src/wasmbus/providers/http_server/mod.rs, tests/builtins.rs
This PR adapts the changes in #4213 to allow for host routing in the builtin provider, along with associated tests.
#4213
next wasmCloud
=> feat(host): builtin http host routing

examples/typescript/components/http-hello-world/README.md
Broken link in docs.
N/A.
N/A.
None.
Previewed the readme file.
N/A.
N/A.
Preview of the markdown.
=> fix: broken link.

crates/host/src/wasmbus/host_config.rs, crates/host/src/wasmbus/mod.rs, crates/runtime/src/runtime.rs, src/main.rs
@LUK3ARK ran into a problem with this setting being a bit too low for his use case, so adding some config to ensure that it's adjustable.
=> feat: allow customizable max core instances

Cargo.lock, Cargo.toml
This release primarily brings in the changes that support handling wRPC errors
wasmCloud 1.8.0
=> chore(wasmcloud): bump to 1.8.0 for release

.github/CODEOWNERS
@brooksmtownsend 
Since Go examples have moved to [wasmCloud/go](https://github.com/wasmCloud/go/tree/main/examples) and Typescript examples have moved to [wasmCloud/typescript](https://github.com/wasmCloud/typescript/tree/main/examples), we can just remove these to make updates like #4387 easier.
=> chore(ci): Remove language-specific rules from CODEOWNERS

Cargo.lock, deny.toml
I was getting tired of rebasing all the different dep updates, so I bumped them all at once 😅
=> chore: Updates all pinned deps

crates/core/src/par.rs, crates/provider-keyvalue-redis/src/lib.rs, crates/runtime/src/component/mod.rs
Seemingly these [minor issues are holding up](https://github.com/wasmCloud/wasmCloud/actions/runs/15009287888/job/42174920414) https://github.com/wasmCloud/wasmCloud/pull/4422, so let's just fix them.
=> chore: Address `cargo clippy` feedback

crates/wash/src/cli/common/registry_cmd.rs
I missed this from #4453 since I didn't realize CI was using a slightly different set of arguments for cargo clippy.
This is holding #4455 up.
#4453
=> chore(wash): Address cargo clippy feedback

crates/provider-keyvalue-redis/src/lib.rs
=> fix(provider-kv-redis)!: search secrets first for default redis URL

crates/provider-keyvalue-redis/README.md, crates/provider-keyvalue-redis/src/lib.rs
=> feat(kv-provider-redis): enable disabling default connection

Cargo.lock, crates/provider-keyvalue-redis/Cargo.toml, crates/provider-keyvalue-redis/README.md, crates/provider-keyvalue-redis/src/lib.rs
=> feat(provider-kv-redis): support connection pooling

crates/wash/src/lib/common.rs
=> chore(wash): update default host version to 1.8.0

Cargo.lock, crates/wascap/Cargo.toml
=> chore(wascap): bump version

Cargo.toml
This commit specifies versions so that cargo smart-release can release wash (`*` version deps are not allowed when attempting to do a publish)
=> chore(deps): update versions to enable release

charts/wasmcloud-host/Chart.yaml
Signed-off-by: Bailey Hayes <behayes2@gmail.com>
=> chore(charts): bump wasmcloud-host

charts/wasmcloud-platform/Chart.yaml, charts/wasmcloud-platform/values.yaml
Signed-off-by: Bailey Hayes <behayes2@gmail.com>
=> chore(charts): bump host and wadm

crates/wash/src/cli/ui.rs
=> feat(wash): Add check in wash ui to confirm server responds with a 200
